/**
 * @file cylindrical_compartment.cc
 * Cylindrical_compartment class implementation
 * @author Ahmed Aldo Faisal &copy; created 26.3.2001  
 * NetTrader - visualisation, scientific and financial analysis and simulation system
 * @version   0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * @section LICENSE
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include "cylindrical_compartment.h"

using namespace modigliani_core;

/* ***      CONSTRUCTORS	***/
/** Create a Cylindrical_compartment */
Cylindrical_compartment::Cylindrical_compartment(
		modigliani_base::Real newLength /* in muMeter */, modigliani_base::Real newDiameter /* in muMeter */, modigliani_base::Real newTemperature)
:
			Membrane_compartment(M_PI * newDiameter * newLength /* in muMeter^2 */, newTemperature) {
	length = newLength;
	diameter = newDiameter;
}

/* ***      COPY AND ASSIGNMENT	***/
Cylindrical_compartment::Cylindrical_compartment(
		const Cylindrical_compartment & original) :
	Membrane_compartment(original.area()) {
	// add assignment code here
}

Cylindrical_compartment&
Cylindrical_compartment::operator=(
		const Cylindrical_compartment & right) {
	if (this == &right)
		return (*this); // Gracefully handle self assignment
	// add assignment code here
	return (*this);
}

/* ***      DESTRUCTOR		***/
Cylindrical_compartment::~Cylindrical_compartment() {
}

/* ***  PUBLIC                                    ***   */
/** @short       
 @param      none
 @return     none
 \warning    unknown
 \bug        unknown
 void
 Cylindrical_compartment::() const
 {
 }
 */

/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */

/* File skeleton generated by GenNTObj version 0.7. */
