NetTrader: TNT::Vector_Adaptor< BBVec > Class Template Reference
TNT::Vector_Adaptor< BBVec > Class Template Reference
#include <vecadaptor.h>
Public Types
typedef BBVec::value_type T
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
Subscript size () const
BBVec & getVector ()
Subscript dim () const
Subscript dim (Subscript i)
Vector_Adaptor ()
Vector_Adaptor (const Vector_Adaptor< BBVec > &A)
Vector_Adaptor (Subscript N, char *s)
Vector_Adaptor (Subscript N, const T &value=T())
Vector_Adaptor (Subscript N, const T *values)
Vector_Adaptor (const BBVec &A)
Vector_Adaptor< BBVec > & free ()
Vector_Adaptor< BBVec > & operator= (const Vector_Adaptor< BBVec > &A)
Vector_Adaptor< BBVec > & newsize (Subscript N)
Vector_Adaptor< BBVec > & operator= (const T &a)
Vector_Adaptor< BBVec > & resize (Subscript N)
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator[] (Subscript i)
const_reference operator[] (Subscript i) const
Protected Attributes
BBVec v_
T * vm1_
Detailed Description
template<class BBVec>
class TNT::Vector_Adaptor< BBVec >
Definition at line 60 of file vecadaptor.h.
Member Typedef Documentation
template<class BBVec> typedef const T* TNT::Vector_Adaptor< BBVec >::const_iterator
Definition at line 70 of file vecadaptor.h.
template<class BBVec> typedef const T& TNT::Vector_Adaptor< BBVec >::const_reference
Definition at line 71 of file vecadaptor.h.
template<class BBVec> typedef T TNT::Vector_Adaptor< BBVec >::element_type
Definition at line 66 of file vecadaptor.h.
template<class BBVec> typedef T* TNT::Vector_Adaptor< BBVec >::iterator
Definition at line 68 of file vecadaptor.h.
template<class BBVec> typedef T* TNT::Vector_Adaptor< BBVec >::pointer
Definition at line 67 of file vecadaptor.h.
template<class BBVec> typedef T& TNT::Vector_Adaptor< BBVec >::reference
Definition at line 69 of file vecadaptor.h.
template<class BBVec> typedef BBVec::value_type TNT::Vector_Adaptor< BBVec >::T
Definition at line 64 of file vecadaptor.h.
template<class BBVec> typedef T TNT::Vector_Adaptor< BBVec >::value_type
Definition at line 65 of file vecadaptor.h.
Constructor & Destructor Documentation
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor () [inline]
Definition at line 108 of file vecadaptor.h.
: v_() {};
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor (const Vector_Adaptor< BBVec > & A) [inline]
Definition at line 109 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
                                                   : v_(A.v_)
    {
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
    }
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor (Subscript N, char * s) [inline]
Definition at line 115 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
                                                   : v_(N)
    {
        istrstream ins(s);
        for (Subscript i=0; i<N; i++)
            ins >> v_[i] ;
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
    };
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor (Subscript N, const T & value = T()) [inline]
Definition at line 124 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
                                                      : v_(N)
    {
        for (Subscript i=0; i<N; i++)
             v_[i]  = value;
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
    }
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor (Subscript N, const T * values) [inline]
Definition at line 132 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
                                                 : v_(N)
    {
        for (Subscript i=0; i<N; i++)
             v_[i]  = values[i];
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
    }
template<class BBVec> TNT::Vector_Adaptor< BBVec >::Vector_Adaptor (const BBVec & A) [inline]
Definition at line 138 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
                                    : v_(A)
    {
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
    }
Member Function Documentation
template<class BBVec> Subscript TNT::Vector_Adaptor< BBVec >::dim () const [inline]
Definition at line 100 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_.
Referenced by TNT::Vector_Adaptor< BBVec >::operator()(), and TNT::Vector_Adaptor< BBVec >::operator[]().
{ return v_.size(); }
template<class BBVec> Subscript TNT::Vector_Adaptor< BBVec >::dim (Subscript i) [inline]
Definition at line 101 of file vecadaptor.h.
References TNT_BASE_OFFSET, and TNT::Vector_Adaptor< BBVec >::v_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(i==TNT_BASE_OFFSET);
#endif
        return (i==TNT_BASE_OFFSET ? v_.size() : 0 );
    }
template<class BBVec> Vector_Adaptor<BBVec>& TNT::Vector_Adaptor< BBVec >::free () [inline]
Definition at line 148 of file vecadaptor.h.
    {
        return *this = Vector_Adaptor<BBVec>(0);
    }
template<class BBVec> BBVec& TNT::Vector_Adaptor< BBVec >::getVector () [inline]
Definition at line 99 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_.
{ return v_; }
template<class BBVec> Subscript TNT::Vector_Adaptor< BBVec >::lbound () const [inline]
Definition at line 73 of file vecadaptor.h.
{ return 1; }
template<class BBVec> Vector_Adaptor<BBVec>& TNT::Vector_Adaptor< BBVec >::newsize (Subscript N) [inline]
Definition at line 160 of file vecadaptor.h.
    {
        // NOTE: this is not as efficient as it could be
        // but to retain compatiblity with STL interface
        // we cannot assume underlying implementation
        // has a newsize() function.
        return *this = Vector_Adaptor<BBVec>(N);
    }
template<class BBVec> reference TNT::Vector_Adaptor< BBVec >::operator() (Subscript i) [inline]
Definition at line 198 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::dim(), and TNT::Vector_Adaptor< BBVec >::vm1_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=dim());
#endif
        return vm1_[i];
    }
template<class BBVec> const_reference TNT::Vector_Adaptor< BBVec >::operator() (Subscript i) const [inline]
Definition at line 207 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::dim(), and TNT::Vector_Adaptor< BBVec >::vm1_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=dim());
#endif
        return vm1_[i];
    }
template<class BBVec> Vector_Adaptor<BBVec>& TNT::Vector_Adaptor< BBVec >::operator= (const T & a) [inline]
Definition at line 171 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_.
    {
        Subscript i;
        Subscript N = v_.size();
        for (i=0; i<N; i++)
            v_[i] = a;
        return *this;
    }
template<class BBVec> Vector_Adaptor<BBVec>& TNT::Vector_Adaptor< BBVec >::operator= (const Vector_Adaptor< BBVec > & A) [inline]
Definition at line 153 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_, and TNT::Vector_Adaptor< BBVec >::vm1_.
    {
        v_ = A.v_ ;
        vm1_ = ( v_.size() > 0 ? &(v_[0]) -1 : NULL);
        return *this;
    }
template<class BBVec> reference TNT::Vector_Adaptor< BBVec >::operator[] (Subscript i) [inline]
Definition at line 216 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::dim(), and TNT::Vector_Adaptor< BBVec >::v_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i<dim());
#endif
        return v_[i];
    }
template<class BBVec> const_reference TNT::Vector_Adaptor< BBVec >::operator[] (Subscript i) const [inline]
Definition at line 225 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::dim(), and TNT::Vector_Adaptor< BBVec >::v_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i<dim());
#endif
        return v_[i];
    }
template<class BBVec> Vector_Adaptor<BBVec>& TNT::Vector_Adaptor< BBVec >::resize (Subscript N) [inline]
Definition at line 181 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::size(), and TNT::Vector_Adaptor< BBVec >::v_.
Referenced by TNT::operator>>().
    {
        if (N == size()) return *this;
        Vector_Adaptor<BBVec> tmp(N);
        Subscript n =  (N < size() ? N : size());  // min(N, size());
        Subscript i;
        for (i=0; i<n; i++)
            tmp[i] = v_[i];
        return (*this = tmp);
    }
template<class BBVec> Subscript TNT::Vector_Adaptor< BBVec >::size () const [inline]
Definition at line 81 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::v_.
Referenced by TNT::Vector_Adaptor< BBVec >::resize().
{ return v_.size(); }
Member Data Documentation
template<class BBVec> BBVec TNT::Vector_Adaptor< BBVec >::v_ [protected]
Definition at line 76 of file vecadaptor.h.
Referenced by TNT::Vector_Adaptor< BBVec >::dim(), TNT::Vector_Adaptor< BBVec >::getVector(), TNT::Vector_Adaptor< BBVec >::operator=(), TNT::Vector_Adaptor< BBVec >::operator[](), TNT::Vector_Adaptor< BBVec >::resize(), TNT::Vector_Adaptor< BBVec >::size(), and TNT::Vector_Adaptor< BBVec >::Vector_Adaptor().
template<class BBVec> T* TNT::Vector_Adaptor< BBVec >::vm1_ [protected]
Definition at line 77 of file vecadaptor.h.
Referenced by TNT::Vector_Adaptor< BBVec >::operator()(), TNT::Vector_Adaptor< BBVec >::operator=(), and TNT::Vector_Adaptor< BBVec >::Vector_Adaptor().
The documentation for this class was generated from the following file:
vecadaptor.h