NetTrader: NT3D_camera_vp_o Class Reference
NT3D_camera_vp_o Class Reference
NT3D_camera_vp_o class Provides a viewport with a universe rendered though the view of an camera abstraction.
#include <nt3d_camera_vp_obj.h>
Public Member Functions
NT3D_camera_vp_o ()
NT3D_camera_vp_o (NT3D_camera_o *newCameraPtr)
NT3D_camera_vp_o (const NT3D_camera_vp_o &original)
const NT3D_camera_vp_o & operator= (const NT3D_camera_vp_o &right)
virtual ~NT3D_camera_vp_o ()
void Draw ()
NTbool SetCamera (NT3D_camera_o *newCameraPtr)
NTbool _hasCamera ()
void RotateX (const NTreal deltaRotX)
void RotateY (const NTreal deltaRotY)
void RotateZ (const NTreal deltaRotZ)
void SetRotationX (const NTreal rotX)
void SetRotationY (const NTreal rotY)
void SetRotationZ (const NTreal rotZ)
void TranslateX (const NTreal deltaTraX)
void TranslateY (const NTreal deltaTraY)
void TranslateZ (const NTreal deltaTraZ)
void SetTranslationX (const NTreal traX)
void SetTranslationY (const NTreal traY)
void SetTranslationZ (const NTreal traZ)
void SetTranslationXYZ (const NT_vector3_o &oTra)
void SetTarget (const NT_vector3_o &oTarget)
Protected Member Functions
virtual void DrawScene ()=0
void RedrawChild ()
NTreturn ResizeChild (NTsize width, NTsize height)
void InitChild ()
Protected Attributes
NT3D_camera_o * cameraPtr
Detailed Description
Bug:
unknown
Warning:
do not override Draw() use DrawScene() instead!
Definition at line 81 of file nt3d_camera_vp_obj.h.
Constructor & Destructor Documentation
NT3D_camera_vp_o::NT3D_camera_vp_o ()
NT3D_camera_vp_o::NT3D_camera_vp_o (NT3D_camera_o * newCameraPtr)
NT3D_camera_vp_o::NT3D_camera_vp_o (const NT3D_camera_vp_o & original)
virtual NT3D_camera_vp_o::~NT3D_camera_vp_o () [virtual]
Member Function Documentation
NTbool NT3D_camera_vp_o::_hasCamera () [inline]
Definition at line 87 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
void NT3D_camera_vp_o::Draw () [virtual]
Implements NT3D_abstract_vp_o.
virtual void NT3D_camera_vp_o::DrawScene () [protected, pure virtual]
Implemented in NT3D_universe_camera_vp_o.
void NT3D_camera_vp_o::InitChild () [protected, virtual]
Implements NT3D_abstract_vp_o.
const NT3D_camera_vp_o& NT3D_camera_vp_o::operator= (const NT3D_camera_vp_o & right)
void NT3D_camera_vp_o::RedrawChild () [inline, protected, virtual]
Implements NT3D_abstract_vp_o.
Definition at line 109 of file nt3d_camera_vp_obj.h.
:
NTreturn NT3D_camera_vp_o::ResizeChild (NTsize width, NTsize height) [protected, virtual]
Implements NT3D_abstract_vp_o.
void NT3D_camera_vp_o::RotateX (const NTreal deltaRotX) [inline]
Definition at line 88 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
void NT3D_camera_vp_o::RotateY (const NTreal deltaRotY) [inline]
Definition at line 89 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
void NT3D_camera_vp_o::RotateZ (const NTreal deltaRotZ) [inline]
Definition at line 90 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
NTbool NT3D_camera_vp_o::SetCamera (NT3D_camera_o * newCameraPtr)
void NT3D_camera_vp_o::SetRotationX (const NTreal rotX) [inline]
Definition at line 91 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
void NT3D_camera_vp_o::SetRotationY (const NTreal rotY) [inline]
Definition at line 92 of file nt3d_camera_vp_obj.h.
{ return haveCamera;}
void NT3D_camera_vp_o::SetRotationZ (const NTreal rotZ) [inline]
Definition at line 93 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::RotateX().
{ cameraPtr->RotateX(deltaRotX);}
void NT3D_camera_vp_o::SetTarget (const NT_vector3_o & oTarget) [inline]
Definition at line 101 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::TranslateZ().
{ cameraPtr->TranslateZ(deltaTraZ);}
void NT3D_camera_vp_o::SetTranslationX (const NTreal traX) [inline]
Definition at line 97 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::SetRotationY().
{ cameraPtr->SetRotationY(rotY); }
void NT3D_camera_vp_o::SetTranslationXYZ (const NT_vector3_o & oTra) [inline]
Definition at line 100 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::TranslateY().
{ cameraPtr->TranslateY(deltaTraY);}
void NT3D_camera_vp_o::SetTranslationY (const NTreal traY) [inline]
Definition at line 98 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::SetRotationZ().
{ cameraPtr->SetRotationZ(rotZ); }
void NT3D_camera_vp_o::SetTranslationZ (const NTreal traZ) [inline]
Definition at line 99 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::TranslateX().
{ cameraPtr->TranslateX(deltaTraX);}
void NT3D_camera_vp_o::TranslateX (const NTreal deltaTraX) [inline]
Definition at line 94 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::RotateY().
{ cameraPtr->RotateY(deltaRotY);}
void NT3D_camera_vp_o::TranslateY (const NTreal deltaTraY) [inline]
Definition at line 95 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::RotateZ().
{ cameraPtr->RotateZ(deltaRotZ);}
void NT3D_camera_vp_o::TranslateZ (const NTreal deltaTraZ) [inline]
Definition at line 96 of file nt3d_camera_vp_obj.h.
References cameraPtr, and NT3D_object_o::SetRotationX().
{ cameraPtr->SetRotationX(rotX); }
Member Data Documentation
NT3D_camera_o* NT3D_camera_vp_o::cameraPtr [protected]
Definition at line 113 of file nt3d_camera_vp_obj.h.
Referenced by SetRotationZ(), SetTarget(), SetTranslationX(), SetTranslationXYZ(), SetTranslationY(), SetTranslationZ(), TranslateX(), TranslateY(), and TranslateZ().
The documentation for this class was generated from the following file:
nt3d_camera_vp_obj.h