NetTrader: NTBP_membrane_current_o Class Reference
NTBP_membrane_current_o Class Reference
NTBP_membrane_current_o class Represents the current accross a membrane, with its generalisable properties.
#include <ntbp_membrane_current_obj.h>
Public Member Functions
NTBP_membrane_current_o (NTreal reversalPotential)
NTBP_membrane_current_o (const NTBP_membrane_current_o &original)
const NTBP_membrane_current_o & operator= (const NTBP_membrane_current_o &right)
virtual ~NTBP_membrane_current_o ()
virtual NTreal _maxConductivity () const =0
NTreal _current () const
momentary current in nA
NTreal _conductance () const
momentary conductance in muFarad
void Set_reversalPotential (NTreal eRev)
reversal potential in mV
NTreal _reversalPotential () const
reversal potential in mV
NTreal _temperature () const
temperature in Celsius
NTreturn Set_temperature (NTreal newTemp)
Set temperature in Celsius.
NTreal _q10 () const
Q10.
NTreturn Set_q10 (NTreal newQ10)
Set Q10.
enum NTBPstochasticType _simulationMode () const
Simulation mode.
virtual void SetSimulationMode (enum NTBPstochasticType newMode)
Set simulation mode.
NTreturn Step (NTreal newVm)
NTreal ComputeCurrent (NTreal vM)
virtual NTreturn StepCurrent ()=0
virtual NTreal ComputeConductance ()=0
compute and return conductance in mSiemens
virtual void ComputeRateConstants (NTreal vM)=0
compute the rate constants (in ms^-1)
virtual NTreal OpenChannels () const
Number of open ionic channels.
virtual NTreal NumChannels () const
Total number of ionic channels.
virtual NTreal OpenChannelsRatio () const
Number of open over total number of channels.
virtual void ShowParam () const
virtual NTreal ComputeChannelStateTimeConstant () const
NTreal ChannelStateTimeConstant () const
bool GillespieStep ()
virtual bool ComputeGillespieStep ()
Protected Member Functions
NTreal Set_current (NTreal newVal)
NTreal Set_conductance (NTreal newVal)
Protected Attributes
NT_uniform_rnd_dist_o uniform
Detailed Description
It computes the actual currents based on the Nernst-Equation accross the membrane neglecting diffusion/concentration effects and the conductivity values provided by the hh_current or channel_current classes.
Bug:
unknown
Warning:
unknown
Definition at line 67 of file ntbp_membrane_current_obj.h.
Constructor & Destructor Documentation
NTBP_membrane_current_o::NTBP_membrane_current_o (NTreal reversalPotential)
NTBP_membrane_current_o::NTBP_membrane_current_o (const NTBP_membrane_current_o & original)
virtual NTBP_membrane_current_o::~NTBP_membrane_current_o () [virtual]
Member Function Documentation
NTreal NTBP_membrane_current_o::_conductance () const [inline]
Definition at line 81 of file ntbp_membrane_current_obj.h.
Referenced by NTBP_hh_sga_leak_current_o::ComputeConductance(), ComputeCurrent(), and NTBP_hh_sga_leak_current_o::Show().
{ return conductance; }
NTreal NTBP_membrane_current_o::_current () const [inline]
Definition at line 79 of file ntbp_membrane_current_obj.h.
{ /*cerr << "Current in nA" << current << endl*/; return current; }
virtual NTreal NTBP_membrane_current_o::_maxConductivity () const [pure virtual]
Implemented in NTBP_channels_current_o, NTBP_hh_current_o, and NTBP_multi_current_o.
NTreal NTBP_membrane_current_o::_q10 () const [inline]
Definition at line 91 of file ntbp_membrane_current_obj.h.
{return q10;}
NTreal NTBP_membrane_current_o::_reversalPotential () const [inline]
Definition at line 85 of file ntbp_membrane_current_obj.h.
Referenced by ComputeCurrent().
{ return reversalPotential; }
enum NTBPstochasticType NTBP_membrane_current_o::_simulationMode () const [inline]
Definition at line 95 of file ntbp_membrane_current_obj.h.
{ return simulationMode; }
NTreal NTBP_membrane_current_o::_temperature () const [inline]
Definition at line 87 of file ntbp_membrane_current_obj.h.
{ return temperature; }
NTreal NTBP_membrane_current_o::ChannelStateTimeConstant () const [inline]
Definition at line 116 of file ntbp_membrane_current_obj.h.
References ComputeChannelStateTimeConstant().
{ return ComputeChannelStateTimeConstant();}
virtual NTreal NTBP_membrane_current_o::ComputeChannelStateTimeConstant () const [inline, virtual]
Reimplemented in NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_delayed_potassium_rectifier_current_o, NTBP_hh_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, NTBP_multi_sodium_current_o, and NTBP_sga_sodium_current_o.
Definition at line 115 of file ntbp_membrane_current_obj.h.
Referenced by ChannelStateTimeConstant().
{ cerr << "NTBP_membrane_current_o::ComputeChannelStateTimeConstant - Error : Method should be overridden by a stochastic current class or not be called for a deterministic current class."<< endl; return 0;}
virtual NTreal NTBP_membrane_current_o::ComputeConductance () [pure virtual]
Implemented in NTBP_channels_current_o, NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_delayed_potassium_rectifier_current_o, NTBP_hh_sga_leak_current_o, NTBP_hh_sga_potassium_current_o, NTBP_hh_sga_sodium_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, NTBP_multi_sodium_current_o, and NTBP_patlak_sodium_multi_current_o.
Referenced by Step().
NTreal NTBP_membrane_current_o::ComputeCurrent (NTreal vM) [inline]
Definition at line 101 of file ntbp_membrane_current_obj.h.
References _conductance(), _reversalPotential(), and Set_current().
Referenced by Step().
{ return Set_current(_conductance() /* mSiemens */ * 1000.0 /* mA/nA */ * (vM /* mV */- _reversalPotential()/* mV */));}
virtual bool NTBP_membrane_current_o::ComputeGillespieStep () [inline, virtual]
Reimplemented in NTBP_channels_current_o, and NTBP_multi_current_o.
Definition at line 118 of file ntbp_membrane_current_obj.h.
Referenced by GillespieStep().
{ cerr << "NTBP_membrane_current_o::ComputeGillespieStep- Error : Method should be overridden by a stochastic current class or not be called for a deterministic current class."<< endl; return NT_NOT_DERIVED;}
virtual void NTBP_membrane_current_o::ComputeRateConstants (NTreal vM) [pure virtual]
Implemented in NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_delayed_potassium_rectifier_current_o, NTBP_hh_sga_leak_current_o, NTBP_hh_sga_potassium_current_o, NTBP_hh_sga_sodium_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, NTBP_multi_sodium_current_o, NTBP_patlak_sodium_multi_current_o, and NTBP_sga_sodium_current_o.
Referenced by Step().
bool NTBP_membrane_current_o::GillespieStep () [inline]
Definition at line 117 of file ntbp_membrane_current_obj.h.
References ComputeGillespieStep(), and StepCurrent().
{/*2DO is this necessary here*/StepCurrent();return ComputeGillespieStep();}
virtual NTreal NTBP_membrane_current_o::NumChannels () const [inline, virtual]
Reimplemented in NTBP_multi_current_o.
Definition at line 110 of file ntbp_membrane_current_obj.h.
{ cerr <<"NTBP_membrane_current_o::NumChannels() - Error : Not Implemented." << endl; return -42; }
virtual NTreal NTBP_membrane_current_o::OpenChannels () const [inline, virtual]
Reimplemented in NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, NTBP_multi_sodium_current_o, and NTBP_patlak_sodium_multi_current_o.
Definition at line 108 of file ntbp_membrane_current_obj.h.
Referenced by NTBP_multi_current_o::OpenChannelsRatio().
{ cerr <<"NTBP_membrane_current_o::OpenChannels() - Error : Not Implemented." << endl; return -42; }
virtual NTreal NTBP_membrane_current_o::OpenChannelsRatio () const [inline, virtual]
Reimplemented in NTBP_hh_sga_potassium_current_o, NTBP_hh_sga_sodium_current_o, and NTBP_multi_current_o.
Definition at line 112 of file ntbp_membrane_current_obj.h.
{ cerr <<"NTBP_membrane_current_o::OpenChannelsRatio() - Error : Not Implemented." << endl; return -42; }
const NTBP_membrane_current_o& NTBP_membrane_current_o::operator= (const NTBP_membrane_current_o & right)
NTreal NTBP_membrane_current_o::Set_conductance (NTreal newVal) [inline, protected]
Definition at line 126 of file ntbp_membrane_current_obj.h.
Referenced by NTBP_delayed_potassium_rectifier_current_o::ComputeConductance(), and NTBP_hh_sga_leak_current_o::UpdateConductance().
{ return conductance = newVal;}
NTreal NTBP_membrane_current_o::Set_current (NTreal newVal) [inline, protected]
Definition at line 125 of file ntbp_membrane_current_obj.h.
Referenced by ComputeCurrent().
{ return current = newVal; }
NTreturn NTBP_membrane_current_o::Set_q10 (NTreal newQ10) [inline]
Definition at line 93 of file ntbp_membrane_current_obj.h.
{ q10 = newQ10; return NT_SUCCESS; }
void NTBP_membrane_current_o::Set_reversalPotential (NTreal eRev) [inline]
Definition at line 83 of file ntbp_membrane_current_obj.h.
{ reversalPotential = eRev;}
NTreturn NTBP_membrane_current_o::Set_temperature (NTreal newTemp) [inline]
Definition at line 89 of file ntbp_membrane_current_obj.h.
References NT_0_KELVIN, and NT_ASSERT.
{ NT_ASSERT(newTemp > NT_0_KELVIN); temperature = newTemp; return NT_SUCCESS;}
virtual void NTBP_membrane_current_o::SetSimulationMode (enum NTBPstochasticType newMode) [inline, virtual]
Definition at line 97 of file ntbp_membrane_current_obj.h.
{ simulationMode = newMode; }
virtual void NTBP_membrane_current_o::ShowParam () const [inline, virtual]
Reimplemented in NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, and NTBP_multi_sodium_current_o.
Definition at line 113 of file ntbp_membrane_current_obj.h.
{ cerr << "NTBP_membrane_current_o::ShowParam - Warning : Not Implemented."<< endl;}
NTreturn NTBP_membrane_current_o::Step (NTreal newVm) [inline]
Definition at line 99 of file ntbp_membrane_current_obj.h.
References ComputeConductance(), ComputeCurrent(), ComputeRateConstants(), and StepCurrent().
{ ComputeRateConstants(newVm); /* UpdateRateConstantsAND*/StepCurrent(); ComputeConductance(); ComputeCurrent(newVm); return NT_SUCCESS;}
virtual NTreturn NTBP_membrane_current_o::StepCurrent () [pure virtual]
Implemented in NTBP_colbert_axonal_potassium_multi_current_o, NTBP_colbert_axonal_sodium_multi_current_o, NTBP_delayed_potassium_rectifier_current_o, NTBP_hh_sga_leak_current_o, NTBP_hh_sga_potassium_current_o, NTBP_hh_sga_sodium_current_o, NTBP_hranvier_potassium_multi_current_o, NTBP_hranvier_sodium_multi_current_o, NTBP_multi_potassium_current_o, NTBP_multi_sodium_current_o, NTBP_patlak_sodium_multi_current_o, and NTBP_sga_sodium_current_o.
Referenced by GillespieStep(), and Step().
Member Data Documentation
NT_uniform_rnd_dist_o NTBP_membrane_current_o::uniform [protected]
Definition at line 128 of file ntbp_membrane_current_obj.h.
The documentation for this class was generated from the following file:
ntbp_membrane_current_obj.h