NetTrader: NTG_edge_o Class Reference
NTG_edge_o Class Reference
NTG_edge_o class This base class mimics <pair<NTid, NTid>>
#include <ntg_edge_obj.h>
Public Member Functions
NTG_edge_o (NTid newSource=0, NTid newTarget=0)
NTG_edge_o (const NTG_edge_o &original)
const NTG_edge_o & operator= (const NTG_edge_o &right)
virtual ~NTG_edge_o ()
NTid first () const
NTid Source () const
NTid second () const
NTid Target () const
NTreturn SetSource (NTid newSource)
NTreturn SetTarget (NTid newTarget)
NTreturn SetConnection (NTid newSource, NTid newTarget)
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 56 of file ntg_edge_obj.h.
Constructor & Destructor Documentation
NTG_edge_o::NTG_edge_o (NTid newSource = 0, NTid newTarget = 0)
NTG_edge_o::NTG_edge_o (const NTG_edge_o & original)
virtual NTG_edge_o::~NTG_edge_o () [virtual]
Member Function Documentation
NTid NTG_edge_o::first () const [inline]
Definition at line 64 of file ntg_edge_obj.h.
References Source().
{ return Source();}
const NTG_edge_o& NTG_edge_o::operator= (const NTG_edge_o & right)
NTid NTG_edge_o::second () const [inline]
Definition at line 66 of file ntg_edge_obj.h.
References Target().
{ return Target();}
NTreturn NTG_edge_o::SetConnection (NTid newSource, NTid newTarget)
NTreturn NTG_edge_o::SetSource (NTid newSource) [inline]
Definition at line 69 of file ntg_edge_obj.h.
{ return NT_NOT_IMPLEMENTED;}
NTreturn NTG_edge_o::SetTarget (NTid newTarget) [inline]
Definition at line 70 of file ntg_edge_obj.h.
{ return NT_NOT_IMPLEMENTED;}
NTid NTG_edge_o::Source () const [inline]
Definition at line 65 of file ntg_edge_obj.h.
Referenced by first().
{ return source;}
NTid NTG_edge_o::Target () const [inline]
Definition at line 67 of file ntg_edge_obj.h.
Referenced by second().
{ return target;}
The documentation for this class was generated from the following file:
ntg_edge_obj.h