NetTrader: TNT::Fortran_Matrix< T > Class Template Reference
TNT::Fortran_Matrix< T > Class Template Reference
#include <fmat.h>
Public Types
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
T * begin ()
const T * begin () const
T * end ()
const T * end () const
Fortran_Matrix ()
Fortran_Matrix (const Fortran_Matrix< T > &A)
Fortran_Matrix (Subscript M, Subscript N, const T &value=T())
Fortran_Matrix (Subscript M, Subscript N, const T *v)
Fortran_Matrix (Subscript M, Subscript N, char *s)
~Fortran_Matrix ()
Fortran_Matrix< T > & operator= (const Fortran_Matrix< T > &A)
Fortran_Matrix< T > & operator= (const T &scalar)
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
Fortran_Matrix< T > & newsize (Subscript M, Subscript N)
reference operator() (Subscript i, Subscript j)
const_reference operator() (Subscript i, Subscript j) const
Protected Member Functions
void initialize (Subscript M, Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
Protected Attributes
T * v_
Subscript m_
Subscript n_
T ** col_
Detailed Description
template<class T>
class TNT::Fortran_Matrix< T >
Definition at line 47 of file fmat.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Fortran_Matrix< T >::const_iterator
Definition at line 58 of file fmat.h.
template<class T> typedef const T& TNT::Fortran_Matrix< T >::const_reference
Definition at line 59 of file fmat.h.
template<class T> typedef T TNT::Fortran_Matrix< T >::element_type
Definition at line 54 of file fmat.h.
template<class T> typedef T* TNT::Fortran_Matrix< T >::iterator
Definition at line 56 of file fmat.h.
template<class T> typedef T* TNT::Fortran_Matrix< T >::pointer
Definition at line 55 of file fmat.h.
template<class T> typedef T& TNT::Fortran_Matrix< T >::reference
Definition at line 57 of file fmat.h.
template<class T> typedef T TNT::Fortran_Matrix< T >::value_type
Definition at line 53 of file fmat.h.
Constructor & Destructor Documentation
template<class T> TNT::Fortran_Matrix< T >::Fortran_Matrix () [inline]
Definition at line 176 of file fmat.h.
: v_(0), m_(0), n_(0), col_(0)  {};
template<class T> TNT::Fortran_Matrix< T >::Fortran_Matrix (const Fortran_Matrix< T > & A) [inline]
Definition at line 177 of file fmat.h.
References TNT::Fortran_Matrix< T >::copy(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
    {
        initialize(A.m_, A.n_);
        copy(A.v_);
    }
template<class T> TNT::Fortran_Matrix< T >::Fortran_Matrix (Subscript M, Subscript N, const T & value = T()) [inline]
Definition at line 183 of file fmat.h.
References TNT::Fortran_Matrix< T >::initialize().
    {
        initialize(M,N);
        set(value);
    }
template<class T> TNT::Fortran_Matrix< T >::Fortran_Matrix (Subscript M, Subscript N, const T * v) [inline]
Definition at line 189 of file fmat.h.
References TNT::Fortran_Matrix< T >::copy(), and TNT::Fortran_Matrix< T >::initialize().
    {
        initialize(M,N);
        copy(v);
    }
template<class T> TNT::Fortran_Matrix< T >::Fortran_Matrix (Subscript M, Subscript N, char * s) [inline]
Definition at line 196 of file fmat.h.
References TNT::Fortran_Matrix< T >::initialize().
    {
        initialize(M,N);
        std::istrstream ins(s);
        Subscript i, j;
        for (i=1; i<=M; i++)
            for (j=1; j<=N; j++)
                ins >> (*this)(i,j);
    }
template<class T> TNT::Fortran_Matrix< T >::~Fortran_Matrix () [inline]
Definition at line 209 of file fmat.h.
References TNT::Fortran_Matrix< T >::destroy().
    {
        destroy();
    }
Member Function Documentation
template<class T> T* TNT::Fortran_Matrix< T >::begin () [inline]
Definition at line 167 of file fmat.h.
References TNT::Fortran_Matrix< T >::v_.
Referenced by TNT::operator*(), and Upper_symmetric_eigenvalue_solve().
{ return v_; }
template<class T> const T* TNT::Fortran_Matrix< T >::begin () const [inline]
Definition at line 168 of file fmat.h.
References TNT::Fortran_Matrix< T >::v_.
{ return v_;}
template<class T> void TNT::Fortran_Matrix< T >::copy (const T * v) [inline, protected]
Definition at line 98 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
Referenced by TNT::Fortran_Matrix< T >::Fortran_Matrix(), and TNT::Fortran_Matrix< T >::operator=().
    {
        Subscript N = m_ * n_;
        Subscript i;
#ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = v[i];
            v_[i+1] = v[i+1];
            v_[i+2] = v[i+2];
            v_[i+3] = v[i+3];
        }
        for (i=N4; i< N; i++)
            v_[i] = v[i];
#else
        for (i=0; i< N; i++)
            v_[i] = v[i];
#endif
    }
template<class T> void TNT::Fortran_Matrix< T >::destroy () [inline, protected]
Definition at line 153 of file fmat.h.
References TNT::Fortran_Matrix< T >::col_, and TNT::Fortran_Matrix< T >::v_.
Referenced by TNT::Fortran_Matrix< T >::newsize(), TNT::Fortran_Matrix< T >::operator=(), and TNT::Fortran_Matrix< T >::~Fortran_Matrix().
    {
        /* do nothing, if no memory has been previously allocated */
        if (v_ == NULL) return ;
        /* if we are here, then matrix was previously allocated */
        delete [] (v_);
        col_ ++;                // changed back to 0-offset
        delete [] (col_);
    }
template<class T> Subscript TNT::Fortran_Matrix< T >::dim (Subscript d) const [inline]
Definition at line 242 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_, and TNT::Fortran_Matrix< T >::n_.
    {
#ifdef TNT_BOUNDS_CHECK
       assert( d >= 1);
        assert( d <= 2);
#endif
        return (d==1) ? m_ : ((d==2) ? n_ : 0);
    }
template<class T> T* TNT::Fortran_Matrix< T >::end () [inline]
Definition at line 170 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
Referenced by TNT::operator*().
{ return v_ + m_*n_; }
template<class T> const T* TNT::Fortran_Matrix< T >::end () const [inline]
Definition at line 171 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
{ return v_ + m_*n_; }
template<class T> void TNT::Fortran_Matrix< T >::initialize (Subscript M, Subscript N) [inline, protected]
Definition at line 72 of file fmat.h.
References TNT::Fortran_Matrix< T >::col_, TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
Referenced by TNT::Fortran_Matrix< T >::Fortran_Matrix(), TNT::Fortran_Matrix< T >::newsize(), and TNT::Fortran_Matrix< T >::operator=().
    {
        // adjust col_[] pointers so that they are 1-offset:
        //   col_[j][i] is really col_[j-1][i-1];
        //
        // v_[] is the internal contiguous array, it is still 0-offset
        //
        v_ = new T[M*N];
        col_ = new T*[N];
        assert(v_  != NULL);
        assert(col_ != NULL);
        m_ = M;
        n_ = N;
        T* p = v_ - 1;
        for (Subscript i=0; i<N; i++)
        {
            col_[i] = p;
            p += M ;
        }
        col_ --;
    }
template<class T> Subscript TNT::Fortran_Matrix< T >::lbound () const [inline]
Definition at line 61 of file fmat.h.
{ return 1;}
template<class T> Fortran_Matrix<T>& TNT::Fortran_Matrix< T >::newsize (Subscript M, Subscript N) [inline]
Definition at line 254 of file fmat.h.
References TNT::Fortran_Matrix< T >::destroy(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
Referenced by TNT::matmult(), and TNT::operator>>().
    {
        if (num_rows() == M && num_cols() == N)
            return *this;
        destroy();
        initialize(M,N);
        return *this;
    }
template<class T> Subscript TNT::Fortran_Matrix< T >::num_cols () const [inline]
Definition at line 252 of file fmat.h.
References TNT::Fortran_Matrix< T >::n_.
Referenced by eigenvalue_solve(), Lapack_LLS_QR_linear_solve(), Lapack_LU_linear_solve(), TNT::matmult(), TNT::mult_element(), TNT::Fortran_Matrix< T >::newsize(), TNT::operator*(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), TNT::transpose(), and Upper_symmetric_eigenvalue_solve().
{ return n_; }
template<class T> Subscript TNT::Fortran_Matrix< T >::num_rows () const [inline]
Definition at line 251 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_.
Referenced by eigenvalue_solve(), Lapack_LLS_QR_linear_solve(), Lapack_LU_linear_solve(), TNT::matmult(), TNT::mult_element(), TNT::Fortran_Matrix< T >::newsize(), TNT::operator*(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), TNT::transpose(), and Upper_symmetric_eigenvalue_solve().
{ return m_; }
template<class T> reference TNT::Fortran_Matrix< T >::operator() (Subscript i, Subscript j) [inline]
Definition at line 269 of file fmat.h.
References TNT::Fortran_Matrix< T >::col_, TNT::Fortran_Matrix< T >::m_, and TNT::Fortran_Matrix< T >::n_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= m_) ;
        assert(1<=j);
        assert(j <= n_);
#endif
        return col_[j][i];
    }
template<class T> const_reference TNT::Fortran_Matrix< T >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 280 of file fmat.h.
References TNT::Fortran_Matrix< T >::col_, TNT::Fortran_Matrix< T >::m_, and TNT::Fortran_Matrix< T >::n_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= m_) ;
        assert(1<=j);
        assert(j <= n_);
#endif
        return col_[j][i];
    }
template<class T> Fortran_Matrix<T>& TNT::Fortran_Matrix< T >::operator= (const T & scalar) [inline]
Definition at line 235 of file fmat.h.
    {
        set(scalar);
        return *this;
    }
template<class T> Fortran_Matrix<T>& TNT::Fortran_Matrix< T >::operator= (const Fortran_Matrix< T > & A) [inline]
Definition at line 217 of file fmat.h.
References TNT::Fortran_Matrix< T >::copy(), TNT::Fortran_Matrix< T >::destroy(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
    {
        if (v_ == A.v_)
            return *this;
        if (m_ == A.m_  && n_ == A.n_)      // no need to re-alloc
            copy(A.v_);
        else
        {
            destroy();
            initialize(A.m_, A.n_);
            copy(A.v_);
        }
        return *this;
    }
template<class T> void TNT::Fortran_Matrix< T >::set (const T & val) [inline, protected]
Definition at line 124 of file fmat.h.
References TNT::Fortran_Matrix< T >::m_, TNT::Fortran_Matrix< T >::n_, and TNT::Fortran_Matrix< T >::v_.
    {
        Subscript N = m_ * n_;
        Subscript i;
#ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = val;
            v_[i+1] = val;
            v_[i+2] = val;
            v_[i+3] = val;
        }
        for (i=N4; i< N; i++)
            v_[i] = val;
#else
        for (i=0; i< N; i++)
            v_[i] = val;
#endif
    }
Member Data Documentation
template<class T> T** TNT::Fortran_Matrix< T >::col_ [protected]
Definition at line 67 of file fmat.h.
Referenced by TNT::Fortran_Matrix< T >::destroy(), TNT::Fortran_Matrix< T >::initialize(), and TNT::Fortran_Matrix< T >::operator()().
template<class T> Subscript TNT::Fortran_Matrix< T >::m_ [protected]
Definition at line 65 of file fmat.h.
Referenced by TNT::Fortran_Matrix< T >::copy(), TNT::Fortran_Matrix< T >::dim(), TNT::Fortran_Matrix< T >::end(), TNT::Fortran_Matrix< T >::Fortran_Matrix(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::num_rows(), TNT::Fortran_Matrix< T >::operator()(), TNT::Fortran_Matrix< T >::operator=(), and TNT::Fortran_Matrix< T >::set().
template<class T> Subscript TNT::Fortran_Matrix< T >::n_ [protected]
Definition at line 66 of file fmat.h.
Referenced by TNT::Fortran_Matrix< T >::copy(), TNT::Fortran_Matrix< T >::dim(), TNT::Fortran_Matrix< T >::end(), TNT::Fortran_Matrix< T >::Fortran_Matrix(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::num_cols(), TNT::Fortran_Matrix< T >::operator()(), TNT::Fortran_Matrix< T >::operator=(), and TNT::Fortran_Matrix< T >::set().
template<class T> T* TNT::Fortran_Matrix< T >::v_ [protected]
Definition at line 64 of file fmat.h.
Referenced by TNT::Fortran_Matrix< T >::begin(), TNT::Fortran_Matrix< T >::copy(), TNT::Fortran_Matrix< T >::destroy(), TNT::Fortran_Matrix< T >::end(), TNT::Fortran_Matrix< T >::Fortran_Matrix(), TNT::Fortran_Matrix< T >::initialize(), TNT::Fortran_Matrix< T >::operator=(), and TNT::Fortran_Matrix< T >::set().
The documentation for this class was generated from the following file:
fmat.h