NetTrader: TNT::Fortran_Sparse_Vector< T > Class Template Reference
TNT::Fortran_Sparse_Vector< T > Class Template Reference
#include <fspvec.h>
Public Types
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
Subscript dim () const
Subscript num_nonzeros () const
T & val (Subscript i)
const T & val (Subscript i) const
Subscript & index (Subscript i)
const Subscript & index (Subscript i) const
Fortran_Sparse_Vector ()
Fortran_Sparse_Vector (Subscript N, Subscript nz)
Fortran_Sparse_Vector (Subscript N, Subscript nz, const T *values, const Subscript *indices)
Fortran_Sparse_Vector (const Fortran_Sparse_Vector< T > &S)
Fortran_Sparse_Vector (Subscript N, Subscript nz, char *v, char *ind)
Fortran_Sparse_Vector< T > & newsize (Subscript N, Subscript nz)
Fortran_Sparse_Vector< T > & operator= (const Fortran_Sparse_Vector< T > &A)
Protected Attributes
Vector< T > val_
Vector< Subscript > index_
Subscript dim_
Detailed Description
template<class T>
class TNT::Fortran_Sparse_Vector< T >
Definition at line 45 of file fspvec.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Fortran_Sparse_Vector< T >::const_iterator
Definition at line 57 of file fspvec.h.
template<class T> typedef const T& TNT::Fortran_Sparse_Vector< T >::const_reference
Definition at line 58 of file fspvec.h.
template<class T> typedef T TNT::Fortran_Sparse_Vector< T >::element_type
Definition at line 53 of file fspvec.h.
template<class T> typedef T* TNT::Fortran_Sparse_Vector< T >::iterator
Definition at line 55 of file fspvec.h.
template<class T> typedef T* TNT::Fortran_Sparse_Vector< T >::pointer
Definition at line 54 of file fspvec.h.
template<class T> typedef T& TNT::Fortran_Sparse_Vector< T >::reference
Definition at line 56 of file fspvec.h.
template<class T> typedef Subscript TNT::Fortran_Sparse_Vector< T >::size_type
Definition at line 51 of file fspvec.h.
template<class T> typedef T TNT::Fortran_Sparse_Vector< T >::value_type
Definition at line 52 of file fspvec.h.
Constructor & Destructor Documentation
template<class T> TNT::Fortran_Sparse_Vector< T >::Fortran_Sparse_Vector () [inline]
Definition at line 85 of file fspvec.h.
: val_(), index_(), dim_(0)  {};
template<class T> TNT::Fortran_Sparse_Vector< T >::Fortran_Sparse_Vector (Subscript N, Subscript nz) [inline]
Definition at line 86 of file fspvec.h.
                                                     : val_(nz),
            index_(nz), dim_(N)  {};
template<class T> TNT::Fortran_Sparse_Vector< T >::Fortran_Sparse_Vector (Subscript N, Subscript nz, const T * values, const Subscript * indices) [inline]
Definition at line 88 of file fspvec.h.
                                 : val_(nz, values), index_(nz, indices),
            dim_(N) {}
template<class T> TNT::Fortran_Sparse_Vector< T >::Fortran_Sparse_Vector (const Fortran_Sparse_Vector< T > & S) [inline]
Definition at line 92 of file fspvec.h.
                                                            :
        val_(S.val_), index_(S.index_), dim_(S.dim_) {}
template<class T> TNT::Fortran_Sparse_Vector< T >::Fortran_Sparse_Vector (Subscript N, Subscript nz, char * v, char * ind) [inline]
Definition at line 99 of file fspvec.h.
                   : val_(nz, v), index_(nz, ind), dim_(N) {}
Member Function Documentation
template<class T> Subscript TNT::Fortran_Sparse_Vector< T >::dim () const [inline]
Definition at line 72 of file fspvec.h.
{ return dim_; }
template<class T> Subscript& TNT::Fortran_Sparse_Vector< T >::index (Subscript i) [inline]
Definition at line 80 of file fspvec.h.
Referenced by TNT::operator>>().
{ return index_(i); }
template<class T> const Subscript& TNT::Fortran_Sparse_Vector< T >::index (Subscript i) const [inline]
Definition at line 81 of file fspvec.h.
{ return index_(i); }
template<class T> Subscript TNT::Fortran_Sparse_Vector< T >::lbound () const [inline]
Definition at line 60 of file fspvec.h.
{ return 1;}
template<class T> Fortran_Sparse_Vector<T>& TNT::Fortran_Sparse_Vector< T >::newsize (Subscript N, Subscript nz) [inline]
Definition at line 104 of file fspvec.h.
Referenced by TNT::operator>>().
    {
        val_.newsize(nz);
        index_.newsize(nz);
        dim_ = N;
        return *this;
    }
template<class T> Subscript TNT::Fortran_Sparse_Vector< T >::num_nonzeros () const [inline]
Definition at line 73 of file fspvec.h.
{ return val_.dim(); }
template<class T> Fortran_Sparse_Vector<T>& TNT::Fortran_Sparse_Vector< T >::operator= (const Fortran_Sparse_Vector< T > & A) [inline]
Definition at line 112 of file fspvec.h.
References TNT::Fortran_Sparse_Vector< T >::dim_, TNT::Fortran_Sparse_Vector< T >::index_, and TNT::Fortran_Sparse_Vector< T >::val_.
    {
        val_ = A.val_;
        index_ = A.index_;
        dim_ = A.dim_;
        return *this;
    }
template<class T> const T& TNT::Fortran_Sparse_Vector< T >::val (Subscript i) const [inline]
Definition at line 78 of file fspvec.h.
{ return val_(i); }
template<class T> T& TNT::Fortran_Sparse_Vector< T >::val (Subscript i) [inline]
Definition at line 77 of file fspvec.h.
Referenced by TNT::operator>>().
{ return val_(i); }
Member Data Documentation
template<class T> Subscript TNT::Fortran_Sparse_Vector< T >::dim_ [protected]
Definition at line 65 of file fspvec.h.
Referenced by TNT::Fortran_Sparse_Vector< T >::operator=().
template<class T> Vector<Subscript> TNT::Fortran_Sparse_Vector< T >::index_ [protected]
Definition at line 64 of file fspvec.h.
Referenced by TNT::Fortran_Sparse_Vector< T >::operator=().
template<class T> Vector<T> TNT::Fortran_Sparse_Vector< T >::val_ [protected]
Definition at line 63 of file fspvec.h.
Referenced by TNT::Fortran_Sparse_Vector< T >::operator=().
The documentation for this class was generated from the following file:
fspvec.h