NetTrader: MTRand Class Reference
MTRand Class Reference
file nt_mersenne_twiser_external_obj.h - uniform random number class 1:1 copy from MersenneTwister.h Mersenne Twister random number generator -- a C++ class MTRand Based on code by Makoto Matsumoto, Takuji Nishimura, and Shawn Cokus Richard J.
#include <nt_mersenne_twister_external_obj.h>
Public Types
enum { N = 624 }
enum { SAVE = N + 1 }
typedef unsigned long uint32
Public Member Functions
MTRand (const uint32 &oneSeed)
MTRand (uint32 *const bigSeed)
MTRand ()
double rand ()
double rand (const double &n)
double randExc ()
double randExc (const double &n)
double randDblExc ()
double randDblExc (const double &n)
uint32 randInt ()
uint32 randInt (const uint32 &n)
double operator() ()
void seed (uint32 oneSeed)
void seed (uint32 *const bigSeed)
void seed ()
void save (uint32 *saveArray) const
void load (uint32 *const loadArray)
Protected Types
enum { M = 397 }
enum { MAGIC = 0x9908b0dfU }
Protected Member Functions
void reload ()
uint32 hiBit (const uint32 &u) const
uint32 loBit (const uint32 &u) const
uint32 loBits (const uint32 &u) const
uint32 mixBits (const uint32 &u, const uint32 &v) const
uint32 twist (const uint32 &m, const uint32 &s0, const uint32 &s1) const
Static Protected Member Functions
static uint32 hash (time_t t, clock_t c)
Protected Attributes
uint32 state [N]
uint32 * pNext
int left
Friends
std::ostream & operator<< (std::ostream &os, const MTRand &mtrand)
std::istream & operator>> (std::istream &is, MTRand &mtrand)
Detailed Description
Wagner v0.7 12 July 2001 rjwagner@writeme.com The Mersenne Twister is an algorithm for generating random numbers. It was designed with consideration of the flaws in various other generators. The period, 2^19937-1, and the order of equidistribution, 623 dimensions, are far greater. The generator is also fast; it avoids multiplication and division, and it benefits from caches and pipelines. For more information see the inventors' web page at http://www.math.keio.ac.jp/~matumoto/emt.html
IMPORTANT: CHECK ON UPDATES FOR THE C++ CODE (AS INITIALISATION WEAKNESS WAS DISCOVERED, 22.2.2002 AAF)
Reference M. Matsumoto and T. Nishimura, "Mersenne Twister: A 623-Dimensionally Equidistributed Uniform Pseudo-Random Number Generator", ACM Transactions on Modeling and Computer Simulation, Vol. 8, No. 1, January 1998, pp 3-30.
Copyright (C) 2001 Richard J. Wagner
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
The original code included the following notice:
Copyright (C) 1997, 1999 Makoto Matsumoto and Takuji Nishimura. When you use this, send an email to: matumoto@math.keio.ac.jp with an appropriate reference to your work.
It would be nice to CC: rjwagner@writeme.com and Cokus@math.washington.edu when you write.
Definition at line 58 of file nt_mersenne_twister_external_obj.h.
Member Typedef Documentation
typedef unsigned long MTRand::uint32
Definition at line 61 of file nt_mersenne_twister_external_obj.h.
Member Enumeration Documentation
anonymous enum
Enumerator:
N
Definition at line 62 of file nt_mersenne_twister_external_obj.h.
{ N = 624 };              // length of state vector
anonymous enum
Enumerator:
SAVE
Definition at line 63 of file nt_mersenne_twister_external_obj.h.
{ SAVE = N + 1 };         // length of array for save()
anonymous enum [protected]
Enumerator:
M
Definition at line 66 of file nt_mersenne_twister_external_obj.h.
{ M = 397 };              // period parameter
anonymous enum [protected]
Enumerator:
MAGIC
Definition at line 67 of file nt_mersenne_twister_external_obj.h.
{ MAGIC = 0x9908b0dfU };  // magic constant
Constructor & Destructor Documentation
MTRand::MTRand (const uint32 & oneSeed) [inline]
Definition at line 118 of file nt_mersenne_twister_external_obj.h.
References seed().
    { seed(oneSeed); }
MTRand::MTRand (uint32 *const bigSeed) [inline]
Definition at line 121 of file nt_mersenne_twister_external_obj.h.
References seed().
    { seed(bigSeed); }
MTRand::MTRand () [inline]
Definition at line 124 of file nt_mersenne_twister_external_obj.h.
References seed().
    { seed(); }
Member Function Documentation
MTRand::uint32 MTRand::hash (time_t t, clock_t c) [inline, static, protected]
Definition at line 254 of file nt_mersenne_twister_external_obj.h.
Referenced by seed().
{
    // Get a uint32 from t and c
    // Better than uint32(x) in case x is floating point in [0,1]
    // Based on code by Lawrence Kirby (fred@genesis.demon.co.uk)
    static uint32 differ = 0;  // guarantee time-based seeds will change
    uint32 h1 = 0;
    unsigned char *p = (unsigned char *) &t;
    for( size_t i = 0; i < sizeof(t); ++i )
    {
        h1 *= UCHAR_MAX + 2U;
        h1 += p[i];
    }
    uint32 h2 = 0;
    p = (unsigned char *) &c;
    for( size_t j = 0; j < sizeof(c); ++j )
    {
        h2 *= UCHAR_MAX + 2U;
        h2 += p[j];
    }
    return ( h1 + differ++ ) ^ h2;
}
uint32 MTRand::hiBit (const uint32 & u) const [inline, protected]
Definition at line 107 of file nt_mersenne_twister_external_obj.h.
Referenced by mixBits().
{ return u & 0x80000000U; }
void MTRand::load (uint32 *const loadArray) [inline]
Definition at line 290 of file nt_mersenne_twister_external_obj.h.
References left, N, pNext, and state.
{
    register uint32 *s = state;
    register uint32 *la = loadArray;
    register int i = N;
    for( ; i--; *s++ = *la++ ) {}
    left = *la;
    pNext = &state[N-left];
}
uint32 MTRand::loBit (const uint32 & u) const [inline, protected]
Definition at line 108 of file nt_mersenne_twister_external_obj.h.
Referenced by twist().
{ return u & 0x00000001U; }
uint32 MTRand::loBits (const uint32 & u) const [inline, protected]
Definition at line 109 of file nt_mersenne_twister_external_obj.h.
Referenced by mixBits().
{ return u & 0x7fffffffU; }
uint32 MTRand::mixBits (const uint32 & u, const uint32 & v) const [inline, protected]
Definition at line 110 of file nt_mersenne_twister_external_obj.h.
References hiBit(), and loBits().
Referenced by twist().
        { return hiBit(u) | loBits(v); }
double MTRand::operator() () [inline]
Definition at line 92 of file nt_mersenne_twister_external_obj.h.
References rand().
{ return rand(); }  // same as rand()
double MTRand::rand () [inline]
Definition at line 127 of file nt_mersenne_twister_external_obj.h.
References randInt().
Referenced by operator()(), rand(), and NT_rnd_dist_o::uniformMT().
    { return double(randInt()) * 2.3283064370807974e-10; }
double MTRand::rand (const double & n) [inline]
Definition at line 130 of file nt_mersenne_twister_external_obj.h.
References rand().
    { return rand() * n; }
double MTRand::randDblExc () [inline]
Definition at line 139 of file nt_mersenne_twister_external_obj.h.
References randInt().
Referenced by randDblExc().
    { return double( 1.0 + randInt() ) * 2.3283064359965952e-10; }
double MTRand::randDblExc (const double & n) [inline]
Definition at line 142 of file nt_mersenne_twister_external_obj.h.
References randDblExc().
    { return randDblExc() * n; }
double MTRand::randExc (const double & n) [inline]
Definition at line 136 of file nt_mersenne_twister_external_obj.h.
References randExc().
    { return randExc() * n; }
double MTRand::randExc () [inline]
Definition at line 133 of file nt_mersenne_twister_external_obj.h.
References randInt().
Referenced by randExc().
    { return double(randInt()) * 2.3283064365386963e-10; }
MTRand::uint32 MTRand::randInt (const uint32 & n) [inline]
Definition at line 159 of file nt_mersenne_twister_external_obj.h.
References randInt().
{
    // Find which bits are used in n
    uint32 used = ~0;
    for( uint32 m = n; m; used <<= 1, m >>= 1 ) {}
    used = ~used;
    // Draw numbers until one is found in [0,n]
    uint32 i;
    do
        i = randInt() & used;  // toss unused bits to shorten search
    while( i > n );
    return i;
}
MTRand::uint32 MTRand::randInt () [inline]
Definition at line 145 of file nt_mersenne_twister_external_obj.h.
References left, pNext, and reload().
Referenced by rand(), randDblExc(), randExc(), and randInt().
{
    if( left == 0 ) reload();
    --left;
    register uint32 s1;
    s1 = *pNext++;
    s1 ^= (s1 >> 11);
    s1 ^= (s1 <<  7) & 0x9d2c5680U;
    s1 ^= (s1 << 15) & 0xefc60000U;
    return ( s1 ^ (s1 >> 18) );
}
void MTRand::reload () [inline, protected]
Definition at line 238 of file nt_mersenne_twister_external_obj.h.
References left, M, N, pNext, state, and twist().
Referenced by randInt(), and seed().
{
    // Generate N new values in state
    // Made clearer and faster by Matthew Bellew (matthew.bellew@home.com)
    register uint32 *p = state;
    register int i;
    for( i = N - M; i--; ++p )
        *p = twist( p[M], p[0], p[1] );
    for( i = M; --i; ++p )
        *p = twist( p[M-N], p[0], p[1] );
    *p = twist( p[M-N], p[0], state[0] );
    left = N, pNext = state;
}
void MTRand::save (uint32 * saveArray) const [inline]
Definition at line 280 of file nt_mersenne_twister_external_obj.h.
References left, and state.
{
    register uint32 *sa = saveArray;
    register const uint32 *s = state;
    register int i = N;
    for( ; i--; *sa++ = *s++ ) {}
    *sa = left;
}
void MTRand::seed (uint32 oneSeed) [inline]
Definition at line 175 of file nt_mersenne_twister_external_obj.h.
References N, reload(), and state.
{
    // Seed the generator with a simple uint32
    register uint32 *s;
    register int i;
    for( i = N, s = state;
         i--;
         *s    = oneSeed & 0xffff0000,
         *s++ |= ( (oneSeed *= 69069U)++ & 0xffff0000 ) >> 16,
         (oneSeed *= 69069U)++ ) {}  // hard to read, but fast
    reload();
}
void MTRand::seed () [inline]
Definition at line 205 of file nt_mersenne_twister_external_obj.h.
References hash(), reload(), and state.
Referenced by MTRand().
{
    // Seed the generator with an array from /dev/urandom if available
    // Otherwise use a hash of time() and clock() values
    // First try getting an array from /dev/urandom
    FILE* urandom = fopen( "/dev/urandom", "rb" );
    if( urandom )
    {
        register uint32 *s = state;
        register int i = N;
        register bool success = true;
        while( success && i-- )
        {
            success = fread( s, sizeof(uint32), 1, urandom );
            *s++ &= 0xffffffff;  // filter in case uint32 > 32 bits
        }
        fclose(urandom);
        if( success )
        {
            // There is a 1 in 2^19937 chance that a working urandom gave
            // 19937 consecutive zeroes and will make the generator fail
            // Ignore that case and continue with initialization
            reload();
            return;
        }
    }
    // Was not successful, so use time() and clock() instead
    seed( hash( time(NULL), clock() ) );
}
void MTRand::seed (uint32 *const bigSeed) [inline]
Definition at line 189 of file nt_mersenne_twister_external_obj.h.
References reload(), and state.
{
    // Seed the generator with an array of 624 uint32's
    // There are 2^19937-1 possible initial states.  This function allows
    // any one of those to be chosen by providing 19937 bits.  The lower
    // 31 bits of the first element, bigSeed[0], are discarded.  Any bits
    // above the lower 32 in each element are also discarded.  Theoretically,
    // the rest of the array can contain any values except all zeroes.
    // Just call seed() if you want to get array from /dev/urandom
    register uint32 *s = state, *b = bigSeed;
    register int i = N;
    for( ; i--; *s++ = *b++ & 0xffffffff ) {}
    reload();
}
uint32 MTRand::twist (const uint32 & m, const uint32 & s0, const uint32 & s1) const [inline, protected]
Definition at line 112 of file nt_mersenne_twister_external_obj.h.
References loBit(), MAGIC, and mixBits().
Referenced by reload().
        { return m ^ (mixBits(s0,s1)>>1) ^ (loBit(s1) ? MAGIC : 0U); }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const MTRand & mtrand) [friend]
Definition at line 301 of file nt_mersenne_twister_external_obj.h.
{
    register const MTRand::uint32 *s = mtrand.state;
    register int i = mtrand.N;
    for( ; i--; os << *s++ << "\t" ) {}
    return os << mtrand.left;
}
std::istream& operator>> (std::istream & is, MTRand & mtrand) [friend]
Definition at line 310 of file nt_mersenne_twister_external_obj.h.
{
    register MTRand::uint32 *s = mtrand.state;
    register int i = mtrand.N;
    for( ; i--; is >> *s++ ) {}
    is >> mtrand.left;
    mtrand.pNext = &mtrand.state[mtrand.N-mtrand.left];
    return is;
}
Member Data Documentation
int MTRand::left [protected]
Definition at line 71 of file nt_mersenne_twister_external_obj.h.
Referenced by load(), operator<<(), operator>>(), randInt(), reload(), and save().
uint32* MTRand::pNext [protected]
Definition at line 70 of file nt_mersenne_twister_external_obj.h.
Referenced by load(), operator>>(), randInt(), and reload().
uint32 MTRand::state[N] [protected]
Definition at line 69 of file nt_mersenne_twister_external_obj.h.
Referenced by load(), operator<<(), operator>>(), reload(), save(), and seed().
The documentation for this class was generated from the following file:
nt_mersenne_twister_external_obj.h