NetTrader: NT3D_plot2d_vp_o Class Reference
NT3D_plot2d_vp_o Class Reference
NT3D_plot2d_vp_o class.
#include <nt3d_plot2d_vp_obj.h>
Public Member Functions
NT3D_plot2d_vp_o ()
NT3D_plot2d_vp_o (const NT3D_plot2d_vp_o &original)
const NT3D_plot2d_vp_o & operator= (const NT3D_plot2d_vp_o &right)
virtual ~NT3D_plot2d_vp_o ()
void Draw ()
void AutoRange (bool decision)
NTreturn SetXRange (NTreal min, NTreal max)
NTreturn SetYRange (NTreal min, NTreal max)
Protected Member Functions
void InitChild ()
NTreturn ResizeChild (NTsize x, NTsize y)
void RedrawChild ()
virtual void DrawData ()=0
void NewXData (NTreal x)
void NewYData (NTreal y)
void DrawCoordinateSystem ()
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 51 of file nt3d_plot2d_vp_obj.h.
Constructor & Destructor Documentation
NT3D_plot2d_vp_o::NT3D_plot2d_vp_o ()
NT3D_plot2d_vp_o::NT3D_plot2d_vp_o (const NT3D_plot2d_vp_o & original)
virtual NT3D_plot2d_vp_o::~NT3D_plot2d_vp_o () [virtual]
Member Function Documentation
void NT3D_plot2d_vp_o::AutoRange (bool decision) [inline]
Definition at line 60 of file nt3d_plot2d_vp_obj.h.
{ autoRange = decision; }
void NT3D_plot2d_vp_o::Draw () [virtual]
Implements NT3D_abstract_vp_o.
void NT3D_plot2d_vp_o::DrawCoordinateSystem () [protected]
Referenced by RedrawChild().
virtual void NT3D_plot2d_vp_o::DrawData () [protected, pure virtual]
Implemented in NT3D_plot2d_vec_vp_o.
Referenced by RedrawChild().
void NT3D_plot2d_vp_o::InitChild () [inline, protected, virtual]
Implements NT3D_abstract_vp_o.
Definition at line 66 of file nt3d_plot2d_vp_obj.h.
{};
void NT3D_plot2d_vp_o::NewXData (NTreal x) [inline, protected]
Definition at line 70 of file nt3d_plot2d_vp_obj.h.
{ if (x < dataXMin) dataXMin = x; else if (x > dataXMax) dataXMax = x; }
void NT3D_plot2d_vp_o::NewYData (NTreal y) [inline, protected]
Definition at line 71 of file nt3d_plot2d_vp_obj.h.
{ if (y < dataYMin) dataYMin = y; else if (y > dataYMax) dataYMax = y; }
const NT3D_plot2d_vp_o& NT3D_plot2d_vp_o::operator= (const NT3D_plot2d_vp_o & right)
void NT3D_plot2d_vp_o::RedrawChild () [inline, protected, virtual]
Implements NT3D_abstract_vp_o.
Definition at line 68 of file nt3d_plot2d_vp_obj.h.
References DrawCoordinateSystem(), and DrawData().
{ DrawCoordinateSystem(); DrawData();}
NTreturn NT3D_plot2d_vp_o::ResizeChild (NTsize x, NTsize y) [inline, protected, virtual]
Implements NT3D_abstract_vp_o.
Definition at line 67 of file nt3d_plot2d_vp_obj.h.
{return NT_SUCCESS;}
NTreturn NT3D_plot2d_vp_o::SetXRange (NTreal min, NTreal max) [inline]
Definition at line 61 of file nt3d_plot2d_vp_obj.h.
References NT_ASSERT.
{ NT_ASSERT(min < max); xMin = min; xMax = max; return NT_SUCCESS;}
NTreturn NT3D_plot2d_vp_o::SetYRange (NTreal min, NTreal max) [inline]
Definition at line 62 of file nt3d_plot2d_vp_obj.h.
References NT_ASSERT.
{ NT_ASSERT(min < max); yMin = min; yMax = max; return NT_SUCCESS;}
The documentation for this class was generated from the following file:
nt3d_plot2d_vp_obj.h