NetTrader: NT_ring_buffer_o< T > Class Template Reference
NT_ring_buffer_o< T > Class Template Reference
NT_ring_buffer_o class.
#include <nt_ring_buffer_obj.h>
Public Member Functions
NT_ring_buffer_o (NTsize newRingLength=2)
NT_ring_buffer_o (const NT_ring_buffer_o &original)
const NT_ring_buffer_o & operator= (const NT_ring_buffer_o &right)
virtual ~NT_ring_buffer_o ()
NTsize _ringLength () const
NTreturn Resize (NTsize newRingLength)
after resize states are reset to scratch
void Push (T value)
void Show ()
vector< T > Buffer ()
Protected Member Functions
NTsize IncreaseCounter ()
NTsize _counter ()
Protected Attributes
NTsize ringLength
Detailed Description
template<class T>
class NT_ring_buffer_o< T >
Bug:
unknown
Warning:
unknown
Definition at line 57 of file nt_ring_buffer_obj.h.
Constructor & Destructor Documentation
template<class T > NT_ring_buffer_o< T >::NT_ring_buffer_o (NTsize newRingLength = 2) [inline]
Definition at line 60 of file nt_ring_buffer_obj.h.
{ Init(newRingLength); }
template<class T > NT_ring_buffer_o< T >::NT_ring_buffer_o (const NT_ring_buffer_o< T > & original)
template<class T > virtual NT_ring_buffer_o< T >::~NT_ring_buffer_o () [inline, virtual]
Definition at line 63 of file nt_ring_buffer_obj.h.
{}
Member Function Documentation
template<class T > NTsize NT_ring_buffer_o< T >::_counter () [inline, protected]
Definition at line 81 of file nt_ring_buffer_obj.h.
Referenced by NT_ring_buffer_o< T >::Buffer().
{ return counter; }
template<class T > NTsize NT_ring_buffer_o< T >::_ringLength () const [inline]
Definition at line 65 of file nt_ring_buffer_obj.h.
References NT_ring_buffer_o< T >::ringLength.
Referenced by NT_ring_buffer_o< T >::Buffer(), and NT_ring_buffer_o< T >::Show().
{ return ringLength;}
template<class T > vector<T> NT_ring_buffer_o< T >::Buffer () [inline]
Definition at line 71 of file nt_ring_buffer_obj.h.
References NT_ring_buffer_o< T >::_counter(), NT_ring_buffer_o< T >::_ringLength(), and NT_ring_buffer_o< T >::ringLength.
Referenced by NT_ring_buffer_o< T >::Show().
                    {
                            vector <T> tmpVec(ringLength);
                            for (NTsize ll=0; ll< _ringLength(); ll++) tmpVec[ll] = bufferVec[(_counter()+ll+1) % ringLength];
                            return tmpVec;
                          }
template<class T > NTsize NT_ring_buffer_o< T >::IncreaseCounter () [inline, protected]
Definition at line 79 of file nt_ring_buffer_obj.h.
References NT_ring_buffer_o< T >::ringLength.
Referenced by NT_ring_buffer_o< T >::Push().
                         {  counter = (counter + 1) % ringLength;
                            return counter; }
template<class T > const NT_ring_buffer_o& NT_ring_buffer_o< T >::operator= (const NT_ring_buffer_o< T > & right)
template<class T > void NT_ring_buffer_o< T >::Push (T value) [inline]
Definition at line 68 of file nt_ring_buffer_obj.h.
References NT_ring_buffer_o< T >::IncreaseCounter().
{ bufferVec[IncreaseCounter()] = value;}
template<class T > NTreturn NT_ring_buffer_o< T >::Resize (NTsize newRingLength) [inline]
Definition at line 67 of file nt_ring_buffer_obj.h.
{ Init(newRingLength); }
template<class T > void NT_ring_buffer_o< T >::Show () [inline]
Definition at line 69 of file nt_ring_buffer_obj.h.
References NT_ring_buffer_o< T >::_ringLength(), and NT_ring_buffer_o< T >::Buffer().
{ vector <T> tmpVec = Buffer(); for(NTsize ll=0; ll< _ringLength(); ll++) cout << tmpVec[ll] << " "; cout << endl;}
Member Data Documentation
template<class T > NTsize NT_ring_buffer_o< T >::ringLength [protected]
Definition at line 83 of file nt_ring_buffer_obj.h.
Referenced by NT_ring_buffer_o< T >::_ringLength(), NT_ring_buffer_o< T >::Buffer(), and NT_ring_buffer_o< T >::IncreaseCounter().
The documentation for this class was generated from the following file:
nt_ring_buffer_obj.h