NetTrader: TNT::const_Region1D< Array1D > Class Template Reference
TNT::const_Region1D< Array1D > Class Template Reference
#include <region1d.h>
Public Member Functions
const Array1D & array () const
Subscript offset () const
Subscript dim () const
Subscript offset (Subscript i) const
Subscript dim (Subscript i) const
const_Region1D (const Array1D &A, Subscript i1, Subscript i2)
const_Region1D (const Array1D &A, const Index1D &I)
const_Region1D (const_Region1D< Array1D > &A, Subscript i1, Subscript i2)
const_Region1D< Array1D > operator() (Subscript i1, Subscript i2)
const_Region1D< Array1D > operator() (const Index1D &I)
const T & operator() (Subscript i) const
Protected Types
typedef Array1D::element_type T
Protected Attributes
const Array1D & A_
Subscript offset_
Subscript dim_
Detailed Description
template<class Array1D>
class TNT::const_Region1D< Array1D >
Definition at line 247 of file region1d.h.
Member Typedef Documentation
template<class Array1D> typedef Array1D::element_type TNT::const_Region1D< Array1D >::T [protected]
Definition at line 254 of file region1d.h.
Constructor & Destructor Documentation
template<class Array1D> TNT::const_Region1D< Array1D >::const_Region1D (const Array1D & A, Subscript i1, Subscript i2) [inline]
Definition at line 279 of file region1d.h.
References TNT::const_Region1D< Array1D >::dim_, TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
                                                                     : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1 );
            assert(i2 <= A.dim() + (TNT_BASE_OFFSET-1));
            assert(i1 <= i2);
#endif
            offset_ = i1 - TNT_BASE_OFFSET;
            dim_ = i2-i1 + 1;
        }
template<class Array1D> TNT::const_Region1D< Array1D >::const_Region1D (const Array1D & A, const Index1D & I) [inline]
Definition at line 290 of file region1d.h.
References TNT::const_Region1D< Array1D >::dim_, TNT::Index1D::lbound(), TNT::const_Region1D< Array1D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
                                                           : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <=I.lbound());
            assert(I.ubound() <= A.dim() + (TNT_BASE_OFFSET-1));
            assert(I.lbound() <= I.ubound());
#endif
            offset_ = I.lbound() - TNT_BASE_OFFSET;
            dim_ = I.ubound() - I.lbound() + 1;
        }
template<class Array1D> TNT::const_Region1D< Array1D >::const_Region1D (const_Region1D< Array1D > & A, Subscript i1, Subscript i2) [inline]
Definition at line 301 of file region1d.h.
References TNT::const_Region1D< Array1D >::dim(), TNT::const_Region1D< Array1D >::dim_, TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
                                                                               :
                A_(A.A_)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1 );
            assert(i2 <= A.dim() + (TNT_BASE_OFFSET - 1));
            assert(i1 <= i2);
#endif
                    //     (old-offset)        (new-offset)
                    //
            offset_ =  (i1 - TNT_BASE_OFFSET) + A.offset_;
            dim_ = i2-i1 + 1;
        }
Member Function Documentation
template<class Array1D> const Array1D& TNT::const_Region1D< Array1D >::array () const [inline]
Definition at line 257 of file region1d.h.
References TNT::const_Region1D< Array1D >::A_.
{ return A_; }
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::dim (Subscript i) const [inline]
Definition at line 270 of file region1d.h.
References TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(i== TNT_BASE_OFFSET);
#endif
            return offset_;
        }
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::dim () const [inline]
Definition at line 260 of file region1d.h.
References TNT::const_Region1D< Array1D >::dim_.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), TNT::const_Region1D< Array1D >::operator()(), and TNT::Region1D< Array1D >::operator=().
{ return dim_; }
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::offset (Subscript i) const [inline]
Definition at line 262 of file region1d.h.
References TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(i==TNT_BASE_OFFSET);
#endif
            return offset_;
        }
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::offset () const [inline]
Definition at line 259 of file region1d.h.
References TNT::const_Region1D< Array1D >::offset_.
{ return offset_;}
template<class Array1D> const T& TNT::const_Region1D< Array1D >::operator() (Subscript i) const [inline]
Definition at line 342 of file region1d.h.
References TNT::const_Region1D< Array1D >::A_, TNT::const_Region1D< Array1D >::dim(), TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i);
            assert(i <= dim() + (TNT_BASE_OFFSET-1));
#endif
            return A_(i+offset_);
        }
template<class Array1D> const_Region1D<Array1D> TNT::const_Region1D< Array1D >::operator() (const Index1D & I) [inline]
Definition at line 330 of file region1d.h.
References TNT::const_Region1D< Array1D >::A_, TNT::const_Region1D< Array1D >::dim(), TNT::Index1D::lbound(), TNT::const_Region1D< Array1D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET<=I.lbound());
            assert(I.ubound() <= dim() + (TNT_BASE_OFFSET-1));
            assert(I.lbound() <= I.ubound());
#endif
            return const_Region1D<Array1D>(A_, I.lbound()+offset_,
                offset_ + I.ubound());
        }
template<class Array1D> const_Region1D<Array1D> TNT::const_Region1D< Array1D >::operator() (Subscript i1, Subscript i2) [inline]
Definition at line 315 of file region1d.h.
References TNT::const_Region1D< Array1D >::A_, TNT::const_Region1D< Array1D >::dim(), TNT::const_Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1);
            assert(i2 <= dim() + (TNT_BASE_OFFSET -1));
            assert(i1 <= i2);
#endif
                    // offset_ is 0-based, so no need for
                    //  ( - TNT_BASE_OFFSET)
                    //
            return const_Region1D<Array1D>(A_, i1+offset_,
                    offset_ + i2);
        }
Member Data Documentation
template<class Array1D> const Array1D& TNT::const_Region1D< Array1D >::A_ [protected]
Definition at line 251 of file region1d.h.
Referenced by TNT::const_Region1D< Array1D >::array(), and TNT::const_Region1D< Array1D >::operator()().
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::dim_ [protected]
Definition at line 253 of file region1d.h.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), and TNT::const_Region1D< Array1D >::dim().
template<class Array1D> Subscript TNT::const_Region1D< Array1D >::offset_ [protected]
Definition at line 252 of file region1d.h.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), TNT::const_Region1D< Array1D >::dim(), TNT::const_Region1D< Array1D >::offset(), and TNT::const_Region1D< Array1D >::operator()().
The documentation for this class was generated from the following file:
region1d.h