NetTrader: NT_vector_o Class Reference
NT_vector_o Class Reference
A n-dimensional real vector class with visualization capabilities.
#include <nt_vector_obj.h>
Public Member Functions
NT_vector_o ()
NT_vector_o (NTuint dim)
NT_vector_o (NTuint dim, NTreal *elemVec)
NT_vector_o (NTuint dim, float *elemVec)
NT_vector_o (NT_vector3_o newVector3)
NT_vector_o (NTreal a, NTreal b)
NT_vector_o (NTreal a, NTreal b, NTreal c)
NT_vector_o (NTreal a, NTreal b, NTreal c, NTreal d)
NT_vector_o (const NT_vector_o &)
NT_vector_o & operator= (NT_vector_o const &)
~NT_vector_o ()
NT_vector_o operator+ (const NT_vector_o &) const
addition C = A+B
NT_vector_o operator- (const NT_vector_o &) const
subtraction C = A-B
NTreal operator* (const NT_vector_o &) const
scalar product r = A*B
NTreal Dot (const NT_vector_o right) const
scalar (dot) product r = A*B
NTreal CosAng (const NT_vector_o right)
cosine of the angle between two NT_vector_o
NT_vector_o operator* (NTreal) const
Scaling, factor multiplication (from the RIGHT) C = A*alpha.
NTreal & operator() (NTint component) const
Access vector components 1..dimension slower and safer.
NTreal & operator[] (NTint component) const
Access vector components 0..(dimension-1) fast and no range checking.
NTreal operator^ (NT_vector_o b)
operator NT_vector3_o () const
NT_vector_o BaseVectorAngle () const
NTreal Length () const
NTreal LenSqr () const
NTuint _dim () const
NTuint _dimension () const
const NTreal * _elem () const
void set_elem (const NTreal *elemVec)
Friends
ostream & operator<< (ostream &os, const NT_vector_o &self)
Detailed Description
Definition at line 120 of file nt_vector_obj.h.
Constructor & Destructor Documentation
NT_vector_o::NT_vector_o ()
NT_vector_o::NT_vector_o (NTuint dim)
NT_vector_o::NT_vector_o (NTuint dim, NTreal * elemVec)
NT_vector_o::NT_vector_o (NTuint dim, float * elemVec)
NT_vector_o::NT_vector_o (NT_vector3_o newVector3)
NT_vector_o::NT_vector_o (NTreal a, NTreal b)
NT_vector_o::NT_vector_o (NTreal a, NTreal b, NTreal c)
NT_vector_o::NT_vector_o (NTreal a, NTreal b, NTreal c, NTreal d)
NT_vector_o::NT_vector_o (const NT_vector_o &)
NT_vector_o::~NT_vector_o ()
Member Function Documentation
NTuint NT_vector_o::_dim () const [inline]
Definition at line 162 of file nt_vector_obj.h.
{ return dimension;}
NTuint NT_vector_o::_dimension () const [inline]
Definition at line 164 of file nt_vector_obj.h.
{ return dimension;  };
const NTreal* NT_vector_o::_elem () const
NT_vector_o NT_vector_o::BaseVectorAngle () const
NTreal NT_vector_o::CosAng (const NT_vector_o right) [inline]
Definition at line 147 of file nt_vector_obj.h.
References Length().
  { return (*this)*(right) / (Length() * right.Length()); }
NTreal NT_vector_o::Dot (const NT_vector_o right) const [inline]
Definition at line 144 of file nt_vector_obj.h.
  { return (*this)*(right);}
NTreal NT_vector_o::Length (void) const [inline]
Definition at line 160 of file nt_vector_obj.h.
References LenSqr().
Referenced by CosAng().
{return sqrt(LenSqr()); };
NTreal NT_vector_o::LenSqr () const
Referenced by Length().
NT_vector_o::operator NT_vector3_o () const
NTreal& NT_vector_o::operator() (NTint component) const
NTreal NT_vector_o::operator* (const NT_vector_o &) const
NT_vector_o NT_vector_o::operator* (NTreal) const
NT_vector_o NT_vector_o::operator+ (const NT_vector_o &) const
NT_vector_o NT_vector_o::operator- (const NT_vector_o &) const
NT_vector_o& NT_vector_o::operator= (NT_vector_o const &)
NTreal& NT_vector_o::operator[] (NTint component) const
NTreal NT_vector_o::operator^ (NT_vector_o b)
void NT_vector_o::set_elem (const NTreal * elemVec)
Friends And Related Function Documentation
ostream& operator<< (ostream & os, const NT_vector_o & self) [friend]
The documentation for this class was generated from the following file:
nt_vector_obj.h