NetTrader: NTBP_multi_sodium_current_o Class Reference
NTBP_multi_sodium_current_o Class Reference
-e ntbp_multi_sodium_current_obj.h - NTBP_multi_sodium_current_o class header by Ahmed Aldo Faisal © created 16.3.2001
#include <ntbp_multi_sodium_current_obj.h>
Public Member Functions
NTBP_multi_sodium_current_o (NTreal area, NTreal density=330, NTreal channelConductave=4.0e-9)
NTBP_multi_sodium_current_o (const NTBP_multi_sodium_current_o &original)
const NTBP_multi_sodium_current_o & operator= (const NTBP_multi_sodium_current_o &right)
virtual ~NTBP_multi_sodium_current_o ()
NTreal ComputeChannelStateTimeConstant () const
in 1/ms or kHz
NTreturn StepCurrent ()
NTreal OpenChannels () const
Number of open ionic channels.
NTreal ComputeConductance ()
compute and return conductance in mSiemens
void ComputeRateConstants (NTreal vM)
compute the rate constants (in ms^-1)
void ShowChannelStatePopulation ()
void Show ()
NTreal AlphaM (NTreal vM)
NTreal BetaM (NTreal vM)
NTreal AlphaH (NTreal vM)
NTreal BetaH (NTreal vM)
void ShowParam () const
Detailed Description
NTBP_multi_sodium_current_o class Channel density 330/muM^2 Single channel conductivity 4 pS Temperature 9 Celsius (see Hille (1992) p. 329 or Conti et. al (1975))
Bug:
unknown
Warning:
unknown
Definition at line 60 of file ntbp_multi_sodium_current_obj.h.
Constructor & Destructor Documentation
NTBP_multi_sodium_current_o::NTBP_multi_sodium_current_o (NTreal area, NTreal density = 330, NTreal channelConductave = 4.0e-9)
NTBP_multi_sodium_current_o::NTBP_multi_sodium_current_o (const NTBP_multi_sodium_current_o & original)
virtual NTBP_multi_sodium_current_o::~NTBP_multi_sodium_current_o () [virtual]
Member Function Documentation
NTreal NTBP_multi_sodium_current_o::AlphaH (NTreal vM) [inline]
Definition at line 79 of file ntbp_multi_sodium_current_obj.h.
{   return 0.07 * exp(-vM / 20.0); }
NTreal NTBP_multi_sodium_current_o::AlphaM (NTreal vM) [inline]
Definition at line 77 of file ntbp_multi_sodium_current_obj.h.
{   return (25.0 - vM) / (10.0 * (exp((25.0 - vM)/10.0) - 1.0));}
NTreal NTBP_multi_sodium_current_o::BetaH (NTreal vM) [inline]
Definition at line 80 of file ntbp_multi_sodium_current_obj.h.
{   return 1.0/(exp(3.0 - vM/10.0) + 1.0); }
NTreal NTBP_multi_sodium_current_o::BetaM (NTreal vM) [inline]
Definition at line 78 of file ntbp_multi_sodium_current_obj.h.
{   return 4.0 * exp(-vM / 18.0); }
NTreal NTBP_multi_sodium_current_o::ComputeChannelStateTimeConstant () const [virtual]
Reimplemented from NTBP_membrane_current_o.
NTreal NTBP_multi_sodium_current_o::ComputeConductance () [virtual]
Implements NTBP_membrane_current_o.
void NTBP_multi_sodium_current_o::ComputeRateConstants (NTreal vM) [virtual]
Implements NTBP_membrane_current_o.
NTreal NTBP_multi_sodium_current_o::OpenChannels () const [virtual]
Reimplemented from NTBP_membrane_current_o.
const NTBP_multi_sodium_current_o& NTBP_multi_sodium_current_o::operator= (const NTBP_multi_sodium_current_o & right)
void NTBP_multi_sodium_current_o::Show () [inline]
Definition at line 75 of file ntbp_multi_sodium_current_obj.h.
References NTBP_ion_channels_o::_numChannels(), NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
            {  cout << " alphaM= " << alphaM << "\t betaM= " << betaM << "\t openRatio= " << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << "\t alphaH= " << alphaH << "\t betaH= " << betaH << "\t openNum= " << channelsPtr->NumOpen();}
void NTBP_multi_sodium_current_o::ShowChannelStatePopulation () [inline]
Definition at line 74 of file ntbp_multi_sodium_current_obj.h.
References NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
{ channelsPtr->ShowStates(); }
void NTBP_multi_sodium_current_o::ShowParam () const [virtual]
Reimplemented from NTBP_membrane_current_o.
NTreturn NTBP_multi_sodium_current_o::StepCurrent () [virtual]
Implements NTBP_membrane_current_o.
The documentation for this class was generated from the following file:
ntbp_multi_sodium_current_obj.h