NetTrader: TNT::UnitLowerTriangularView< MaTRiX > Class Template Reference
TNT::UnitLowerTriangularView< MaTRiX > Class Template Reference
#include <triang.h>
Public Types
typedef MaTRiX::const_reference const_reference
typedef MaTRiX::element_type element_type
typedef MaTRiX::element_type value_type
typedef element_type T
Public Member Functions
Subscript lbound () const
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
UnitLowerTriangularView (MaTRiX &A)
const_reference get (Subscript i, Subscript j) const
const_reference operator() (Subscript i, Subscript j) const
Protected Attributes
const MaTRiX & A_
const MaTRiX::element_type zero
const MaTRiX::element_type one
Detailed Description
template<class MaTRiX>
class TNT::UnitLowerTriangularView< MaTRiX >
Definition at line 154 of file triang.h.
Member Typedef Documentation
template<class MaTRiX> typedef MaTRiX::const_reference TNT::UnitLowerTriangularView< MaTRiX >::const_reference
Definition at line 164 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UnitLowerTriangularView< MaTRiX >::element_type
Definition at line 165 of file triang.h.
template<class MaTRiX> typedef element_type TNT::UnitLowerTriangularView< MaTRiX >::T
Definition at line 167 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UnitLowerTriangularView< MaTRiX >::value_type
Definition at line 166 of file triang.h.
Constructor & Destructor Documentation
template<class MaTRiX> TNT::UnitLowerTriangularView< MaTRiX >::UnitLowerTriangularView (MaTRiX & A) [inline]
Definition at line 177 of file triang.h.
: A_(A), zero(0), one(1) {}
Member Function Documentation
template<class MaTRiX> Subscript TNT::UnitLowerTriangularView< MaTRiX >::dim (Subscript d) const [inline]
Definition at line 170 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::A_.
{  return A_.dim(d); }
template<class MaTRiX> const_reference TNT::UnitLowerTriangularView< MaTRiX >::get (Subscript i, Subscript j) const [inline]
Definition at line 180 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::A_, TNT::UnitLowerTriangularView< MaTRiX >::one, and TNT::UnitLowerTriangularView< MaTRiX >::zero.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=A_.dim(1));
        assert(1<=j);
        assert(j<=A_.dim(2));
        assert(0<=i && i<A_.dim(0) && 0<=j && j<A_.dim(1));
#endif
        if (i>j)
            return A_(i,j);
        else if (i==j)
            return one;
        else
            return zero;
    }
template<class MaTRiX> Subscript TNT::UnitLowerTriangularView< MaTRiX >::lbound () const [inline]
Definition at line 169 of file triang.h.
Referenced by TNT::matmult().
{ return 1; }
template<class MaTRiX> Subscript TNT::UnitLowerTriangularView< MaTRiX >::num_cols () const [inline]
Definition at line 172 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_cols(); }
template<class MaTRiX> Subscript TNT::UnitLowerTriangularView< MaTRiX >::num_rows () const [inline]
Definition at line 171 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_rows(); }
template<class MaTRiX> const_reference TNT::UnitLowerTriangularView< MaTRiX >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 198 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::A_, TNT::UnitLowerTriangularView< MaTRiX >::one, and TNT::UnitLowerTriangularView< MaTRiX >::zero.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=A_.dim(1));
        assert(1<=j);
        assert(j<=A_.dim(2));
#endif
        if (i>j)
            return A_(i,j);
        else if (i==j)
            return one;
        else
            return zero;
    }
Member Data Documentation
template<class MaTRiX> const MaTRiX& TNT::UnitLowerTriangularView< MaTRiX >::A_ [protected]
Definition at line 158 of file triang.h.
Referenced by TNT::UnitLowerTriangularView< MaTRiX >::dim(), TNT::UnitLowerTriangularView< MaTRiX >::get(), TNT::UnitLowerTriangularView< MaTRiX >::num_cols(), TNT::UnitLowerTriangularView< MaTRiX >::num_rows(), and TNT::UnitLowerTriangularView< MaTRiX >::operator()().
template<class MaTRiX> const MaTRiX::element_type TNT::UnitLowerTriangularView< MaTRiX >::one [protected]
Definition at line 160 of file triang.h.
Referenced by TNT::UnitLowerTriangularView< MaTRiX >::get(), and TNT::UnitLowerTriangularView< MaTRiX >::operator()().
template<class MaTRiX> const MaTRiX::element_type TNT::UnitLowerTriangularView< MaTRiX >::zero [protected]
Definition at line 159 of file triang.h.
Referenced by TNT::UnitLowerTriangularView< MaTRiX >::get(), and TNT::UnitLowerTriangularView< MaTRiX >::operator()().
The documentation for this class was generated from the following file:
triang.h