NetTrader: NTBP_sodium_ion_channels_o Class Reference
NTBP_sodium_ion_channels_o Class Reference
NTBP_sodium_ion_channels_o class 8 state Hodgkin-Huxley based model of Sodium conducting ion channels.
#include <ntbp_sodium_ion_channels_obj.h>
Public Member Functions
NTBP_sodium_ion_channels_o (NTsize numNewChannels=1)
NTBP_sodium_ion_channels_o (const NTBP_sodium_ion_channels_o &original)
const NTBP_sodium_ion_channels_o & operator= (const NTBP_sodium_ion_channels_o &right)
virtual ~NTBP_sodium_ion_channels_o ()
NTreturn Step ()
void ShowStates () const
NTsize NumOpen () const
NTsize NumClosed () const
NTreal ComputeChannelStateTimeConstant () const
Sum of escape rates from current state [1/s].
NTreturn UpdateStateProb (vector< NTreal > rateConstVec)
bool ComputeGillespieStep (NTsize stateId)
NTreturn SteadyStateDistribution ()
set the steady state distribution of channel states for current rate constants, DIRTY HACK
NTreturn BinomialStep ()
No descriptions.
Detailed Description
The open state has stateIndex 4.
Bug:
unknown
Warning:
1. has to be take on stateCounterVec (as it is 9 dimensional (loop index!)) 2. alpha and beta RATE CONSTANTS name TRANSITION probability variables !
Definition at line 60 of file ntbp_sodium_ion_channels_obj.h.
Constructor & Destructor Documentation
NTBP_sodium_ion_channels_o::NTBP_sodium_ion_channels_o (NTsize numNewChannels = 1)
NTBP_sodium_ion_channels_o::NTBP_sodium_ion_channels_o (const NTBP_sodium_ion_channels_o & original)
virtual NTBP_sodium_ion_channels_o::~NTBP_sodium_ion_channels_o () [virtual]
Member Function Documentation
NTreturn NTBP_sodium_ion_channels_o::BinomialStep () [virtual]
Reimplemented from NTBP_ion_channels_o.
NTreal NTBP_sodium_ion_channels_o::ComputeChannelStateTimeConstant () const [virtual]
Implements NTBP_ion_channels_o.
bool NTBP_sodium_ion_channels_o::ComputeGillespieStep (NTsize stateId) [virtual]
Reimplemented from NTBP_ion_channels_o.
NTsize NTBP_sodium_ion_channels_o::NumClosed () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 71 of file ntbp_sodium_ion_channels_obj.h.
References NTBP_ion_channels_o::_numChannels(), and NumOpen().
{ return _numChannels() - NumOpen();}
NTsize NTBP_sodium_ion_channels_o::NumOpen () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 70 of file ntbp_sodium_ion_channels_obj.h.
References NTBP_ion_channels_o::stateCounterVec.
Referenced by NumClosed().
{ return stateCounterVec[4];}// because 0 is num total channels
const NTBP_sodium_ion_channels_o& NTBP_sodium_ion_channels_o::operator= (const NTBP_sodium_ion_channels_o & right)
void NTBP_sodium_ion_channels_o::ShowStates () const [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_sodium_ion_channels_o::SteadyStateDistribution () [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_sodium_ion_channels_o::Step () [virtual]
Reimplemented from NTBP_object_o.
NTreturn NTBP_sodium_ion_channels_o::UpdateStateProb (vector< NTreal > rateConstVec) [virtual]
Implements NTBP_ion_channels_o.
The documentation for this class was generated from the following file:
ntbp_sodium_ion_channels_obj.h