NetTrader: NTBP_sga_sodium_current_o Class Reference
NTBP_sga_sodium_current_o Class Reference
NTBP_sga_sodium_current_o class Channel density 330/muM^2 Single channel conductivity 4 pS Temperature 9 Celsius (see Hille (1992) p.
#include <ntbp_sga_sodium_current_obj.h>
Public Member Functions
NTBP_sga_sodium_current_o (NTreal area, NTreal density=330)
NTBP_sga_sodium_current_o (const NTBP_sga_sodium_current_o &original)
const NTBP_sga_sodium_current_o & operator= (const NTBP_sga_sodium_current_o &right)
virtual ~NTBP_sga_sodium_current_o ()
NTreturn StepCurrent ()
NTreal ComputeChannelStateTimeConstant () const
void ComputeRateConstants (NTreal vM)
compute the rate constants (in ms^-1)
void ShowChannelStatePopulation ()
void Show ()
Detailed Description
329 or Conti et. al (1975))
Bug:
unknown
Warning:
unknown
Definition at line 52 of file ntbp_sga_sodium_current_obj.h.
Constructor & Destructor Documentation
NTBP_sga_sodium_current_o::NTBP_sga_sodium_current_o (NTreal area, NTreal density = 330)
NTBP_sga_sodium_current_o::NTBP_sga_sodium_current_o (const NTBP_sga_sodium_current_o & original)
virtual NTBP_sga_sodium_current_o::~NTBP_sga_sodium_current_o () [virtual]
Member Function Documentation
NTreal NTBP_sga_sodium_current_o::ComputeChannelStateTimeConstant () const [virtual]
Reimplemented from NTBP_membrane_current_o.
void NTBP_sga_sodium_current_o::ComputeRateConstants (NTreal vM) [virtual]
Implements NTBP_membrane_current_o.
const NTBP_sga_sodium_current_o& NTBP_sga_sodium_current_o::operator= (const NTBP_sga_sodium_current_o & right)
void NTBP_sga_sodium_current_o::Show () [inline]
Definition at line 64 of file ntbp_sga_sodium_current_obj.h.
References NTBP_ion_channels_o::_numChannels(), NTBP_channels_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
            {  cout << " alphaM= " << alphaM << "\t betaM= " << betaM << "\t openRatio= " << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << "\t alphaH= " << alphaH << "\t betaH= " << betaH << "\t openNum= " << channelsPtr->NumOpen();}
void NTBP_sga_sodium_current_o::ShowChannelStatePopulation () [inline]
Definition at line 63 of file ntbp_sga_sodium_current_obj.h.
References NTBP_channels_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
{ channelsPtr->ShowStates(); }
NTreturn NTBP_sga_sodium_current_o::StepCurrent () [virtual]
Implements NTBP_membrane_current_o.
The documentation for this class was generated from the following file:
ntbp_sga_sodium_current_obj.h