NetTrader: TNT::UpperTriangularView< MaTRiX > Class Template Reference
TNT::UpperTriangularView< MaTRiX > Class Template Reference
#include <triang.h>
Public Types
typedef MaTRiX::const_reference const_reference
typedef MaTRiX::element_type element_type
typedef MaTRiX::element_type value_type
typedef element_type T
Public Member Functions
Subscript dim (Subscript d) const
Subscript lbound () const
Subscript num_rows () const
Subscript num_cols () const
UpperTriangularView (MaTRiX &A)
const_reference get (Subscript i, Subscript j) const
const_reference operator() (Subscript i, Subscript j) const
Protected Attributes
MaTRiX & A_
MaTRiX::element_type zero_
Detailed Description
template<class MaTRiX>
class TNT::UpperTriangularView< MaTRiX >
Definition at line 336 of file triang.h.
Member Typedef Documentation
template<class MaTRiX> typedef MaTRiX::const_reference TNT::UpperTriangularView< MaTRiX >::const_reference
Definition at line 347 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UpperTriangularView< MaTRiX >::element_type
Definition at line 348 of file triang.h.
template<class MaTRiX> typedef element_type TNT::UpperTriangularView< MaTRiX >::T
Definition at line 350 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UpperTriangularView< MaTRiX >::value_type
Definition at line 349 of file triang.h.
Constructor & Destructor Documentation
template<class MaTRiX> TNT::UpperTriangularView< MaTRiX >::UpperTriangularView (MaTRiX & A) [inline]
Definition at line 360 of file triang.h.
: A_(A),  zero_(0) {}
Member Function Documentation
template<class MaTRiX> Subscript TNT::UpperTriangularView< MaTRiX >::dim (Subscript d) const [inline]
Definition at line 352 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_.
{  return A_.dim(d); }
template<class MaTRiX> const_reference TNT::UpperTriangularView< MaTRiX >::get (Subscript i, Subscript j) const [inline]
Definition at line 363 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_, TNT::UpperTriangularView< MaTRiX >::lbound(), and TNT::UpperTriangularView< MaTRiX >::zero_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(lbound()<=i);
        assert(i<=A_.num_rows() + lbound() - 1);
        assert(lbound()<=j);
        assert(j<=A_.num_cols() + lbound() - 1);
#endif
        if (i>j)
            return zero_;
        else
            return A_(i,j);
    }
template<class MaTRiX> Subscript TNT::UpperTriangularView< MaTRiX >::lbound () const [inline]
Definition at line 353 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_.
Referenced by TNT::UpperTriangularView< MaTRiX >::get(), TNT::matmult(), and TNT::UpperTriangularView< MaTRiX >::operator()().
{ return A_.lbound(); }
template<class MaTRiX> Subscript TNT::UpperTriangularView< MaTRiX >::num_cols () const [inline]
Definition at line 355 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_cols(); }
template<class MaTRiX> Subscript TNT::UpperTriangularView< MaTRiX >::num_rows () const [inline]
Definition at line 354 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_rows(); }
template<class MaTRiX> const_reference TNT::UpperTriangularView< MaTRiX >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 378 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::A_, TNT::UpperTriangularView< MaTRiX >::lbound(), and TNT::UpperTriangularView< MaTRiX >::zero_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(lbound()<=i);
        assert(i<=A_.num_rows() + lbound() - 1);
        assert(lbound()<=j);
        assert(j<=A_.num_cols() + lbound() - 1);
#endif
        if (i>j)
            return zero_;
        else
            return A_(i,j);
    }
Member Data Documentation
template<class MaTRiX> MaTRiX& TNT::UpperTriangularView< MaTRiX >::A_ [protected]
Definition at line 341 of file triang.h.
Referenced by TNT::UpperTriangularView< MaTRiX >::dim(), TNT::UpperTriangularView< MaTRiX >::get(), TNT::UpperTriangularView< MaTRiX >::lbound(), TNT::UpperTriangularView< MaTRiX >::num_cols(), TNT::UpperTriangularView< MaTRiX >::num_rows(), and TNT::UpperTriangularView< MaTRiX >::operator()().
template<class MaTRiX> MaTRiX::element_type TNT::UpperTriangularView< MaTRiX >::zero_ [protected]
Definition at line 342 of file triang.h.
Referenced by TNT::UpperTriangularView< MaTRiX >::get(), and TNT::UpperTriangularView< MaTRiX >::operator()().
The documentation for this class was generated from the following file:
triang.h