NetTrader: NTBP_cylindrical_compartment_o Class Reference
NTBP_cylindrical_compartment_o Class Reference
NTBP_cylindrical_compartment_o class.
#include <ntbp_cylindrical_compartment_obj.h>
Public Member Functions
NTBP_cylindrical_compartment_o (NTreal length, NTreal diameter)
NTBP_cylindrical_compartment_o (const NTBP_cylindrical_compartment_o &original)
const
NTBP_cylindrical_compartment_o & operator= (const NTBP_cylindrical_compartment_o &right)
virtual ~NTBP_cylindrical_compartment_o ()
NTreal ActiveLengthConstant ()
length constant in muMeter for instantenous membrane conductance
NTreal _CrosssectionalArea () const
NTreal _diameter () const
NTreal _radius () const
NTreal _length () const
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 48 of file ntbp_cylindrical_compartment_obj.h.
Constructor & Destructor Documentation
NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o (NTreal length, NTreal diameter)
NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o (const NTBP_cylindrical_compartment_o & original)
virtual NTBP_cylindrical_compartment_o::~NTBP_cylindrical_compartment_o () [virtual]
Member Function Documentation
NTreal NTBP_cylindrical_compartment_o::_CrosssectionalArea () const [inline]
Definition at line 59 of file ntbp_cylindrical_compartment_obj.h.
References _radius().
{return _radius() * _radius() * M_PI;}
NTreal NTBP_cylindrical_compartment_o::_diameter () const [inline]
Definition at line 61 of file ntbp_cylindrical_compartment_obj.h.
Referenced by _radius(), and ActiveLengthConstant().
{ return diameter;}
NTreal NTBP_cylindrical_compartment_o::_length () const [inline]
Definition at line 65 of file ntbp_cylindrical_compartment_obj.h.
{ return length; }
NTreal NTBP_cylindrical_compartment_o::_radius () const [inline]
Definition at line 63 of file ntbp_cylindrical_compartment_obj.h.
References _diameter().
Referenced by _CrosssectionalArea().
{ return _diameter()/2.0;}
NTreal NTBP_cylindrical_compartment_o::ActiveLengthConstant () [inline]
Definition at line 57 of file ntbp_cylindrical_compartment_obj.h.
References _diameter(), NTBP_membrane_compartment_o::_rA(), and NTBP_membrane_compartment_o::TotalConductance().
{ return _diameter()/(4.0 * _rA() * 1.0e4 * TotalConductance());}
const NTBP_cylindrical_compartment_o& NTBP_cylindrical_compartment_o::operator= (const NTBP_cylindrical_compartment_o & right)
The documentation for this class was generated from the following file:
ntbp_cylindrical_compartment_obj.h