NetTrader: TNT::Index1D Class Reference
TNT::Index1D Class Reference
#include <index.h>
Public Member Functions
Subscript lbound () const
Subscript ubound () const
Index1D (const Index1D &D)
Index1D (Subscript i1, Subscript i2)
Index1D & operator= (const Index1D &D)
Detailed Description
Definition at line 36 of file index.h.
Constructor & Destructor Documentation
TNT::Index1D::Index1D (const Index1D & D) [inline]
Definition at line 46 of file index.h.
: lbound_(D.lbound_), ubound_(D.ubound_) {}
TNT::Index1D::Index1D (Subscript i1, Subscript i2) [inline]
Definition at line 47 of file index.h.
: lbound_(i1), ubound_(i2) {}
Member Function Documentation
Subscript TNT::Index1D::lbound () const [inline]
Definition at line 43 of file index.h.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), TNT::const_Region2D< Array2D >::const_Region2D(), TNT::const_Region2D< Array2D >::operator()(), TNT::Region2D< Array2D >::operator()(), TNT::const_Region1D< Array1D >::operator()(), TNT::Region1D< Array1D >::operator()(), TNT::operator+(), TNT::operator-(), TNT::Region1D< Array1D >::Region1D(), and TNT::Region2D< Array2D >::Region2D().
{ return lbound_; }
Index1D& TNT::Index1D::operator= (const Index1D & D) [inline]
Definition at line 49 of file index.h.
    {
        lbound_ = D.lbound_;
        ubound_ = D.ubound_;
        return *this;
    }
Subscript TNT::Index1D::ubound () const [inline]
Definition at line 44 of file index.h.
Referenced by TNT::const_Region1D< Array1D >::const_Region1D(), TNT::const_Region2D< Array2D >::const_Region2D(), TNT::const_Region2D< Array2D >::operator()(), TNT::Region2D< Array2D >::operator()(), TNT::const_Region1D< Array1D >::operator()(), TNT::Region1D< Array1D >::operator()(), TNT::operator+(), TNT::operator-(), TNT::Region1D< Array1D >::Region1D(), and TNT::Region2D< Array2D >::Region2D().
{ return ubound_; }
The documentation for this class was generated from the following file:
index.h