NetTrader: NT3D_vp_o Class Reference
NT3D_vp_o Class Reference
NT3D_vp_o class Superclass that unifys a common interface for abstract viewport implementations and their driver dependend realisations for various window systems (viewport driver).
#include <nt3d_vp_obj.h>
Public Member Functions
NT3D_vp_o ()
NT3D_vp_o (const NT3D_vp_o &original)
const NT3D_vp_o & operator= (const NT3D_vp_o &right)
virtual ~NT3D_vp_o ()
virtual void Init ()=0
virtual void MakeCurrent ()=0
virtual void SwapBuffer ()
virtual NTreturn Resize (NTsize width, NTsize height)=0
virtual void Redraw ()=0
NTreturn Connect (NT3D_vp_o *connectingVP)
NTreturn Disconnect ()
virtual NT3D_bitmap_o View2Bitmap ()=0
virtual NT3D_bitmap_o * View2BitmapPtr (NT3D_bitmap_o *bmpPtr)=0
virtual NTsize _width ()=0
virtual NTsize _height ()=0
Protected Attributes
NT3D_vp_o * pVP
Detailed Description
NT3D_drv_vp_o basically provides an implementation for all the functionality or infrastructure defined by this class, which is assigned to an NT3D_abstract_vp_o which uses this infrastructure. In this context it is possible that an NT3D_abstract_vp_o can be assigned to different drivers. On the other side the abstract viewport should provide all drawing within the Draw() method for the viewport drivers, which is the only method called from the driver classes. In the other direction the abstract classes should actually avoid to call the Draw() method themselves.
Bug:
unknown
Warning:
unknown
Definition at line 84 of file nt3d_vp_obj.h.
Constructor & Destructor Documentation
NT3D_vp_o::NT3D_vp_o ()
NT3D_vp_o::NT3D_vp_o (const NT3D_vp_o & original)
virtual NT3D_vp_o::~NT3D_vp_o () [inline, virtual]
Definition at line 90 of file nt3d_vp_obj.h.
References Disconnect().
{Disconnect();};
Member Function Documentation
virtual NTsize NT3D_vp_o::_height () [pure virtual]
Implemented in NT3D_abstract_vp_o, NT3D_drv_vp_o, and NT3D_glx_drv_o.
virtual NTsize NT3D_vp_o::_width () [pure virtual]
Implemented in NT3D_abstract_vp_o, NT3D_drv_vp_o, and NT3D_glx_drv_o.
NTreturn NT3D_vp_o::Connect (NT3D_vp_o * connectingVP)
NTreturn NT3D_vp_o::Disconnect ()
Referenced by ~NT3D_vp_o().
virtual void NT3D_vp_o::Init () [pure virtual]
Implemented in NT3D_abstract_vp_o, and NT3D_drv_vp_o.
Referenced by NT3D_abstract_vp_o::_height().
virtual void NT3D_vp_o::MakeCurrent () [pure virtual]
Implemented in NT3D_abstract_vp_o, and NT3D_glx_drv_o.
const NT3D_vp_o& NT3D_vp_o::operator= (const NT3D_vp_o & right)
virtual void NT3D_vp_o::Redraw () [pure virtual]
Implemented in NT3D_abstract_vp_o, and NT3D_drv_vp_o.
virtual NTreturn NT3D_vp_o::Resize (NTsize width, NTsize height) [pure virtual]
Implemented in NT3D_abstract_vp_o, NT3D_drv_vp_o, and NT3D_glx_drv_o.
virtual void NT3D_vp_o::SwapBuffer () [inline, virtual]
Reimplemented in NT3D_abstract_vp_o, and NT3D_glx_drv_o.
Definition at line 94 of file nt3d_vp_obj.h.
{};
virtual NT3D_bitmap_o NT3D_vp_o::View2Bitmap () [pure virtual]
Implemented in NT3D_abstract_vp_o, NT3D_drv_vp_o, and NT3D_glx_drv_o.
virtual NT3D_bitmap_o* NT3D_vp_o::View2BitmapPtr (NT3D_bitmap_o * bmpPtr) [pure virtual]
Implemented in NT3D_abstract_vp_o, NT3D_drv_vp_o, and NT3D_glx_drv_o.
Member Data Documentation
NT3D_vp_o* NT3D_vp_o::pVP [protected]
Definition at line 106 of file nt3d_vp_obj.h.
Referenced by NT3D_abstract_vp_o::_height().
The documentation for this class was generated from the following file:
nt3d_vp_obj.h