NetTrader: NTBP_hh_sga_leak_current_o Class Reference
NTBP_hh_sga_leak_current_o Class Reference
NTBP_hh_sga_leak_current_o class.
#include <ntbp_hh_sga_leak_current_obj.h>
Public Member Functions
NTBP_hh_sga_leak_current_o (NTreal newArea, NTreal newLeakConductance=0.3)
NTBP_hh_sga_leak_current_o (const NTBP_hh_sga_leak_current_o &original)
const NTBP_hh_sga_leak_current_o & operator= (const NTBP_hh_sga_leak_current_o &right)
virtual ~NTBP_hh_sga_leak_current_o ()
void ComputeRateConstants (NTreal voltage)
compute the rate constants (in ms^-1)
NTreturn StepCurrent ()
in mSiemens
void UpdateConductance ()
compute and return conductance in mSiemens
NTreal ComputeConductance ()
Return leak conductance in mSiemens (note: function return constant value (leak!) set in constructor).
NTreturn DeterministicStepCurrent ()
void Show ()
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 48 of file ntbp_hh_sga_leak_current_obj.h.
Constructor & Destructor Documentation
NTBP_hh_sga_leak_current_o::NTBP_hh_sga_leak_current_o (NTreal newArea, NTreal newLeakConductance = 0.3)
NTBP_hh_sga_leak_current_o::NTBP_hh_sga_leak_current_o (const NTBP_hh_sga_leak_current_o & original)
virtual NTBP_hh_sga_leak_current_o::~NTBP_hh_sga_leak_current_o () [virtual]
Member Function Documentation
NTreal NTBP_hh_sga_leak_current_o::ComputeConductance () [inline, virtual]
Implements NTBP_membrane_current_o.
Definition at line 62 of file ntbp_hh_sga_leak_current_obj.h.
References NTBP_membrane_current_o::_conductance().
{ return _conductance(); }
void NTBP_hh_sga_leak_current_o::ComputeRateConstants (NTreal vM) [inline, virtual]
Implements NTBP_membrane_current_o.
Definition at line 56 of file ntbp_hh_sga_leak_current_obj.h.
{}
NTreturn NTBP_hh_sga_leak_current_o::DeterministicStepCurrent () [inline]
Definition at line 63 of file ntbp_hh_sga_leak_current_obj.h.
{ return NT_SUCCESS;}
const NTBP_hh_sga_leak_current_o& NTBP_hh_sga_leak_current_o::operator= (const NTBP_hh_sga_leak_current_o & right)
void NTBP_hh_sga_leak_current_o::Show () [inline, virtual]
Implements NTBP_hh_current_o.
Definition at line 64 of file ntbp_hh_sga_leak_current_obj.h.
References NTBP_membrane_current_o::_conductance().
{ cout << "g_Leak [mSiemens]=" <<_conductance();}
NTreturn NTBP_hh_sga_leak_current_o::StepCurrent () [inline, virtual]
Implements NTBP_membrane_current_o.
Definition at line 58 of file ntbp_hh_sga_leak_current_obj.h.
{return NT_SUCCESS;}
void NTBP_hh_sga_leak_current_o::UpdateConductance () [inline]
Definition at line 60 of file ntbp_hh_sga_leak_current_obj.h.
References NTBP_hh_current_o::_area(), NTBP_hh_current_o::_maxConductivity(), and NTBP_membrane_current_o::Set_conductance().
{ Set_conductance(_maxConductivity() * _area() * 1.0e-8); }
The documentation for this class was generated from the following file:
ntbp_hh_sga_leak_current_obj.h