NetTrader: NT3D_arrow_o Class Reference
NT3D_arrow_o Class Reference
NT3D_arrow_o class Draw an arrow which, is constructed of a cylinder as shaft and a conus as arrow head.
#include <nt3d_arrow_obj.h>
Public Member Functions
NT3D_arrow_o ()
NT3D_arrow_o (const NT3D_arrow_o &original)
NT3D_arrow_o (const NT_vector3_o &newBase, const NT_vector3_o &newTip)
const NT3D_arrow_o & operator= (const NT3D_arrow_o &right)
virtual ~NT3D_arrow_o ()
void Collinearize (const NT_vector3_o &)
rotate the object such that its (oRotation vector would rotate a vector on the) x-axis in the direction of oRelativeVector
void DrawSolidObject () const
Detailed Description
It can either be rotated into a desired direction as all NT3D_objects_o OR it can be created and manipulated specifying a head and tail position for it in space.
Bug:
unknown
Warning:
In case the arrow is ment to point into a certain direction designated by a base-tip constructor is used be sure to not rotate the object using any of the rotate calls!
Definition at line 75 of file nt3d_arrow_obj.h.
Constructor & Destructor Documentation
NT3D_arrow_o::NT3D_arrow_o ()
Referenced by DrawSolidObject().
NT3D_arrow_o::NT3D_arrow_o (const NT3D_arrow_o & original)
NT3D_arrow_o::NT3D_arrow_o (const NT_vector3_o & newBase, const NT_vector3_o & newTip)
virtual NT3D_arrow_o::~NT3D_arrow_o () [virtual]
Referenced by DrawSolidObject().
Member Function Documentation
void NT3D_arrow_o::Collinearize (const NT_vector3_o & oRelativeVector)
Reimplemented from NT3D_object_o.
Referenced by DrawSolidObject().
void NT3D_arrow_o::DrawSolidObject () const [inline]
Definition at line 75 of file nt3d_arrow_obj.h.
References Collinearize(), NT3D_arrow_o(), operator=(), and ~NT3D_arrow_o().
: public NT3D_solid_o {
const NT3D_arrow_o& NT3D_arrow_o::operator= (const NT3D_arrow_o & right)
Referenced by DrawSolidObject().
The documentation for this class was generated from the following file:
nt3d_arrow_obj.h