NetTrader: NTBP_ion_channels_o Class Reference
NTBP_ion_channels_o Class Reference
NTBP_ion_channels_o class.
#include <ntbp_ion_channels_obj.h>
Public Member Functions
NTBP_ion_channels_o (NTsize numNewChannels=1, NTsize numNewStates=1)
NTBP_ion_channels_o (const NTBP_ion_channels_o &original)
const NTBP_ion_channels_o & operator= (const NTBP_ion_channels_o &right)
virtual ~NTBP_ion_channels_o ()
NTsize _numChannels () const
NTsize _numStates () const
bool GillespieStep ()
virtual NTreturn BinomialStep ()
virtual bool ComputeGillespieStep (NTsize channelStateId)
virtual void ShowStates () const =0
virtual NTsize NumOpen () const =0
virtual NTsize NumClosed () const =0
virtual NTreturn SteadyStateDistribution ()=0
virtual NTreal ComputeChannelStateTimeConstant () const =0
Sum of escape rates from current state [1/s].
virtual NTreturn UpdateStateProb (vector< NTreal > rateConstVec)=0
Protected Attributes
vector< NTreal > statePersistenceProbVec
vector< NTsize > stateCounterVec
Static Protected Attributes
static NT_uniform_rnd_dist_o uniformRnd
static NT_binomial_rnd_dist_o binomRnd
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 58 of file ntbp_ion_channels_obj.h.
Constructor & Destructor Documentation
NTBP_ion_channels_o::NTBP_ion_channels_o (NTsize numNewChannels = 1, NTsize numNewStates = 1)
NTBP_ion_channels_o::NTBP_ion_channels_o (const NTBP_ion_channels_o & original)
virtual NTBP_ion_channels_o::~NTBP_ion_channels_o () [virtual]
Member Function Documentation
NTsize NTBP_ion_channels_o::_numChannels () const [inline]
Definition at line 66 of file ntbp_ion_channels_obj.h.
Referenced by NTBP_sodium_ion_channels_o::NumClosed(), NTBP_potassium_ion_channels_o::NumClosed(), NTBP_patlak_sodium_ion_channels_o::NumClosed(), NTBP_sga_sodium_current_o::Show(), NTBP_multi_sodium_current_o::Show(), and NTBP_hranvier_sodium_multi_current_o::Show().
{ return numChannels;}
NTsize NTBP_ion_channels_o::_numStates () const [inline]
Definition at line 67 of file ntbp_ion_channels_obj.h.
{ return numStates;}
virtual NTreturn NTBP_ion_channels_o::BinomialStep () [inline, virtual]
Reimplemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
Definition at line 69 of file ntbp_ion_channels_obj.h.
{ cerr << "NTBP_ion_channels_o::BinomialStep was not derived." << endl; return NT_NOT_IMPLEMENTED;}
virtual NTreal NTBP_ion_channels_o::ComputeChannelStateTimeConstant () const [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
virtual bool NTBP_ion_channels_o::ComputeGillespieStep (NTsize channelStateId) [inline, virtual]
Reimplemented in NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
Definition at line 70 of file ntbp_ion_channels_obj.h.
{ cerr << "NTBP_ion_channels::ComputeGillespieStep - Error : Should be overridden by derived class." << endl; return false;}
bool NTBP_ion_channels_o::GillespieStep ()
Referenced by NTBP_multi_current_o::ComputeGillespieStep().
virtual NTsize NTBP_ion_channels_o::NumClosed () const [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
virtual NTsize NTBP_ion_channels_o::NumOpen () const [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
Referenced by NTBP_delayed_potassium_rectifier_current_o::ComputeConductance(), NTBP_sga_sodium_current_o::Show(), NTBP_multi_sodium_current_o::Show(), and NTBP_hranvier_sodium_multi_current_o::Show().
const NTBP_ion_channels_o& NTBP_ion_channels_o::operator= (const NTBP_ion_channels_o & right)
virtual void NTBP_ion_channels_o::ShowStates () const [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
Referenced by NTBP_sga_sodium_current_o::ShowChannelStatePopulation(), NTBP_multi_sodium_current_o::ShowChannelStatePopulation(), and NTBP_hranvier_sodium_multi_current_o::ShowChannelStatePopulation().
virtual NTreturn NTBP_ion_channels_o::SteadyStateDistribution () [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
virtual NTreturn NTBP_ion_channels_o::UpdateStateProb (vector< NTreal > rateConstVec) [pure virtual]
Implemented in NTBP_patlak_sodium_ion_channels_o, NTBP_potassium_ion_channels_o, and NTBP_sodium_ion_channels_o.
Member Data Documentation
NT_binomial_rnd_dist_o NTBP_ion_channels_o::binomRnd [static, protected]
Definition at line 86 of file ntbp_ion_channels_obj.h.
vector< NTsize > NTBP_ion_channels_o::stateCounterVec [protected]
Definition at line 84 of file ntbp_ion_channels_obj.h.
Referenced by NTBP_sodium_ion_channels_o::NumOpen(), NTBP_potassium_ion_channels_o::NumOpen(), and NTBP_patlak_sodium_ion_channels_o::NumOpen().
vector< NTreal > NTBP_ion_channels_o::statePersistenceProbVec [protected]
Definition at line 83 of file ntbp_ion_channels_obj.h.
NT_uniform_rnd_dist_o NTBP_ion_channels_o::uniformRnd [static, protected]
Definition at line 85 of file ntbp_ion_channels_obj.h.
The documentation for this class was generated from the following file:
ntbp_ion_channels_obj.h