NetTrader: NT3D_abstract_vp_o Class Reference
NT3D_abstract_vp_o Class Reference
NT3D_abstract_vp_o class The abstract viewport class houses the driver independent part of the visualisation routines.
#include <nt3d_abstract_vp_obj.h>
Public Member Functions
NT3D_abstract_vp_o ()
NT3D_abstract_vp_o (const NT3D_abstract_vp_o &original)
const NT3D_abstract_vp_o & operator= (const NT3D_abstract_vp_o &right)
~NT3D_abstract_vp_o ()
virtual void Draw ()=0
void Init ()
These methods call child and drv implementations.
NTreturn Resize (NTsize newWidth, NTsize newHeight)
void Redraw ()
void MakeCurrent ()
void SwapBuffer ()
NT3D_bitmap_o View2Bitmap ()
NT3D_bitmap_o * View2BitmapPtr (NT3D_bitmap_o *bmpPtr)
NTsize _width ()
NTsize _height ()
Protected Member Functions
virtual void InitChild ()=0
virtual NTreturn ResizeChild (NTsize width, NTsize height)=0
virtual void RedrawChild ()=0
Detailed Description
It is connected/registered with a viewport driver class NT3D_driver_vp_o childs. It uses the infrastructure provided by a driver class via the NT3D_vp_o interface.
Bug:
unknown
Warning:
do not override MakeCurrent() and SwapBuffer()
Definition at line 80 of file nt3d_abstract_vp_obj.h.
Constructor & Destructor Documentation
NT3D_abstract_vp_o::NT3D_abstract_vp_o ()
NT3D_abstract_vp_o::NT3D_abstract_vp_o (const NT3D_abstract_vp_o & original)
NT3D_abstract_vp_o::~NT3D_abstract_vp_o ()
Member Function Documentation
NTsize NT3D_abstract_vp_o::_height () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 88 of file nt3d_abstract_vp_obj.h.
References NT3D_vp_o::Init(), InitChild(), and NT3D_vp_o::pVP.
{InitChild();pVP->Init();}
NTsize NT3D_abstract_vp_o::_width () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 87 of file nt3d_abstract_vp_obj.h.
{InitChild();pVP->Init();}
virtual void NT3D_abstract_vp_o::Draw () [pure virtual]
Implements NT3D_o.
Implemented in NT3D_bitmap_vp_o, NT3D_camera_vp_o, NT3D_plot2d_vp_o, NT3D_universal_vp_o, and NT3D_universe_vp_o.
void NT3D_abstract_vp_o::Init () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 79 of file nt3d_abstract_vp_obj.h.
: public NT3D_vp_o {
virtual void NT3D_abstract_vp_o::InitChild () [protected, pure virtual]
Implemented in NT3D_bitmap_vp_o, NT3D_camera_vp_o, NT3D_plot2d_vp_o, and NT3D_spheric_camera_o.
Referenced by _height().
void NT3D_abstract_vp_o::MakeCurrent () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 83 of file nt3d_abstract_vp_obj.h.
{InitChild();pVP->Init();}
const NT3D_abstract_vp_o& NT3D_abstract_vp_o::operator= (const NT3D_abstract_vp_o & right)
void NT3D_abstract_vp_o::Redraw () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 81 of file nt3d_abstract_vp_obj.h.
:
virtual void NT3D_abstract_vp_o::RedrawChild () [protected, pure virtual]
Implemented in NT3D_bitmap_vp_o, NT3D_camera_vp_o, NT3D_plot2d_vp_o, and NT3D_spheric_camera_o.
NTreturn NT3D_abstract_vp_o::Resize (NTsize newWidth, NTsize newHeight) [inline, virtual]
Implements NT3D_vp_o.
Definition at line 80 of file nt3d_abstract_vp_obj.h.
: public NT3D_vp_o {
virtual NTreturn NT3D_abstract_vp_o::ResizeChild (NTsize width, NTsize height) [protected, pure virtual]
Implemented in NT3D_bitmap_vp_o, NT3D_camera_vp_o, NT3D_plot2d_vp_o, and NT3D_spheric_camera_o.
void NT3D_abstract_vp_o::SwapBuffer () [inline, virtual]
Reimplemented from NT3D_vp_o.
Definition at line 84 of file nt3d_abstract_vp_obj.h.
{InitChild();pVP->Init();}
NT3D_bitmap_o NT3D_abstract_vp_o::View2Bitmap () [inline, virtual]
Implements NT3D_vp_o.
Definition at line 85 of file nt3d_abstract_vp_obj.h.
{InitChild();pVP->Init();}
NT3D_bitmap_o* NT3D_abstract_vp_o::View2BitmapPtr (NT3D_bitmap_o * bmpPtr) [inline, virtual]
Implements NT3D_vp_o.
Definition at line 86 of file nt3d_abstract_vp_obj.h.
{InitChild();pVP->Init();}
The documentation for this class was generated from the following file:
nt3d_abstract_vp_obj.h