NetTrader: NTBP_patlak_sodium_ion_channels_o Class Reference
NTBP_patlak_sodium_ion_channels_o Class Reference
NTBP_patlak_sodium_ion_channels_o class The ion channels kinetical scheme is based on J.
#include <ntbp_patlak_sodium_ion_channels_obj.h>
Public Member Functions
NTBP_patlak_sodium_ion_channels_o (NTsize numNewChannels=1)
NTBP_patlak_sodium_ion_channels_o (const NTBP_patlak_sodium_ion_channels_o &original)
const
NTBP_patlak_sodium_ion_channels_o & operator= (const NTBP_patlak_sodium_ion_channels_o &right)
virtual ~NTBP_patlak_sodium_ion_channels_o ()
NTreturn Step ()
void ShowStates () const
NTsize NumOpen () const
NTsize NumClosed () const
NTreal ComputeChannelStateTimeConstant () const
Sum of escape rates from current state [1/s].
NTreturn UpdateStateProb (vector< NTreal > rateConstVec)
NTreturn SteadyStateDistribution ()
set the steady state distribution of channel states for current rate constants, DIRTY HACK
NTreturn BinomialStep ()
No descriptions.
Detailed Description
Patlak (1991) "Molecular kinetics of voltage-dependent Na^+ channels", Physiological Review, Vol. 71, No. 6, p. 1047-1080 and implements model number 8. It consists of 7 discrete states, of which 1-4 are closed, 5 is open and 6-7 are inactivated.
Bug:
unknown
Warning:
unknown
Definition at line 54 of file ntbp_patlak_sodium_ion_channels_obj.h.
Constructor & Destructor Documentation
NTBP_patlak_sodium_ion_channels_o::NTBP_patlak_sodium_ion_channels_o (NTsize numNewChannels = 1)
NTBP_patlak_sodium_ion_channels_o::NTBP_patlak_sodium_ion_channels_o (const NTBP_patlak_sodium_ion_channels_o & original)
virtual NTBP_patlak_sodium_ion_channels_o::~NTBP_patlak_sodium_ion_channels_o () [virtual]
Member Function Documentation
NTreturn NTBP_patlak_sodium_ion_channels_o::BinomialStep () [virtual]
Reimplemented from NTBP_ion_channels_o.
NTreal NTBP_patlak_sodium_ion_channels_o::ComputeChannelStateTimeConstant () const [virtual]
Implements NTBP_ion_channels_o.
NTsize NTBP_patlak_sodium_ion_channels_o::NumClosed () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 65 of file ntbp_patlak_sodium_ion_channels_obj.h.
References NTBP_ion_channels_o::_numChannels(), and NumOpen().
{ return _numChannels() - NumOpen();}
NTsize NTBP_patlak_sodium_ion_channels_o::NumOpen () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 64 of file ntbp_patlak_sodium_ion_channels_obj.h.
References NTBP_ion_channels_o::stateCounterVec.
Referenced by NumClosed().
{ return stateCounterVec[5];} // because 0 is num total channels
const NTBP_patlak_sodium_ion_channels_o& NTBP_patlak_sodium_ion_channels_o::operator= (const NTBP_patlak_sodium_ion_channels_o & right)
void NTBP_patlak_sodium_ion_channels_o::ShowStates () const [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_patlak_sodium_ion_channels_o::SteadyStateDistribution () [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_patlak_sodium_ion_channels_o::Step () [virtual]
Reimplemented from NTBP_object_o.
NTreturn NTBP_patlak_sodium_ion_channels_o::UpdateStateProb (vector< NTreal > rateConstVec) [virtual]
Implements NTBP_ion_channels_o.
The documentation for this class was generated from the following file:
ntbp_patlak_sodium_ion_channels_obj.h