NetTrader: TNT::Region2D< Array2D > Class Template Reference
TNT::Region2D< Array2D > Class Template Reference
#include <region2d.h>
Public Types
typedef Array2D::value_type T
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Array2D & array ()
const Array2D & array () const
Subscript lbound () const
Subscript num_rows () const
Subscript num_cols () const
Subscript offset (Subscript i) const
Subscript dim (Subscript i) const
Region2D (Array2D &A, Subscript i1, Subscript i2, Subscript j1, Subscript j2)
Region2D (Array2D &A, const Index1D &I, const Index1D &J)
Region2D (Region2D< Array2D > &A, Subscript i1, Subscript i2, Subscript j1, Subscript j2)
Region2D< Array2D > operator() (Subscript i1, Subscript i2, Subscript j1, Subscript j2)
Region2D< Array2D > operator() (const Index1D &I, const Index1D &J)
T & operator() (Subscript i, Subscript j)
const T & operator() (Subscript i, Subscript j) const
Region2D< Array2D > & operator= (const Region2D< Array2D > &R)
Region2D< Array2D > & operator= (const const_Region2D< Array2D > &R)
Region2D< Array2D > & operator= (const Array2D &R)
Region2D< Array2D > & operator= (const T &scalar)
Protected Attributes
Array2D & A_
Subscript offset_ [2]
Subscript dim_ [2]
Detailed Description
template<class Array2D>
class TNT::Region2D< Array2D >
Definition at line 42 of file region2d.h.
Member Typedef Documentation
template<class Array2D> typedef const T* TNT::Region2D< Array2D >::const_iterator
Definition at line 58 of file region2d.h.
template<class Array2D> typedef const T& TNT::Region2D< Array2D >::const_reference
Definition at line 59 of file region2d.h.
template<class Array2D> typedef T TNT::Region2D< Array2D >::element_type
Definition at line 54 of file region2d.h.
template<class Array2D> typedef T* TNT::Region2D< Array2D >::iterator
Definition at line 56 of file region2d.h.
template<class Array2D> typedef T* TNT::Region2D< Array2D >::pointer
Definition at line 55 of file region2d.h.
template<class Array2D> typedef T& TNT::Region2D< Array2D >::reference
Definition at line 57 of file region2d.h.
template<class Array2D> typedef Subscript TNT::Region2D< Array2D >::size_type
Definition at line 52 of file region2d.h.
template<class Array2D> typedef Array2D::value_type TNT::Region2D< Array2D >::T
Definition at line 51 of file region2d.h.
template<class Array2D> typedef T TNT::Region2D< Array2D >::value_type
Definition at line 53 of file region2d.h.
Constructor & Destructor Documentation
template<class Array2D> TNT::Region2D< Array2D >::Region2D (Array2D & A, Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 86 of file region2d.h.
References TNT::Region2D< Array2D >::dim_, and TNT::Region2D< Array2D >::offset_.
                              : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( A.lbound() <= i1);
            assert( i2<= A.dim(A.lbound()) + A.lbound()-1);
            assert( A.lbound() <= j1);
            assert( j2<= A.dim(A.lbound()+1) + A.lbound()-1 );
#endif
            offset_[0] = i1-A.lbound();
            offset_[1] = j1-A.lbound();
            dim_[0] = i2-i1+1;
            dim_[1] = j2-j1+1;
        }
template<class Array2D> TNT::Region2D< Array2D >::Region2D (Array2D & A, const Index1D & I, const Index1D & J) [inline]
Definition at line 105 of file region2d.h.
References TNT::Region2D< Array2D >::dim_, TNT::Index1D::lbound(), TNT::Region2D< Array2D >::offset_, and TNT::Index1D::ubound().
                                                                 : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( I.lbound() <= I.ubound() );
            assert( J.lbound() <= J.ubound() );
            assert( A.lbound() <= I.lbound());
            assert( I.ubound()<= A.dim(A.lbound()) + A.lbound()-1);
            assert( A.lbound() <= J.lbound());
            assert( J.ubound() <= A.dim(A.lbound()+1) + A.lbound()-1 );
#endif
            offset_[0] = I.lbound()-A.lbound();
            offset_[1] = J.lbound()-A.lbound();
            dim_[0] = I.ubound() - I.lbound() + 1;
            dim_[1] = J.ubound() - J.lbound() + 1;
        }
template<class Array2D> TNT::Region2D< Array2D >::Region2D (Region2D< Array2D > & A, Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 122 of file region2d.h.
References TNT::Region2D< Array2D >::dim(), TNT::Region2D< Array2D >::dim_, TNT::Region2D< Array2D >::lbound(), and TNT::Region2D< Array2D >::offset_.
                                        : A_(A.A_)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( A.lbound() <= i1);
            assert( i2<= A.dim(A.lbound()) + A.lbound()-1);
            assert( A.lbound() <= j1);
            assert( j2<= A.dim(A.lbound()+1) + A.lbound()-1 );
#endif
            offset_[0] = (i1 - A.lbound()) + A.offset_[0];
            offset_[1] = (j1 - A.lbound()) + A.offset_[1];
            dim_[0] = i2-i1 + 1;
            dim_[1] = j2-j1+1;
        }
Member Function Documentation
template<class Array2D> Array2D& TNT::Region2D< Array2D >::array () [inline]
Definition at line 61 of file region2d.h.
References TNT::Region2D< Array2D >::A_.
{ return A_; }
template<class Array2D> const Array2D& TNT::Region2D< Array2D >::array () const [inline]
Definition at line 62 of file region2d.h.
References TNT::Region2D< Array2D >::A_.
{ return A_; }
template<class Array2D> Subscript TNT::Region2D< Array2D >::dim (Subscript i) const [inline]
Definition at line 75 of file region2d.h.
References TNT::Region2D< Array2D >::A_, and TNT::Region2D< Array2D >::dim_.
Referenced by TNT::Region2D< Array2D >::Region2D().
        {
#ifdef TNT_BOUNDS_CHECK
            assert( A_.lbound() <= i);
            assert( i<= dim_[0] + A_.lbound()-1);
#endif
            return dim_[i-A_.lbound()];
        }
template<class Array2D> Subscript TNT::Region2D< Array2D >::lbound () const [inline]
Definition at line 63 of file region2d.h.
References TNT::Region2D< Array2D >::A_.
Referenced by TNT::Region2D< Array2D >::operator=(), and TNT::Region2D< Array2D >::Region2D().
{ return A_.lbound(); }
template<class Array2D> Subscript TNT::Region2D< Array2D >::num_cols () const [inline]
Definition at line 65 of file region2d.h.
References TNT::Region2D< Array2D >::dim_.
Referenced by TNT::Region2D< Array2D >::operator=().
{ return dim_[1]; }
template<class Array2D> Subscript TNT::Region2D< Array2D >::num_rows () const [inline]
Definition at line 64 of file region2d.h.
References TNT::Region2D< Array2D >::dim_.
Referenced by TNT::Region2D< Array2D >::operator=().
{ return dim_[0]; }
template<class Array2D> Subscript TNT::Region2D< Array2D >::offset (Subscript i) const [inline]
Definition at line 66 of file region2d.h.
References TNT::Region2D< Array2D >::A_, TNT::Region2D< Array2D >::dim_, and TNT::Region2D< Array2D >::offset_.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( A_.lbound() <= i);
            assert( i<= dim_[0] + A_.lbound()-1);
#endif
            return offset_[i-A_.lbound()];
        }
template<class Array2D> Region2D<Array2D> TNT::Region2D< Array2D >::operator() (const Index1D & I, const Index1D & J) [inline]
Definition at line 156 of file region2d.h.
References TNT::Region2D< Array2D >::A_, TNT::Region2D< Array2D >::dim_, TNT::Index1D::lbound(), TNT::Region2D< Array2D >::offset_, and TNT::Index1D::ubound().
        {
#ifdef TNT_BOUNDS_CHECK
            assert( I.lbound() <= I.ubound() );
            assert( J.lbound() <= J.ubound() );
            assert( A_.lbound() <= I.lbound());
            assert( I.ubound()<= dim_[0] + A_.lbound()-1);
            assert( A_.lbound() <= J.lbound());
            assert( J.ubound() <= dim_[1] + A_.lbound()-1 );
#endif
            return Region2D<Array2D>(A_, I.lbound()+offset_[0],
                offset_[0] + I.ubound(), offset_[1]+J.lbound(),
                offset_[1] + J.ubound());
        }
template<class Array2D> const T& TNT::Region2D< Array2D >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 184 of file region2d.h.
References TNT::Region2D< Array2D >::A_, TNT::Region2D< Array2D >::dim_, and TNT::Region2D< Array2D >::offset_.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( A_.lbound() <= i);
            assert( i<= dim_[0] + A_.lbound()-1);
            assert( A_.lbound() <= j);
            assert( j<= dim_[1] + A_.lbound()-1 );
#endif
            return A_(i+offset_[0], j+offset_[1]);
        }
template<class Array2D> Region2D<Array2D> TNT::Region2D< Array2D >::operator() (Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 139 of file region2d.h.
References TNT::Region2D< Array2D >::A_, TNT::Region2D< Array2D >::dim_, and TNT::Region2D< Array2D >::offset_.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( A_.lbound() <= i1);
            assert( i2<= dim_[0] + A_.lbound()-1);
            assert( A_.lbound() <= j1);
            assert( j2<= dim_[1] + A_.lbound()-1 );
#endif
            return Region2D<Array2D>(A_,
                    i1+offset_[0], offset_[0] + i2,
                    j1+offset_[1], offset_[1] + j2);
        }
template<class Array2D> T& TNT::Region2D< Array2D >::operator() (Subscript i, Subscript j) [inline]
Definition at line 173 of file region2d.h.
References TNT::Region2D< Array2D >::A_, TNT::Region2D< Array2D >::dim_, and TNT::Region2D< Array2D >::offset_.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( A_.lbound() <= i);
            assert( i<= dim_[0] + A_.lbound()-1);
            assert( A_.lbound() <= j);
            assert( j<= dim_[1] + A_.lbound()-1 );
#endif
            return A_(i+offset_[0], j+offset_[1]);
        }
template<class Array2D> Region2D<Array2D>& TNT::Region2D< Array2D >::operator= (const Array2D & R) [inline]
Definition at line 236 of file region2d.h.
References TNT::Region2D< Array2D >::num_cols(), and TNT::Region2D< Array2D >::num_rows().
        {
            Subscript M = num_rows();
            Subscript N = num_cols();
            // make sure both sides conform
            assert(M == R.num_rows());
            assert(N == R.num_cols());
            Subscript start = R.lbound();
            Subscript Mend =  start + M - 1;
            Subscript Nend =  start + N - 1;
            for (Subscript i=start; i<=Mend; i++)
              for (Subscript j=start; j<=Nend; j++)
                (*this)(i,j) = R(i,j);
            return *this;
        }
template<class Array2D> Region2D<Array2D>& TNT::Region2D< Array2D >::operator= (const Region2D< Array2D > & R) [inline]
Definition at line 196 of file region2d.h.
References TNT::Region2D< Array2D >::lbound(), TNT::Region2D< Array2D >::num_cols(), and TNT::Region2D< Array2D >::num_rows().
        {
            Subscript M = num_rows();
            Subscript N = num_cols();
            // make sure both sides conform
            assert(M == R.num_rows());
            assert(N == R.num_cols());
            Subscript start = R.lbound();
            Subscript Mend =  start + M - 1;
            Subscript Nend =  start + N - 1;
            for (Subscript i=start; i<=Mend; i++)
              for (Subscript j=start; j<=Nend; j++)
                (*this)(i,j) = R(i,j);
            return *this;
        }
template<class Array2D> Region2D<Array2D>& TNT::Region2D< Array2D >::operator= (const T & scalar) [inline]
Definition at line 256 of file region2d.h.
References TNT::Region2D< Array2D >::lbound(), TNT::Region2D< Array2D >::num_cols(), and TNT::Region2D< Array2D >::num_rows().
        {
            Subscript start = lbound();
            Subscript Mend = lbound() + num_rows() - 1;
            Subscript Nend = lbound() + num_cols() - 1;
            for (Subscript i=start; i<=Mend; i++)
              for (Subscript j=start; j<=Nend; j++)
                (*this)(i,j) = scalar;
            return *this;
        }
template<class Array2D> Region2D<Array2D>& TNT::Region2D< Array2D >::operator= (const const_Region2D< Array2D > & R) [inline]
Definition at line 216 of file region2d.h.
References TNT::const_Region2D< Array2D >::lbound(), TNT::const_Region2D< Array2D >::num_cols(), TNT::Region2D< Array2D >::num_cols(), TNT::const_Region2D< Array2D >::num_rows(), and TNT::Region2D< Array2D >::num_rows().
        {
            Subscript M = num_rows();
            Subscript N = num_cols();
            // make sure both sides conform
            assert(M == R.num_rows());
            assert(N == R.num_cols());
            Subscript start = R.lbound();
            Subscript Mend =  start + M - 1;
            Subscript Nend =  start + N - 1;
            for (Subscript i=start; i<=Mend; i++)
              for (Subscript j=start; j<=Nend; j++)
                (*this)(i,j) = R(i,j);
            return *this;
        }
Member Data Documentation
template<class Array2D> Array2D& TNT::Region2D< Array2D >::A_ [protected]
Definition at line 46 of file region2d.h.
Referenced by TNT::Region2D< Array2D >::array(), TNT::Region2D< Array2D >::dim(), TNT::Region2D< Array2D >::lbound(), TNT::Region2D< Array2D >::offset(), and TNT::Region2D< Array2D >::operator()().
template<class Array2D> Subscript TNT::Region2D< Array2D >::dim_[2] [protected]
Definition at line 48 of file region2d.h.
Referenced by TNT::Region2D< Array2D >::dim(), TNT::Region2D< Array2D >::num_cols(), TNT::Region2D< Array2D >::num_rows(), TNT::Region2D< Array2D >::offset(), TNT::Region2D< Array2D >::operator()(), and TNT::Region2D< Array2D >::Region2D().
template<class Array2D> Subscript TNT::Region2D< Array2D >::offset_[2] [protected]
Definition at line 47 of file region2d.h.
Referenced by TNT::Region2D< Array2D >::offset(), TNT::Region2D< Array2D >::operator()(), and TNT::Region2D< Array2D >::Region2D().
The documentation for this class was generated from the following file:
region2d.h