NetTrader: TNT::UnitUpperTriangularView< MaTRiX > Class Template Reference
TNT::UnitUpperTriangularView< MaTRiX > Class Template Reference
#include <triang.h>
Public Types
typedef MaTRiX::const_reference const_reference
typedef MaTRiX::element_type element_type
typedef MaTRiX::element_type value_type
typedef element_type T
Public Member Functions
Subscript lbound () const
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
UnitUpperTriangularView (MaTRiX &A)
const_reference get (Subscript i, Subscript j) const
const_reference operator() (Subscript i, Subscript j) const
Protected Attributes
const MaTRiX & A_
const MaTRiX::element_type zero
const MaTRiX::element_type one
Detailed Description
template<class MaTRiX>
class TNT::UnitUpperTriangularView< MaTRiX >
Definition at line 452 of file triang.h.
Member Typedef Documentation
template<class MaTRiX> typedef MaTRiX::const_reference TNT::UnitUpperTriangularView< MaTRiX >::const_reference
Definition at line 462 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UnitUpperTriangularView< MaTRiX >::element_type
Definition at line 463 of file triang.h.
template<class MaTRiX> typedef element_type TNT::UnitUpperTriangularView< MaTRiX >::T
Definition at line 465 of file triang.h.
template<class MaTRiX> typedef MaTRiX::element_type TNT::UnitUpperTriangularView< MaTRiX >::value_type
Definition at line 464 of file triang.h.
Constructor & Destructor Documentation
template<class MaTRiX> TNT::UnitUpperTriangularView< MaTRiX >::UnitUpperTriangularView (MaTRiX & A) [inline]
Definition at line 475 of file triang.h.
: A_(A), zero(0), one(1) {}
Member Function Documentation
template<class MaTRiX> Subscript TNT::UnitUpperTriangularView< MaTRiX >::dim (Subscript d) const [inline]
Definition at line 468 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::A_.
{  return A_.dim(d); }
template<class MaTRiX> const_reference TNT::UnitUpperTriangularView< MaTRiX >::get (Subscript i, Subscript j) const [inline]
Definition at line 478 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::A_, TNT::UnitUpperTriangularView< MaTRiX >::one, and TNT::UnitUpperTriangularView< MaTRiX >::zero.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=A_.dim(1));
        assert(1<=j);
        assert(j<=A_.dim(2));
        assert(0<=i && i<A_.dim(0) && 0<=j && j<A_.dim(1));
#endif
        if (i<j)
            return A_(i,j);
        else if (i==j)
            return one;
        else
            return zero;
    }
template<class MaTRiX> Subscript TNT::UnitUpperTriangularView< MaTRiX >::lbound () const [inline]
Definition at line 467 of file triang.h.
Referenced by TNT::matmult().
{ return 1; }
template<class MaTRiX> Subscript TNT::UnitUpperTriangularView< MaTRiX >::num_cols () const [inline]
Definition at line 470 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_cols(); }
template<class MaTRiX> Subscript TNT::UnitUpperTriangularView< MaTRiX >::num_rows () const [inline]
Definition at line 469 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult(), and TNT::operator<<().
{ return A_.num_rows(); }
template<class MaTRiX> const_reference TNT::UnitUpperTriangularView< MaTRiX >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 496 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::A_, TNT::UnitUpperTriangularView< MaTRiX >::one, and TNT::UnitUpperTriangularView< MaTRiX >::zero.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i<=A_.dim(1));
        assert(1<=j);
        assert(j<=A_.dim(2));
#endif
        if (i<j)
            return A_(i,j);
        else if (i==j)
            return one;
        else
            return zero;
    }
Member Data Documentation
template<class MaTRiX> const MaTRiX& TNT::UnitUpperTriangularView< MaTRiX >::A_ [protected]
Definition at line 456 of file triang.h.
Referenced by TNT::UnitUpperTriangularView< MaTRiX >::dim(), TNT::UnitUpperTriangularView< MaTRiX >::get(), TNT::UnitUpperTriangularView< MaTRiX >::num_cols(), TNT::UnitUpperTriangularView< MaTRiX >::num_rows(), and TNT::UnitUpperTriangularView< MaTRiX >::operator()().
template<class MaTRiX> const MaTRiX::element_type TNT::UnitUpperTriangularView< MaTRiX >::one [protected]
Definition at line 458 of file triang.h.
Referenced by TNT::UnitUpperTriangularView< MaTRiX >::get(), and TNT::UnitUpperTriangularView< MaTRiX >::operator()().
template<class MaTRiX> const MaTRiX::element_type TNT::UnitUpperTriangularView< MaTRiX >::zero [protected]
Definition at line 457 of file triang.h.
Referenced by TNT::UnitUpperTriangularView< MaTRiX >::get(), and TNT::UnitUpperTriangularView< MaTRiX >::operator()().
The documentation for this class was generated from the following file:
triang.h