NetTrader: TNT::const_Region2D< Array2D > Class Template Reference
TNT::const_Region2D< Array2D > Class Template Reference
#include <region2d.h>
Public Types
typedef Array2D::value_type T
typedef T value_type
typedef T element_type
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
const Array2D & array () const
Subscript lbound () const
Subscript num_rows () const
Subscript num_cols () const
Subscript offset (Subscript i) const
Subscript dim (Subscript i) const
const_Region2D (const Array2D &A, Subscript i1, Subscript i2, Subscript j1, Subscript j2)
const_Region2D (const Array2D &A, const Index1D &I, const Index1D &J)
const_Region2D (const_Region2D< Array2D > &A, Subscript i1, Subscript i2, Subscript j1, Subscript j2)
const_Region2D< Array2D > operator() (Subscript i1, Subscript i2, Subscript j1, Subscript j2)
const_Region2D< Array2D > operator() (const Index1D &I, const Index1D &J)
const T & operator() (Subscript i, Subscript j) const
Protected Attributes
const Array2D & A_
Subscript offset_ [2]
Subscript dim_ [2]
Detailed Description
template<class Array2D>
class TNT::const_Region2D< Array2D >
Definition at line 275 of file region2d.h.
Member Typedef Documentation
template<class Array2D> typedef const T* TNT::const_Region2D< Array2D >::const_iterator
Definition at line 287 of file region2d.h.
template<class Array2D> typedef const T& TNT::const_Region2D< Array2D >::const_reference
Definition at line 288 of file region2d.h.
template<class Array2D> typedef T TNT::const_Region2D< Array2D >::element_type
Definition at line 286 of file region2d.h.
template<class Array2D> typedef Array2D::value_type TNT::const_Region2D< Array2D >::T
Definition at line 284 of file region2d.h.
template<class Array2D> typedef T TNT::const_Region2D< Array2D >::value_type
Definition at line 285 of file region2d.h.
Constructor & Destructor Documentation
template<class Array2D> TNT::const_Region2D< Array2D >::const_Region2D (const Array2D & A, Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 313 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_, TNT::const_Region2D< Array2D >::offset_, and TNT_BASE_OFFSET.
                                            : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( TNT_BASE_OFFSET <= i1);
            assert( i2<= A.dim(TNT_BASE_OFFSET) + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= j1);
            assert( j2<= A.dim(TNT_BASE_OFFSET+1) + TNT_BASE_OFFSET-1 );
#endif
            offset_[0] = i1-TNT_BASE_OFFSET;
            offset_[1] = j1-TNT_BASE_OFFSET;
            dim_[0] = i2-i1+1;
            dim_[1] = j2-j1+1;
        }
template<class Array2D> TNT::const_Region2D< Array2D >::const_Region2D (const Array2D & A, const Index1D & I, const Index1D & J) [inline]
Definition at line 331 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_, TNT::Index1D::lbound(), TNT::const_Region2D< Array2D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
                : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( I.lbound() <= I.ubound() );
            assert( J.lbound() <= J.ubound() );
            assert( TNT_BASE_OFFSET <= I.lbound());
            assert( I.ubound()<= A.dim(TNT_BASE_OFFSET) + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= J.lbound());
            assert( J.ubound() <= A.dim(TNT_BASE_OFFSET+1) + TNT_BASE_OFFSET-1 );
#endif
            offset_[0] = I.lbound()-TNT_BASE_OFFSET;
            offset_[1] = J.lbound()-TNT_BASE_OFFSET;
            dim_[0] = I.ubound() - I.lbound() + 1;
            dim_[1] = J.ubound() - J.lbound() + 1;
        }
template<class Array2D> TNT::const_Region2D< Array2D >::const_Region2D (const_Region2D< Array2D > & A, Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 350 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim(), TNT::const_Region2D< Array2D >::dim_, TNT::const_Region2D< Array2D >::offset_, and TNT_BASE_OFFSET.
                                        : A_(A.A_)
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( TNT_BASE_OFFSET <= i1);
            assert( i2<= A.dim(TNT_BASE_OFFSET) + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= j1);
            assert( j2<= A.dim(TNT_BASE_OFFSET+1) + TNT_BASE_OFFSET-1 );
#endif
            offset_[0] = (i1 - TNT_BASE_OFFSET) + A.offset_[0];
            offset_[1] = (j1 - TNT_BASE_OFFSET) + A.offset_[1];
            dim_[0] = i2-i1 + 1;
            dim_[1] = j2-j1+1;
        }
Member Function Documentation
template<class Array2D> const Array2D& TNT::const_Region2D< Array2D >::array () const [inline]
Definition at line 290 of file region2d.h.
References TNT::const_Region2D< Array2D >::A_.
{ return A_; }
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::dim (Subscript i) const [inline]
Definition at line 303 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_, and TNT_BASE_OFFSET.
Referenced by TNT::const_Region2D< Array2D >::const_Region2D().
        {
#ifdef TNT_BOUNDS_CHECK
            assert( TNT_BASE_OFFSET <= i);
            assert( i<= dim_[0] + TNT_BASE_OFFSET-1);
#endif
            return dim_[i-TNT_BASE_OFFSET];
        }
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::lbound () const [inline]
Definition at line 291 of file region2d.h.
References TNT::const_Region2D< Array2D >::A_.
Referenced by TNT::Region2D< Array2D >::operator=().
{ return A_.lbound(); }
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::num_cols () const [inline]
Definition at line 293 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_.
Referenced by TNT::Region2D< Array2D >::operator=().
{ return dim_[1]; }
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::num_rows () const [inline]
Definition at line 292 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_.
Referenced by TNT::Region2D< Array2D >::operator=().
{ return dim_[0]; }
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::offset (Subscript i) const [inline]
Definition at line 294 of file region2d.h.
References TNT::const_Region2D< Array2D >::dim_, TNT::const_Region2D< Array2D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( TNT_BASE_OFFSET <= i);
            assert( i<= dim_[0] + TNT_BASE_OFFSET-1);
#endif
            return offset_[i-TNT_BASE_OFFSET];
        }
template<class Array2D> const_Region2D<Array2D> TNT::const_Region2D< Array2D >::operator() (const Index1D & I, const Index1D & J) [inline]
Definition at line 385 of file region2d.h.
References TNT::const_Region2D< Array2D >::A_, TNT::const_Region2D< Array2D >::dim_, TNT::Index1D::lbound(), TNT::const_Region2D< Array2D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
        {
#ifdef TNT_BOUNDS_CHECK
            assert( I.lbound() <= I.ubound() );
            assert( J.lbound() <= J.ubound() );
            assert( TNT_BASE_OFFSET <= I.lbound());
            assert( I.ubound()<= dim_[0] + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= J.lbound());
            assert( J.ubound() <= dim_[1] + TNT_BASE_OFFSET-1 );
#endif
            return const_Region2D<Array2D>(A_, I.lbound()+offset_[0],
                offset_[0] + I.ubound(), offset_[1]+J.lbound(),
                offset_[1] + J.ubound());
        }
template<class Array2D> const T& TNT::const_Region2D< Array2D >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 403 of file region2d.h.
References TNT::const_Region2D< Array2D >::A_, TNT::const_Region2D< Array2D >::dim_, TNT::const_Region2D< Array2D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( TNT_BASE_OFFSET <= i);
            assert( i<= dim_[0] + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= j);
            assert( j<= dim_[1] + TNT_BASE_OFFSET-1 );
#endif
            return A_(i+offset_[0], j+offset_[1]);
        }
template<class Array2D> const_Region2D<Array2D> TNT::const_Region2D< Array2D >::operator() (Subscript i1, Subscript i2, Subscript j1, Subscript j2) [inline]
Definition at line 368 of file region2d.h.
References TNT::const_Region2D< Array2D >::A_, TNT::const_Region2D< Array2D >::dim_, TNT::const_Region2D< Array2D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert( i1 <= i2 );
            assert( j1 <= j2);
            assert( TNT_BASE_OFFSET <= i1);
            assert( i2<= dim_[0] + TNT_BASE_OFFSET-1);
            assert( TNT_BASE_OFFSET <= j1);
            assert( j2<= dim_[0] + TNT_BASE_OFFSET-1 );
#endif
            return const_Region2D<Array2D>(A_,
                    i1+offset_[0], offset_[0] + i2,
                    j1+offset_[1], offset_[1] + j2);
        }
Member Data Documentation
template<class Array2D> const Array2D& TNT::const_Region2D< Array2D >::A_ [protected]
Definition at line 279 of file region2d.h.
Referenced by TNT::const_Region2D< Array2D >::array(), TNT::const_Region2D< Array2D >::lbound(), and TNT::const_Region2D< Array2D >::operator()().
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::dim_[2] [protected]
Definition at line 281 of file region2d.h.
Referenced by TNT::const_Region2D< Array2D >::const_Region2D(), TNT::const_Region2D< Array2D >::dim(), TNT::const_Region2D< Array2D >::num_cols(), TNT::const_Region2D< Array2D >::num_rows(), TNT::const_Region2D< Array2D >::offset(), and TNT::const_Region2D< Array2D >::operator()().
template<class Array2D> Subscript TNT::const_Region2D< Array2D >::offset_[2] [protected]
Definition at line 280 of file region2d.h.
Referenced by TNT::const_Region2D< Array2D >::const_Region2D(), TNT::const_Region2D< Array2D >::offset(), and TNT::const_Region2D< Array2D >::operator()().
The documentation for this class was generated from the following file:
region2d.h