NetTrader: TNT::Region1D< Array1D > Class Template Reference
TNT::Region1D< Array1D > Class Template Reference
#include <region1d.h>
Public Member Functions
const Array1D & array () const
Subscript offset () const
Subscript dim () const
Subscript offset (Subscript i) const
Subscript dim (Subscript i) const
Region1D (Array1D &A, Subscript i1, Subscript i2)
Region1D (Array1D &A, const Index1D &I)
Region1D (Region1D< Array1D > &A, Subscript i1, Subscript i2)
Region1D< Array1D > operator() (Subscript i1, Subscript i2)
Region1D< Array1D > operator() (const Index1D &I)
T & operator() (Subscript i)
const T & operator() (Subscript i) const
Region1D< Array1D > & operator= (const Region1D< Array1D > &R)
Region1D< Array1D > & operator= (const const_Region1D< Array1D > &R)
Region1D< Array1D > & operator= (const T &t)
Region1D< Array1D > & operator= (const Array1D &R)
Protected Types
typedef Array1D::element_type T
Protected Attributes
Array1D & A_
Subscript offset_
Subscript dim_
Detailed Description
template<class Array1D>
class TNT::Region1D< Array1D >
Definition at line 43 of file region1d.h.
Member Typedef Documentation
template<class Array1D> typedef Array1D::element_type TNT::Region1D< Array1D >::T [protected]
Definition at line 51 of file region1d.h.
Constructor & Destructor Documentation
template<class Array1D> TNT::Region1D< Array1D >::Region1D (Array1D & A, Subscript i1, Subscript i2) [inline]
Definition at line 76 of file region1d.h.
References TNT::Region1D< Array1D >::dim_, TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
                                                         : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1 );
            assert(i2 <= A.dim() + (TNT_BASE_OFFSET-1));
            assert(i1 <= i2);
#endif
            offset_ = i1 - TNT_BASE_OFFSET;
            dim_ = i2-i1 + 1;
        }
template<class Array1D> TNT::Region1D< Array1D >::Region1D (Array1D & A, const Index1D & I) [inline]
Definition at line 87 of file region1d.h.
References TNT::Region1D< Array1D >::dim_, TNT::Index1D::lbound(), TNT::Region1D< Array1D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
                                               : A_(A)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <=I.lbound());
            assert(I.ubound() <= A.dim() + (TNT_BASE_OFFSET-1));
            assert(I.lbound() <= I.ubound());
#endif
            offset_ = I.lbound() - TNT_BASE_OFFSET;
            dim_ = I.ubound() - I.lbound() + 1;
        }
template<class Array1D> TNT::Region1D< Array1D >::Region1D (Region1D< Array1D > & A, Subscript i1, Subscript i2) [inline]
Definition at line 98 of file region1d.h.
References TNT::Region1D< Array1D >::dim(), TNT::Region1D< Array1D >::dim_, TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
                                                                   :
                A_(A.A_)
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1 );
            assert(i2 <= A.dim() + (TNT_BASE_OFFSET - 1));
            assert(i1 <= i2);
#endif
                    //     (old-offset)        (new-offset)
                    //
            offset_ =  (i1 - TNT_BASE_OFFSET) + A.offset_;
            dim_ = i2-i1 + 1;
        }
Member Function Documentation
template<class Array1D> const Array1D& TNT::Region1D< Array1D >::array () const [inline]
Definition at line 54 of file region1d.h.
References TNT::Region1D< Array1D >::A_.
{ return A_; }
template<class Array1D> Subscript TNT::Region1D< Array1D >::dim (Subscript i) const [inline]
Definition at line 67 of file region1d.h.
References TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(i== TNT_BASE_OFFSET);
#endif
            return offset_;
        }
template<class Array1D> Subscript TNT::Region1D< Array1D >::dim () const [inline]
Definition at line 57 of file region1d.h.
References TNT::Region1D< Array1D >::dim_.
Referenced by TNT::Region1D< Array1D >::operator()(), TNT::Region1D< Array1D >::operator=(), and TNT::Region1D< Array1D >::Region1D().
{ return dim_; }
template<class Array1D> Subscript TNT::Region1D< Array1D >::offset (Subscript i) const [inline]
Definition at line 59 of file region1d.h.
References TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(i==TNT_BASE_OFFSET);
#endif
            return offset_;
        }
template<class Array1D> Subscript TNT::Region1D< Array1D >::offset () const [inline]
Definition at line 56 of file region1d.h.
References TNT::Region1D< Array1D >::offset_.
{ return offset_;}
template<class Array1D> T& TNT::Region1D< Array1D >::operator() (Subscript i) [inline]
Definition at line 141 of file region1d.h.
References TNT::Region1D< Array1D >::A_, TNT::Region1D< Array1D >::dim(), TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i);
            assert(i <=  dim() + (TNT_BASE_OFFSET-1));
#endif
            return A_(i+offset_);
        }
template<class Array1D> const T& TNT::Region1D< Array1D >::operator() (Subscript i) const [inline]
Definition at line 150 of file region1d.h.
References TNT::Region1D< Array1D >::A_, TNT::Region1D< Array1D >::dim(), TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i);
            assert(i <= dim() + (TNT_BASE_OFFSET-1));
#endif
            return A_(i+offset_);
        }
template<class Array1D> Region1D<Array1D> TNT::Region1D< Array1D >::operator() (const Index1D & I) [inline]
Definition at line 127 of file region1d.h.
References TNT::Region1D< Array1D >::A_, TNT::Region1D< Array1D >::dim(), TNT::Index1D::lbound(), TNT::Region1D< Array1D >::offset_, TNT_BASE_OFFSET, and TNT::Index1D::ubound().
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET<=I.lbound());
            assert(I.ubound() <= dim() + (TNT_BASE_OFFSET-1));
            assert(I.lbound() <= I.ubound());
#endif
            return Region1D<Array1D>(A_, I.lbound()+offset_,
                offset_ + I.ubound());
        }
template<class Array1D> Region1D<Array1D> TNT::Region1D< Array1D >::operator() (Subscript i1, Subscript i2) [inline]
Definition at line 112 of file region1d.h.
References TNT::Region1D< Array1D >::A_, TNT::Region1D< Array1D >::dim(), TNT::Region1D< Array1D >::offset_, and TNT_BASE_OFFSET.
        {
#ifdef TNT_BOUNDS_CHECK
            assert(TNT_BASE_OFFSET <= i1);
            assert(i2 <= dim() + (TNT_BASE_OFFSET -1));
            assert(i1 <= i2);
#endif
                    // offset_ is 0-based, so no need for
                    //  ( - TNT_BASE_OFFSET)
                    //
            return Region1D<Array1D>(A_, i1+offset_,
                    offset_ + i2);
        }
template<class Array1D> Region1D<Array1D>& TNT::Region1D< Array1D >::operator= (const const_Region1D< Array1D > & R) [inline]
Definition at line 178 of file region1d.h.
References TNT::const_Region1D< Array1D >::dim(), and TNT::Region1D< Array1D >::dim().
        {
            // make sure both sides conform
            assert(dim() == R.dim());
            Subscript N = dim();
            Subscript i;
            Subscript istart = TNT_BASE_OFFSET;
            Subscript iend = istart + N-1;
            for (i=istart; i<=iend; i++)
                (*this)(i) = R(i);
            return *this;
        }
template<class Array1D> Region1D<Array1D>& TNT::Region1D< Array1D >::operator= (const Region1D< Array1D > & R) [inline]
Definition at line 160 of file region1d.h.
References TNT::Region1D< Array1D >::dim().
        {
            // make sure both sides conform
            assert(dim() == R.dim());
            Subscript N = dim();
            Subscript i;
            Subscript istart = TNT_BASE_OFFSET;
            Subscript iend = istart + N-1;
            for (i=istart; i<=iend; i++)
                (*this)(i) = R(i);
            return *this;
        }
template<class Array1D> Region1D<Array1D>& TNT::Region1D< Array1D >::operator= (const T & t) [inline]
Definition at line 196 of file region1d.h.
References TNT::Region1D< Array1D >::dim().
        {
            Subscript N=dim();
            Subscript i;
            Subscript istart = TNT_BASE_OFFSET;
            Subscript iend = istart + N-1;
            for (i=istart; i<= iend; i++)
                (*this)(i) = t;
            return *this;
        }
template<class Array1D> Region1D<Array1D>& TNT::Region1D< Array1D >::operator= (const Array1D & R) [inline]
Definition at line 211 of file region1d.h.
References TNT::Region1D< Array1D >::dim().
        {
            // make sure both sides conform
            Subscript N = dim();
            assert(dim() == R.dim());
            Subscript i;
            Subscript istart = TNT_BASE_OFFSET;
            Subscript iend = istart + N-1;
            for (i=istart; i<=iend; i++)
                (*this)(i) = R(i);
            return *this;
        }
Member Data Documentation
template<class Array1D> Array1D& TNT::Region1D< Array1D >::A_ [protected]
Definition at line 47 of file region1d.h.
Referenced by TNT::Region1D< Array1D >::array(), and TNT::Region1D< Array1D >::operator()().
template<class Array1D> Subscript TNT::Region1D< Array1D >::dim_ [protected]
Definition at line 49 of file region1d.h.
Referenced by TNT::Region1D< Array1D >::dim(), and TNT::Region1D< Array1D >::Region1D().
template<class Array1D> Subscript TNT::Region1D< Array1D >::offset_ [protected]
Definition at line 48 of file region1d.h.
Referenced by TNT::Region1D< Array1D >::dim(), TNT::Region1D< Array1D >::offset(), TNT::Region1D< Array1D >::operator()(), and TNT::Region1D< Array1D >::Region1D().
The documentation for this class was generated from the following file:
region1d.h