NetTrader: NTBP_membrane_compartment_o Class Reference
NTBP_membrane_compartment_o Class Reference
NTBP_membrane_compartment_o class acts as a "container + glue" for the various membrane_current classes that can be attached to it.
#include <ntbp_membrane_compartment_obj.h>
Public Member Functions
NTBP_membrane_compartment_o (NTreal area)
NTBP_membrane_compartment_o (const NTBP_membrane_compartment_o &original)
const NTBP_membrane_compartment_o & operator= (const NTBP_membrane_compartment_o &right)
virtual ~NTBP_membrane_compartment_o ()
NTreturn AttachCurrent (NTBP_membrane_current_o *currentPtr, NTBPcurrentType type)
NTreturn Step (NTreal newVM)
NTreturn InjectCurrent (NTreal current)
NTreal AttachedCurrent (NTsize currentIndex)
NTreal AttachedConductance (NTsize currentIndex)
NTreal AttachedReversalPotential (NTsize currentIndex)
NTreal TimeConstant ()
membrane time constant at instaneous membrane conductivity in ms
const NTBP_membrane_current_o * Current (NTsize currentIndex)
NTreal _area () const
NTreal _vM () const
void Set_cM (NTreal newCm)
Set specific membrane capacitance in muF / cm^2.
NTreal _cM () const
void Set_rA (NTreal newRa)
Set specific axoplasmic resistivity in Ohm cm.
NTreal _rA () const
NTreturn Set_temperature (NTreal newTemp)
NTreal _temperature () const
NTreal _compartmentMembraneCapacitance () const
NTreal CompartmentMembraneCapacitance () const
NTreal CompartmentMembraneNetCurrent () const
NTreal CompartmentChannelStateTimeConstant () const
in 1/mSec or 1 kHz
bool GillespieStep ()
void ShowParam () const
Protected Member Functions
NTreal TotalConductance () const
NTreal WeightedConductance () const
Protected Attributes
NTreal vM
NTreal iInj
vector< NTBP_membrane_current_o * > currentVec
Detailed Description
Bug:
unknown
Warning:
1. rA, rM and cM are set to (arbitrary) standard values, overwrite in derived class 2. leak current IS incorported into the COMPARTMENT VECTOR
Definition at line 71 of file ntbp_membrane_compartment_obj.h.
Constructor & Destructor Documentation
NTBP_membrane_compartment_o::NTBP_membrane_compartment_o (NTreal area)
NTBP_membrane_compartment_o::NTBP_membrane_compartment_o (const NTBP_membrane_compartment_o & original)
virtual NTBP_membrane_compartment_o::~NTBP_membrane_compartment_o () [virtual]
Member Function Documentation
NTreal NTBP_membrane_compartment_o::_area () const [inline]
Definition at line 89 of file ntbp_membrane_compartment_obj.h.
Referenced by TimeConstant().
{ return area; }
NTreal NTBP_membrane_compartment_o::_cM () const [inline]
Definition at line 95 of file ntbp_membrane_compartment_obj.h.
Referenced by TimeConstant().
{ return cM; }
NTreal NTBP_membrane_compartment_o::_compartmentMembraneCapacitance () const [inline]
Definition at line 105 of file ntbp_membrane_compartment_obj.h.
{ return compartmentMembraneCapacitance; }
NTreal NTBP_membrane_compartment_o::_rA () const [inline]
Definition at line 99 of file ntbp_membrane_compartment_obj.h.
Referenced by NTBP_cylindrical_compartment_o::ActiveLengthConstant().
{ return rA; }
NTreal NTBP_membrane_compartment_o::_temperature () const [inline]
Definition at line 103 of file ntbp_membrane_compartment_obj.h.
{ return temperature;}
NTreal NTBP_membrane_compartment_o::_vM () const [inline]
Definition at line 91 of file ntbp_membrane_compartment_obj.h.
References vM.
Referenced by NTBP_membrane_patch_o::MembranePotential().
{ return vM; }
NTreturn NTBP_membrane_compartment_o::AttachCurrent (NTBP_membrane_current_o * currentPtr, NTBPcurrentType type)
NTreal NTBP_membrane_compartment_o::AttachedConductance (NTsize currentIndex) [inline]
Definition at line 83 of file ntbp_membrane_compartment_obj.h.
References currentVec, and NT_ASSERT.
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_conductance();}
NTreal NTBP_membrane_compartment_o::AttachedCurrent (NTsize currentIndex) [inline]
Definition at line 82 of file ntbp_membrane_compartment_obj.h.
References currentVec, and NT_ASSERT.
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_current();}
NTreal NTBP_membrane_compartment_o::AttachedReversalPotential (NTsize currentIndex) [inline]
Definition at line 84 of file ntbp_membrane_compartment_obj.h.
References currentVec, and NT_ASSERT.
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_reversalPotential();}
NTreal NTBP_membrane_compartment_o::CompartmentChannelStateTimeConstant () const
NTreal NTBP_membrane_compartment_o::CompartmentMembraneCapacitance () const
Referenced by Set_cM().
NTreal NTBP_membrane_compartment_o::CompartmentMembraneNetCurrent () const
const NTBP_membrane_current_o* NTBP_membrane_compartment_o::Current (NTsize currentIndex) [inline]
Definition at line 87 of file ntbp_membrane_compartment_obj.h.
References currentVec, and NT_ASSERT.
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1];}
bool NTBP_membrane_compartment_o::GillespieStep ()
NTreturn NTBP_membrane_compartment_o::InjectCurrent (NTreal current)
const NTBP_membrane_compartment_o& NTBP_membrane_compartment_o::operator= (const NTBP_membrane_compartment_o & right)
void NTBP_membrane_compartment_o::Set_cM (NTreal newCm) [inline]
Definition at line 93 of file ntbp_membrane_compartment_obj.h.
References CompartmentMembraneCapacitance().
{ cM = newCm;  compartmentMembraneCapacitance = CompartmentMembraneCapacitance(); }
void NTBP_membrane_compartment_o::Set_rA (NTreal newRa) [inline]
Definition at line 97 of file ntbp_membrane_compartment_obj.h.
{ rA = newRa;}
NTreturn NTBP_membrane_compartment_o::Set_temperature (NTreal newTemp) [inline]
Definition at line 101 of file ntbp_membrane_compartment_obj.h.
References currentVec, and Set_temperature().
Referenced by Set_temperature().
{ temperature = newTemp; for (NTsize i = 0; i < currentVec.size(); i++) currentVec[i]->Set_temperature(newTemp); return NT_SUCCESS;}
void NTBP_membrane_compartment_o::ShowParam () const
NTreturn NTBP_membrane_compartment_o::Step (NTreal newVM)
NTreal NTBP_membrane_compartment_o::TimeConstant () [inline]
Definition at line 86 of file ntbp_membrane_compartment_obj.h.
References _area(), _cM(), and TotalConductance().
{ return (_cM()/TotalConductance())*_area()*1.0e8; }
NTreal NTBP_membrane_compartment_o::TotalConductance () const [protected]
Referenced by NTBP_cylindrical_compartment_o::ActiveLengthConstant(), and TimeConstant().
NTreal NTBP_membrane_compartment_o::WeightedConductance () const [protected]
Member Data Documentation
vector< NTBP_membrane_current_o * > NTBP_membrane_compartment_o::currentVec [protected]
Definition at line 124 of file ntbp_membrane_compartment_obj.h.
Referenced by AttachedConductance(), AttachedCurrent(), AttachedReversalPotential(), Current(), NTBP_membrane_patch_o::MembraneCurrent(), and Set_temperature().
NTreal NTBP_membrane_compartment_o::iInj [protected]
Definition at line 123 of file ntbp_membrane_compartment_obj.h.
NTreal NTBP_membrane_compartment_o::vM [protected]
Definition at line 122 of file ntbp_membrane_compartment_obj.h.
Referenced by _vM().
The documentation for this class was generated from the following file:
ntbp_membrane_compartment_obj.h