NetTrader: NT_multidim_array_o< T > Class Template Reference
NT_multidim_array_o< T > Class Template Reference
NT_multidim_array_o class Implements a regular - multidimensional, i.e.
#include <nt_multidim_array_obj.h>
Public Member Functions
NT_multidim_array_o (NTsize d, NTsize n)
NT_multidim_array_o (const NT_multidim_array_o &original)
copy constructor currently not to be implemented.
const NT_multidim_array_o & operator= (const NT_multidim_array_o &right)
assignment operator currently not to be implemented.
virtual ~NT_multidim_array_o ()
T & Elem (const vector< NTsize > &coordinateVec)
access element at given coordinate position
const T & ElemByIndex (NTsize index) const
access a element with a "meaningless" index
void SetAll (const T &val)
T & Elem (NTsize index1...)
access element at given coordinate position
NTsize TotalNumElem () const
Detailed Description
template<class T>
class NT_multidim_array_o< T >
a "dim"-diemsional hypercube with "num" elements per dimension.
Bug:
unknown
Warning:
unknown
Definition at line 66 of file nt_multidim_array_obj.h.
Constructor & Destructor Documentation
template<class T> NT_multidim_array_o< T >::NT_multidim_array_o (NTsize d, NTsize n) [inline]
Definition at line 69 of file nt_multidim_array_obj.h.
{
    NT_ASSERT(d > 0);
    dim = d;
    NT_ASSERT(n > 0);
    num = n;
    // implementation range checking
    /* 2DO not working as numeric_limits not implemented in gcc 2.95
    NTreal numElem = pow(n,d);
    NTreal maxIndexRange = numeric_limits<NTsize>::max();
    if (numElem >= maxIndexRange) {
        cerr <<
        "NT_multidim_array_o::NT_multidim_array_o - Error : array will contain to many elements"
        << numElem << " for supported implementation range "
        << maxIndexRange << " ("<< numeric_limits<NTsize>.max()
        << "). Undefined behaviour may result." << endl;
    }
    */
    // cache setup
    powerSeriesCacheVec.resize(dim+1);
    // = {1,num,num^2,...,num^dim}
    powerSeriesCacheVec[0] = 1;
    for (NTsize ll = 1; ll < dim+1; ll++){
        powerSeriesCacheVec[ll] = num * powerSeriesCacheVec[ll-1];
        cerr <<powerSeriesCacheVec[ll] << endl;
    }
    // memory allocation
    try {
        dataVec.resize(powerSeriesCacheVec[dim]);
    }
    catch (bad_alloc) {
        cerr << "NT_multidim_array_o::NT_multidim_array_o - Error : Memory exhausted by allocation of multidimensional array."
        << ">" << powerSeriesCacheVec[dim] * sizeof(T) << " bytes of memory are necessary for this object."
        << endl;
    }
}
template<class T> NT_multidim_array_o< T >::NT_multidim_array_o (const NT_multidim_array_o< T > & original) [inline]
Definition at line 108 of file nt_multidim_array_obj.h.
{
 cerr <<"NT_multidim_array_o::(const NT_multidim_array_o) - Error : Not implemented. Not to be supported ?" << endl;
}
template<class T> virtual NT_multidim_array_o< T >::~NT_multidim_array_o () [inline, virtual]
Definition at line 123 of file nt_multidim_array_obj.h.
{
}
Member Function Documentation
template<class T> T& NT_multidim_array_o< T >::Elem (const vector< NTsize > & coordinateVec) [inline]
Parameters:
none
Returns:
none
Warning:
no range checking done on the coordinates
Bug:
unknown
Definition at line 135 of file nt_multidim_array_obj.h.
Referenced by NT_multidim_array_o< NTsize >::Elem().
{
    NTsize hash = Hash(coordinateVec);
    NT_ASSERT (dataVec.size() >= hash);
    return dataVec[ hash ];
}
template<class T> T& NT_multidim_array_o< T >::Elem (NTsize index1...) [inline]
Parameters:
none
Returns:
none
Warning:
no range checking done on the coordinates
Bug:
unknown
Definition at line 176 of file nt_multidim_array_obj.h.
{
    vector <NTsize> coorVec(dim);
    va_list args;
    va_start(args,index1);
    for (NTsize ld=0; ld < dim; ld++){
        coorVec[ld] = va_arg(args, NTsize);
    }
    va_end(args);
    return Elem(coorVec);
}
template<class T> const T& NT_multidim_array_o< T >::ElemByIndex (NTsize index) const [inline]
Parameters:
An index that is guaranteed to touch all elements but has no assigned meaning as to the position of element in relation to others. However index $ [0,num^dim]$ is guaranteed and will touch all elements ones.
Returns:
none
Warning:
Arbitrary index, no information inferable from the index, might change anytime (only range remains guaranteed).
Bug:
unknown
Definition at line 154 of file nt_multidim_array_obj.h.
{
    NT_ASSERT( (index >= 0) && (index < TotalNumElem()) );
    return dataVec[index];
}
template<class T> const NT_multidim_array_o& NT_multidim_array_o< T >::operator= (const NT_multidim_array_o< T > & right) [inline]
Definition at line 115 of file nt_multidim_array_obj.h.
{
 if (this == &right) return *this; // Gracefully handle self assignment
 cerr <<"NT_multidim_array_o::operator= - Error : Not implemented. Not to be supported ?" << endl;
 return *this;
}
template<class T> void NT_multidim_array_o< T >::SetAll (const T & val) [inline]
Definition at line 162 of file nt_multidim_array_obj.h.
{
    for (NTsize ll = 0; ll < TotalNumElem(); ll++){
        dataVec[ll] = val;
    }
}
template<class T> NTsize NT_multidim_array_o< T >::TotalNumElem () const [inline]
Definition at line 190 of file nt_multidim_array_obj.h.
Referenced by NT_multidim_array_o< NTsize >::ElemByIndex(), and NT_multidim_array_o< NTsize >::SetAll().
{
    return powerSeriesCacheVec[dim];
}
The documentation for this class was generated from the following file:
nt_multidim_array_obj.h