NetTrader: TNT::Vector< T > Class Template Reference
TNT::Vector< T > Class Template Reference
#include <vec.h>
Public Types
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
iterator begin ()
iterator end ()
const iterator begin () const
const iterator end () const
~Vector ()
Vector ()
Vector (const Vector< T > &A)
Vector (Subscript N, const T &value=T())
Vector (Subscript N, const T *v)
Vector (Subscript N, char *s)
Vector< T > & newsize (Subscript N)
Vector< T > & operator= (const Vector< T > &A)
Vector< T > & operator= (const T &scalar)
Subscript dim () const
Subscript size () const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator[] (Subscript i)
const_reference operator[] (Subscript i) const
Protected Member Functions
void initialize (Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
Protected Attributes
T * v_
T * vm1_
Subscript n_
Detailed Description
template<class T>
class TNT::Vector< T >
Definition at line 41 of file vec.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Vector< T >::const_iterator
Definition at line 53 of file vec.h.
template<class T> typedef const T& TNT::Vector< T >::const_reference
Definition at line 54 of file vec.h.
template<class T> typedef T TNT::Vector< T >::element_type
Definition at line 49 of file vec.h.
template<class T> typedef T* TNT::Vector< T >::iterator
Definition at line 51 of file vec.h.
template<class T> typedef T* TNT::Vector< T >::pointer
Definition at line 50 of file vec.h.
template<class T> typedef T& TNT::Vector< T >::reference
Definition at line 52 of file vec.h.
template<class T> typedef Subscript TNT::Vector< T >::size_type
Definition at line 47 of file vec.h.
template<class T> typedef T TNT::Vector< T >::value_type
Definition at line 48 of file vec.h.
Constructor & Destructor Documentation
template<class T> TNT::Vector< T >::~Vector () [inline]
Definition at line 157 of file vec.h.
    {
        destroy();
    }
template<class T> TNT::Vector< T >::Vector () [inline]
Definition at line 164 of file vec.h.
: v_(0), vm1_(0), n_(0)  {};
template<class T> TNT::Vector< T >::Vector (const Vector< T > & A) [inline]
Definition at line 166 of file vec.h.
                               : v_(0), vm1_(0), n_(0)
    {
        initialize(A.n_);
        copy(A.v_);
    }
template<class T> TNT::Vector< T >::Vector (Subscript N, const T & value = T()) [inline]
Definition at line 172 of file vec.h.
                                              :  v_(0), vm1_(0), n_(0)
    {
        initialize(N);
        set(value);
    }
template<class T> TNT::Vector< T >::Vector (Subscript N, const T * v) [inline]
Definition at line 178 of file vec.h.
                                    :  v_(0), vm1_(0), n_(0)
    {
        initialize(N);
        copy(v);
    }
template<class T> TNT::Vector< T >::Vector (Subscript N, char * s) [inline]
Definition at line 184 of file vec.h.
                                 :  v_(0), vm1_(0), n_(0)
    {
        initialize(N);
        std::istrstream ins(s);
        Subscript i;
        for (i=0; i<N; i++)
                ins >> v_[i];
    }
Member Function Documentation
template<class T> iterator TNT::Vector< T >::begin () [inline]
Definition at line 150 of file vec.h.
Referenced by Upper_symmetric_eigenvalue_solve().
{ return v_;}
template<class T> const iterator TNT::Vector< T >::begin () const [inline]
Definition at line 152 of file vec.h.
{ return v_;}
template<class T> void TNT::Vector< T >::copy (const T * v) [inline, protected]
Definition at line 78 of file vec.h.
Referenced by TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::Vector().
    {
        Subscript N = n_;
        Subscript i;
#ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = v[i];
            v_[i+1] = v[i+1];
            v_[i+2] = v[i+2];
            v_[i+3] = v[i+3];
        }
        for (i=N4; i< N; i++)
            v_[i] = v[i];
#else
        for (i=0; i< N; i++)
            v_[i] = v[i];
#endif
    }
template<class T> void TNT::Vector< T >::destroy () [inline, protected]
Definition at line 133 of file vec.h.
Referenced by TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::~Vector().
    {
        /* do nothing, if no memory has been previously allocated */
        if (v_ == NULL) return ;
        /* if we are here, then matrix was previously allocated */
        delete [] (v_);
        v_ = NULL;
        vm1_ = NULL;
    }
template<class T> Subscript TNT::Vector< T >::dim () const [inline]
Definition at line 235 of file vec.h.
Referenced by TNT::dot_prod(), TNT::matmult(), TNT::operator*(), TNT::operator+(), TNT::operator-(), TNT::QR_solve(), and TNT::R_solve().
    {
        return  n_;
    }
template<class T> const iterator TNT::Vector< T >::end () const [inline]
Definition at line 153 of file vec.h.
{ return v_ + n_; }
template<class T> iterator TNT::Vector< T >::end () [inline]
Definition at line 151 of file vec.h.
{ return v_ + n_; }
template<class T> void TNT::Vector< T >::initialize (Subscript N) [inline, protected]
Definition at line 66 of file vec.h.
Referenced by TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator=(), and TNT::Vector< Subscript >::Vector().
    {
        // adjust pointers so that they are 1-offset:
        // v_[] is the internal contiguous array, it is still 0-offset
        //
        assert(v_ == NULL);
        v_ = new T[N];
        assert(v_  != NULL);
        vm1_ = v_-1;
        n_ = N;
    }
template<class T> Subscript TNT::Vector< T >::lbound () const [inline]
Definition at line 56 of file vec.h.
Referenced by TNT::QR_factor(), TNT::QR_solve(), and TNT::R_solve().
{ return 1;}
template<class T> Vector<T>& TNT::Vector< T >::newsize (Subscript N) [inline]
Definition at line 198 of file vec.h.
Referenced by eigenvalue_solve(), TNT::operator>>(), and TNT::QR_factor().
    {
        if (n_ == N) return *this;
        destroy();
        initialize(N);
        return *this;
    }
template<class T> const_reference TNT::Vector< T >::operator() (Subscript i) const [inline]
Definition at line 255 of file vec.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= n_) ;
#endif
        return vm1_[i];
    }
template<class T> reference TNT::Vector< T >::operator() (Subscript i) [inline]
Definition at line 246 of file vec.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= n_) ;
#endif
        return vm1_[i];
    }
template<class T> Vector<T>& TNT::Vector< T >::operator= (const Vector< T > & A) [inline]
Definition at line 211 of file vec.h.
    {
        if (v_ == A.v_)
            return *this;
        if (n_ == A.n_)         // no need to re-alloc
            copy(A.v_);
        else
        {
            destroy();
            initialize(A.n_);
            copy(A.v_);
        }
        return *this;
    }
template<class T> Vector<T>& TNT::Vector< T >::operator= (const T & scalar) [inline]
Definition at line 229 of file vec.h.
    {
        set(scalar);
        return *this;
    }
template<class T> reference TNT::Vector< T >::operator[] (Subscript i) [inline]
Definition at line 264 of file vec.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i < n_) ;
#endif
        return v_[i];
    }
template<class T> const_reference TNT::Vector< T >::operator[] (Subscript i) const [inline]
Definition at line 273 of file vec.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i < n_) ;
#endif
        return v_[i];
    }
template<class T> void TNT::Vector< T >::set (const T & val) [inline, protected]
Definition at line 104 of file vec.h.
    {
        Subscript N = n_;
        Subscript i;
#ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = val;
            v_[i+1] = val;
            v_[i+2] = val;
            v_[i+3] = val;
        }
        for (i=N4; i< N; i++)
            v_[i] = val;
#else
        for (i=0; i< N; i++)
            v_[i] = val;
#endif
    }
template<class T> Subscript TNT::Vector< T >::size () const [inline]
Definition at line 240 of file vec.h.
Referenced by TNT::operator>>(), and TNT::QR_factor().
    {
        return  n_;
    }
Member Data Documentation
template<class T> Subscript TNT::Vector< T >::n_ [protected]
Definition at line 61 of file vec.h.
Referenced by TNT::Vector< Subscript >::copy(), TNT::Vector< Subscript >::dim(), TNT::Vector< Subscript >::end(), TNT::Vector< Subscript >::initialize(), TNT::Vector< Subscript >::newsize(), TNT::Vector< Subscript >::operator()(), TNT::Vector< Subscript >::operator=(), TNT::Vector< Subscript >::operator[](), TNT::Vector< Subscript >::set(), TNT::Vector< Subscript >::size(), and TNT::Vector< Subscript >::Vector().
template<class T> T* TNT::Vector< T >::v_ [protected]
Definition at line 59 of file vec.h.
Referenced by TNT::Vector< Subscript >::begin(), TNT::Vector< Subscript >::copy(), TNT::Vector< Subscript >::destroy(), TNT::Vector< Subscript >::end(), TNT::Vector< Subscript >::initialize(), TNT::Vector< Subscript >::operator=(), TNT::Vector< Subscript >::operator[](), TNT::Vector< Subscript >::set(), and TNT::Vector< Subscript >::Vector().
template<class T> T* TNT::Vector< T >::vm1_ [protected]
Definition at line 60 of file vec.h.
Referenced by TNT::Vector< Subscript >::destroy(), TNT::Vector< Subscript >::initialize(), and TNT::Vector< Subscript >::operator()().
The documentation for this class was generated from the following file:
vec.h