NetTrader: TNT::Matrix< T > Class Template Reference
TNT::Matrix< T > Class Template Reference
#include <cmat.h>
Public Types
typedef Subscript size_type
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
Subscript lbound () const
operator T ** ()
operator T ** () const
Subscript size () const
Matrix ()
Matrix (const Matrix< T > &A)
Matrix (Subscript M, Subscript N, const T &value=T())
Matrix (Subscript M, Subscript N, const T *v)
Matrix (Subscript M, Subscript N, const char *s)
~Matrix ()
Matrix< T > & newsize (Subscript M, Subscript N)
Matrix< T > & operator= (const Matrix< T > &A)
Matrix< T > & operator= (const T &scalar)
Subscript dim (Subscript d) const
Subscript num_rows () const
Subscript num_cols () const
T * operator[] (Subscript i)
const T * operator[] (Subscript i) const
reference operator() (Subscript i)
const_reference operator() (Subscript i) const
reference operator() (Subscript i, Subscript j)
const_reference operator() (Subscript i, Subscript j) const
Protected Member Functions
void initialize (Subscript M, Subscript N)
void copy (const T *v)
void set (const T &val)
void destroy ()
Protected Attributes
Subscript m_
Subscript n_
Subscript mn_
T * v_
T ** row_
T * vm1_
T ** rowm1_
Detailed Description
template<class T>
class TNT::Matrix< T >
Definition at line 46 of file cmat.h.
Member Typedef Documentation
template<class T> typedef const T* TNT::Matrix< T >::const_iterator
Definition at line 56 of file cmat.h.
template<class T> typedef const T& TNT::Matrix< T >::const_reference
Definition at line 57 of file cmat.h.
template<class T> typedef T TNT::Matrix< T >::element_type
Definition at line 52 of file cmat.h.
template<class T> typedef T* TNT::Matrix< T >::iterator
Definition at line 54 of file cmat.h.
template<class T> typedef T* TNT::Matrix< T >::pointer
Definition at line 53 of file cmat.h.
template<class T> typedef T& TNT::Matrix< T >::reference
Definition at line 55 of file cmat.h.
template<class T> typedef Subscript TNT::Matrix< T >::size_type
Definition at line 50 of file cmat.h.
template<class T> typedef T TNT::Matrix< T >::value_type
Definition at line 51 of file cmat.h.
Constructor & Destructor Documentation
template<class T> TNT::Matrix< T >::Matrix () [inline]
Definition at line 172 of file cmat.h.
: m_(0), n_(0), mn_(0), v_(0), row_(0), vm1_(0), rowm1_(0) {};
template<class T> TNT::Matrix< T >::Matrix (const Matrix< T > & A) [inline]
Definition at line 174 of file cmat.h.
    {
        initialize(A.m_, A.n_);
        copy(A.v_);
    }
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T & value = T()) [inline]
Definition at line 180 of file cmat.h.
    {
        initialize(M,N);
        set(value);
    }
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const T * v) [inline]
Definition at line 186 of file cmat.h.
    {
        initialize(M,N);
        copy(v);
    }
template<class T> TNT::Matrix< T >::Matrix (Subscript M, Subscript N, const char * s) [inline]
Definition at line 192 of file cmat.h.
    {
        initialize(M,N);
        std::istrstream ins(s);
        Subscript i, j;
        for (i=0; i<M; i++)
            for (j=0; j<N; j++)
                ins >> row_[i][j];
    }
template<class T> TNT::Matrix< T >::~Matrix () [inline]
Definition at line 206 of file cmat.h.
    {
        destroy();
    }
Member Function Documentation
template<class T> void TNT::Matrix< T >::copy (const T * v) [inline, protected]
Definition at line 97 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::Matrix(), and TNT::Matrix< NTreal >::operator=().
    {
        Subscript N = m_ * n_;
        Subscript i;
    #ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = v[i];
            v_[i+1] = v[i+1];
            v_[i+2] = v[i+2];
            v_[i+3] = v[i+3];
        }
        for (i=N4; i< N; i++)
            v_[i] = v[i];
    #else
        for (i=0; i< N; i++)
            v_[i] = v[i];
    #endif
    }
template<class T> void TNT::Matrix< T >::destroy () [inline, protected]
Definition at line 147 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::newsize(), TNT::Matrix< NTreal >::operator=(), and TNT::Matrix< NTreal >::~Matrix().
    {
        /* do nothing, if no memory has been previously allocated */
        if (v_ == NULL) return ;
        /* if we are here, then matrix was previously allocated */
        if (v_ != NULL) delete [] (v_);
        if (row_ != NULL) delete [] (row_);
        /* return rowm1_ back to original value */
        rowm1_ ++;
        if (rowm1_ != NULL ) delete [] (rowm1_);
    }
template<class T> Subscript TNT::Matrix< T >::dim (Subscript d) const [inline]
Definition at line 255 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
       assert( d >= 1);
        assert( d <= 2);
#endif
        return (d==1) ? m_ : ((d==2) ? n_ : 0);
    }
template<class T> void TNT::Matrix< T >::initialize (Subscript M, Subscript N) [inline, protected]
Definition at line 70 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::Matrix(), TNT::Matrix< NTreal >::newsize(), and TNT::Matrix< NTreal >::operator=().
    {
        mn_ = M*N;
        m_ = M;
        n_ = N;
        v_ = new T[mn_];
        row_ = new T*[M];
        rowm1_ = new T*[M];
        assert(v_  != NULL);
        assert(row_  != NULL);
        assert(rowm1_ != NULL);
        T* p = v_;
        vm1_ = v_ - 1;
        for (Subscript i=0; i<M; i++)
        {
            row_[i] = p;
            rowm1_[i] = p-1;
            p += N ;
        }
        rowm1_ -- ;     // compensate for 1-based offset
    }
template<class T> Subscript TNT::Matrix< T >::lbound () const [inline]
Definition at line 58 of file cmat.h.
{ return 1;}
template<class T> Matrix<T>& TNT::Matrix< T >::newsize (Subscript M, Subscript N) [inline]
Definition at line 214 of file cmat.h.
Referenced by TNT::matmult(), and TNT::operator>>().
    {
        if (num_rows() == M && num_cols() == N)
            return *this;
        destroy();
        initialize(M,N);
        return *this;
    }
template<class T> Subscript TNT::Matrix< T >::num_cols () const [inline]
Definition at line 265 of file cmat.h.
Referenced by TNT::matmult(), TNT::mult_element(), TNT::Matrix< NTreal >::newsize(), NodeDistanceMatrixConditioning(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), and TNT::transpose().
{ return n_; }
template<class T> Subscript TNT::Matrix< T >::num_rows () const [inline]
Definition at line 264 of file cmat.h.
Referenced by TNT::matmult(), TNT::mult_element(), TNT::Matrix< NTreal >::newsize(), NodeDistanceMatrixConditioning(), TNT::operator+(), TNT::operator-(), TNT::operator>>(), and TNT::transpose().
{ return m_; }
template<class T> TNT::Matrix< T >::operator T ** () [inline]
Definition at line 164 of file cmat.h.
References TNT::Matrix< T >::row_.
{ return  row_; }
template<class T> TNT::Matrix< T >::operator T ** () const [inline]
Definition at line 165 of file cmat.h.
References TNT::Matrix< T >::row_.
{ return row_; }
template<class T> reference TNT::Matrix< T >::operator() (Subscript i) [inline]
Definition at line 288 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= mn_) ;
#endif
        return vm1_[i];
    }
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i) const [inline]
Definition at line 297 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= mn_) ;
#endif
        return vm1_[i];
    }
template<class T> const_reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 321 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= m_) ;
        assert(1<=j);
        assert(j <= n_);
#endif
        return rowm1_[i][j];
    }
template<class T> reference TNT::Matrix< T >::operator() (Subscript i, Subscript j) [inline]
Definition at line 308 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(1<=i);
        assert(i <= m_) ;
        assert(1<=j);
        assert(j <= n_);
#endif
        return  rowm1_[i][j];
    }
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const T & scalar) [inline]
Definition at line 248 of file cmat.h.
    {
        set(scalar);
        return *this;
    }
template<class T> Matrix<T>& TNT::Matrix< T >::operator= (const Matrix< T > & A) [inline]
Definition at line 230 of file cmat.h.
    {
        if (v_ == A.v_)
            return *this;
        if (m_ == A.m_  && n_ == A.n_)      // no need to re-alloc
            copy(A.v_);
        else
        {
            destroy();
            initialize(A.m_, A.n_);
            copy(A.v_);
        }
        return *this;
    }
template<class T> const T* TNT::Matrix< T >::operator[] (Subscript i) const [inline]
Definition at line 279 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i < m_) ;
#endif
        return row_[i];
    }
template<class T> T* TNT::Matrix< T >::operator[] (Subscript i) [inline]
Definition at line 270 of file cmat.h.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(0<=i);
        assert(i < m_) ;
#endif
        return row_[i];
    }
template<class T> void TNT::Matrix< T >::set (const T & val) [inline, protected]
Definition at line 122 of file cmat.h.
    {
        Subscript N = m_ * n_;
        Subscript i;
    #ifdef TNT_UNROLL_LOOPS
        Subscript Nmod4 = N & 3;
        Subscript N4 = N - Nmod4;
        for (i=0; i<N4; i+=4)
        {
            v_[i] = val;
            v_[i+1] = val;
            v_[i+2] = val;
            v_[i+3] = val;
        }
        for (i=N4; i< N; i++)
            v_[i] = val;
    #else
        for (i=0; i< N; i++)
            v_[i] = val;
    #endif
    }
template<class T> Subscript TNT::Matrix< T >::size () const [inline]
Definition at line 168 of file cmat.h.
Referenced by NodeDistanceMatrixConditioning().
{ return mn_; }
Member Data Documentation
template<class T> Subscript TNT::Matrix< T >::m_ [protected]
Definition at line 60 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::copy(), TNT::Matrix< NTreal >::dim(), TNT::Matrix< NTreal >::initialize(), TNT::Matrix< NTreal >::Matrix(), TNT::Matrix< NTreal >::num_rows(), TNT::Matrix< NTreal >::operator()(), TNT::Matrix< NTreal >::operator=(), TNT::Matrix< NTreal >::operator[](), and TNT::Matrix< NTreal >::set().
template<class T> Subscript TNT::Matrix< T >::mn_ [protected]
Definition at line 62 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::initialize(), TNT::Matrix< NTreal >::operator()(), and TNT::Matrix< NTreal >::size().
template<class T> Subscript TNT::Matrix< T >::n_ [protected]
Definition at line 61 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::copy(), TNT::Matrix< NTreal >::dim(), TNT::Matrix< NTreal >::initialize(), TNT::Matrix< NTreal >::Matrix(), TNT::Matrix< NTreal >::num_cols(), TNT::Matrix< NTreal >::operator()(), TNT::Matrix< NTreal >::operator=(), and TNT::Matrix< NTreal >::set().
template<class T> T** TNT::Matrix< T >::row_ [protected]
Definition at line 64 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::destroy(), TNT::Matrix< NTreal >::initialize(), TNT::Matrix< NTreal >::Matrix(), TNT::Matrix< T >::operator T **(), and TNT::Matrix< NTreal >::operator[]().
template<class T> T** TNT::Matrix< T >::rowm1_ [protected]
Definition at line 66 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::destroy(), TNT::Matrix< NTreal >::initialize(), and TNT::Matrix< NTreal >::operator()().
template<class T> T* TNT::Matrix< T >::v_ [protected]
Definition at line 63 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::copy(), TNT::Matrix< NTreal >::destroy(), TNT::Matrix< NTreal >::initialize(), TNT::Matrix< NTreal >::Matrix(), TNT::Matrix< NTreal >::operator=(), and TNT::Matrix< NTreal >::set().
template<class T> T* TNT::Matrix< T >::vm1_ [protected]
Definition at line 65 of file cmat.h.
Referenced by TNT::Matrix< NTreal >::initialize(), and TNT::Matrix< NTreal >::operator()().
The documentation for this class was generated from the following file:
cmat.h