NetTrader: TNT::Transpose_View< Array2D > Class Template Reference
TNT::Transpose_View< Array2D > Class Template Reference
#include <transv.h>
Public Types
typedef Array2D::element_type T
typedef T value_type
typedef T element_type
typedef T * pointer
typedef T * iterator
typedef T & reference
typedef const T * const_iterator
typedef const T & const_reference
Public Member Functions
const Array2D & array () const
Subscript num_rows () const
Subscript num_cols () const
Subscript lbound () const
Subscript dim (Subscript i) const
Transpose_View (const Transpose_View< Array2D > &A)
Transpose_View (const Array2D &A)
const Array2D::element_type & operator() (Subscript i, Subscript j) const
Protected Attributes
const Array2D & A_
Detailed Description
template<class Array2D>
class TNT::Transpose_View< Array2D >
Definition at line 39 of file transv.h.
Member Typedef Documentation
template<class Array2D> typedef const T* TNT::Transpose_View< Array2D >::const_iterator
Definition at line 53 of file transv.h.
template<class Array2D> typedef const T& TNT::Transpose_View< Array2D >::const_reference
Definition at line 54 of file transv.h.
template<class Array2D> typedef T TNT::Transpose_View< Array2D >::element_type
Definition at line 49 of file transv.h.
template<class Array2D> typedef T* TNT::Transpose_View< Array2D >::iterator
Definition at line 51 of file transv.h.
template<class Array2D> typedef T* TNT::Transpose_View< Array2D >::pointer
Definition at line 50 of file transv.h.
template<class Array2D> typedef T& TNT::Transpose_View< Array2D >::reference
Definition at line 52 of file transv.h.
template<class Array2D> typedef Array2D::element_type TNT::Transpose_View< Array2D >::T
Definition at line 47 of file transv.h.
template<class Array2D> typedef T TNT::Transpose_View< Array2D >::value_type
Definition at line 48 of file transv.h.
Constructor & Destructor Documentation
template<class Array2D> TNT::Transpose_View< Array2D >::Transpose_View (const Transpose_View< Array2D > & A) [inline]
Definition at line 74 of file transv.h.
: A_(A.A_) {};
template<class Array2D> TNT::Transpose_View< Array2D >::Transpose_View (const Array2D & A) [inline]
Definition at line 75 of file transv.h.
: A_(A) {};
Member Function Documentation
template<class Array2D> const Array2D& TNT::Transpose_View< Array2D >::array () const [inline]
Definition at line 57 of file transv.h.
References TNT::Transpose_View< Array2D >::A_.
{ return A_; }
template<class Array2D> Subscript TNT::Transpose_View< Array2D >::dim (Subscript i) const [inline]
Definition at line 61 of file transv.h.
References TNT::Transpose_View< Array2D >::A_, TNT::Transpose_View< Array2D >::num_cols(), and TNT::Transpose_View< Array2D >::num_rows().
        {
#ifdef TNT_BOUNDS_CHECK
            assert( A_.lbound() <= i);
            assert( i<= A_.lbound()+1);
#endif
            if (i== A_.lbound())
                return num_rows();
            else
                return num_cols();
        }
template<class Array2D> Subscript TNT::Transpose_View< Array2D >::lbound () const [inline]
Definition at line 60 of file transv.h.
References TNT::Transpose_View< Array2D >::A_.
Referenced by TNT::Transpose_View< Array2D >::operator()().
{ return A_.lbound(); }
template<class Array2D> Subscript TNT::Transpose_View< Array2D >::num_cols () const [inline]
Definition at line 59 of file transv.h.
References TNT::Transpose_View< Array2D >::A_.
Referenced by TNT::Transpose_View< Array2D >::dim(), and TNT::matmult().
{ return A_.num_rows();}
template<class Array2D> Subscript TNT::Transpose_View< Array2D >::num_rows () const [inline]
Definition at line 58 of file transv.h.
References TNT::Transpose_View< Array2D >::A_.
Referenced by TNT::Transpose_View< Array2D >::dim(), and TNT::matmult().
{ return A_.num_cols();}
template<class Array2D> const Array2D::element_type& TNT::Transpose_View< Array2D >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 78 of file transv.h.
References TNT::Transpose_View< Array2D >::A_, and TNT::Transpose_View< Array2D >::lbound().
        {
#ifdef TNT_BOUNDS_CHECK
        assert(lbound()<=i);
        assert(i<=A_.num_cols() + lbound() - 1);
        assert(lbound()<=j);
        assert(j<=A_.num_rows() + lbound() - 1);
#endif
            return A_(j,i);
        }
Member Data Documentation
template<class Array2D> const Array2D& TNT::Transpose_View< Array2D >::A_ [protected]
Definition at line 43 of file transv.h.
Referenced by TNT::Transpose_View< Array2D >::array(), TNT::Transpose_View< Array2D >::dim(), TNT::Transpose_View< Array2D >::lbound(), TNT::Transpose_View< Array2D >::num_cols(), TNT::Transpose_View< Array2D >::num_rows(), and TNT::Transpose_View< Array2D >::operator()().
The documentation for this class was generated from the following file:
transv.h