NetTrader: NTBP_multi_current_o Class Reference
NTBP_multi_current_o Class Reference
NTBP_multi_current_o class Base class for stochastic channel simulations of individual channels.
#include <ntbp_multi_current_obj.h>
Public Member Functions
NTBP_multi_current_o (NTreal reversalPotential, NTreal density, NTreal area, NTreal conductivity, NTreal vBase=0)
NTBP_multi_current_o (const NTBP_multi_current_o &original)
const NTBP_multi_current_o & operator= (const NTBP_multi_current_o &right)
virtual ~NTBP_multi_current_o ()
NTreal _density () const
NTreal _area () const
NTreal _conductivity () const
NTreal _maxConductivity () const
bool ComputeGillespieStep ()
void UpdateNumChannels ()
NTsize _numChannels () const
NTreal NumChannels () const
Number of total ionic channels.
NTreal OpenChannelsRatio () const
Number of open over total number of channels.
NTreal _vBase () const
Protected Attributes
NTreal conductivity
NTreal density
NTBP_ion_channels_o * channelsPtr
Static Protected Attributes
static NT_uniform_rnd_dist_o uniformRnd
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 61 of file ntbp_multi_current_obj.h.
Constructor & Destructor Documentation
NTBP_multi_current_o::NTBP_multi_current_o (NTreal reversalPotential, NTreal density, NTreal area, NTreal conductivity, NTreal vBase = 0)
NTBP_multi_current_o::NTBP_multi_current_o (const NTBP_multi_current_o & original)
virtual NTBP_multi_current_o::~NTBP_multi_current_o () [virtual]
Member Function Documentation
NTreal NTBP_multi_current_o::_area () const [inline]
Definition at line 79 of file ntbp_multi_current_obj.h.
{ return area; }
NTreal NTBP_multi_current_o::_conductivity () const [inline]
Definition at line 81 of file ntbp_multi_current_obj.h.
{ return conductivity; }
NTreal NTBP_multi_current_o::_density () const [inline]
Definition at line 78 of file ntbp_multi_current_obj.h.
{ return density;}
NTreal NTBP_multi_current_o::_maxConductivity () const [inline, virtual]
Implements NTBP_membrane_current_o.
Definition at line 83 of file ntbp_multi_current_obj.h.
{return density /* num/muMeter^2 */ * conductivity /* mSiemens */* 1.0e8 /* muMeter^2/cm^2 */;}
NTsize NTBP_multi_current_o::_numChannels () const [inline]
Definition at line 87 of file ntbp_multi_current_obj.h.
Referenced by NumChannels().
{ return numChannels; }
NTreal NTBP_multi_current_o::_vBase () const [inline]
Definition at line 91 of file ntbp_multi_current_obj.h.
Referenced by NTBP_hranvier_sodium_multi_current_o::AlphaH(), NTBP_hranvier_sodium_multi_current_o::AlphaM(), NTBP_hranvier_potassium_multi_current_o::AlphaN(), NTBP_hranvier_sodium_multi_current_o::BetaH(), NTBP_hranvier_sodium_multi_current_o::BetaM(), and NTBP_hranvier_potassium_multi_current_o::BetaN().
{ return vBase;}
bool NTBP_multi_current_o::ComputeGillespieStep () [inline, virtual]
Reimplemented from NTBP_membrane_current_o.
Definition at line 85 of file ntbp_multi_current_obj.h.
References channelsPtr, and NTBP_ion_channels_o::GillespieStep().
{cerr <<"NTBP_multi_current_o::ComputeGillespieStep()" << endl; return channelsPtr->GillespieStep();}
NTreal NTBP_multi_current_o::NumChannels () const [inline, virtual]
Reimplemented from NTBP_membrane_current_o.
Definition at line 89 of file ntbp_multi_current_obj.h.
References _numChannels().
Referenced by OpenChannelsRatio().
{ return _numChannels(); }
NTreal NTBP_multi_current_o::OpenChannelsRatio () const [inline, virtual]
Reimplemented from NTBP_membrane_current_o.
Definition at line 90 of file ntbp_multi_current_obj.h.
References NumChannels(), and NTBP_membrane_current_o::OpenChannels().
{ return OpenChannels()/NumChannels(); }
const NTBP_multi_current_o& NTBP_multi_current_o::operator= (const NTBP_multi_current_o & right)
void NTBP_multi_current_o::UpdateNumChannels () [inline]
Definition at line 86 of file ntbp_multi_current_obj.h.
{ numChannels = (NTsize) ceil(density*area); }
Member Data Documentation
NTBP_ion_channels_o* NTBP_multi_current_o::channelsPtr [protected]
Definition at line 101 of file ntbp_multi_current_obj.h.
Referenced by ComputeGillespieStep(), NTBP_multi_sodium_current_o::Show(), NTBP_hranvier_sodium_multi_current_o::Show(), NTBP_multi_sodium_current_o::ShowChannelStatePopulation(), and NTBP_hranvier_sodium_multi_current_o::ShowChannelStatePopulation().
NTreal NTBP_multi_current_o::conductivity [protected]
Definition at line 99 of file ntbp_multi_current_obj.h.
NTreal NTBP_multi_current_o::density [protected]
Definition at line 100 of file ntbp_multi_current_obj.h.
NT_uniform_rnd_dist_o NTBP_multi_current_o::uniformRnd [static, protected]
Definition at line 98 of file ntbp_multi_current_obj.h.
The documentation for this class was generated from the following file:
ntbp_multi_current_obj.h