NetTrader: NT3D_object_o Class Reference
NT3D_object_o Class Reference
NT3D object class.
#include <nt3d_object_obj.h>
Public Member Functions
NT3D_object_o ()
NT3D_object_o (const NT_vector3_o &oNewPosition)
NT3D_object_o (const NT3D_object_o &original)
virtual ~NT3D_object_o ()
void Rotate (const NT_vector3_o &oDeltaRotation)
void RotateX (NTreal deltaRotX)
void RotateY (NTreal deltaRotY)
void RotateZ (NTreal deltaRotZ)
void RotateXYZ (NT_vector3_o oDeltaRot)
void RotateXYZ (const NTreal deltaRot[3])
void RotateNull ()
void SetRotationX (const NTreal rotX)
void SetRotationY (const NTreal rotY)
void SetRotationZ (const NTreal rotZ)
void SetRotationXYZ (const NT_vector3_o &oRot)
virtual void Translate (const NT_vector3_o &oDeltaTranslation)
virtual void TranslateX (const NTreal deltaTraX)
virtual void TranslateY (const NTreal deltaTraY)
virtual void TranslateZ (const NTreal deltaTraZ)
virtual void TranslateXYZ (const NT_vector3_o &oDeltaTra)
virtual void TranslateXYZ (const NTreal deltaTra[3])
virtual void TranslateNull ()
virtual void SetTranslationX (const NTreal traX)
virtual void SetTranslationY (const NTreal traY)
virtual void SetTranslationZ (const NTreal traZ)
virtual void SetTranslationXYZ (const NT_vector3_o &oTra)
void Collinearize (const NT_vector3_o &oRelativeVector)
rotate the object such that its (oRotation vector would rotate a vector on the) x-axis in the direction of oRelativeVector
NT_vector3_o _oTranslation () const
NT_vector3_o _oRotation () const
virtual void Draw ()=0
The Draw() method is the invocation method to use for users.
void Control (NT3Dcontroller cntrl, NTint value)
Set any control/state variables in the object and in the child tree.
void Control (NT3Dcontroller cntrl, NTreal value)
void Control (NT3Dcontroller cntrl, NT_vector_o value)
Protected Member Functions
virtual void ControlImpl (NT3Dcontroller cntrl, NTint value)=0
Set the control/state variable in *this object.
virtual void ControlImpl (NT3Dcontroller cntrl, NTreal value)=0
virtual void ControlImpl (NT3Dcontroller cntrl, NT_vector_o value)=0
Protected Attributes
NT_vector3_o oTranslation
NT_vector3_o oRotation
Detailed Description
Definition of a drawable entity with positional and rotational characteristics in 3D space.
The "main axis" of an object in space, should be constructed along the X-Axis, as methods will assume this.
Definition at line 149 of file nt3d_object_obj.h.
Constructor & Destructor Documentation
NT3D_object_o::NT3D_object_o ()
NT3D_object_o::NT3D_object_o (const NT_vector3_o & oNewPosition)
NT3D_object_o::NT3D_object_o (const NT3D_object_o & original)
virtual NT3D_object_o::~NT3D_object_o () [virtual]
Member Function Documentation
NT_vector3_o NT3D_object_o::_oRotation () const [inline]
Definition at line 187 of file nt3d_object_obj.h.
References oRotation.
{ return oRotation; }
NT_vector3_o NT3D_object_o::_oTranslation () const [inline]
Definition at line 186 of file nt3d_object_obj.h.
References oTranslation.
{ return oTranslation; }
void NT3D_object_o::Collinearize (const NT_vector3_o & oRelativeVector)
Reimplemented in NT3D_arrow_o.
void NT3D_object_o::Control (NT3Dcontroller cntrl, NTint value) [inline]
Definition at line 194 of file nt3d_object_obj.h.
References ControlImpl().
{ControlImpl(cntrl , value);}
void NT3D_object_o::Control (NT3Dcontroller cntrl, NTreal value) [inline]
Definition at line 195 of file nt3d_object_obj.h.
References ControlImpl().
{ControlImpl(cntrl , value);}
void NT3D_object_o::Control (NT3Dcontroller cntrl, NT_vector_o value) [inline]
Definition at line 196 of file nt3d_object_obj.h.
References ControlImpl().
{ControlImpl(cntrl , value);}
virtual void NT3D_object_o::ControlImpl (NT3Dcontroller cntrl, NT_vector_o value) [protected, pure virtual]
Implemented in NT3D_camera_o, and NT3D_hierarchic_object_o.
virtual void NT3D_object_o::ControlImpl (NT3Dcontroller cntrl, NTreal value) [protected, pure virtual]
Implemented in NT3D_camera_o, and NT3D_hierarchic_object_o.
virtual void NT3D_object_o::ControlImpl (NT3Dcontroller cntrl, NTint value) [protected, pure virtual]
ControlImpl() should be overridden by derived classes ONLY if control/state are to be applied to *this object !
Implemented in NT3D_camera_o, and NT3D_hierarchic_object_o.
Referenced by Control().
virtual void NT3D_object_o::Draw () [pure virtual]
It handles the drawing of the object
Implements NT3D_o.
Implemented in NT3D_camera_o, NT3D_hierarchic_object_o, and NT3D_target_camera_o.
void NT3D_object_o::Rotate (const NT_vector3_o & oDeltaRotation)
void NT3D_object_o::RotateNull () [inline]
Definition at line 163 of file nt3d_object_obj.h.
References NT_OriginVec3(), and oRotation.
{ oRotation = NT_OriginVec3();};
void NT3D_object_o::RotateX (NTreal deltaRotX)
Referenced by NT3D_camera_vp_o::SetRotationZ().
void NT3D_object_o::RotateXYZ (NT_vector3_o oDeltaRot) [inline]
Definition at line 161 of file nt3d_object_obj.h.
References oRotation.
{ oRotation += oDeltaRot; }
void NT3D_object_o::RotateXYZ (const NTreal deltaRot[3])
void NT3D_object_o::RotateY (NTreal deltaRotY)
Referenced by NT3D_camera_vp_o::TranslateX().
void NT3D_object_o::RotateZ (NTreal deltaRotZ)
Referenced by NT3D_camera_vp_o::TranslateY().
void NT3D_object_o::SetRotationX (const NTreal rotX) [inline]
Definition at line 164 of file nt3d_object_obj.h.
References oRotation, and NT_vector3_o::x.
Referenced by NT3D_camera_vp_o::TranslateZ().
{ oRotation.x= rotX; }
void NT3D_object_o::SetRotationXYZ (const NT_vector3_o & oRot) [inline]
Definition at line 167 of file nt3d_object_obj.h.
References oTranslation.
{ oTranslation = oRot; }
void NT3D_object_o::SetRotationY (const NTreal rotY) [inline]
Definition at line 165 of file nt3d_object_obj.h.
References oRotation, and NT_vector3_o::y.
Referenced by NT3D_camera_vp_o::SetTranslationX().
{ oRotation.y= rotY; }
void NT3D_object_o::SetRotationZ (const NTreal rotZ) [inline]
Definition at line 166 of file nt3d_object_obj.h.
References oRotation, and NT_vector3_o::z.
Referenced by NT3D_camera_vp_o::SetTranslationY().
{ oRotation.z= rotZ; }
virtual void NT3D_object_o::SetTranslationX (const NTreal traX) [inline, virtual]
Definition at line 176 of file nt3d_object_obj.h.
References oTranslation, and NT_vector3_o::x.
{ oTranslation.x= traX; }
virtual void NT3D_object_o::SetTranslationXYZ (const NT_vector3_o & oTra) [inline, virtual]
Definition at line 179 of file nt3d_object_obj.h.
References oTranslation.
{ oTranslation = oTra; }
virtual void NT3D_object_o::SetTranslationY (const NTreal traY) [inline, virtual]
Definition at line 177 of file nt3d_object_obj.h.
References oTranslation, and NT_vector3_o::y.
{ oTranslation.y= traY; }
virtual void NT3D_object_o::SetTranslationZ (const NTreal traZ) [inline, virtual]
Definition at line 178 of file nt3d_object_obj.h.
References oTranslation, and NT_vector3_o::z.
{ oTranslation.z= traZ; }
virtual void NT3D_object_o::Translate (const NT_vector3_o & oDeltaTranslation) [virtual]
virtual void NT3D_object_o::TranslateNull () [inline, virtual]
Definition at line 175 of file nt3d_object_obj.h.
References NT_OriginVec3(), and oTranslation.
{ oTranslation = NT_OriginVec3();};
virtual void NT3D_object_o::TranslateX (const NTreal deltaTraX) [virtual]
Referenced by NT3D_camera_vp_o::SetTranslationZ().
virtual void NT3D_object_o::TranslateXYZ (const NT_vector3_o & oDeltaTra) [inline, virtual]
Definition at line 173 of file nt3d_object_obj.h.
References oTranslation.
{ oTranslation += oDeltaTra; }
virtual void NT3D_object_o::TranslateXYZ (const NTreal deltaTra[3]) [virtual]
virtual void NT3D_object_o::TranslateY (const NTreal deltaTraY) [virtual]
Referenced by NT3D_camera_vp_o::SetTranslationXYZ().
virtual void NT3D_object_o::TranslateZ (const NTreal deltaTraZ) [virtual]
Referenced by NT3D_camera_vp_o::SetTarget().
Member Data Documentation
NT_vector3_o NT3D_object_o::oRotation [protected]
Definition at line 200 of file nt3d_object_obj.h.
Referenced by _oRotation(), RotateNull(), RotateXYZ(), SetRotationX(), SetRotationY(), and SetRotationZ().
NT_vector3_o NT3D_object_o::oTranslation [protected]
Definition at line 199 of file nt3d_object_obj.h.
Referenced by _oTranslation(), SetRotationXYZ(), SetTranslationX(), SetTranslationXYZ(), SetTranslationY(), SetTranslationZ(), TranslateNull(), and TranslateXYZ().
The documentation for this class was generated from the following file:
nt3d_object_obj.h