NetTrader: NTBP_hranvier_sodium_multi_current_o Class Reference
NTBP_hranvier_sodium_multi_current_o Class Reference
NTBP_hranvier_sodium_multi_current_o class based on Schwartz, J.
#include <ntbp_hranvier_sodium_multi_current_obj.h>
Public Member Functions
NTBP_hranvier_sodium_multi_current_o (NTreal area, NTreal density=110, NTreal channelConductance=1.3e-8, NTreal vBase=-84)
NTBP_hranvier_sodium_multi_current_o (const NTBP_hranvier_sodium_multi_current_o &original)
const
NTBP_hranvier_sodium_multi_current_o & operator= (const NTBP_hranvier_sodium_multi_current_o &right)
virtual ~NTBP_hranvier_sodium_multi_current_o ()
NTreal ComputeChannelStateTimeConstant () const
in 1/ms or kHz
NTreturn StepCurrent ()
NTreal OpenChannels () const
Number of open ionic channels.
NTreal ComputeConductance ()
compute and return conductance in mSiemens
void ComputeRateConstants (NTreal vM)
compute the rate constants (in ms^-1)
void ShowChannelStatePopulation ()
void Show ()
NTreal AlphaM (NTreal vM)
NTreal BetaM (NTreal vM)
NTreal AlphaH (NTreal vM)
NTreal BetaH (NTreal vM)
void ShowParam () const
Detailed Description
and Reid, G. and Bostock, H. (1995) "Action potentials and membrane currents in the human node of Ranvier" J.Physiol. 430:283-292
Bug:
unknown
Warning:
unknown
Definition at line 64 of file ntbp_hranvier_sodium_multi_current_obj.h.
Constructor & Destructor Documentation
NTBP_hranvier_sodium_multi_current_o::NTBP_hranvier_sodium_multi_current_o (NTreal area, NTreal density = 110, NTreal channelConductance = 1.3e-8, NTreal vBase = -84)
NTBP_hranvier_sodium_multi_current_o::NTBP_hranvier_sodium_multi_current_o (const NTBP_hranvier_sodium_multi_current_o & original)
virtual NTBP_hranvier_sodium_multi_current_o::~NTBP_hranvier_sodium_multi_current_o () [virtual]
Member Function Documentation
NTreal NTBP_hranvier_sodium_multi_current_o::AlphaH (NTreal vM) [inline]
Definition at line 87 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_multi_current_o::_vBase().
{   vM += _vBase(); return 0.0336*(-111.0-vM)/(1-exp((vM+111.0)/11.0)); }
NTreal NTBP_hranvier_sodium_multi_current_o::AlphaM (NTreal vM) [inline]
Definition at line 85 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_multi_current_o::_vBase().
{    vM += _vBase(); return 1.86*(vM+18.4)/(1-exp((-18.4-vM)/10.3));}
NTreal NTBP_hranvier_sodium_multi_current_o::BetaH (NTreal vM) [inline]
Definition at line 88 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_multi_current_o::_vBase().
{   vM += _vBase(); return 2.30/(1+exp((-28.8-vM)/13.4)); }
NTreal NTBP_hranvier_sodium_multi_current_o::BetaM (NTreal vM) [inline]
Definition at line 86 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_multi_current_o::_vBase().
{   vM += _vBase(); return 0.0860*(-22.7-vM)/(1-exp((vM+22.7)/9.16)); }
NTreal NTBP_hranvier_sodium_multi_current_o::ComputeChannelStateTimeConstant () const [virtual]
Reimplemented from NTBP_membrane_current_o.
NTreal NTBP_hranvier_sodium_multi_current_o::ComputeConductance () [virtual]
Implements NTBP_membrane_current_o.
void NTBP_hranvier_sodium_multi_current_o::ComputeRateConstants (NTreal vM) [virtual]
Implements NTBP_membrane_current_o.
NTreal NTBP_hranvier_sodium_multi_current_o::OpenChannels () const [virtual]
Reimplemented from NTBP_membrane_current_o.
const NTBP_hranvier_sodium_multi_current_o& NTBP_hranvier_sodium_multi_current_o::operator= (const NTBP_hranvier_sodium_multi_current_o & right)
void NTBP_hranvier_sodium_multi_current_o::Show () [inline]
Definition at line 83 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_ion_channels_o::_numChannels(), NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
            {  cout << " alphaM= " << alphaM << "\t betaM= " << betaM << "\t openRatio= " << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << "\t alphaH= " << alphaH << "\t betaH= " << betaH << "\t openNum= " << channelsPtr->NumOpen();}
void NTBP_hranvier_sodium_multi_current_o::ShowChannelStatePopulation () [inline]
Definition at line 82 of file ntbp_hranvier_sodium_multi_current_obj.h.
References NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
{ channelsPtr->ShowStates(); }
void NTBP_hranvier_sodium_multi_current_o::ShowParam () const [virtual]
Reimplemented from NTBP_membrane_current_o.
NTreturn NTBP_hranvier_sodium_multi_current_o::StepCurrent () [virtual]
Implements NTBP_membrane_current_o.
The documentation for this class was generated from the following file:
ntbp_hranvier_sodium_multi_current_obj.h