NetTrader: NTBP_potassium_ion_channels_o Class Reference
NTBP_potassium_ion_channels_o Class Reference
NTBP_potassium_ion_channels_o class 4 state Hodgkin-Huxley based model of potassium conducting ion channels.
#include <ntbp_potassium_ion_channels_obj.h>
Public Member Functions
NTBP_potassium_ion_channels_o (NTsize numNewChannels=1)
NTBP_potassium_ion_channels_o (const NTBP_potassium_ion_channels_o &original)
const
NTBP_potassium_ion_channels_o & operator= (const NTBP_potassium_ion_channels_o &right)
virtual ~NTBP_potassium_ion_channels_o ()
NTreturn Step ()
NTreturn BinomialStep ()
void ShowStates () const
NTsize NumOpen () const
NTsize NumClosed () const
NTreturn UpdateStateProb (vector< NTreal > rateConstVec)
NTreturn SteadyStateDistribution ()
set the steady state distribution of channel states for current rate constants, DIRTY HACK
bool ComputeGillespieStep (NTsize stateId)
NTreal ComputeChannelStateTimeConstant () const
Sum of escape rates from current state [1/s].
Detailed Description
The open state has stateIndex 5.
Bug:
unknown
Warning:
1. Care has to be take on stateCounterVec (as it is 9 dimensional (1 based index, 0 is SumVec)) 2. alpha and beta ARE RATE CONSTANTS (this changed)
Definition at line 59 of file ntbp_potassium_ion_channels_obj.h.
Constructor & Destructor Documentation
NTBP_potassium_ion_channels_o::NTBP_potassium_ion_channels_o (NTsize numNewChannels = 1)
NTBP_potassium_ion_channels_o::NTBP_potassium_ion_channels_o (const NTBP_potassium_ion_channels_o & original)
virtual NTBP_potassium_ion_channels_o::~NTBP_potassium_ion_channels_o () [virtual]
Member Function Documentation
NTreturn NTBP_potassium_ion_channels_o::BinomialStep () [virtual]
Reimplemented from NTBP_ion_channels_o.
NTreal NTBP_potassium_ion_channels_o::ComputeChannelStateTimeConstant () const [virtual]
Implements NTBP_ion_channels_o.
bool NTBP_potassium_ion_channels_o::ComputeGillespieStep (NTsize stateId) [virtual]
Reimplemented from NTBP_ion_channels_o.
NTsize NTBP_potassium_ion_channels_o::NumClosed () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 72 of file ntbp_potassium_ion_channels_obj.h.
References NTBP_ion_channels_o::_numChannels(), and NumOpen().
{ return _numChannels() - NumOpen();}
NTsize NTBP_potassium_ion_channels_o::NumOpen () const [inline, virtual]
Implements NTBP_ion_channels_o.
Definition at line 71 of file ntbp_potassium_ion_channels_obj.h.
References NTBP_ion_channels_o::stateCounterVec.
Referenced by NumClosed().
{ return stateCounterVec[5];}
const NTBP_potassium_ion_channels_o& NTBP_potassium_ion_channels_o::operator= (const NTBP_potassium_ion_channels_o & right)
void NTBP_potassium_ion_channels_o::ShowStates () const [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_potassium_ion_channels_o::SteadyStateDistribution () [virtual]
Implements NTBP_ion_channels_o.
NTreturn NTBP_potassium_ion_channels_o::Step () [virtual]
Reimplemented from NTBP_object_o.
NTreturn NTBP_potassium_ion_channels_o::UpdateStateProb (vector< NTreal > rateConstVec) [virtual]
Implements NTBP_ion_channels_o.
The documentation for this class was generated from the following file:
ntbp_potassium_ion_channels_obj.h