NetTrader: NT3D_light_o Class Reference
NT3D_light_o Class Reference
NT3D_light_o class Light setup and manipulation (based OpenGL light implementation).
#include <nt3d_light_obj.h>
Public Member Functions
NT3D_light_o ()
NT3D_light_o (const NT3D_light_o &original)
const NT3D_light_o & operator= (const NT3D_light_o &right)
virtual ~NT3D_light_o ()
void Illuminate ()
Do not override in derived classes use DrawLight() instead Do ONLY use calls to Illuminate() from outside this hierarchy.
void On ()
void Off ()
Public Attributes
NT3D_color_o colorAmbient
NT3D_color_o colorDiffuse
NT3D_color_o colorSpecular
Protected Member Functions
virtual void IlluminateLight ()=0
Derive to implement lights.
void IlluminateAmbient ()
void IlluminateDiffuse ()
void IlluminateSpecular ()
Protected Attributes
NTid lightId
Detailed Description
Bug:
unknown
Warning:
unknown
Definition at line 72 of file nt3d_light_obj.h.
Constructor & Destructor Documentation
NT3D_light_o::NT3D_light_o ()
NT3D_light_o::NT3D_light_o (const NT3D_light_o & original)
virtual NT3D_light_o::~NT3D_light_o () [virtual]
Member Function Documentation
void NT3D_light_o::Illuminate ()
Referenced by NT3D_lamp_o::DrawObj().
void NT3D_light_o::IlluminateAmbient () [inline, protected]
Definition at line 93 of file nt3d_light_obj.h.
References NT3D_color_o::_colorPtr(), colorAmbient, and lightId.
{ glLightfv((GLenum) lightId, GL_AMBIENT,  colorAmbient._colorPtr());}
void NT3D_light_o::IlluminateDiffuse () [inline, protected]
Definition at line 94 of file nt3d_light_obj.h.
References NT3D_color_o::_colorPtr(), colorDiffuse, and lightId.
{ glLightfv((GLenum) lightId, GL_DIFFUSE,  colorDiffuse._colorPtr());}
virtual void NT3D_light_o::IlluminateLight () [protected, pure virtual]
Implemented in NT3D_ambient_light_o.
void NT3D_light_o::IlluminateSpecular () [inline, protected]
Definition at line 95 of file nt3d_light_obj.h.
References NT3D_color_o::_colorPtr(), colorSpecular, and lightId.
{ glLightfv((GLenum) lightId, GL_SPECULAR, colorSpecular._colorPtr());}
void NT3D_light_o::Off ()
void NT3D_light_o::On ()
const NT3D_light_o& NT3D_light_o::operator= (const NT3D_light_o & right)
Member Data Documentation
NT3D_color_o NT3D_light_o::colorAmbient
Definition at line 86 of file nt3d_light_obj.h.
Referenced by IlluminateAmbient().
NT3D_color_o NT3D_light_o::colorDiffuse
Definition at line 87 of file nt3d_light_obj.h.
Referenced by IlluminateDiffuse().
NT3D_color_o NT3D_light_o::colorSpecular
Definition at line 88 of file nt3d_light_obj.h.
Referenced by IlluminateSpecular().
NTid NT3D_light_o::lightId [protected]
Definition at line 99 of file nt3d_light_obj.h.
Referenced by IlluminateAmbient(), IlluminateDiffuse(), and IlluminateSpecular().
The documentation for this class was generated from the following file:
nt3d_light_obj.h