NetTrader: TNT::stopwatch Class Reference
TNT::stopwatch Class Reference
#include <stopwatch.h>
Public Member Functions
stopwatch ()
void reset ()
void start ()
double stop ()
double read ()
Detailed Description
Definition at line 51 of file stopwatch.h.
Constructor & Destructor Documentation
TNT::stopwatch::stopwatch () [inline]
Definition at line 58 of file stopwatch.h.
: running(0), last_time(0.0), total(0.0) {}
Member Function Documentation
double TNT::stopwatch::read () [inline]
Definition at line 68 of file stopwatch.h.
References TNT::seconds().
                        {  if (running)
{
                                total+= seconds() - last_time;
                                last_time = seconds();
                            }
                           return total;
                        }
void TNT::stopwatch::reset () [inline]
Definition at line 59 of file stopwatch.h.
{ running = 0; last_time = 0.0; total=0.0; }
void TNT::stopwatch::start () [inline]
Definition at line 60 of file stopwatch.h.
References TNT::seconds().
{ if (!running) { last_time = seconds(); running = 1;}}
double TNT::stopwatch::stop () [inline]
Definition at line 61 of file stopwatch.h.
References TNT::seconds().
                       { if (running)
{
                                total += seconds() - last_time;
                                running = 0;
                             }
                          return total;
                        }
The documentation for this class was generated from the following file:
stopwatch.h