NetTrader: NT_timing_o Class Reference
NT_timing_o Class Reference
NT_timing_o a stopwatch like measurement object: void start() : start timing double stop() : stop timing void reset() : set elapsed time to 0.0 double read() : read elapsed time (in seconds).
#include <nt_timing_obj.h>
Public Member Functions
NT_timing_o ()
void reset ()
void start ()
NTdouble stop ()
NTdouble read ()
NTdouble seconds ()
Detailed Description
Definition at line 73 of file nt_timing_obj.h.
Constructor & Destructor Documentation
NT_timing_o::NT_timing_o () [inline]
Definition at line 80 of file nt_timing_obj.h.
References reset().
{ reset(); secs_per_tick = 1.0 / CLOCKS_PER_SEC;}
Member Function Documentation
NTdouble NT_timing_o::read () [inline]
Definition at line 90 of file nt_timing_obj.h.
References seconds().
                          {  if (isRunning)
{
                                total+= seconds() - last_time;
                                last_time = seconds();
                            }
                           return total;
                        }
void NT_timing_o::reset () [inline]
Definition at line 81 of file nt_timing_obj.h.
Referenced by NT_timing_o().
{ isRunning = false; last_time = 0.0; total=0.0; }
NTdouble NT_timing_o::seconds () [inline]
Definition at line 97 of file nt_timing_obj.h.
Referenced by read(), start(), and stop().
{ return ((NTdouble) clock()) * secs_per_tick;}
void NT_timing_o::start () [inline]
Definition at line 82 of file nt_timing_obj.h.
References seconds().
{ if (!isRunning) { last_time = seconds(); isRunning = true;}}
NTdouble NT_timing_o::stop () [inline]
Definition at line 83 of file nt_timing_obj.h.
References seconds().
                         { if (isRunning)
{
                                total += seconds() - last_time;
                                isRunning = false;
                             }
                          return total;
                        }
The documentation for this class was generated from the following file:
nt_timing_obj.h