NetTrader: TNT::LowerTriangularView< MaTRiX > Class Template Reference
TNT::LowerTriangularView< MaTRiX > Class Template Reference
#include <triang.h>
Public Types
typedef MaTRiX::const_reference const_reference
typedef const MaTRiX::element_type element_type
typedef const MaTRiX::element_type value_type
typedef element_type T
Public Member Functions
Subscript dim (Subscript d) const
Subscript lbound () const
Subscript num_rows () const
Subscript num_cols () const
LowerTriangularView (MaTRiX &A)
const_reference get (Subscript i, Subscript j) const
const_reference operator() (Subscript i, Subscript j) const
Protected Attributes
const MaTRiX & A_
const MaTRiX::element_type zero_
Detailed Description
template<class MaTRiX>
class TNT::LowerTriangularView< MaTRiX >
Definition at line 38 of file triang.h.
Member Typedef Documentation
template<class MaTRiX> typedef MaTRiX::const_reference TNT::LowerTriangularView< MaTRiX >::const_reference
Definition at line 49 of file triang.h.
template<class MaTRiX> typedef const MaTRiX::element_type TNT::LowerTriangularView< MaTRiX >::element_type
Definition at line 50 of file triang.h.
template<class MaTRiX> typedef element_type TNT::LowerTriangularView< MaTRiX >::T
Definition at line 52 of file triang.h.
template<class MaTRiX> typedef const MaTRiX::element_type TNT::LowerTriangularView< MaTRiX >::value_type
Definition at line 51 of file triang.h.
Constructor & Destructor Documentation
template<class MaTRiX> TNT::LowerTriangularView< MaTRiX >::LowerTriangularView (MaTRiX & A) [inline]
Definition at line 62 of file triang.h.
: A_(A),  zero_(0) {}
Member Function Documentation
template<class MaTRiX> Subscript TNT::LowerTriangularView< MaTRiX >::dim (Subscript d) const [inline]
Definition at line 54 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_.
{  return A_.dim(d); }
template<class MaTRiX> const_reference TNT::LowerTriangularView< MaTRiX >::get (Subscript i, Subscript j) const [inline]
Definition at line 65 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_, TNT::LowerTriangularView< MaTRiX >::lbound(), and TNT::LowerTriangularView< MaTRiX >::zero_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(lbound()<=i);
        assert(i<=A_.num_rows() + lbound() - 1);
        assert(lbound()<=j);
        assert(j<=A_.num_cols() + lbound() - 1);
#endif
        if (i<j)
            return zero_;
        else
            return A_(i,j);
    }
template<class MaTRiX> Subscript TNT::LowerTriangularView< MaTRiX >::lbound () const [inline]
Definition at line 55 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_.
Referenced by TNT::LowerTriangularView< MaTRiX >::get(), TNT::matmult(), and TNT::LowerTriangularView< MaTRiX >::operator()().
{ return A_.lbound(); }
template<class MaTRiX> Subscript TNT::LowerTriangularView< MaTRiX >::num_cols () const [inline]
Definition at line 57 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult().
{ return A_.num_cols(); }
template<class MaTRiX> Subscript TNT::LowerTriangularView< MaTRiX >::num_rows () const [inline]
Definition at line 56 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_.
Referenced by TNT::matmult().
{ return A_.num_rows(); }
template<class MaTRiX> const_reference TNT::LowerTriangularView< MaTRiX >::operator() (Subscript i, Subscript j) const [inline]
Definition at line 80 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::A_, TNT::LowerTriangularView< MaTRiX >::lbound(), and TNT::LowerTriangularView< MaTRiX >::zero_.
    {
#ifdef TNT_BOUNDS_CHECK
        assert(lbound()<=i);
        assert(i<=A_.num_rows() + lbound() - 1);
        assert(lbound()<=j);
        assert(j<=A_.num_cols() + lbound() - 1);
#endif
        if (i<j)
            return zero_;
        else
            return A_(i,j);
    }
Member Data Documentation
template<class MaTRiX> const MaTRiX& TNT::LowerTriangularView< MaTRiX >::A_ [protected]
Definition at line 43 of file triang.h.
Referenced by TNT::LowerTriangularView< MaTRiX >::dim(), TNT::LowerTriangularView< MaTRiX >::get(), TNT::LowerTriangularView< MaTRiX >::lbound(), TNT::LowerTriangularView< MaTRiX >::num_cols(), TNT::LowerTriangularView< MaTRiX >::num_rows(), and TNT::LowerTriangularView< MaTRiX >::operator()().
template<class MaTRiX> const MaTRiX::element_type TNT::LowerTriangularView< MaTRiX >::zero_ [protected]
Definition at line 44 of file triang.h.
Referenced by TNT::LowerTriangularView< MaTRiX >::get(), and TNT::LowerTriangularView< MaTRiX >::operator()().
The documentation for this class was generated from the following file:
triang.h