NetTrader: NT3D_color_o Class Reference
NT3D_color_o Class Reference
THe NT3D_color_o class handles the abstract color concept.
#include <nt3d_color_obj.h>
Public Member Functions
NT3D_color_o ()
NT3D_color_o (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)
NT3D_color_o (const valarray< GLfloat > &newColorRGBA)
NT3D_color_o (const NT3D_color_o &original)
const NT3D_color_o & operator= (const NT3D_color_o &right)
~NT3D_color_o ()
virtual void Paint () const
void SetColor (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)
void SetColor (const GLfloat newColor[])
void SetColor (const NT3D_color_o &newColor)
NTreal _R ()
NTreal _G ()
NTreal _B ()
NTreal _Alpha ()
NT3D_color_o operator+ (const NT3D_color_o &right) const
NT3D_color_o operator- (const NT3D_color_o &right) const
NT3D_color_o operator* (NTreal alpha) const
const GLfloat * _colorPtr ()
Detailed Description
Warning:
Once its derived classes are called in the drawing tree they affected ALL subsequent drawing (Modifies OpenGL state).
Bug:
unknown
Definition at line 81 of file nt3d_color_obj.h.
Constructor & Destructor Documentation
NT3D_color_o::NT3D_color_o ()
NT3D_color_o::NT3D_color_o (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)
NT3D_color_o::NT3D_color_o (const valarray< GLfloat > & newColorRGBA)
NT3D_color_o::NT3D_color_o (const NT3D_color_o & original)
NT3D_color_o::~NT3D_color_o ()
Member Function Documentation
NTreal NT3D_color_o::_Alpha () [inline]
Definition at line 98 of file nt3d_color_obj.h.
{ return colorRGBA[3];}
NTreal NT3D_color_o::_B () [inline]
Definition at line 97 of file nt3d_color_obj.h.
{ return colorRGBA[2];}
const GLfloat* NT3D_color_o::_colorPtr () [inline]
Definition at line 103 of file nt3d_color_obj.h.
Referenced by NT3D_light_o::IlluminateAmbient(), NT3D_light_o::IlluminateDiffuse(), and NT3D_light_o::IlluminateSpecular().
{Update(); return (const GLfloat*) colorPtr;}
NTreal NT3D_color_o::_G () [inline]
Definition at line 96 of file nt3d_color_obj.h.
{ return colorRGBA[1];}
NTreal NT3D_color_o::_R () [inline]
Definition at line 95 of file nt3d_color_obj.h.
{ return colorRGBA[0];}
NT3D_color_o NT3D_color_o::operator* (NTreal alpha) const
NT3D_color_o NT3D_color_o::operator+ (const NT3D_color_o & right) const
NT3D_color_o NT3D_color_o::operator- (const NT3D_color_o & right) const
const NT3D_color_o& NT3D_color_o::operator= (const NT3D_color_o & right)
virtual void NT3D_color_o::Paint () const [inline, virtual]
Definition at line 91 of file nt3d_color_obj.h.
{ glColor4fv(colorPtr);}
void NT3D_color_o::SetColor (const GLfloat newColor[])
void NT3D_color_o::SetColor (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)
void NT3D_color_o::SetColor (const NT3D_color_o & newColor)
The documentation for this class was generated from the following file:
nt3d_color_obj.h