NetTrader: lapack.h File Reference
lapack.h File Reference
#include "tnt/fortran.h"
#include "tnt/vec.h"
#include "tnt/fmat.h"
Defines
#define F77_DGESV dgesv_
#define F77_DGELS dgels_
#define F77_DSYEV dsyev_
#define F77_DGEEV dgeev_
Functions
void F77_DGESV (cfi_ N, cfi_ nrhs, fda_ A, cfi_ lda, fia_ ipiv, fda_ b, cfi_ ldb, fi_ info)
void F77_DGELS (cfch_ trans, cfi_ M, cfi_ N, cfi_ nrhs, fda_ A, cfi_ lda, fda_ B, cfi_ ldb, fda_ work, cfi_ lwork, fi_ info)
void F77_DSYEV (cfch_ jobz, cfch_ uplo, cfi_ N, fda_ A, cfi_ lda, fda_ W, fda_ work, cfi_ lwork, fi_ info)
void F77_DGEEV (cfch_ jobvl, cfch_ jobvr, cfi_ N, fda_ A, cfi_ lda, fda_ wr, fda_ wi, fda_ vl, cfi_ ldvl, fda_ vr, cfi_ ldvr, fda_ work, cfi_ lwork, fi_ info)
Vector< double > Lapack_LU_linear_solve (const Fortran_Matrix< double > &A, const Vector< double > &b)
Vector< double > Lapack_LLS_QR_linear_solve (const Fortran_Matrix< double > &A, const Vector< double > &b)
Vector< double > Upper_symmetric_eigenvalue_solve (const Fortran_Matrix< double > &A)
int eigenvalue_solve (const Fortran_Matrix< double > &A, Vector< double > &wr, Vector< double > &wi)
Define Documentation
#define F77_DGEEV dgeev_
Definition at line 42 of file lapack.h.
Referenced by eigenvalue_solve().
#define F77_DGELS dgels_
Definition at line 40 of file lapack.h.
Referenced by Lapack_LLS_QR_linear_solve().
#define F77_DGESV dgesv_
Definition at line 39 of file lapack.h.
Referenced by Lapack_LU_linear_solve().
#define F77_DSYEV dsyev_
Definition at line 41 of file lapack.h.
Referenced by Upper_symmetric_eigenvalue_solve().
Function Documentation
int eigenvalue_solve (const Fortran_Matrix< double > & A, Vector< double > & wr, Vector< double > & wi)
Definition at line 148 of file lapack.h.
References F77_DGEEV, TNT::Vector< T >::newsize(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    char jobvl = 'N';
    char jobvr = 'N';
    Fortran_integer N = A.num_rows();
    assert(N == A.num_cols());
    if (N<1) return 1;
    Fortran_Matrix<double> vl(1,N);  /* should be NxN ? **** */
    Fortran_Matrix<double> vr(1,N);
    Fortran_integer one = 1;
    Fortran_integer worksize = 5*N;
    Fortran_integer info = 0;
    Vector<double> work(worksize, 0.0);
    Fortran_Matrix<double> Tmp = A;
    wr.newsize(N);
    wi.newsize(N);
//  void F77_DGEEV(cfch_ jobvl, cfch_ jobvr, cfi_ N, fda_ A, cfi_ lda,
//      fda_ wr, fda_ wi, fda_ vl, cfi_ ldvl, fda_ vr,
//      cfi_ ldvr, fda_ work, cfi_ lwork, fi_ info);
    F77_DGEEV(&jobvl, &jobvr, &N, &Tmp(1,1), &N, &(wr(1)),
        &(wi(1)), &(vl(1,1)), &one, &(vr(1,1)), &one,
        &(work(1)), &worksize, &info);
    return (info==0 ? 0: 1);
}
void F77_DGEEV (cfch_ jobvl, cfch_ jobvr, cfi_ N, fda_ A, cfi_ lda, fda_ wr, fda_ wi, fda_ vl, cfi_ ldvl, fda_ vr, cfi_ ldvr, fda_ work, cfi_ lwork, fi_ info)
void F77_DGELS (cfch_ trans, cfi_ M, cfi_ N, cfi_ nrhs, fda_ A, cfi_ lda, fda_ B, cfi_ ldb, fda_ work, cfi_ lwork, fi_ info)
void F77_DGESV (cfi_ N, cfi_ nrhs, fda_ A, cfi_ lda, fia_ ipiv, fda_ b, cfi_ ldb, fi_ info)
void F77_DSYEV (cfch_ jobz, cfch_ uplo, cfi_ N, fda_ A, cfi_ lda, fda_ W, fda_ work, cfi_ lwork, fi_ info)
Vector<double> Lapack_LLS_QR_linear_solve (const Fortran_Matrix< double > & A, const Vector< double > & b)
Definition at line 96 of file lapack.h.
References F77_DGELS, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    const Fortran_integer one=1;
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    Fortran_Matrix<double> Tmp(A);
    Vector<double> x(b);
    Fortran_integer info = 0;
    char transp = 'N';
    Fortran_integer lwork = 5 * (M+N);      // temporary work space
    Vector<double> work(lwork);
    F77_DGELS(&transp, &M, &N, &one, &Tmp(1,1), &M, &x(1), &M,  &work(1),
        &lwork, &info);
    if (info != 0) return Vector<double>(0);
    else
        return x;
}
Vector<double> Lapack_LU_linear_solve (const Fortran_Matrix< double > & A, const Vector< double > & b)
Definition at line 75 of file lapack.h.
References F77_DGESV, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    const Fortran_integer one=1;
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    Fortran_Matrix<double> Tmp(A);
    Vector<double> x(b);
    Vector<Fortran_integer> index(M);
    Fortran_integer info = 0;
    F77_DGESV(&N, &one, &Tmp(1,1), &M, &index(1), &x(1), &M, &info);
    if (info != 0) return Vector<double>(0);
    else
        return x;
}
Vector<double> Upper_symmetric_eigenvalue_solve (const Fortran_Matrix< double > & A)
Definition at line 123 of file lapack.h.
References TNT::Vector< T >::begin(), TNT::Fortran_Matrix< T >::begin(), F77_DSYEV, TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    char jobz = 'N';
    char uplo = 'U';
    Subscript N = A.num_rows();
    assert(N == A.num_cols());
    Vector<double> eigvals(N);
    Fortran_integer worksize = 3*N;
    Fortran_integer info = 0;
    Vector<double> work(worksize);
    Fortran_Matrix<double> Tmp = A;
    F77_DSYEV(&jobz, &uplo, &N, &Tmp(1,1), &N, eigvals.begin(), work.begin(),
        &worksize, &info);
    if (info != 0) return Vector<double>();
    else
        return eigvals;
}