NetTrader: TNT Namespace Reference
TNT Namespace Reference
Classes
class Matrix
class Fortran_Sparse_Col_Matrix
class Fortran_Matrix
class Fortran_Sparse_Vector
class Index1D
class Region1D
class const_Region1D
class Region2D
class const_Region2D
class stopwatch
class Transpose_View
class LowerTriangularView
class UnitLowerTriangularView
class UpperTriangularView
class UnitUpperTriangularView
class Vector
class Vector_Adaptor
Typedefs
typedef TNT_SUBSCRIPT_TYPE Subscript
Functions
template<class SPDMatrix , class SymmMatrix >
int Cholesky_upper_factorization (SPDMatrix &A, SymmMatrix &L)
template<class T >
std::ostream & operator<< (std::ostream &s, const Matrix< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Matrix< T > &A)
template<class T >
Matrix< T > operator+ (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > operator- (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > mult_element (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > transpose (const Matrix< T > &A)
template<class T >
Matrix< T > matmult (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Matrix< T > operator* (const Matrix< T > &A, const Matrix< T > &B)
template<class T >
int matmult (Matrix< T > &C, const Matrix< T > &A, const Matrix< T > &B)
template<class T >
Vector< T > matmult (const Matrix< T > &A, const Vector< T > &x)
template<class T >
Vector< T > operator* (const Matrix< T > &A, const Vector< T > &x)
template<class T >
ostream & operator<< (ostream &s, const Fortran_Sparse_Col_Matrix< T > &A)
template<class T >
std::ostream & operator<< (std::ostream &s, const Fortran_Matrix< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Fortran_Matrix< T > &A)
template<class T >
Fortran_Matrix< T > operator+ (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > operator- (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > mult_element (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > transpose (const Fortran_Matrix< T > &A)
template<class T >
Fortran_Matrix< T > matmult (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Fortran_Matrix< T > operator* (const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
int matmult (Fortran_Matrix< T > &C, const Fortran_Matrix< T > &A, const Fortran_Matrix< T > &B)
template<class T >
Vector< T > matmult (const Fortran_Matrix< T > &A, const Vector< T > &x)
template<class T >
Vector< T > operator* (const Fortran_Matrix< T > &A, const Vector< T > &x)
template<class T >
Fortran_Matrix< T > operator* (const Fortran_Matrix< T > &A, const T &x)
template<class T >
ostream & operator<< (ostream &s, const Fortran_Sparse_Vector< T > &A)
template<class T >
istream & operator>> (istream &s, Fortran_Sparse_Vector< T > &A)
Index1D operator+ (const Index1D &D, Subscript i)
Index1D operator+ (Subscript i, const Index1D &D)
Index1D operator- (Index1D &D, Subscript i)
Index1D operator- (Subscript i, Index1D &D)
template<class MaTRiX , class VecToRSubscript >
int LU_factor (MaTRiX &A, VecToRSubscript &indx)
template<class MaTRiX , class VecToR , class VecToRSubscripts >
int LU_solve (const MaTRiX &A, const VecToRSubscripts &indx, VecToR &b)
template<class MaTRiX , class Vector >
int QR_factor (MaTRiX &A, Vector &C, Vector &D)
template<class MaTRiX , class Vector >
int R_solve (const MaTRiX &A, Vector &D, Vector &b)
template<class MaTRiX , class Vector >
int QR_solve (const MaTRiX &A, const Vector &c, Vector &d, Vector &b)
template<class Array1D >
std::ostream & operator<< (std::ostream &s, Region1D< Array1D > &A)
template<class Array1D >
std::ostream & operator<< (std::ostream &s, const_Region1D< Array1D > &A)
template<class Array2D >
std::ostream & operator<< (std::ostream &s, const const_Region2D< Array2D > &A)
template<class Array2D >
std::ostream & operator<< (std::ostream &s, const Region2D< Array2D > &A)
double seconds (void)
double abs (double t)
double min (double a, double b)
double max (double a, double b)
float abs (float t)
float min (float a, float b)
float max (float a, float b)
double sign (double a)
float sign (float a)
template<class Matrix >
Transpose_View< Matrix > Transpose_view (const Matrix &A)
template<class Matrix , class T >
Vector< T > matmult (const Transpose_View< Matrix > &A, const Vector< T > &B)
template<class Matrix , class T >
Vector< T > operator* (const Transpose_View< Matrix > &A, const Vector< T > &B)
template<class Matrix >
std::ostream & operator<< (std::ostream &s, const Transpose_View< Matrix > &A)
template<class MaTRiX , class VecToR >
VecToR matmult (LowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (LowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
LowerTriangularView< MaTRiX > Lower_triangular_view (MaTRiX &A)
template<class MaTRiX >
UnitLowerTriangularView< MaTRiX > Unit_lower_triangular_view (MaTRiX &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UnitLowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UnitLowerTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, const LowerTriangularView< MaTRiX > &A)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, const UnitLowerTriangularView< MaTRiX > &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
UpperTriangularView< MaTRiX > Upper_triangular_view (MaTRiX &A)
template<class MaTRiX >
UnitUpperTriangularView< MaTRiX > Unit_upper_triangular_view (MaTRiX &A)
template<class MaTRiX , class VecToR >
VecToR matmult (UnitUpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX , class VecToR >
VecToR operator* (UnitUpperTriangularView< MaTRiX > &A, VecToR &x)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, UpperTriangularView< MaTRiX > &A)
template<class MaTRiX >
std::ostream & operator<< (std::ostream &s, UnitUpperTriangularView< MaTRiX > &A)
template<class MaTriX , class VecToR >
VecToR Lower_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Unit_lower_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (LowerTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UnitLowerTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Upper_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR Unit_upper_triangular_solve (MaTriX &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UpperTriangularView< MaTriX > &A, VecToR &b)
template<class MaTriX , class VecToR >
VecToR linear_solve (UnitUpperTriangularView< MaTriX > &A, VecToR &b)
template<class T >
std::ostream & operator<< (std::ostream &s, const Vector< T > &A)
template<class T >
std::istream & operator>> (std::istream &s, Vector< T > &A)
template<class T >
Vector< T > operator+ (const Vector< T > &A, const Vector< T > &B)
template<class T >
Vector< T > operator- (const Vector< T > &A, const Vector< T > &B)
template<class T >
Vector< T > operator* (const Vector< T > &A, const Vector< T > &B)
template<class T >
T dot_prod (const Vector< T > &A, const Vector< T > &B)
template<class BBVec >
std::ostream & operator<< (std::ostream &s, const Vector_Adaptor< BBVec > &A)
template<class BBVec >
std::istream & operator>> (std::istream &s, Vector_Adaptor< BBVec > &A)
Typedef Documentation
typedef TNT_SUBSCRIPT_TYPE TNT::Subscript
Definition at line 47 of file subscript.h.
Function Documentation
double TNT::abs (double t) [inline]
Definition at line 38 of file tntmath.h.
{
    return ( t > 0 ? t : -t);
}
float TNT::abs (float t) [inline]
Definition at line 53 of file tntmath.h.
{
    return ( t > 0 ? t : -t);
}
template<class SPDMatrix , class SymmMatrix > int TNT::Cholesky_upper_factorization (SPDMatrix & A, SymmMatrix & L)
Definition at line 42 of file cholesky.h.
{
    Subscript M = A.dim(1);
    Subscript N = A.dim(2);
    assert(M == N);                 // make sure A is square
    // readjust size of L, if necessary
    if (M != L.dim(1) || N != L.dim(2))
        L = SymmMatrix(N,N);
    Subscript i,j,k;
    typename SPDMatrix::element_type dot=0;
    for (j=1; j<=N; j++)                // form column j of L
    {
        dot= 0;
        for (i=1; i<j; i++)             // for k= 1 TO j-1
            dot = dot +  L(j,i)*L(j,i);
        L(j,j) = A(j,j) - dot;
        for (i=j+1; i<=N; i++)
        {
            dot = 0;
            for (k=1; k<j; k++)
                dot = dot +  L(i,k)*L(j,k);
            L(i,j) = A(j,i) - dot;
        }
        if (L(j,j) <= 0.0) return 1;
        L(j,j) = sqrt( L(j,j) );
        for (i=j+1; i<=N; i++)
            L(i,j) = L(i,j) / L(j,j);
    }
    return 0;
}
template<class T > T TNT::dot_prod (const Vector< T > & A, const Vector< T > & B)
Definition at line 386 of file vec.h.
References TNT::Vector< T >::dim().
{
    Subscript N = A.dim();
    assert(N == B.dim());
    Subscript i;
    T sum = 0;
    for (i=0; i<N; i++)
        sum += A[i] * B[i];
    return sum;
}
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (LowerTriangularView< MaTriX > & A, VecToR & b)
Definition at line 91 of file trisolve.h.
References Lower_triangular_solve().
{
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UnitLowerTriangularView< MaTriX > & A, VecToR & b)
Definition at line 98 of file trisolve.h.
References Unit_lower_triangular_solve().
{
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UpperTriangularView< MaTriX > & A, VecToR & b)
Definition at line 165 of file trisolve.h.
References Upper_triangular_solve().
{
template<class MaTriX , class VecToR > VecToR TNT::linear_solve (UnitUpperTriangularView< MaTriX > & A, VecToR & b)
Definition at line 172 of file trisolve.h.
References Unit_upper_triangular_solve().
{
template<class MaTriX , class VecToR > VecToR TNT::Lower_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 36 of file trisolve.h.
Referenced by linear_solve().
{
    Subscript N = A.num_rows();
    // make sure matrix sizes agree; A must be square
    assert(A.num_cols() == N);
    assert(b.dim() == N);
    VecToR x(N);
    Subscript i;
    for (i=1; i<=N; i++)
    {
        typename MaTriX::element_type tmp=0;
        for (Subscript j=1; j<i; j++)
                tmp = tmp + A(i,j)*x(j);
        x(i) =  (b(i) - tmp)/ A(i,i);
    }
template<class MaTRiX > LowerTriangularView<MaTRiX> TNT::Lower_triangular_view (MaTRiX & A)
Definition at line 237 of file triang.h.
{
    return LowerTriangularView<MaTRiX>(A);
}
template<class MaTRiX , class VecToRSubscript > int TNT::LU_factor (MaTRiX & A, VecToRSubscript & indx)
Definition at line 84 of file lu.h.
{
    assert(A.lbound() == 1);                // currently for 1-offset
    assert(indx.lbound() == 1);             // vectors and matrices
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    if (M == 0 || N==0) return 0;
    if (indx.dim() != M)
        indx.newsize(M);
    Subscript i=0,j=0,k=0;
    Subscript jp=0;
    typename MaTRiX::element_type t;
    Subscript minMN =  (M < N ? M : N) ;        // min(M,N);
    for (j=1; j<= minMN; j++)
    {
        // find pivot in column j and  test for singularity.
        jp = j;
        t = fabs(A(j,j));
        for (i=j+1; i<=M; i++)
            if ( fabs(A(i,j)) > t)
            {
                jp = i;
                t = fabs(A(i,j));
            }
        indx(j) = jp;
        // jp now has the index of maximum element
        // of column j, below the diagonal
        if ( A(jp,j) == 0 )
            return 1;       // factorization failed because of zero pivot
        if (jp != j)            // swap rows j and jp
            for (k=1; k<=N; k++)
            {
                t = A(j,k);
                A(j,k) = A(jp,k);
                A(jp,k) =t;
            }
        if (j<M)                // compute elements j+1:M of jth column
        {
            // note A(j,j), was A(jp,p) previously which was
            // guarranteed not to be zero (Label #1)
            //
            typename MaTRiX::element_type recp =  1.0 / A(j,j);
            for (k=j+1; k<=M; k++)
                A(k,j) *= recp;
        }
        if (j < minMN)
        {
            // rank-1 update to trailing submatrix:   E = E - x*y;
            //
            // E is the region A(j+1:M, j+1:N)
            // x is the column vector A(j+1:M,j)
            // y is row vector A(j,j+1:N)
            Subscript ii,jj;
            for (ii=j+1; ii<=M; ii++)
                for (jj=j+1; jj<=N; jj++)
                    A(ii,jj) -= A(ii,j)*A(j,jj);
        }
    }
    return 0;
}
template<class MaTRiX , class VecToR , class VecToRSubscripts > int TNT::LU_solve (const MaTRiX & A, const VecToRSubscripts & indx, VecToR & b)
Definition at line 169 of file lu.h.
{
    assert(A.lbound() == 1);                // currently for 1-offset
    assert(indx.lbound() == 1);             // vectors and matrices
    assert(b.lbound() == 1);
    Subscript i,ii=0,ip,j;
    Subscript n = b.dim();
    typename MaTRiX::element_type sum = 0.0;
    for (i=1;i<=n;i++)
    {
        ip=indx(i);
        sum=b(ip);
        b(ip)=b(i);
        if (ii)
            for (j=ii;j<=i-1;j++)
                sum -= A(i,j)*b(j);
        else if (sum) ii=i;
            b(i)=sum;
    }
    for (i=n;i>=1;i--)
    {
        sum=b(i);
        for (j=i+1;j<=n;j++)
            sum -= A(i,j)*b(j);
        b(i)=sum/A(i,i);
    }
    return 0;
}
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UnitUpperTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 550 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::lbound(), TNT::UnitUpperTriangularView< MaTRiX >::num_cols(), and TNT::UnitUpperTriangularView< MaTRiX >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(N == x.dim());
    Subscript i, j;
    typename VecToR::element_type sum=0.0;
    VecToR result(M);
    Subscript start = A.lbound();
    Subscript Mend = M + A.lbound() -1 ;
    for (i=start; i<=Mend; i++)
    {
        sum = x(i);
        for (j=i+1; j<=N; j++)
            sum = sum + A(i,j)*x(j);
        result(i) = sum + x(i);
    }
    return result;
}
template<class T > Matrix<T> TNT::matmult (const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 487 of file cmat.h.
References TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
Referenced by operator*().
{
#ifdef TNT_BOUNDS_CHECK
    assert(A.num_cols() == B.num_rows());
#endif
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Subscript K = B.num_cols();
    Matrix<T> tmp(M,K);
    T sum;
    for (Subscript i=0; i<M; i++)
    for (Subscript k=0; k<K; k++)
    {
        sum = 0;
        for (Subscript j=0; j<N; j++)
            sum = sum +  A[i][j] * B[j][k];
        tmp[i][k] = sum;
    }
    return tmp;
}
template<class T > int TNT::matmult (Matrix< T > & C, const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 523 of file cmat.h.
References TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    assert(A.num_cols() == B.num_rows());
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Subscript K = B.num_cols();
    C.newsize(M,K);
    T sum;
    const T* row_i;
    const T* col_k;
    for (Subscript i=0; i<M; i++)
    for (Subscript k=0; k<K; k++)
    {
        row_i  = &(A[i][0]);
        col_k  = &(B[0][k]);
        sum = 0;
        for (Subscript j=0; j<N; j++)
        {
            sum  += *row_i * *col_k;
            row_i++;
            col_k += K;
        }
        C[i][k] = sum;
    }
    return 0;
}
template<class T > Fortran_Matrix<T> TNT::matmult (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 447 of file fmat.h.
References TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
#ifdef TNT_BOUNDS_CHECK
    assert(A.num_cols() == B.num_rows());
#endif
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Subscript K = B.num_cols();
    Fortran_Matrix<T> tmp(M,K);
    T sum;
    for (Subscript i=1; i<=M; i++)
    for (Subscript k=1; k<=K; k++)
    {
        sum = 0;
        for (Subscript j=1; j<=N; j++)
            sum = sum +  A(i,j) * B(j,k);
        tmp(i,k) = sum;
    }
    return tmp;
}
template<class T > Vector<T> TNT::matmult (const Matrix< T > & A, const Vector< T > & x)
Definition at line 560 of file cmat.h.
References TNT::Vector< T >::dim(), TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
#ifdef TNT_BOUNDS_CHECK
    assert(A.num_cols() == x.dim());
#endif
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Vector<T> tmp(M);
    T sum;
    for (Subscript i=0; i<M; i++)
    {
        sum = 0;
        const T* rowi = A[i];
        for (Subscript j=0; j<N; j++)
            sum = sum +  rowi[j] * x[j];
        tmp[i] = sum;
    }
    return tmp;
}
template<class T > int TNT::matmult (Fortran_Matrix< T > & C, const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 483 of file fmat.h.
References TNT::Fortran_Matrix< T >::newsize(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    assert(A.num_cols() == B.num_rows());
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Subscript K = B.num_cols();
    C.newsize(M,K);         // adjust shape of C, if necessary
    T sum;
    const T* row_i;
    const T* col_k;
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript k=1; k<=K; k++)
        {
            row_i = &A(i,1);
            col_k = &B(1,k);
            sum = 0;
            for (Subscript j=1; j<=N; j++)
            {
                sum +=  *row_i * *col_k;
                row_i += M;
                col_k ++;
            }
            C(i,k) = sum;
        }
    }
    return 0;
}
template<class T > Vector<T> TNT::matmult (const Fortran_Matrix< T > & A, const Vector< T > & x)
Definition at line 525 of file fmat.h.
References TNT::Vector< T >::dim(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
#ifdef TNT_BOUNDS_CHECK
    assert(A.num_cols() == x.dim());
#endif
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Vector<T> tmp(M);
    T sum;
    for (Subscript i=1; i<=M; i++)
    {
        sum = 0;
        for (Subscript j=1; j<=N; j++)
            sum = sum +  A(i,j) * x(j);
        tmp(i) = sum;
    }
    return tmp;
}
template<class MaTRiX , class VecToR > VecToR TNT::matmult (LowerTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 122 of file triang.h.
References TNT::LowerTriangularView< MaTRiX >::lbound(), TNT::LowerTriangularView< MaTRiX >::num_cols(), and TNT::LowerTriangularView< MaTRiX >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(N == x.dim());
    Subscript i, j;
    typename MaTRiX::element_type sum=0.0;
    VecToR result(M);
    Subscript start = A.lbound();
    Subscript Mend = M + A.lbound() -1 ;
    for (i=start; i<=Mend; i++)
    {
        sum = 0.0;
        for (j=start; j<=i; j++)
            sum = sum + A(i,j)*x(j);
        result(i) = sum;
    }
    return result;
}
template<class Matrix , class T > Vector<T> TNT::matmult (const Transpose_View< Matrix > & A, const Vector< T > & B)
Definition at line 101 of file transv.h.
References TNT::Vector< T >::dim(), TNT::Transpose_View< Array2D >::num_cols(), and TNT::Transpose_View< Array2D >::num_rows().
{
    Subscript  M = A.num_rows();
    Subscript  N = A.num_cols();
    assert(B.dim() == N);
    Vector<T> x(N);
    Subscript i, j;
    T tmp = 0;
    for (i=1; i<=M; i++)
    {
        tmp = 0;
        for (j=1; j<=N; j++)
            tmp += A(i,j) * B(j);
        x(i) = tmp;
    }
    return x;
}
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UnitLowerTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 252 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::lbound(), TNT::UnitLowerTriangularView< MaTRiX >::num_cols(), and TNT::UnitLowerTriangularView< MaTRiX >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(N == x.dim());
    Subscript i, j;
    typename MaTRiX::element_type sum=0.0;
    VecToR result(M);
    Subscript start = A.lbound();
    Subscript Mend = M + A.lbound() -1 ;
    for (i=start; i<=Mend; i++)
    {
        sum = 0.0;
        for (j=start; j<i; j++)
            sum = sum + A(i,j)*x(j);
        result(i) = sum + x(i);
    }
    return result;
}
template<class MaTRiX , class VecToR > VecToR TNT::matmult (UpperTriangularView< MaTRiX > & A, VecToR & x)
Definition at line 420 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::lbound(), TNT::UpperTriangularView< MaTRiX >::num_cols(), and TNT::UpperTriangularView< MaTRiX >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(N == x.dim());
    Subscript i, j;
    typename VecToR::element_type sum=0.0;
    VecToR result(M);
    Subscript start = A.lbound();
    Subscript Mend = M + A.lbound() -1 ;
    for (i=start; i<=Mend; i++)
    {
        sum = 0.0;
        for (j=i; j<=N; j++)
            sum = sum + A(i,j)*x(j);
        result(i) = sum;
    }
    return result;
}
double TNT::max (double a, double b) [inline]
Definition at line 48 of file tntmath.h.
{
    return (a > b ? a : b);
}
float TNT::max (float a, float b) [inline]
Definition at line 63 of file tntmath.h.
{
    return (a > b ? a : b);
}
double TNT::min (double a, double b) [inline]
Definition at line 43 of file tntmath.h.
{
    return (a < b ? a : b);
}
float TNT::min (float a, float b) [inline]
Definition at line 58 of file tntmath.h.
{
    return (a < b ? a : b);
}
template<class T > Fortran_Matrix<T> TNT::mult_element (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 408 of file fmat.h.
References TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Fortran_Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=1; i<=M; i++)
        for (j=1; j<=N; j++)
            tmp(i,j) = A(i,j) * B(i,j);
    return tmp;
}
template<class T > Matrix<T> TNT::mult_element (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 448 of file cmat.h.
References TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=0; i<M; i++)
        for (j=0; j<N; j++)
            tmp[i][j] = A[i][j] * B[i][j];
    return tmp;
}
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UnitUpperTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 576 of file triang.h.
References matmult().
{
    return matmult(A,x);
}
template<class T > Matrix<T> TNT::operator* (const Matrix< T > & A, const Matrix< T > & B) [inline]
Definition at line 516 of file cmat.h.
References matmult().
{
    return matmult(A,B);
}
template<class T > Vector<T> TNT::operator* (const Vector< T > & A, const Vector< T > & B)
Definition at line 368 of file vec.h.
References TNT::Vector< T >::dim().
{
    Subscript N = A.dim();
    assert(N==B.dim());
    Vector<T> tmp(N);
    Subscript i;
    for (i=0; i<N; i++)
            tmp[i] = A[i] * B[i];
    return tmp;
}
template<class T > Fortran_Matrix<T> TNT::operator* (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B) [inline]
Definition at line 476 of file fmat.h.
References matmult().
{
    return matmult(A,B);
}
template<class T > Vector<T> TNT::operator* (const Matrix< T > & A, const Vector< T > & x) [inline]
Definition at line 587 of file cmat.h.
References matmult().
{
    return matmult(A,x);
}
template<class T > Vector<T> TNT::operator* (const Fortran_Matrix< T > & A, const Vector< T > & x) [inline]
Definition at line 551 of file fmat.h.
References matmult().
{
    return matmult(A,x);
}
template<class T > Fortran_Matrix<T> TNT::operator* (const Fortran_Matrix< T > & A, const T & x) [inline]
Definition at line 557 of file fmat.h.
References TNT::Fortran_Matrix< T >::begin(), TNT::Fortran_Matrix< T >::end(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Subscript MN = M*N;
    Fortran_Matrix<T> res(M,N);
    const T* a = A.begin();
    T* t = res.begin();
    T* tend = res.end();
    for (t=res.begin(); t < tend; t++, a++)
        *t = *a * x;
    return res;
}
template<class Matrix , class T > Vector<T> TNT::operator* (const Transpose_View< Matrix > & A, const Vector< T > & B) [inline]
Definition at line 127 of file transv.h.
References matmult().
{
    return matmult(A,B);
}
template<class MaTRiX , class VecToR > VecToR TNT::operator* (LowerTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 148 of file triang.h.
References matmult().
{
    return matmult(A,x);
}
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UnitLowerTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 278 of file triang.h.
References matmult().
{
    return matmult(A,x);
}
template<class MaTRiX , class VecToR > VecToR TNT::operator* (UpperTriangularView< MaTRiX > & A, VecToR & x) [inline]
Definition at line 446 of file triang.h.
References matmult().
{
    return matmult(A,x);
}
template<class T > Fortran_Matrix<T> TNT::operator+ (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 364 of file fmat.h.
References TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Fortran_Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=1; i<=M; i++)
        for (j=1; j<=N; j++)
            tmp(i,j) = A(i,j) + B(i,j);
    return tmp;
}
template<class T > Matrix<T> TNT::operator+ (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 408 of file cmat.h.
References TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=0; i<M; i++)
        for (j=0; j<N; j++)
            tmp[i][j] = A[i][j] + B[i][j];
    return tmp;
}
template<class T > Vector<T> TNT::operator+ (const Vector< T > & A, const Vector< T > & B)
Definition at line 334 of file vec.h.
References TNT::Vector< T >::dim().
{
    Subscript N = A.dim();
    assert(N==B.dim());
    Vector<T> tmp(N);
    Subscript i;
    for (i=0; i<N; i++)
            tmp[i] = A[i] + B[i];
    return tmp;
}
Index1D TNT::operator+ (Subscript i, const Index1D & D) [inline]
Definition at line 63 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
{
    return Index1D(i+D.lbound(), i+D.ubound());
}
Index1D TNT::operator+ (const Index1D & D, Subscript i) [inline]
Definition at line 58 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
{
    return Index1D(i+D.lbound(), i+D.ubound());
}
template<class T > Fortran_Matrix<T> TNT::operator- (const Fortran_Matrix< T > & A, const Fortran_Matrix< T > & B)
Definition at line 384 of file fmat.h.
References TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Fortran_Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=1; i<=M; i++)
        for (j=1; j<=N; j++)
            tmp(i,j) = A(i,j) - B(i,j);
    return tmp;
}
template<class T > Vector<T> TNT::operator- (const Vector< T > & A, const Vector< T > & B)
Definition at line 351 of file vec.h.
References TNT::Vector< T >::dim().
{
    Subscript N = A.dim();
    assert(N==B.dim());
    Vector<T> tmp(N);
    Subscript i;
    for (i=0; i<N; i++)
            tmp[i] = A[i] - B[i];
    return tmp;
}
template<class T > Matrix<T> TNT::operator- (const Matrix< T > & A, const Matrix< T > & B)
Definition at line 428 of file cmat.h.
References TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M==B.num_rows());
    assert(N==B.num_cols());
    Matrix<T> tmp(M,N);
    Subscript i,j;
    for (i=0; i<M; i++)
        for (j=0; j<N; j++)
            tmp[i][j] = A[i][j] - B[i][j];
    return tmp;
}
Index1D TNT::operator- (Index1D & D, Subscript i) [inline]
Definition at line 70 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
{
    return Index1D(D.lbound()-i, D.ubound()-i);
}
Index1D TNT::operator- (Subscript i, Index1D & D) [inline]
Definition at line 75 of file index.h.
References TNT::Index1D::lbound(), and TNT::Index1D::ubound().
{
    return Index1D(i-D.lbound(), i-D.ubound());
}
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Matrix< T > & A)
Definition at line 360 of file cmat.h.
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << "\n";
    for (Subscript i=0; i<M; i++)
    {
        for (Subscript j=0; j<N; j++)
        {
            s << A[i][j] << " ";
        }
        s << "\n";
    }
    return s;
}
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, UpperTriangularView< MaTRiX > & A)
Definition at line 587 of file triang.h.
References TNT::UpperTriangularView< MaTRiX >::num_cols(), and TNT::UpperTriangularView< MaTRiX >::num_rows().
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << endl;
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript j=1; j<=N; j++)
        {
            s << A(i,j) << " ";
        }
        s << endl;
    }
    return s;
}
template<class Array1D > std::ostream& TNT::operator<< (std::ostream & s, Region1D< Array1D > & A)
Definition at line 231 of file region1d.h.
{
    Subscript N=A.dim();
    Subscript istart = TNT_BASE_OFFSET;
    Subscript iend = N - 1 + TNT_BASE_OFFSET;
    for (Subscript i=istart; i<=iend; i++)
        s << A(i) << endl;
    return s;
}
template<class Array1D > std::ostream& TNT::operator<< (std::ostream & s, const_Region1D< Array1D > & A)
Definition at line 357 of file region1d.h.
{
    Subscript N=A.dim();
    for (Subscript i=1; i<=N; i++)
        s << A(i) << endl;
    return s;
}
template<class Array2D > std::ostream& TNT::operator<< (std::ostream & s, const const_Region2D< Array2D > & A)
Definition at line 420 of file region2d.h.
{
    Subscript start = A.lbound();
    Subscript Mend=A.lbound()+ A.num_rows() - 1;
    Subscript Nend=A.lbound() + A.num_cols() - 1;
    s << A.num_rows() << "  " << A.num_cols() << "\n";
    for (Subscript i=start; i<=Mend; i++)
    {
        for (Subscript j=start; j<=Nend; j++)
        {
            s << A(i,j) << " ";
        }
        s << "\n";
    }
    return s;
}
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, const UnitLowerTriangularView< MaTRiX > & A)
Definition at line 310 of file triang.h.
References TNT::UnitLowerTriangularView< MaTRiX >::num_cols(), and TNT::UnitLowerTriangularView< MaTRiX >::num_rows().
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << endl;
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript j=1; j<=N; j++)
        {
            s << A(i,j) << " ";
        }
        s << endl;
    }
    return s;
}
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, const LowerTriangularView< MaTRiX > & A)
Definition at line 289 of file triang.h.
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << endl;
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript j=1; j<=N; j++)
        {
            s << A(i,j) << " ";
        }
        s << endl;
    }
    return s;
}
template<class BBVec > std::ostream& TNT::operator<< (std::ostream & s, const Vector_Adaptor< BBVec > & A)
Definition at line 262 of file vecadaptor.h.
{
    Subscript M=A.size();
    s << M << endl;
    for (Subscript i=1; i<=M; i++)
            s << A(i) << endl;
    return s;
}
template<class MaTRiX > std::ostream& TNT::operator<< (std::ostream & s, UnitUpperTriangularView< MaTRiX > & A)
Definition at line 609 of file triang.h.
References TNT::UnitUpperTriangularView< MaTRiX >::num_cols(), and TNT::UnitUpperTriangularView< MaTRiX >::num_rows().
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << endl;
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript j=1; j<=N; j++)
        {
            s << A(i,j) << " ";
        }
        s << endl;
    }
    return s;
}
template<class T > ostream& TNT::operator<< (ostream & s, const Fortran_Sparse_Vector< T > & A)
Definition at line 131 of file fspvec.h.
{
    // output format is :   N nz val1 ind1 val2 ind2 ...
    Subscript nz=A.num_nonzeros();
    s <<  A.dim() << " " << nz << endl;
    for (Subscript i=1; i<=nz; i++)
        s   << A.val(i) << "  " << A.index(i) << endl;
    s << endl;
    return s;
}
template<class Matrix > std::ostream& TNT::operator<< (std::ostream & s, const Transpose_View< Matrix > & A)
Definition at line 134 of file transv.h.
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    Subscript start = A.lbound();
    Subscript Mend = M + A.lbound() - 1;
    Subscript Nend = N + A.lbound() - 1;
    s << M << "  " << N << endl;
    for (Subscript i=start; i<=Mend; i++)
    {
        for (Subscript j=start; j<=Nend; j++)
        {
            s << A(i,j) << " ";
        }
        s << endl;
    }
    return s;
}
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Fortran_Matrix< T > & A)
Definition at line 316 of file fmat.h.
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << "\n";
    for (Subscript i=1; i<=M; i++)
    {
        for (Subscript j=1; j<=N; j++)
        {
            s << A(i,j) << " ";
        }
        s << "\n";
    }
    return s;
}
template<class T > ostream& TNT::operator<< (ostream & s, const Fortran_Sparse_Col_Matrix< T > & A)
Definition at line 137 of file fcscmat.h.
{
    Subscript M=A.num_rows();
    Subscript N=A.num_cols();
    s << M << " " << N << " " << A.num_nonzeros() <<  endl;
    for (Subscript k=1; k<=N; k++)
    {
        Subscript start = A.col_ptr(k);
        Subscript end = A.col_ptr(k+1);
        for (Subscript i= start; i<end; i++)
        {
            s << A.row_ind(i) << " " << k << " " << A.val(i) << endl;
        }
    }
    return s;
}
template<class Array2D > std::ostream& TNT::operator<< (std::ostream & s, const Region2D< Array2D > & A)
Definition at line 442 of file region2d.h.
{
    Subscript start = A.lbound();
    Subscript Mend=A.lbound()+ A.num_rows() - 1;
    Subscript Nend=A.lbound() + A.num_cols() - 1;
    s << A.num_rows() << "  " << A.num_cols() << "\n";
    for (Subscript i=start; i<=Mend; i++)
    {
        for (Subscript j=start; j<=Nend; j++)
        {
            s << A(i,j) << " ";
        }
        s << "\n";
    }
    return s;
}
template<class T > std::ostream& TNT::operator<< (std::ostream & s, const Vector< T > & A)
Definition at line 296 of file vec.h.
{
    Subscript N=A.dim();
    s <<  N << endl;
    for (Subscript i=0; i<N; i++)
        s   << A[i] << " " << endl;
    s << endl;
    return s;
}
template<class BBVec > std::istream& TNT::operator>> (std::istream & s, Vector_Adaptor< BBVec > & A)
Definition at line 273 of file vecadaptor.h.
References TNT::Vector_Adaptor< BBVec >::resize().
{
    Subscript N;
    s >> N;
    A.resize(N);
    for (Subscript i=1; i<=N; i++)
        s >> A(i);
    return s;
}
template<class T > std::istream& TNT::operator>> (std::istream & s, Fortran_Matrix< T > & A)
Definition at line 337 of file fmat.h.
References TNT::Fortran_Matrix< T >::newsize(), TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M, N;
    s >> M >> N;
    if ( !(M == A.num_rows() && N == A.num_cols()))
    {
        A.newsize(M,N);
    }
    for (Subscript i=1; i<=M; i++)
        for (Subscript j=1; j<=N; j++)
        {
            s >>  A(i,j);
        }
    return s;
}
template<class T > std::istream& TNT::operator>> (std::istream & s, Vector< T > & A)
Definition at line 310 of file vec.h.
References TNT::Vector< T >::newsize(), and TNT::Vector< T >::size().
{
    Subscript N;
    s >> N;
    if ( !(N == A.size() ))
    {
        A.newsize(N);
    }
    for (Subscript i=0; i<N; i++)
            s >>  A[i];
    return s;
}
template<class T > istream& TNT::operator>> (istream & s, Fortran_Sparse_Vector< T > & A)
Definition at line 147 of file fspvec.h.
References TNT::Fortran_Sparse_Vector< T >::index(), TNT::Fortran_Sparse_Vector< T >::newsize(), and TNT::Fortran_Sparse_Vector< T >::val().
{
    // output format is :   N nz val1 ind1 val2 ind2 ...
    Subscript N;
    Subscript nz;
    s >> N >> nz;
    A.newsize(N, nz);
    for (Subscript i=1; i<=nz; i++)
            s >>  A.val(i) >> A.index(i);
    return s;
}
template<class T > std::istream& TNT::operator>> (std::istream & s, Matrix< T > & A)
Definition at line 381 of file cmat.h.
References TNT::Matrix< T >::newsize(), TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    Subscript M, N;
    s >> M >> N;
    if ( !(M == A.num_rows() && N == A.num_cols() ))
    {
        A.newsize(M,N);
    }
    for (Subscript i=0; i<M; i++)
        for (Subscript j=0; j<N; j++)
        {
            s >>  A[i][j];
        }
    return s;
}
template<class MaTRiX , class Vector > int TNT::QR_factor (MaTRiX & A, Vector & C, Vector & D)
Definition at line 85 of file qr.h.
References TNT::Vector< T >::lbound(), TNT::Vector< T >::newsize(), sign(), and TNT::Vector< T >::size().
{
    assert(A.lbound() == 1);        // ensure these are all
    assert(C.lbound() == 1);        // 1-based arrays and vectors
    assert(D.lbound() == 1);
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    assert(M == N);                 // make sure A is square
    Subscript i,j,k;
    typename MaTRiX::element_type eta, sigma, sum;
    // adjust the shape of C and D, if needed...
    if (N != C.size())  C.newsize(N);
    if (N != D.size())  D.newsize(N);
    for (k=1; k<N; k++)
    {
        // eta = max |M(i,k)|,  for k <= i <= n
        //
        eta = 0;
        for (i=k; i<=N; i++)
        {
            double absA = fabs(A(i,k));
            eta = ( absA >  eta ? absA : eta );
        }
        if (eta == 0)           // matrix is singular
        {
            cerr << "QR: k=" << k << "\n";
            return 1;
        }
        // form Qk and premiltiply M by it
        //
        for(i=k; i<=N; i++)
            A(i,k)  = A(i,k) / eta;
        sum = 0;
        for (i=k; i<=N; i++)
            sum = sum + A(i,k)*A(i,k);
        sigma = sign(A(k,k)) *  sqrt(sum);
        A(k,k) = A(k,k) + sigma;
        C(k) = sigma * A(k,k);
        D(k) = -eta * sigma;
        for (j=k+1; j<=N; j++)
        {
            sum = 0;
            for (i=k; i<=N; i++)
                sum = sum + A(i,k)*A(i,j);
            sum = sum / C(k);
            for (i=k; i<=N; i++)
                A(i,j) = A(i,j) - sum * A(i,k);
        }
        D(N) = A(N,N);
    }
    return 0;
}
template<class MaTRiX , class Vector > int TNT::QR_solve (const MaTRiX & A, const Vector & c, Vector & d, Vector & b)
Definition at line 194 of file qr.h.
References TNT::Vector< T >::dim(), TNT::Vector< T >::lbound(), and R_solve().
{
    assert(A.lbound() == 1);        // ensure these are all
    assert(c.lbound() == 1);        // 1-based arrays and vectors
    assert(d.lbound() == 1);
    Subscript N=A.num_rows();
    assert(N == A.num_cols());
    assert(N == c.dim());
    assert(N == d.dim());
    assert(N == b.dim());
    Subscript i,j;
    typename MaTRiX::element_type sum, tau;
    for (j=1; j<N; j++)
    {
        // form Q'*b
        sum = 0;
        for (i=j; i<=N; i++)
            sum = sum + A(i,j)*b(i);
        if (c(j) == 0)
            return 1;
        tau = sum / c(j);
       for (i=j; i<=N; i++)
            b(i) = b(i) - tau * A(i,j);
    }
    return R_solve(A, d, b);        // solve Rx = Q'b
}
template<class MaTRiX , class Vector > int TNT::R_solve (const MaTRiX & A, Vector & D, Vector & b)
Definition at line 157 of file qr.h.
References TNT::Vector< T >::dim(), and TNT::Vector< T >::lbound().
Referenced by QR_solve().
{
    assert(A.lbound() == 1);        // ensure these are all
    assert(D.lbound() == 1);        // 1-based arrays and vectors
    assert(b.lbound() == 1);
    Subscript i,j;
    Subscript N = A.num_rows();
    assert(N == A.num_cols());
    assert(N == D.dim());
    assert(N == b.dim());
    typename MaTRiX::element_type sum;
    if (D(N) == 0)
        return 1;
    b(N) = b(N) /
            D(N);
    for (i=N-1; i>=1; i--)
    {
        if (D(i) == 0)
            return 1;
        sum = 0;
        for (j=i+1; j<=N; j++)
            sum = sum + A(i,j)*b(j);
        b(i) = ( b(i) - sum ) /
            D(i);
    }
    return 0;
}
double TNT::seconds (void) [inline]
Definition at line 44 of file stopwatch.h.
Referenced by TNT::stopwatch::read(), TNT::stopwatch::start(), and TNT::stopwatch::stop().
{
    static const double secs_per_tick = 1.0 / CLOCKS_PER_SEC;
    return ( (double) clock() ) * secs_per_tick;
}
float TNT::sign (float a) [inline]
Definition at line 75 of file tntmath.h.
{
    return (a > 0.0 ? 1.0f : -1.0f);
}
double TNT::sign (double a) [inline]
Definition at line 68 of file tntmath.h.
Referenced by QR_factor().
{
    return (a > 0 ? 1.0 : -1.0);
}
template<class T > Matrix<T> TNT::transpose (const Matrix< T > & A)
Definition at line 469 of file cmat.h.
References TNT::Matrix< T >::num_cols(), and TNT::Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Matrix<T> S(N,M);
    Subscript i, j;
    for (i=0; i<M; i++)
        for (j=0; j<N; j++)
            S[j][i] = A[i][j];
    return S;
}
template<class T > Fortran_Matrix<T> TNT::transpose (const Fortran_Matrix< T > & A)
Definition at line 429 of file fmat.h.
References TNT::Fortran_Matrix< T >::num_cols(), and TNT::Fortran_Matrix< T >::num_rows().
{
    Subscript M = A.num_rows();
    Subscript N = A.num_cols();
    Fortran_Matrix<T> S(N,M);
    Subscript i, j;
    for (i=1; i<=M; i++)
        for (j=1; j<=N; j++)
            S(j,i) = A(i,j);
    return S;
}
template<class Matrix > Transpose_View<Matrix> TNT::Transpose_view (const Matrix & A)
Definition at line 95 of file transv.h.
{
    return Transpose_View<Matrix>(A);
}
template<class MaTriX , class VecToR > VecToR TNT::Unit_lower_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 63 of file trisolve.h.
Referenced by linear_solve().
{
    Subscript N = A.num_rows();
    // make sure matrix sizes agree; A must be square
    assert(A.num_cols() == N);
    assert(b.dim() == N);
    VecToR x(N);
    Subscript i;
    for (i=1; i<=N; i++)
    {
        typename MaTriX::element_type tmp=0;
        for (Subscript j=1; j<i; j++)
                tmp = tmp + A(i,j)*x(j);
        x(i) =  b(i) - tmp;
    }
template<class MaTRiX > UnitLowerTriangularView<MaTRiX> TNT::Unit_lower_triangular_view (MaTRiX & A)
Definition at line 245 of file triang.h.
{
    return UnitLowerTriangularView<MaTRiX>(A);
}
template<class MaTriX , class VecToR > VecToR TNT::Unit_upper_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 137 of file trisolve.h.
Referenced by linear_solve().
{
    Subscript N = A.num_rows();
    // make sure matrix sizes agree; A must be square
    assert(A.num_cols() == N);
    assert(b.dim() == N);
    VecToR x(N);
    Subscript i;
    for (i=N; i>=1; i--)
    {
        typename MaTriX::element_type tmp=0;
        for (Subscript j=i+1; j<i; j++)
                tmp = tmp + A(i,j)*x(j);
        x(i) =  b(i) - tmp;
    }
template<class MaTRiX > UnitUpperTriangularView<MaTRiX> TNT::Unit_upper_triangular_view (MaTRiX & A)
Definition at line 543 of file triang.h.
{
    return UnitUpperTriangularView<MaTRiX>(A);
}
template<class MaTriX , class VecToR > VecToR TNT::Upper_triangular_solve (MaTriX & A, VecToR & b)
Definition at line 109 of file trisolve.h.
Referenced by linear_solve().
{
    Subscript N = A.num_rows();
    // make sure matrix sizes agree; A must be square
    assert(A.num_cols() == N);
    assert(b.dim() == N);
    VecToR x(N);
    Subscript i;
    for (i=N; i>=1; i--)
    {
        typename MaTriX::element_type tmp=0;
        for (Subscript j=i+1; j<=N; j++)
                tmp = tmp + A(i,j)*x(j);
        x(i) =  (b(i) - tmp)/ A(i,i);
    }
template<class MaTRiX > UpperTriangularView<MaTRiX> TNT::Upper_triangular_view (MaTRiX & A)
Definition at line 535 of file triang.h.
{
    return UpperTriangularView<MaTRiX>(A);
}