NetTrader: nt_vector3_obj.h File Reference
nt_vector3_obj.h File Reference
NT_solid_o class declaration by Ahmed Aldo Faisal © created 15.10.1998
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
#include "nt_error_obj.h"
#include "nt_aux_math_func.h"
#include <iostream>
Classes
class NT_vector3_o
Functions
NT_vector3_o & NT_UnitXVec3 ()
NT_vector3_o & NT_UnitYVec3 ()
NT_vector3_o & NT_UnitZVec3 ()
NT_vector3_o & NT_UnitMinusZVec3 ()
NT_vector3_o & NT_UnitXYZVec3 ()
NT_vector3_o & NT_OriginVec3 ()
Detailed Description
Definition in file nt_vector3_obj.h.
Function Documentation
NT_vector3_o& NT_OriginVec3 ()
Referenced by NT_vector3_o::Norm(), NT3D_object_o::RotateNull(), and NT3D_object_o::TranslateNull().
NT_vector3_o& NT_UnitMinusZVec3 ()
NT_vector3_o& NT_UnitXVec3 ()
NT_vector3_o& NT_UnitXYZVec3 ()
NT_vector3_o& NT_UnitYVec3 ()
NT_vector3_o& NT_UnitZVec3 ()