NetTrader: nt_types.h File Reference
nt_types.h File Reference
#include "nt_main.h"
#include <string>
#include <cmath>
#include <iostream>
Defines
#define NT_CERR(L, M) (NT_cerr(NT_TALKLEVEL, L , M))
#define M_PI 3.14159265358979323846
#define M_E 2.7182818284590452354
#define M_SQRT2 1.41421356237309504880
#define NT_SELF (*this)
Typedefs
typedef float NTfloat
typedef double NTdouble
typedef NTdouble NTreal
typedef int NTint
typedef unsigned int NTuint
typedef unsigned int NTsize
typedef long int NTlong
typedef NTlong NTnum
typedef long int NTid
typedef char NTchar
typedef char * NT_string
typedef string NT_string_o
typedef bool NTbool
Enumerations
enum NTreturn {
NT_SUCCESS, NT_FAIL, NT_NOT_IMPLEMENTED, NT_NOT_DERIVED,
NT_OUT_OF_MEMORY, NT_FILE_NOT_FOUND, NT_WRONG_FILE_TYPE, NT_BAD_FILE,
NT_EMPTY_FILE, NT_BAD_DATA, NT_READ_FAIL, NT_NO_SPACE_LEFT,
NT_WRITE_FAIL, NT_NOT_EXISTING_NODE, NT_NOT_EXISTING_EDGE, NT_PARAM_OUT_OF_RANGE,
NT_PARAM_UNSUPPORTED
}
Functions
void NT_cerr (NTsize currentTalkLevel, NTsize talkLevel, string message)
template<class T >
T NT_Max (T a, T b)
template<class T >
T NT_Min (T a, T b)
template<class T >
T NT_Abs (T x)
template<class T >
void NT_Swap (T &a, T &b)
Variables
const NTbool NT_FALSE = (NTbool) false
const NTbool NT_TRUE = (NTbool) true
Define Documentation
#define M_E 2.7182818284590452354
Definition at line 176 of file nt_types.h.
#define M_PI 3.14159265358979323846
Definition at line 173 of file nt_types.h.
#define M_SQRT2 1.41421356237309504880
Definition at line 179 of file nt_types.h.
#define NT_CERR (L, M) (NT_cerr(NT_TALKLEVEL, L , M))
Definition at line 170 of file nt_types.h.
Referenced by NT3D_hierarchic_object_o::ControlObj(), NT3D_solid_o::DrawSolidObj(), and NT3D_surfaced_object_o::DrawSurfacedObj().
#define NT_SELF (*this)
Definition at line 182 of file nt_types.h.
Referenced by NT_vector3_o::operator^().
Typedef Documentation
typedef char* NT_string
Definition at line 144 of file nt_types.h.
typedef string NT_string_o
Definition at line 145 of file nt_types.h.
typedef bool NTbool
Definition at line 147 of file nt_types.h.
typedef char NTchar
Definition at line 143 of file nt_types.h.
typedef double NTdouble
Definition at line 132 of file nt_types.h.
typedef float NTfloat
Definition at line 131 of file nt_types.h.
typedef long int NTid
Definition at line 141 of file nt_types.h.
typedef int NTint
Definition at line 135 of file nt_types.h.
typedef long int NTlong
Definition at line 138 of file nt_types.h.
typedef NTlong NTnum
Definition at line 139 of file nt_types.h.
typedef NTdouble NTreal
Definition at line 133 of file nt_types.h.
typedef unsigned int NTsize
Definition at line 137 of file nt_types.h.
typedef unsigned int NTuint
Definition at line 136 of file nt_types.h.
Enumeration Type Documentation
enum NTreturn
Enumerator:
NT_SUCCESS
NT_FAIL
NT_NOT_IMPLEMENTED
NT_NOT_DERIVED
NT_OUT_OF_MEMORY
NT_FILE_NOT_FOUND
NT_WRONG_FILE_TYPE
NT_BAD_FILE
NT_EMPTY_FILE
NT_BAD_DATA
NT_READ_FAIL
NT_NO_SPACE_LEFT
NT_WRITE_FAIL
NT_NOT_EXISTING_NODE
NT_NOT_EXISTING_EDGE
NT_PARAM_OUT_OF_RANGE
NT_PARAM_UNSUPPORTED
Definition at line 151 of file nt_types.h.
              {NT_SUCCESS, NT_FAIL, NT_NOT_IMPLEMENTED, NT_NOT_DERIVED, /* SUCCESS FAIL ... , used for return "error codes" of funcs */
               NT_OUT_OF_MEMORY, /* memory operations */
               NT_FILE_NOT_FOUND, NT_WRONG_FILE_TYPE, NT_BAD_FILE, NT_EMPTY_FILE, NT_BAD_DATA, NT_READ_FAIL, NT_NO_SPACE_LEFT, NT_WRITE_FAIL, /* file op returns */
               NT_NOT_EXISTING_NODE, NT_NOT_EXISTING_EDGE, /* NTG graph operations */
           NT_PARAM_OUT_OF_RANGE, NT_PARAM_UNSUPPORTED}; /* parameter errors */
Function Documentation
template<class T > T NT_Abs (T x) [inline]
Definition at line 186 of file nt_types.h.
{return (x) >= 0 ? (x) : -(x);}
void NT_cerr (NTsize currentTalkLevel, NTsize talkLevel, string message) [inline]
Definition at line 165 of file nt_types.h.
{
    if (currentTalkLevel >= talkLevel) cerr << message << endl;
}
template<class T > T NT_Max (T a, T b) [inline]
Definition at line 184 of file nt_types.h.
{ return a > b ? a : b; }
template<class T > T NT_Min (T a, T b) [inline]
Definition at line 185 of file nt_types.h.
{ return a < b ? a : b; }
template<class T > void NT_Swap (T & a, T & b) [inline]
Definition at line 187 of file nt_types.h.
{ T temp = a; a = b; b = temp;}
Variable Documentation
const NTbool NT_FALSE = (NTbool) false
Definition at line 148 of file nt_types.h.
Referenced by NT_vector3_o::operator!=(), and NT_vector3_o::operator==().
const NTbool NT_TRUE = (NTbool) true
Definition at line 149 of file nt_types.h.
Referenced by NTG_graph_o::GraphConsistency(), NT_vector3_o::operator!=(), and NT_vector3_o::operator==().