NetTrader: ntg_graph_obj.h File Reference
ntg_graph_obj.h File Reference
NTG_graph_o class header by Ahmed Aldo Faisal © created 30.9.2000
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
#include "nt_id_management_obj.h"
#include "ntg_node_obj.h"
#include "ntg_edge_obj.h"
#include "nt_uniform_rnd_dist_obj.h"
#include "nt_sequential_statistics_obj.h"
#include <vector>
#include <algorithm>
#include "tnt/tnt.h"
#include "tnt/cmat.h"
#include <string>
Classes
class NTG_vertex_o
class NTG_graph_o
Defines
#define NTG_MAX_NODES_IN_GRAPH 100000
NTG_graph_o class Concepts: the NTG_graph_o mimics the mathematical definition of a graph it is composed by a set E (here a <vector>) of NTG_edge_o objects and of vertices (here a <vector>) V.
Typedefs
typedef vector< NTG_vertex_o > NTG_NodeContainer
typedef vector< NTG_edge_o > NTG_EdgeContainer
typedef vector< NTid > NTG_NodeIdList
typedef Matrix< NTreal > NTG_PositiveCostMatrix
typedef Matrix< bool > NTG_AdjacencyMatrix
typedef Matrix< NTreal > NTG_NodeDistanceMatrix
Functions
template<class T >
NTG_NodeDistanceMatrix NodeDistanceMatrixConditioning (const Matrix< T > &aMtr)
Detailed Description
Definition in file ntg_graph_obj.h.
Define Documentation
#define NTG_MAX_NODES_IN_GRAPH 100000
A vertex is a pair (<pair>) composed of a vertex id and a NTG_node_o which can be derived by the user according to needs. Similar edges can be derived using an NTG_edge_o object.
Bug:
unknown
Warning:
For digraphs: Adjacency and Connectivity matrices use A[i][j] to denote the connection from node i to node j. This does not correspond to standard dynamical system notation.
Definition at line 85 of file ntg_graph_obj.h.
Typedef Documentation
typedef Matrix< bool > NTG_AdjacencyMatrix
Definition at line 110 of file ntg_graph_obj.h.
typedef vector< NTG_edge_o > NTG_EdgeContainer
Definition at line 107 of file ntg_graph_obj.h.
typedef vector< NTG_vertex_o > NTG_NodeContainer
Definition at line 106 of file ntg_graph_obj.h.
typedef Matrix< NTreal > NTG_NodeDistanceMatrix
Definition at line 111 of file ntg_graph_obj.h.
typedef vector< NTid > NTG_NodeIdList
Definition at line 108 of file ntg_graph_obj.h.
typedef Matrix< NTreal > NTG_PositiveCostMatrix
Definition at line 109 of file ntg_graph_obj.h.
Function Documentation
template<class T > NTG_NodeDistanceMatrix NodeDistanceMatrixConditioning (const Matrix< T > & aMtr)
Definition at line 114 of file ntg_graph_obj.h.
References NT_ASSERT, TNT::Matrix< T >::num_cols(), TNT::Matrix< T >::num_rows(), and TNT::Matrix< T >::size().
{
    NTG_NodeDistanceMatrix dMtr(aMtr.num_rows(),aMtr.num_cols());
    NT_ASSERT( aMtr.size() == dMtr.size() );
    for (NTsize lr=0; lr < (NTsize)aMtr.num_rows(); lr++){
        for (NTsize lc=0; lc < (NTsize)aMtr.num_cols(); lc++) {
            if (lr == lc) dMtr[lr][lc] = 0;
            else {
                T tmpVal = aMtr[lr][lc];
                if ( 0 ==  tmpVal) dMtr[lr][lc] = 1/0.0; /* set value to infinity (NAN), this is correct code ! */
                else
                if ( (NTreal)tmpVal < 0) {
                    cerr << "NodeDistanceMatrixPrecondition - Warning : Negative values in matrix encountered. Using absolute values." << endl;
                    dMtr[lr][lc] = -tmpVal;
                } else dMtr[lr][lc] = tmpVal;
            }
        }
    }
    return dMtr;
}