sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=g++-5
        - CC=gcc-5
        - CXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=clang++-3.7

# Build steps
script:
  - autoreconf -fvi
  - ./configure
  - make
  - make test
  - test/tests
install: true
