sudo: false
language: C++
addons:
  apt:
    source:
    - boost-latest
    packages:
    - boost
    - lua
compiler:
  - gcc
  - clang
script: autoreconf -fvi && make && make test && test/tests
install: true
