sudo: false
language: C++

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
          source:
            - boost-latest
          packages:
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - liblua5.1-0-dev
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
          source:
            - boost-latest
          packages:
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - liblua5.2-0-dev
      env: COMPILER=clang++-3.7
compiler:
  - gcc
  - clang
# Build steps
script:
  - autoreconf -fvi
  - ./configure
  - make
  - make test
  - test/tests
install: true
