sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-5
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-random1.55-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=gcc-5
        - COMPILERXX=g++-5
        - WINE=
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - boost-latest
          packages:
            - clang-3.7
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-random1.55-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILERXX=clang++-3.7
        - COMPILER=clang-3.7
        - WINE=
    - compiler: mingw
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-mingw-w64
            - gcc-mingw-w64
            - binutils-mingw-w64
            - wine
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-random1.55-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=mingw-w64
        - COMPILERXX=
        - WINE=wine

# Build steps
script:
  - autoreconf -fvi
  - CC=$COMPILER CXX=$COMPILERXX ./configure
  - make
  - make test
  - $WINE test/tests
install: true
