sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=gcc-5
        - COMPILERXX=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libboost-filesystem-dev
            - libboost-program-options-dev
            - libboost-random-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILERXX=clang++-3.7
        - COMPILER=clang-3.7

# Build steps
script:
  - autoreconf -fvi
  - CC=$COMPILER CXX=$COMPILERXX ./configure
  - make
  - make test
  - test/tests
install: true
