sudo: false
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - boost-latest
          packages:
            - g++-6
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-random1.55-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILER=gcc-6
        - COMPILERXX=g++-6

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
            - boost-latest
          packages:
            - clang-3.9
            - libboost-filesystem1.55-dev
            - libboost-program-options1.55-dev
            - libboost-random1.55-dev
            - lua5.2
            - liblua5.2-0
            - liblua5.2-dev
      env:
        - COMPILERXX=clang++-3.9
        - COMPILER=clang-3.9

# Build steps
script:
  - autoreconf -fvi
  - CC=$COMPILER CXX=$COMPILERXX ./configure
  - make
  - make test
  - test/tests
install: true
