/**\file ntg_undirected_graph_obj.h - NTG_undirected_graph_o class header
 * by Ahmed Aldo Faisal &copy; created 13.10.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: ntg_undirected_graph_obj.h,v 1.1 2001/06/29 13:16:58 face Exp $
* $Log: ntg_undirected_graph_obj.h,v $
* Revision 1.1  2001/06/29 13:16:58  face
* *** empty log message ***
*
* Revision 1.3  2000/11/04 10:32:18  face
* *** empty log message ***
*
* Revision 1.1  2000/10/15 19:21:38  face
* *** empty log message ***
*

*/
#ifndef _ntg_undirected_graph_obj_h_
#define _ntg_undirected_graph_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "ntg_graph_obj.h"
/* NT includes */

/* other includes */

/** @short NTG_undirected_graph_o class
\bug unknown
\warning unknown
*/
class NTG_undirected_graph_o : public NTG_graph_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NTG_undirected_graph_o();
    NTG_undirected_graph_o(const NTG_undirected_graph_o & original);
    const NTG_undirected_graph_o & operator= (const NTG_undirected_graph_o & right);
    virtual ~NTG_undirected_graph_o();
    /* ***  Methods              ***/
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    NTreturn Connect(NTid source, NTid target) {
        return NTG_graph_o::Connect(source,target);
    }
    NTreturn Connect(NTid source, NTid target, const NTG_edge_o & newEdge) {
        return NTG_graph_o::Connect(source,target,newEdge);
    }
    NTreturn Disconnect(NTid source, NTid target) {
        return NTG_graph_o::Disconnect(source,target);
    }
    NTreturn DisconnectDivergence(NTid source) {
        return NTG_graph_o::DisconnectDivergence(source);
    }
    NTreturn DisconnectConvergence(NTid target) {
        return NTG_graph_o::DisconnectConvergence(target);
    }
    /* ***  Data                 ***/
};
#endif /* _ntg_undirected_graph_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
