/**\file Channels_current.h - NTBP_channels_current_o class header
 * by Ahmed Aldo Faisal &copy; created 16.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_channels_current_h_
#define _mcore_channels_current_h_

/* Parent includes */
#include "Membrane_current.h"
/* NT includes */
#include "Ion_channels.h"
/* other includes */

/** @short NTBP_channels_current_o class 
 Base class for stochastic channel simulations of individual channels
 \bug unknown
 \warning unknown
 */
namespace mcore {
class Channels_current: public Membrane_current {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Channels_current(mbase::Real reversalPotential, // in mV
			mbase::Real density, // channels per mumeter^2
			mbase::Real area, // in mumeter^2
			mbase::Real conductivity // in mSiemens per channel
			);
	Channels_current(const Channels_current & original);
	const Channels_current & operator=(const Channels_current & right);
	virtual ~Channels_current();
	/* ***  Methods              ***/
	/* mementary total conductance */
	mbase::Real _density() const {
		return (density);
	}
	mbase::Real _area() const {
		return (area);
	}
	/* conductivity per channel */
	mbase::Real _conductivity() const {
		return (conductivity);
	} /* in mSiemens per channel */
	/* conductivity if all channels open in mSiemens/cm^2 */
	mbase::Real _maxConductivity() const {
		return (density * conductivity * 1e-8);
	}
	/**  */

	bool ComputeGillespieStep() {
		return (channelsPtr->GillespieStep(voltage));
	}
	mbase::Real ComputeConductance() {
		return (Set_conductance(channelsPtr->NumOpen() * conductivity));
	}
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	Ion_channels * channelsPtr;
	mbase::Real density; // channels per mumeter^2
	mbase::Real area; // in mumeter^2
	mbase::Real conductivity; // in mSiemens per channel
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
};
}
#endif /* _mcore_channels_current.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
