/**\file mcore_hh_current.h - NTBP_hh_current_o class header
 * by Ahmed Aldo Faisal &copy; created 17.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_hh_current_h_
#define _mcore_hh_current_h_

/* NT core includes */
#include "../ntsrc/nt_main.h" 
#include "../ntsrc/nt_types.h" 
#include "../ntsrc/nt_obj.h"  
/* Parent includes */
#include "Membrane_current.h"
/* NT includes */

/* other includes */

/** @short NTBP_hh_current_o class 
 Hodkgin-Huxley type description of population of ion-channels
 \bug unknown
 \warning unknown
 */
namespace mcore {
class HH_current: public Membrane_current {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	HH_current(NTreal reversalPotential, NTreal maxConductivity, NTreal area);
	HH_current(const HH_current & original);
	const HH_current & operator=(const HH_current & right);
	virtual ~HH_current();
	/* ***  Methods              ***/
	NTreal ComputeChannelStateTimeConstant() const {
		return (0); /* no stochasticity */
	}
	/** in mSiemens/cm^2 */
	NTreal _maxConductivity() const {
		return (maxConductivity);
	}
	/** in muMeter^2 */
	NTreal _area() const {
		return (area);
	}
	/* ***  Data                 ***/
	virtual void Show() = 0;
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	NTreal maxConductivity; // in mSiemens / muMeter^2
	NTreal density; // channels per mumeter^2
	NTreal area; // in mumeter^2
	NTreal conductivity; // in mSiemens per channel
};
}
#endif /* _mcore_hh_current.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
