/**\file ntbp_membrane.h - Membrane class header 
 * by Ahmed Aldo Faisal &copy; created 16.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: ntbp_membrane.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
 * $Log: ntbp_membrane.h,v $
 * Revision 1.1.1.1  2004/12/16 01:38:36  face
 * Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
 *
 * Revision 1.1  2001/10/03 14:37:52  face
 * *** empty log message ***
 *

 */
#ifndef _mcore_membrane_h_
#define _mcore_membrane_h_

/* Parent includes */
#include "Object.h"
/* NT includes */
#include "Membrane_compartment.h"
/* other includes */

/** @short Membrane class 
 \bug unknown
 \warning unknown
 */
namespace mcore {
class Membrane: public Object {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Membrane();
	Membrane(const Membrane & original);
	Membrane & operator=(const Membrane & right);
	virtual ~Membrane();
	/* ***  Methods              ***/
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	std::vector<mcore::Membrane_compartment> membCompVec;
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
};
}
#endif /* _ntbp_membrane.h_ */ 

/* File skeleton generated by GenNTObj version 0.7. */
