/**\file Membrane_patch.h - Membrane_patch_o class header
 * by Ahmed Aldo Faisal &copy; created 21.1.2002  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000,2001,2002 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_membrane_patch_h_
#define _mcore_membrane_patch_h_

/* NT includes */
#include "Membrane_compartment.h"
#include "Object.h"
/* other includes */

/** @short Membrane_patch_o class
 \bug unknown
 \warning unknown
 */
namespace mcore {
class Membrane_patch: public Membrane_compartment {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Membrane_patch(mbase::Real area /* [muM^2] */, mbase::Real newCM /* muF/cm^2 */);
	Membrane_patch(const Membrane_patch & original);
	const Membrane_patch & operator=(const Membrane_patch & right);
	virtual ~Membrane_patch();
	/* ***  Methods              ***/
	mbase::Real MembranePotential() const {
		return (_vM());
	}
	/** No descriptions */
	mbase::Mreturn Step();
	/** No descriptions */
	mbase::Mreturn InitialStep();
	/** Current [nA]  */
	mbase::Real MembraneCurrent(mbase::Msize currentIndex) const {
		M_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size()));
		return (currentVec[currentIndex - 1]->_current());
	}
	/* in muMeter^2 */

	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
};
}
#endif /* _mcore_membrane_patch.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
