/**\file Multi_current.h - Multi_current_o class header
 * by Ahmed Aldo Faisal &copy; created 16.3.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_multi_current_h_
#define _mcore_multi_current_h_

/* NT core includes */
#include "mbase/Obj.h"
/* Parent includes */
#include "Membrane_current.h"
/* NT includes */
#include "Ion_channels.h"
/* other includes */

namespace mcore {
/** @short NTBP_multi_current_o class
 Base class for stochastic channel simulations of individual channels
 \bug unknown
 \warning unknown
 */
class Multi_current: public Membrane_current {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Multi_current(mbase::Real reversalPotential, // in mV
			mbase::Real density, // channels per mumeter^2
			mbase::Real area, // in mumeter^2
			mbase::Real conductivity // in mSiemens per channel
			);
	Multi_current(const Multi_current & original);
	Multi_current & operator=(const Multi_current & right);
	virtual ~Multi_current();
	/* ***  Methods              ***/
	/* mementary total conductance */
	mbase::Real _density() const {
		return (density);
	}
	mbase::Real _area() const {
		return (area);
	}
	/* conductivity per channel in mSiemens */
	mbase::Real _conductivity() const {
		return (conductivity);
	}
	/* conductivity if all channels open in mSiemens/cm^2, */
	mbase::Real _maxConductivity() const {
		return (density /* num/muMeter^2 */* conductivity /* mSiemens */* 1.0e8 /* muMeter^2/cm^2 */);
	}
	/**  */
	bool ComputeGillespieStep() {
		std::cerr << "NTBP_multi_current_o::ComputeGillespieStep()"
				<< std::endl;
		return (channelsPtr->GillespieStep(voltage));
	}
	void UpdateNumChannels() {
		numChannels = (mbase::Size_t) ceil(density * area);
	}
	mbase::Size_t _numChannels() const {
		return (numChannels);
	}
	/** Number of total ionic channels */
	mbase::Real NumChannels() const {
		return (_numChannels());
	}
	mbase::Real OpenChannelsRatio() const {
		return (open_channels() / NumChannels());
	}
// Dangerous: since cached values are not automatically recomputed in derived classes
//void Set_vBase(mbase::Real newVBase /* mV */){ vBase = newVBase; }
	Ion_channels * getChannelsPtr() {
		return (channelsPtr);
	}

	/* ***  Data                 ***/
public:
	Ion_channels * channelsPtr;
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	static mbase::Uniform_rnd_dist uniformRnd;
	mbase::Real conductivity; // in mSiemens per channel
	mbase::Real density; // channels per muMeter^2
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	mbase::Size_t numChannels;
	mbase::Real area; // in mumeter^2
	bool ratesComputed;

};
}
#endif /* _mcore_multi_current.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
