/**\file Spherical_compartment.h
 * Spherical_compartment class header
 * @author Ahmed Aldo Faisal &copy; created 19.3.2001  
 * @version   0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * @section LICENSE
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_spherical_compartment_h_
#define _mcore_spherical_compartment_h_

/* Parent includes */
#include "Membrane_compartment.h"
/* NT includes */

/* other includes */
#include <cmath>
//#include <math.h>


namespace mcore {
/**
 * @short mcore_spherical_compartment class
 * \bug unknown
 * \warning unknown
 */
class Spherical_compartment: public Membrane_compartment {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Spherical_compartment(modigliani_base::Real radius /* muMeter */,
			modigliani_base::Real cM /* muFarad/cm^2 */);
	Spherical_compartment(const Spherical_compartment & original);
	Spherical_compartment & operator=(
			const Spherical_compartment & right);
	virtual ~Spherical_compartment();
	/* ***  Methods              ***/
	modigliani_base::Real _radius() const {
		return (radius);
	}
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	modigliani_base::Real radius; // in
};
}
#endif /* _mcore_spherical_compartment.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
