/**\file Synaptic_background.h - Synaptic_background_o class header
 * by Ahmed Aldo Faisal &copy; created 20.8.2003  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License alhttp://npg.nature.com/npg/servlet/Content?data=xml/05_home.xml&style=xml/05_home.xslong with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_synaptic_background_h_
#define _mcore_synaptic_background_h_

/* Parent includes */
#include "Membrane_current.h"
/* NT includes */
#include "mbase/Gaussian_rnd_dist.h"

/* other includes */

/** @short Synaptic_background_o class
 \bug unknown
 \warning unknown
 */
namespace mcore {
class Synaptic_background: public Membrane_current {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Synaptic_background(mbase::Mreal avgSynBkCond, /* in nS */
	mbase::Mreal eSynBk, /* Synaptic background reversal potentialin mV (with vRest = vBase */
	mbase::Mreal synSigma, /* Synaptic noise "diffusion" nS */
	mbase::Mreal synTau, /* Synaptic time constant */
	mbase::Mreal vBase = -65.0 /* in mV */
	);
	Synaptic_background(const Synaptic_background & original);
	const Synaptic_background & operator=(const Synaptic_background & right);

	mbase::Mreturn step_current()
override	;
	/** compute and return conductance in mSiemens */
	mbase::Mreal compute_conductance() override;
	virtual ~Synaptic_background();
	/* ***  Methods              ***/
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	mbase::Mreal avgSynBkCond; /* ns */
	mbase::Mreal synSigma; /* ns */
	mbase::Mreal synVar; /* ns^2 */
	mbase::Mreal synTau; /* ms */
	mbase::Mreal vBase; /* mV */
	mbase::Mreal gT; /* nS */
	mbase::Mreal amplitude;/* nS */
	mbase::Gaussian_rnd_dist normRnd;
};}
#endif /* _mcore_synaptic_background.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
