/**\file nt3d_universe_vp_obj.cpp - NT3D_universe_vp_o class implementation 
 * by Ahmed Aldo Faisal &copy; created 13.5.1999  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal                            
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 


/* $Id: nt3d_universe_vp_obj.cpp,v 1.1.1.1 2004/12/16 01:38:36 face Exp $
 * $Log: nt3d_universe_vp_obj.cpp,v $
 * Revision 1.1.1.1  2004/12/16 01:38:36  face
 * Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
 *
 * Revision 1.1  2001/06/29 13:16:55  face
 * *** empty log message ***
 *
 * Revision 1.4  2000/10/03 08:29:59  face
 * *** empty log message ***
 *
 * Revision 1.3  2000/04/26 17:10:34  face
 * minor bug fixed
 * and upgrades:
 *
 * Revision 1.2  1999/07/17 18:22:09  face
 * imodified
 *
 * Revision 1.1.1.1  1999/07/03 15:17:20  face
 * Switching from RCS to CVS to improve
 * the handling of the new src code subdirectory
 * structure. aaf
 *
 *
 * Revision 1.2  1999/06/26 16:49:02  face
 * *** empty log message ***
 *
 * Revision 1.1  1999/06/06 23:51:34  face
 * Initial revision
 *
 * Revision 1.2  1999/05/09 09:34:15  face
 * corrected output
 *
 * Revision 1.1  1999/04/22 11:37:49  face
 * Initial revision
 *
 *
 */

#include "nt3d_universe_vp_obj.h" 

/* ***      CONSTRUCTORS	***//** Create a NT3D_universe_vp_o */
 NT3D_universe_vp_o::NT3D_universe_vp_o()
{
		haveUniverse = false;
}


NT3D_universe_vp_o::NT3D_universe_vp_o(NT3D_universe_o * pNewUniverse)
{
	pUniverse = pNewUniverse;
	haveUniverse = true;
}

/* ***      COPY AND ASSIGNMENT	***/
NT3D_universe_vp_o::NT3D_universe_vp_o(const NT3D_universe_vp_o __attribute__((unused)) & original):
		NT3D_abstract_vp_o()
{
	NT_CERR(1,"NT3D_universe_vp_o::NT3D_universe_vp_o(...) - Error : copy constructor not implemented .");
	
}

const NT3D_universe_vp_o&  
NT3D_universe_vp_o::operator= (const NT3D_universe_vp_o & right)
{
  if (this == &right) return *this; // Gracefully handle self assignment
  NT_CERR(1,"NT3D_universe_vp_o::operator= - Error : not implemented .");
  // add assignment code here
  return *this;
}


/* ***      DESTRUCTOR		***/
NT3D_universe_vp_o::~NT3D_universe_vp_o()
{
}

/* ***  PUBLIC                                    ***   */  
/** @short    	Generic draw with DrawUniverse() and optional ClearBuffer() to be added by derived classes   
    @param      none
    @return     none
    \warning    unknown
    \bug        unknown
 */

void
NT3D_universe_vp_o::Draw()
{
 	if (true == haveUniverse) {
		MakeCurrent();
 		DrawChild(); 
 		SwapBuffer();
 	} else NT_CERR(1,"NT3D_universe_vp_o::Draw() - Error : Attempt to draw without universe assigned.");
}


/** @short       
    @param      none
    @return     none
    \warning    unknown
    \bug        unknown
 */
NTreturn NT3D_universe_vp_o::SetUniverse(NT3D_universe_o * pNewUniverse)
{
	if (NT_TRUE == haveUniverse)
			NT_CERR(3,"NT3D_universe_camera_vp_o::AddUniverse - warning : new universe is overwriting old universe pointer.");
		pUniverse = pNewUniverse;
		haveUniverse = true;
		return NT_SUCCESS;
}

/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */


/* File skeleton generated by GenNTObj version 0.4. */
