/**\file nt3d_drv_vp_obj.h - NT3D_drv_vp_o class header 
 * by Ahmed Aldo Faisal &copy; created 9.5.1999  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal                            
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: nt3d_drv_vp_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $
 * $Log: nt3d_drv_vp_obj.h,v $
 * Revision 1.1.1.1  2004/12/16 01:38:36  face
 * Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
 *
 * Revision 1.1  2001/06/29 13:16:55  face
 * *** empty log message ***
 *
 * Revision 1.4  2000/10/03 08:29:59  face
 * *** empty log message ***
 *
 * Revision 1.3  2000/06/13 20:10:25  face
 * *** empty log message ***
 *
 * Revision 1.2  2000/04/26 17:10:34  face
 * minor bug fixed
 * and upgrades:
 *
 * Revision 1.1.1.1  1999/07/03 15:17:20  face
 * Switching from RCS to CVS to improve
 * the handling of the new src code subdirectory
 * structure. aaf
 *
 *
 * Revision 1.3  1999/06/19 16:15:49  face
 * *** empty log message ***
 *
 * Revision 1.2  1999/06/06 23:51:28  face
 * *** empty log message ***
 *
 * Revision 1.1  1999/05/13 11:34:59  face
 * Initial revision
 *
 * Revision 1.2  1999/05/09 09:34:15  face
 * corrected output
 *
 * Revision 1.1  1999/04/22 11:37:49  face
 * Initial revision
 *
 */
#ifndef _nt3d_drv_vp_h_
#define _nt3d_drv_vp_h_

#include "ntsrc/nt_main.h"
#include "ntsrc/nt_types.h"
#include "ntsrc/nt_obj.h"

#include "nt3d_vp_spec_obj.h"

#include "nt3d_vp_obj.h"
#include "nt3d_bitmap_obj.h"

/** @short NT3D_drv_vp_o class
 This viewport driver parent class provides the infrastructure for
 the NT3D_abstract_vp_o child classes which register with this class.
 In return this class dos not use its Draw() method so the draw method
 in the abstract class is called!
 \bug unknown
 \warning Do not override Draw() !
 */

class NT3D_drv_vp_o: public NT3D_vp_o {
public:
	/***   Constructors, CopyAssignment and Destructor  ***/
	NT3D_drv_vp_o();
	/*NT3D_drv_vp_o(const NT3D_drv_vp_o & original);
	 const NT3D_drv_vp_o & operator= (const NT3D_drv_vp_o & right);*/
	virtual ~NT3D_drv_vp_o();
	/* ***  Methods              ***/
	virtual mbase::Mreturn Open(NT3D_vp_spec_o __attribute__((unused)) newWinSpec) {
		NT_CERR(5, "NT3D_drv_vp_o::Open()");
		return mbase::M_SUCCESS;
	}
	;
	virtual mbase::Mreturn Close() {
		NT_CERR(5, "NT3D_drv_vp_o::Close()");
		return mbase::M_SUCCESS;
	}
	virtual void Init() {
	}
	;
	virtual mbase::Mreturn Resize(mbase::Msize __attribute__((unused)) width,
			mbase::Msize __attribute__((unused)) height) {
		NT_CERR(5, "NT3D_drv_vp_o::Resize()");
		return mbase::M_FAIL;
	}
	virtual void Redraw() {
	}
	;
	virtual NT3D_bitmap_o View2Bitmap() {
		NT_CERR(
				3,
				"NT3D_bitmap_o NT3D_drv_vp_o::View2Mem - Warning : Method should be implemented in derived class .");
		NT3D_bitmap_o oTmp;
		return oTmp;
	}
	virtual NT3D_bitmap_o * View2BitmapPtr(NT3D_bitmap_o * bmpPtr) {
		NT_CERR(
				3,
				"NT3D_bitmap_o * NT3D_drv_vp_o::View2Mem - Warning : Method should be implemented in derived class .");
		return bmpPtr;
	} //2DO implement code to handle continuos use of same allocated pointer
	  // take care that resize event are handled though!
	virtual mbase::Msize _width() {
		NT_CERR(
				1,
				"NT3D_drv_vp_o::_width() - Error : Should be implemented in derived class");
		return 0;
	}
	virtual mbase::Msize _height() {
		NT_CERR(
				1,
				"NT3D_drv_vp_o::_height() - Error : Should be implemented in derived class");
		return 0;
	}

	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	void Draw() {
		pVP->Draw();
	}
	;
	/* ***  Data                 ***/
};
#endif /* _nt3d_drv_vp_h_ */ 

/* File skeleton generated by GenNTObj version 0.4. */
