/**\file nt3d_open_box_obj.cpp - NT3D_open_box_o class implementation 
 * by Ahmed Aldo Faisal &copy; created 18.5.2000  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 
  

/* $Id: nt3d_open_box_obj.cpp,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
* $Log: nt3d_open_box_obj.cpp,v $
* Revision 1.1.1.1  2004/12/16 01:38:36  face
* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
*
* Revision 1.1  2001/06/29 13:16:55  face
* *** empty log message ***
*
* Revision 1.3  2000/07/06 08:06:10  face
* *** empty log message ***
*
* Revision 1.2  2000/06/26 19:14:06  face
* finally found the error that caused solid object to disappear:
* the scaling std::vector was not constructed in the 2nd constructor
* of the solid bject thus resulting in a zero object
* new demo file: showing some random graphics
*
* Revision 1.1  2000/06/13 20:10:25  face
* *** empty log message ***
*

*/
#include "nt3d_open_box_obj.h" 

#include "nt3d_rainbow_texture_obj.h"

/* ***      CONSTRUCTORS	***/
/** Create a NT3D_open_box_o */
NT3D_open_box_o::NT3D_open_box_o(mbase::Mreal newWidth, mbase::Mreal newDepth, mbase::Mreal newHeight)
:
NT3D_surfaced_object_o(),
oScaling(1,1,1),
width(newWidth),
depth(newDepth),
height(newHeight)
{
	//SetTexture();
	
}
/* ***      COPY AND ASSIGNMENT	***/ 
NT3D_open_box_o::NT3D_open_box_o(const NT3D_open_box_o & original):
		NT3D_surfaced_object_o(),
		oScaling(original.oScaling),
		width(original.width),
		depth(original.depth),
		height(original.height)
{
 // add assignment code here
}

const NT3D_open_box_o&  
NT3D_open_box_o::operator= (const NT3D_open_box_o & right)
{
 if (this == &right) return *this; // Gracefully handle self assignment
 // add assignment code here
   return *this;
}

/* ***      DESTRUCTOR		***/
NT3D_open_box_o::~NT3D_open_box_o()
{
}

/* ***  PUBLIC                                    ***   */  
/** @short       
    @param      none
    @return     none
   \warning    unknown
   \bug        unknown
 */
void
NT3D_open_box_o::DrawSurfacedObj() 
{
	mbase::Mreal x = depth/2 * oScaling.x;
	mbase::Mreal y = height/2 * oScaling.y;
	mbase::Mreal z = width/2 * oScaling.z;
	
	oMaterial.Paint();
    oTexturePtr->Paint();
    glBegin(GL_QUAD_STRIP);
	glTexCoord2f(1.0,0.0); glVertex3f(-x, -y, z); 
	glTexCoord2f(0.0,0.0); glVertex3f(-x, -y, -z);
	glTexCoord2f(1.0,1.0); glVertex3f(-x, y, z); 
	glTexCoord2f(0.0,1.0); glVertex3f(-x , y, -z);     // |    Open box - Viewed looking towards -Z Axis

	glTexCoord2f(1.0,0.0); glVertex3f(-x, y, z); 
	glTexCoord2f(0.0,0.0); glVertex3f(-x , y, -z);     // |-
	glTexCoord2f(1.0,1.0); glVertex3f(x , y, z); 
	glTexCoord2f(0.0,1.0); glVertex3f(x , y, -z);

	glTexCoord2f(1.0,0.0); glVertex3f(x , y, z); 
	glTexCoord2f(0.0,0.0); glVertex3f(x , y, -z);	
	glTexCoord2f(1.0,1.0); glVertex3f(x ,-y, z); 
	glTexCoord2f(0.0,1.0); glVertex3f(x , -y,-z );	  // |-|

	glTexCoord2f(1.0,0.0); glVertex3f(x ,-y, z); 
	glTexCoord2f(0.0,0.0); glVertex3f(x , -y,-z );
	glTexCoord2f(1.0,1.0); glVertex3f(-x, -y, z); 
	glTexCoord2f(0.0,1.0); glVertex3f(-x, -y, -z);    //  |=|
	glEnd();

	oTexturePtr->Painted();
}


/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */

/* File skeleton generated by GenNTObj version 0.7. */
