/**\file nt3d_light_obj.h - NT3D_light_o class declaration 
 * by Ahmed Aldo Faisal &copy; created 3.7.1999  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.4
 * Copyright (C) 1998,199 Ahmed Aldo Faisal                            
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 

/* $Id: nt3d_light_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
* $Log: nt3d_light_obj.h,v $
* Revision 1.1.1.1  2004/12/16 01:38:36  face
* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
*
* Revision 1.1  2001/06/29 13:16:55  face
* *** empty log message ***
*
* Revision 1.8  2000/05/13 09:42:55  face
* *** empty log message ***
*
* Revision 1.7  2000/05/11 12:42:08  face
* removed nt3d_rainbow_o by intergrating it into nt3d_light_o
*
* Revision 1.6  2000/05/11 11:32:44  face
* upgrade to NetTrader Version 0.5.
* Common state of all files checkin (Versioon 0.5)
* rearranged color and material classes...
* texture class added
*
* Revision 1.5  1999/07/17 18:22:02  face
* imodified
*
* Revision 1.4  1999/07/16 15:05:11  face
* added code::^
*
* Revision 1.3  1999/07/05 00:50:43  face
* updated light color model
*
* Revision 1.2  1999/07/04 03:17:31  face
* minor mods
*

*/
#ifndef _nt3d_light_h_
#define _nt3d_light_h_


#include "ntsrc/nt_main.h"
#include "ntsrc/nt_types.h"
#include "ntsrc/nt_obj.h"

#include "nt3d_object_obj.h"
#include "nt3d_color_obj.h"
#include "ntsrc/nt_id_management_obj.h"


/** @short NT3D_light_o class
 Light setup and manipulation (based OpenGL light implementation)
\bug unknown
\warning unknown 
 */
class NT3D_light_o : public NT_o {
public:
  /***   Constructors, Copy/Assignment and Destructor  ***/  
  NT3D_light_o();
  NT3D_light_o(const NT3D_light_o & original);
  const NT3D_light_o & operator= (const NT3D_light_o & right);
  virtual ~NT3D_light_o();
  /* ***  Methods              ***/
  /** Do not override in derived classes use DrawLight() instead 
      Do ONLY use calls to Illuminate() from outside this hierarchy */
  void Illuminate();
  void On();
  void Off();
  /* ***  Data                 ***/  
  NT3D_color_o colorAmbient;
  NT3D_color_o colorDiffuse;
  NT3D_color_o colorSpecular;
  protected:
  /* ***  Methods              ***/ 
  /** Derive to implement lights */
  virtual void IlluminateLight() = 0;
  void IlluminateAmbient() { glLightfv( (GLenum) lightId, GL_AMBIENT,  colorAmbient._colorPtr());}
  void IlluminateDiffuse() { glLightfv( (GLenum) lightId, GL_DIFFUSE,  colorDiffuse._colorPtr());}
  void IlluminateSpecular() { glLightfv( (GLenum) lightId, GL_SPECULAR, colorSpecular._colorPtr());}


  /* ***  Data                 ***/
  NTid lightId;
  private:
  /* ***  Methods              ***/
  void InitLights();
  NTid CreateLight(); 
  void DeleteLight(); 
  /* ***  Data                 ***/
  mbase::Mbool lightOn;
  static NT_id_management_o idManager;
};
#endif /* _nt3d_light_h_ */ 

/* File skeleton generated by GenNTObj version 0.5. */
