/**\file nt3d_abstract_vp_obj.h - NT3D_abstract_vp_o class header 
 * by Ahmed Aldo Faisal &copy; created 9.5.1999  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal                            
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 

/* $Id: nt3d_abstract_vp_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $
 * $Log: nt3d_abstract_vp_obj.h,v $
 * Revision 1.1.1.1  2004/12/16 01:38:36  face
 * Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
 *
 * Revision 1.1  2001/06/29 13:16:55  face
 * *** empty log message ***
 *
 * Revision 1.4  2000/10/03 08:29:59  face
 * *** empty log message ***
 *
 * Revision 1.3  2000/06/13 20:10:25  face
 * *** empty log message ***
 *
 * Revision 1.2  2000/04/26 17:10:34  face
 * minor bug fixed
 * and upgrades:
 *
 * Revision 1.1.1.1  1999/07/03 15:17:20  face
 * Switching from RCS to CVS to improve
 * the handling of the new src code subdirectory
 * structure. aaf
 *
 *
 * Revision 1.3  1999/06/19 16:15:49  face
 * *** empty log message ***
 *
 * Revision 1.2  1999/06/06 23:51:28  face
 * *** empty log message ***
 *
 * Revision 1.1  1999/05/13 11:34:59  face
 * Initial revision
 *
 * Revision 1.2  1999/05/09 09:34:15  face
 * corrected output
 *
 * Revision 1.1  1999/04/22 11:37:49  face
 * Initial revision
 *
*/
#ifndef _nt3d_abstract_vp_h_
#define _nt3d_abstract_vp_h_


#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"

#include "nt3d_vp_obj.h"
/** @short NT3D_abstract_vp_o class
The abstract viewport class houses the driver independent part
of the visualisation routines. It is connected/registered with a viewport
driver class NT3D_driver_vp_o childs. It uses the infrastructure
provided by a driver class via the NT3D_vp_o interface. 
\bug unknown
\warning do not override MakeCurrent() and SwapBuffer()
 */


 
class NT3D_abstract_vp_o : public NT3D_vp_o {
public:
  /***   Constructors, CopyAssignment and Destructor  ***/  
  NT3D_abstract_vp_o();
  NT3D_abstract_vp_o(const NT3D_abstract_vp_o & original);
  const NT3D_abstract_vp_o & operator= (const NT3D_abstract_vp_o & right);
  ~NT3D_abstract_vp_o();
  /* ***  Methods              ***/  
  virtual void Draw() = 0; 
  /** These methods call child and drv implementations */
  void Init() {InitChild();pVP->Init();}
  NTreturn Resize(NTsize newWidth, NTsize newHeight) {ResizeChild(newWidth,newHeight); return pVP->Resize(newWidth,newHeight);}
  void Redraw() {RedrawChild(); pVP->Redraw();}
  /* These methods call drv implemetnations only */
  void MakeCurrent() {pVP->MakeCurrent();}
  void SwapBuffer() {pVP->SwapBuffer();}
  NT3D_bitmap_o View2Bitmap() {return (NT3D_bitmap_o) pVP->View2Bitmap();}
  NT3D_bitmap_o * View2BitmapPtr(NT3D_bitmap_o * bmpPtr) {return pVP->View2BitmapPtr(bmpPtr);}
  NTsize _width(){return pVP->_width();}
  NTsize _height(){return pVP->_height();}
  /* ***  Data                 ***/
  protected:
  /* ***  Methods              ***/
  virtual void InitChild() = 0;
  virtual NTreturn ResizeChild(NTsize width, NTsize height) = 0;
  /* ***  Data                 ***/
  virtual void RedrawChild() = 0;
  /* ***  Data                 ***/  
  private:
  /* ***  Methods              ***/   
  /* ***  Data                 ***/
};
#endif /* _nt3d_abstract_vp_h_ */ 

/* File skeleton generated by GenNTObj version 0.4. */
