/**\file ntbp_hh_sga_sodium_current_obj.h - NTBP_hh_sga_sodium_current_o class header
 * by Ahmed Aldo Faisal &copy; created 17.3.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: ntbp_hh_sga_sodium_current_obj.h,v 1.2 2001/10/12 09:18:36 face Exp $
* $Log: ntbp_hh_sga_sodium_current_obj.h,v $
* Revision 1.2  2001/10/12 09:18:36  face
* *** empty log message ***
*
* Revision 1.1  2001/10/03 14:37:52  face
* *** empty log message ***
*

*/
#ifndef _ntbp_hh_sga_sodium_current_obj_h_
#define _ntbp_hh_sga_sodium_current_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "ntbp_hh_current_obj.h"
/* NT includes */

/* other includes */
#include <cmath>

/** @short NTBP_hh_sga_sodium_current_o class
\bug unknown
\warning unknown
*/
class NTBP_hh_sga_sodium_current_o : public NTBP_hh_current_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NTBP_hh_sga_sodium_current_o(NTreal area);
    NTBP_hh_sga_sodium_current_o(const NTBP_hh_sga_sodium_current_o & original);
    const NTBP_hh_sga_sodium_current_o & operator= (const NTBP_hh_sga_sodium_current_o & right);
    virtual ~NTBP_hh_sga_sodium_current_o();
    /* ***  Methods              ***/
    /** comptue and return conductance in mSiemens */
    NTreal ComputeConductance();
    void ComputeRateConstants(NTreal vM /* in mV */);
    NTreturn StepCurrent();
    NTreal OpenChannelsRatio() const {
        return m * m * m * h;
    }
    void Show() {
        cout << "alphaM= " << alphaM << "\t betaM= " << betaM << "\t m= " << m
             << "\t alphaM= " << alphaH << "\t betaH= " << betaH << "\t h= " << h;
    }
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    NTreal alphaM; // in msec^-1
    NTreal betaM;// in msec^-1
    NTreal m;

    NTreal alphaH;// in msec^-1
    NTreal betaH;// in msec^-1
    NTreal h;
};

#endif /* _ntbp_hh_sga_sodium_current_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
