///**\file ntbp_patlak_sodium_ion_channels_obj.h - NTBP_patlak_sodium_ion_channels_o class header
// * by Ahmed Aldo Faisal &copy; created 12.1.2003
// */
///* NetTrader - visualisation, scientific and financial analysis and simulation system
// * Version:  0.5
// * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
// *
// * This library is free software; you can redistribute it and/or
// * modify it under the terms of the GNU Library General Public
// * License as published by the Free Software Foundation; either
// * version 2 of the License, or (at your option) any later version.
// *
// * This library is distributed in the hope that it will be useful,
// * but WITHOUT ANY WARRANTY; without even the implied warranty of
// * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// * Library General Public License for more details.
// *
// * You should have received a copy of the GNU Library General Public
// * License along with this library; if not, write to the Free
// * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
// */
//
//
///* $Id: ntbp_patlak_sodium_ion_channels_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $
//* $Log: ntbp_patlak_sodium_ion_channels_obj.h,v $
//* Revision 1.1.1.1  2004/12/16 01:38:36  face
//* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
//*
//* Revision 1.1  2003/01/30 17:13:44  face
//* *** empty log message ***
//*
//
//*/
//#ifndef _ntbp_patlak_sodium_ion_channels_obj_h_
//#define _ntbp_patlak_sodium_ion_channels_obj_h_
//
///* NT core includes */
//#include "nt_main.h"
//#include "nt_types.h"
//#include "nt_obj.h"
///* Parent includes */
//#include "ntbp_ion_channels_obj.h"
///* NT includes */
//
///* other includes */
//
///** @short NTBP_patlak_sodium_ion_channels_o class
//The ion channels kinetical scheme is based on
//J. Patlak (1991) "Molecular kinetics of voltage-dependent Na^+ channels",
//Physiological Review, Vol. 71, No. 6, p. 1047-1080
//and implements model number 8.
//It consists of 7 discrete states, of which
//1-4 are closed, 5 is open and 6-7 are inactivated.
//\bug unknown
//\warning unknown
//*/
//class NTBP_patlak_sodium_ion_channels_o : public NTBP_ion_channels_o {
//public:
///***   Constructors, Copy/Assignment and Destructor  ***/
//NTBP_patlak_sodium_ion_channels_o(NTsize numNewChannels = 1);
//NTBP_patlak_sodium_ion_channels_o(const NTBP_patlak_sodium_ion_channels_o & original);
//const NTBP_patlak_sodium_ion_channels_o & operator= (const NTBP_patlak_sodium_ion_channels_o & right);
//virtual ~NTBP_patlak_sodium_ion_channels_o();
///* ***  Methods              ***/
//NTreturn Step();
//void ShowStates() const;
//NTsize NumOpen() const { return stateCounterVec[5];} // because 0 is num total channels
//NTsize NumClosed() const { return _numChannels() - NumOpen();}
///**  */
//NTreal ComputeChannelStateTimeConstant( ) const;
///**  */
//NTreturn UpdateStateProb( vector < NTreal > rateConstVec);
///**  */
///** set the steady state distribution of channel states for current rate constants, DIRTY HACK*/
//NTreturn SteadyStateDistribution();
///** No descriptions */
//NTreturn BinomialStep();
///* ***  Data                 ***/
//protected:
///* ***  Methods              ***/
///* ***  Data                 ***/
//private:
///* ***  Methods              ***/
///* ***  Data                 ***/
//NTreal alphaMP;
//NTreal betaMP;
//
//NTreal alphaHP;
//NTreal betaHP;
//
//NTreal gammaP;
//NTreal deltaP;
//
//NTreal kicP;
//NTreal kciP;
//
//NTreal kappaP;
//NTreal lambdaP;
//
//NTreal p12;
//NTreal p21;
//
//NTreal p23;
//NTreal p32;
//
//NTreal p34;
//NTreal p43;
//
//NTreal p45;
//NTreal p54;
//
//NTreal p67;
//NTreal p76;
//
//NTreal p36;
//NTreal p63;
//
//NTreal p46;
//NTreal p64;
//
//NTreal p57;
//NTreal p75;
//
//NTreal t21;
//
//NTreal t36;
//NTreal t32;
//
//NTreal t46;
//NTreal t43;
//
//NTreal t54;
//
//NTreal t64;
//NTreal t67;
//
//NTreal t75;
//
//};
//#endif /* _ntbp_patlak_sodium_ion_channels_obj_h_ */
//
///* File skeleton generated by GenNTObj version 0.7. */
