/**\file ntbp_sga_sodium_current_obj.h - NTBP_sga_sodium_current_o class header
 * by Ahmed Aldo Faisal &copy; created 16.3.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: ntbp_sga_sodium_current_obj.h,v 1.1 2001/10/03 14:37:52 face Exp $
* $Log: ntbp_sga_sodium_current_obj.h,v $
* Revision 1.1  2001/10/03 14:37:52  face
* *** empty log message ***
*

*/
#ifndef _ntbp_sga_sodium_current_obj_h_
#define _ntbp_sga_sodium_current_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "ntbp_channels_current_obj.h"
/* NT includes */
#include "ntbp_sodium_ion_channels_obj.h"
/* other includes */

/** @short NTBP_sga_sodium_current_o class
Channel density 330/muM^2
Single channel conductivity 4 pS
Temperature 9 Celsius
(see Hille (1992) p. 329 or Conti et. al (1975) )
\bug unknown
\warning unknown
*/
class NTBP_sga_sodium_current_o : public NTBP_channels_current_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NTBP_sga_sodium_current_o(NTreal area /* in muMeter^2 */, NTreal density = 330 /* in num/muMeter^2 */);
    NTBP_sga_sodium_current_o(const NTBP_sga_sodium_current_o & original);
    const NTBP_sga_sodium_current_o & operator= (const NTBP_sga_sodium_current_o & right);
    virtual ~NTBP_sga_sodium_current_o();
    /* ***  Methods              ***/
    NTreturn StepCurrent();
    NTreal ComputeChannelStateTimeConstant() const;
    void ComputeRateConstants(NTreal vM /* in mV */);
    void ShowChannelStatePopulation() {
        channelsPtr->ShowStates();
    }
    void Show() {
        cout << " alphaM= " << alphaM << "\t betaM= " << betaM << "\t openRatio= " << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
             << "\t alphaH= " << alphaH << "\t betaH= " << betaH << "\t openNum= " << channelsPtr->NumOpen();
    }
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    NTreal alphaM;
    NTreal betaM;
    NTreal m;

    NTreal alphaH;
    NTreal betaH;
    NTreal h;
    /* ***  Data                 ***/
};
#endif /* _ntbp_sga_sodium_current_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
