/**\file ntbp_potassium_multi_current_obj.h - NTBP_potassium_multi_current_o class header
 * by Ahmed Aldo Faisal &copy; created 16.3.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: ntbp_potassium_multi_current_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $
* $Log: ntbp_potassium_multi_current_obj.h,v $
* Revision 1.1.1.1  2004/12/16 01:38:36  face
* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
*
* Revision 1.1  2003/08/24 10:44:18  face
* *** empty log message ***
*
* Revision 1.2  2002/03/13 19:23:27  face
* *** empty log message ***
*
* Revision 1.1  2001/10/03 14:37:52  face
* *** empty log message ***
*

*/
#ifndef _ntbp_potassium_multi_current_obj_h_
#define _ntbp_potassium_multi_current_obj_h_


/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "ntbp_multi_current_obj.h"
/* NT includes */
#include "ntbp_potassium_ion_channels_obj.h"
#include "nt_gaussian_rnd_dist_obj.h"
/* other includes */


/** @short NTBP_potassium_multi_current_o class */
/* data based on Hille (1992) and other literature
\bug unknown
\warning unknown
*/


class NTBP_potassium_multi_current_o : public NTBP_multi_current_o {
public:
/***   Constructors, Copy/Assignment and Destructor  ***/
NTBP_potassium_multi_current_o(NTreal area /* in muMeter^2 */,
                               NTreal density = 8/* in num/muMeter^2 */,
                               NTreal channelConductance = 2.0e-8, /* in mSiemens per channel = 13pS */
                               NTreal newVBase = -65.0, /* in mV */
                               NTreal newTBase = 6.3 /* in C */,
                               NTreal newEK = -12.0 /* mV */
                               );
NTBP_potassium_multi_current_o(const NTBP_potassium_multi_current_o & original);
const NTBP_potassium_multi_current_o & operator= (const NTBP_potassium_multi_current_o & right);
virtual ~NTBP_potassium_multi_current_o();
/* ***  Methods              ***/
NTreal ComputeRateSum() const;
NTreal OpenChannels() const;
NTreal ComputeConductance();
void ComputeRateConstants(NTreal voltage);
/**  in kHz */
NTreal ComputeChannelStateTimeConstant() const;
/**  */
NTreturn StepCurrent();
/** rate constant in ms^-1 */
NTreal AlphaN( NTreal voltage /* in mV */ ) {
        voltage += _vBase();
        return ((10.0 - (65.0+voltage))/(100.0 * ( exp( (10.0 - (65.0+voltage))/10.0 ) - 1.0) ));
        }
NTreal BetaN ( NTreal voltage /* in mV */ ) {
        voltage += _vBase();
        return 0.125 * exp(-(65.0+voltage) / 80.0);
        }
/**  */
NTreal _baseTemp() const { return baseTemp;}
void ShowParam() const;
/* ***  Data                 ***/
protected:
/* ***  Methods              ***/
/* ***  Data                 ***/
private:
/* ***  Methods              ***/
/* ***  Data                 ***/
NTreal baseTemp;
NTBPdelayedPotassiumRectifierType type;
static NT_gaussian_rnd_dist_o normalRnd;
static bool initTableLookUp;
static NTreal alphaNvec [15000];
static NTreal betaNvec [15000];
NTreal alphaN;
NTreal betaN;
NTreal n;
NTreal noiseN;
};

#endif /* _ntbp_potassium_multi_current_obj_h_ */ 

/* File skeleton generated by GenNTObj version 0.7. */
