/**\file nt_2dim_histogram_obj.h - NT_2dim_histogram_o class header
 * by Ahmed Aldo Faisal &copy; created 11.10.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: nt_2dim_histogram_obj.h,v 1.3 2003/06/19 11:05:05 face Exp $
* $Log: nt_2dim_histogram_obj.h,v $
* Revision 1.3  2003/06/19 11:05:05  face
* *** empty log message ***
*
* Revision 1.2  2002/02/25 22:48:54  face
* *** empty log message ***
*
* Revision 1.1  2001/10/12 09:18:38  face
* *** empty log message ***
*
*/

#ifndef _nt_2dim_histogram_obj_h_
#define _nt_2dim_histogram_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* NT includes */
#include "nt_error_obj.h"
#include "nt_aux_math_func.h"

/* other includes */
#include <vector>
#include <tnt/cmat.h>

using namespace TNT;
using TNT::Matrix;

/** @short NT_2dim_histogram_o class
\bug unknown
\warning unknown
*/


class NT_2dim_histogram_o : public NT_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT_2dim_histogram_o(NTsize numBinsA, NTreal minA, NTreal maxA, NTsize numBinsB, NTreal minB, NTreal maxB);
    NT_2dim_histogram_o(const NT_2dim_histogram_o & original);
    const NT_2dim_histogram_o & operator= (const NT_2dim_histogram_o & right);
    virtual ~NT_2dim_histogram_o();
    /* ***  Methods              ***/
    /** No descriptions */
    NTreturn Reset();
    /** No descriptions */
    NTreal ShannonEntropy() const;
    /** No descriptions */
    NTsize BinValue(NTreal valueA, NTreal valueB);
    /** No descriptions */
    void Show() const;
    /** No descriptions */
    Matrix <NTreal> PDF() const;
    /** No descriptions */
    NTsize BinValue ( vector <NTreal> valueVec);
    /** No descriptions */
    NTsize _numBinned() {
        return numBinned;
    }
    NTsize _numUnbinned() {
        return numUnbinned;
    }
    /** No descriptions */
    /** No descriptions */

    /* ***  Data                 ***/
protected:
    /* ***  Methods
       ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    Matrix <NTsize> table;
    NTsize numBinsA;
    NTreal maxA;
    NTreal minA;
    NTreal rangeA;
    NTsize numBinsB;
    NTreal maxB;
    NTreal minB;
    NTreal rangeB;
    NTsize numBinned;
    NTsize numUnbinned;
};

#endif /* _nt_2dim_histogram_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
