/**\file nt_aux_math_obj.h - NT_aux_math_o auxiliary functions header
 * by Ahmed Aldo Faisal &copy; created 27.4.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.4
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt_aux_math_func.h,v 1.5 2002/03/04 18:09:10 face Exp $
* $Log: nt_aux_math_func.h,v $
* Revision 1.5  2002/03/04 18:09:10  face
* added checking for NaN and Inf values in find_spikes_in_binary_file-
* BinomialStep: redo loop if after state change the states do not sum up
*
* Revision 1.4  2001/11/06 16:28:15  face
* *** empty log message ***
*
* Revision 1.3  2001/10/12 09:18:39  face
* *** empty log message ***
*
* Revision 1.2  2001/06/25 13:04:57  face
* *** empty log message ***
*
* Revision 1.1  2001/06/11 13:18:56  face
* *** empty log message ***
*
* Revision 1.3  2000/10/15 19:22:58  face
* *** empty log message ***
*
* Revision 1.2  2000/04/27 23:52:45  face
* IMPLEMENT nt_vector_o DESTRUCTOR
*
* Revision 1.1  2000/04/27 18:20:50  face
* loads of changes:
* -static init. fiasco workaounrd
* -texture objects have new structure
* ...
*

*/
#ifndef _nt_aux_math_func_h_
#define _nt_aux_math_func_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* NT includes */
#include "nt_mersenne_twister_external_obj.h"
/* other includes */
#include <cmath>

/* *** METHODS *** */

/** @short NTlimit01
Limit a value between [0,1]
\bug unknown
\warning unknown
*/
extern NTreal NTComputePLogP(NTreal prob);
extern NTreal NTlimit01 (NTreal value);
extern NTreal NTround (NTreal value);
extern NTreal NTLogGammaFunction(NTreal arg);
extern MTRand NTMakeMTRandFunction(MTRand::uint32 oneSeed);
extern int    NTisnan (double value);
extern int    NTisinf (double value);


/* *** DATA *** */
#ifndef M_PI
#define M_PI 3.14159265358979323846  /* pi */
#endif


#endif /* _nt_aux_math_h_ */

/* File skeleton generated by GenNTObj version 0.6. */
