/**\file nt_binomial_rnd_dist_obj.h - NT_binomial_rnd_dist_o class header
 * by Ahmed Aldo Faisal &copy; created 19.6.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt_binomial_rnd_dist_obj.h,v 1.2 2001/10/08 11:01:45 face Exp $
* $Log: nt_binomial_rnd_dist_obj.h,v $
* Revision 1.2  2001/10/08 11:01:45  face
* *** empty log message ***
*
* Revision 1.1  2001/06/29 13:14:44  face
* adding vraious addtions
* mainly in ntsrc (multidim_array)
*

*/
#ifndef _nt_binomial_rnd_dist_obj_h_
#define _nt_binomial_rnd_dist_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "nt_rnd_dist_obj.h"
/* NT includes */

/* other includes */
#include <cmath>
#include <vector>

/** @short NT_binomial_rnd_dist_o class
\bug unknown
\warning unknown
*/
class NT_binomial_rnd_dist_o : public NT_rnd_dist_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT_binomial_rnd_dist_o(NTreal pp, NTsize n);
    NT_binomial_rnd_dist_o(const NT_binomial_rnd_dist_o & original);
    const NT_binomial_rnd_dist_o & operator= (const NT_binomial_rnd_dist_o & right);
    virtual ~NT_binomial_rnd_dist_o();
    NTreal RndVal() const;
    /** Identical to method 'bnldev' from Numerical Recipes in C (Press et al.) */
    NTreal Binomial(float pp, int n) const;
    NTreal LogGamma(NTreal val) const;
    /* ***  Methods              ***/
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    NTreal p;
    NTsize n;
    static vector <NTreal> logGammaTable;
    static bool init;
};
#endif /* _nt_binomial_rnd_dist_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
