/**
 * @file str2real.h
 * str2real class header
 * @author Ahmed Aldo Faisal &copy; created 3.7.1999
 * code is originally based on Chameleon.h by Ren��� Nyffenegger
 * see http://www.adp-gmbh.ch/cpp/chameleon.html
 * NetTrader - visualisation, scientific and financial analysis and simulation system
 * @version  0.5
 * Copyright (C) 1998-20005 Ahmed Aldo Faisal    
 *
 * @section LICENSE
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _modigliani_base_str2real_h_ 
#define _modigliani_base_str2real_h_ 

/* M core includes */
#include "main.h" 
#include "types.h" 
#include "obj.h"  
/* M includes */

/* other includes */
#include <cstring>
#include <sstream>
#include <cstdlib>

namespace modigliani_base {
/** @short Str2real class
 A class that can can act as a number and a string
 \bug unknown
 \warning unknown
 */
class Str2real: public Obj {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    Str2real() {
    }
    ;
    Str2real(const std::string&);
    Str2real(double);
    Str2real(const char*);

    Str2real(const Str2real&);
    Str2real& operator=(Str2real const&);

    Str2real& operator=(double);
    Str2real& operator=(std::string const&);
    virtual ~Str2real();

    /* ***  Methods              ***/
    operator std::string() const;
    operator double() const;
private:
    /* ***  Data                 ***/
    std::string value_;
};
}

#endif /* _modigliani_base_str2real_h_ */ 

/* File skeleton generated by GenMObj version 0.7. */
