/**
 * @file vec_rnd_dist.h
 * Vec_rnd_dist class header
 * @author Ahmed Aldo Faisal &copy; created 26.6.1999
 * @version  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * @section LICENSE
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mbase_vec_rnd_dist_h_
#define _mbase_vec_rnd_dist_h_

#include "types.h"
#include "obj.h"

#include <vector>

#include "vector.h"
#include "rnd_dist.h"

namespace modigliani_base {
/** @short Vec_rnd_dist class

 \bug unknown
 \warning unknown
 */
class Vec_rnd_dist: public Obj {
public:
    /***   Constructors, CopyAssignment and Destructor  ***/
    Vec_rnd_dist(Size newDim = 3);
    Vec_rnd_dist(const Vec_rnd_dist & original);
    const Vec_rnd_dist & operator=(const Vec_rnd_dist & right);
    virtual ~Vec_rnd_dist();
    /* ***  Methods              ***/
    modigliani_base::Vector RndVec() const;
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    Size dim;
    std::vector<Rnd_dist *> rndDistPtrVec;
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/

};
}
#endif /* _mbase_vec_rnd_dist_h_ */

/* File skeleton generated by GenMObj version 0.4. */

