/**\file ntbp_cylindrical_compartment_obj.cpp - NTBP_cylindrical_compartment_o class implementation 
 * by Ahmed Aldo Faisal &copy; created 26.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: ntbp_cylindrical_compartment_obj.cpp,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
 * $Log: ntbp_cylindrical_compartment_obj.cpp,v $
 * Revision 1.1.1.1  2004/12/16 01:38:36  face
 * Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
 *
 * Revision 1.2  2002/03/08 15:13:26  face
 * *** empty log message ***
 *
 * Revision 1.1  2001/10/03 14:37:52  face
 * *** empty log message ***
 *

 */
#include "ntbp_cylindrical_compartment_obj.h" 

/* ***      CONSTRUCTORS	***/
/** Create a NTBP_cylindrical_compartment_o */
NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o(
		NTreal newLength /* in muMeter */, NTreal newDiameter /* in muMeter */, NTreal newTemperature)
:
			NTBP_membrane_compartment_o(M_PI * newDiameter * newLength /* in muMeter^2 */, newTemperature) {
	length = newLength;
	diameter = newDiameter;
}

/* ***      COPY AND ASSIGNMENT	***/
NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o(
		const NTBP_cylindrical_compartment_o & original) :
	NTBP_membrane_compartment_o(original._area()) {
	// add assignment code here
}

const NTBP_cylindrical_compartment_o&
NTBP_cylindrical_compartment_o::operator=(
		const NTBP_cylindrical_compartment_o & right) {
	if (this == &right)
		return (*this); // Gracefully handle self assignment
	// add assignment code here
	return (*this);
}

/* ***      DESTRUCTOR		***/
NTBP_cylindrical_compartment_o::~NTBP_cylindrical_compartment_o() {
	for (auto it=currentVec.begin(); it!=currentVec.end(); ++it){
		delete *it;
	}
}

/* ***  PUBLIC                                    ***   */
/** @short       
 @param      none
 @return     none
 \warning    unknown
 \bug        unknown
 void
 NTBP_cylindrical_compartment_o::() const
 {
 }
 */

/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */

/* File skeleton generated by GenNTObj version 0.7. */
