/**\file ntbp_synaptic_background_obj.h - NTBP_synaptic_background_o class header 
 * by Ahmed Aldo Faisal &copy; created 20.8.2003  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License alhttp://npg.nature.com/npg/servlet/Content?data=xml/05_home.xml&style=xml/05_home.xslong with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 
  

/* $Id: ntbp_synaptic_background_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
* $Log: ntbp_synaptic_background_obj.h,v $
* Revision 1.1.1.1  2004/12/16 01:38:36  face
* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
*
* Revision 1.2  2004/12/14 15:48:34  face
* *** empty log message ***
*
* Revision 1.1  2003/08/24 10:44:18  face
* *** empty log message ***
*

*/
#ifndef _ntbp_synaptic_background_obj_h_ 
#define _ntbp_synaptic_background_obj_h_ 

/* NT core includes */
#include "ntsrc/nt_main.h" 
#include "ntsrc/nt_types.h" 
#include "ntsrc/nt_obj.h"  
/* Parent includes */
#include "ntbp_membrane_current_obj.h" 
/* NT includes */
#include "ntsrc/nt_gaussian_rnd_dist_obj.h"

/* other includes */

/** @short NTBP_synaptic_background_o class 
\bug unknown
\warning unknown 
*/
class NTBP_synaptic_background_o : public NTBP_membrane_current_o {
public:
/***   Constructors, Copy/Assignment and Destructor  ***/  
NTBP_synaptic_background_o(NTreal avgSynBkCond, /* in nS */
                           NTreal eSynBk,   /* Synaptic background reversal potentialin mV (with vRest = vBase */
                           NTreal synSigma, /* Synaptic noise "diffusion" nS */
                           NTreal synTau,   /* Synaptic time constant */
                           NTreal vBase = -65.0 /* in mV */
                           );
NTBP_synaptic_background_o(const NTBP_synaptic_background_o & original);
const NTBP_synaptic_background_o & operator= (const NTBP_synaptic_background_o & right);

NTreturn step_current();
/** compute and return conductance in mSiemens */
NTreal compute_conductance();
virtual ~NTBP_synaptic_background_o();
/* ***  Methods              ***/  
/* ***  Data                 ***/  
protected:
/* ***  Methods              ***/  
/* ***  Data                 ***/  
private:
/* ***  Methods              ***/  
/* ***  Data                 ***/
NTreal avgSynBkCond; /* ns */
NTreal synSigma; /* ns */
NTreal synVar;   /* ns^2 */
NTreal synTau;   /* ms */
NTreal vBase;    /* mV */
NTreal gT;       /* nS */
NTreal amplitude;/* nS */
NT_gaussian_rnd_dist_o normRnd;
};
#endif /* _ntbp_synaptic_background_obj_h_ */ 

/* File skeleton generated by GenNTObj version 0.7. */
