/**\file ntbp_hh_current_obj.h - NTBP_hh_current_o class header 
 * by Ahmed Aldo Faisal &copy; created 17.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 
  

/* $Id: ntbp_hh_current_obj.h,v 1.1.1.1 2004/12/16 01:38:36 face Exp $ 
* $Log: ntbp_hh_current_obj.h,v $
* Revision 1.1.1.1  2004/12/16 01:38:36  face
* Imported NetTrader 0.5 source from flyeye02.zoo.cam.ac.uk repository
*
* Revision 1.1  2001/10/03 14:37:52  face
* *** empty log message ***
*

*/
#ifndef _ntbp_hh_current_obj_h_ 
#define _ntbp_hh_current_obj_h_ 

/* NT core includes */
#include "../ntsrc/nt_main.h" 
#include "../ntsrc/nt_types.h" 
#include "../ntsrc/nt_obj.h"  
/* Parent includes */
#include "ntbp_membrane_current_obj.h" 
/* NT includes */

/* other includes */

/** @short NTBP_hh_current_o class 
Hodkgin-Huxley type description of population of ion-channels
\bug unknown
\warning unknown 
*/
class NTBP_hh_current_o : public NTBP_membrane_current_o {
public:
/***   Constructors, Copy/Assignment and Destructor  ***/  
NTBP_hh_current_o(NTreal reversalPotential, NTreal maxConductivity, NTreal area);
NTBP_hh_current_o(const NTBP_hh_current_o & original);
const NTBP_hh_current_o & operator= (const NTBP_hh_current_o & right);
virtual ~NTBP_hh_current_o();
/* ***  Methods              ***/
NTreal ComputeChannelStateTimeConstant() const {return 0; /* no stochasticity */ }
/** in mSiemens/cm^2 */
NTreal _maxConductivity() const {return maxConductivity;}
/** in muMeter^2 */
NTreal _area() const { return area; }
/* ***  Data                 ***/
virtual void Show() = 0;
protected:
/* ***  Methods              ***/  
/* ***  Data                 ***/
private:
/* ***  Methods              ***/  
/* ***  Data                 ***/
NTreal maxConductivity;  // in mSiemens / muMeter^2
NTreal density; // channels per mumeter^2
NTreal area; // in mumeter^2
NTreal conductivity; // in mSiemens per channel
};
#endif /* _ntbp_hh_current_obj_h_ */ 

/* File skeleton generated by GenNTObj version 0.7. */
