/**\file ntbp_ion_channels_obj.h - NTBP_ion_channels_o class header 
 * by Ahmed Aldo Faisal &copy; created 15.3.2001  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _ntbp_ion_channels_obj_h_
#define _ntbp_ion_channels_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "ntbp_object_obj.h"
/* NT includes */
#include "nt_error_obj.h"
#include "nt_uniform_rnd_dist_obj.h"
#include "nt_binomial_rnd_dist_obj.h"
#include "ntbp_transition_rate_matrix_obj.h"
/* other includes */
#include <vector>
#include <iostream>

//#include "boost/multi_array.hpp"

/** @short NTBP_ion_channels_o class
 \bug unknown
 \warning unknown
 */
class NTBP_ion_channels_o: public NTBP_object_o {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	NTBP_ion_channels_o(NTsize numNewChannels, NTsize numNewStates, NTBP_transition_rate_matrix_o* probMatrix, NTreal newTimeStep=0.1);
	NTBP_ion_channels_o(const NTBP_ion_channels_o & original);
	const NTBP_ion_channels_o & operator=(const NTBP_ion_channels_o & right);
	virtual ~NTBP_ion_channels_o();
	/* ***  Methods              ***/
	NTsize _numChannels() const {
		return numChannels;
	}
	NTsize _numStates() const {
		return numStates;
	}
	NTreturn GillespieStep(NTreal voltage);
	void setAsOpenState(NTsize newOpenState);
	NTreturn BinomialStep(NTreal voltage);
	NTreturn DeterministicStep(NTreal voltage);
	NTreturn Step(NTreal voltage);
	NTreturn ComputeGillespieStep(NTsize channelStateId, NTreal voltage);
	void ShowStates() const;
	NTsize NumOpen() const;
	NTsize numChannelsInState(NTsize state) const {
		return stateCounterVec[state];
	}
	NTsize NumClosed() const {
		return _numChannels() - NumOpen();
	}
	virtual NTreturn SteadyStateDistribution(NTreal voltage);
	/** Sum of escape rates from current state [1/s] */
	virtual NTreal ComputeChannelStateTimeConstant(NTreal voltage) const;
	//virtual NTreturn UpdateStateProb(vector <NTreal> rateConstVec /* in mSec^-1 */) = 0;
	/**  */
	void setRatesComputed(bool newValue) {
		ratesComputed = newValue;
	}
	bool getRatesComputed() {
		return ratesComputed;
	}
	/* ***  Data                 ***/

protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	// TODO remove this
	vector<NTreal> statePersistenceProbVec;
	vector<NTint> stateCounterVec;
	static NT_uniform_rnd_dist_o uniformRnd; // [0,1] random number generation
	static NT_binomial_rnd_dist_o binomRnd;

private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	NTBP_transition_rate_matrix_o* _probMatrix;
	vector<NTsize> openStates;
	NTsize numStates;
	NTsize numChannels;
	bool ratesComputed;
};

#endif /* _ntbp_ion_channels_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
