/**\file Synaptic_background.h - Synaptic_background_o class header
 * by Ahmed Aldo Faisal &copy; created 20.8.2003  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License alhttp://npg.nature.com/npg/servlet/Content?data=xml/05_home.xml&style=xml/05_home.xslong with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mcore_synaptic_background_h_
#define _mcore_synaptic_background_h_

/* NT core includes */
#include "ntsrc/nt_main.h" 
#include "ntsrc/nt_types.h" 
#include "ntsrc/nt_obj.h"  
/* Parent includes */
#include "Membrane_current.h"
/* NT includes */
#include "ntsrc/nt_gaussian_rnd_dist_obj.h"

/* other includes */

/** @short Synaptic_background_o class
 \bug unknown
 \warning unknown
 */
namespace mcore {
class Synaptic_background: public Membrane_current {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Synaptic_background(NTreal avgSynBkCond, /* in nS */
	NTreal eSynBk, /* Synaptic background reversal potentialin mV (with vRest = vBase */
	NTreal synSigma, /* Synaptic noise "diffusion" nS */
	NTreal synTau, /* Synaptic time constant */
	NTreal vBase = -65.0 /* in mV */
	);
	Synaptic_background(const Synaptic_background & original);
	const Synaptic_background & operator=(const Synaptic_background & right);

	NTreturn step_current()
override	;
	/** compute and return conductance in mSiemens */
	NTreal compute_conductance() override;
	virtual ~Synaptic_background();
	/* ***  Methods              ***/
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	NTreal avgSynBkCond; /* ns */
	NTreal synSigma; /* ns */
	NTreal synVar; /* ns^2 */
	NTreal synTau; /* ms */
	NTreal vBase; /* mV */
	NTreal gT; /* nS */
	NTreal amplitude;/* nS */
	NT_gaussian_rnd_dist_o normRnd;
};}
#endif /* _mcore_synaptic_background.h_ */

/* File skeleton generated by GenNTObj version 0.7. */
