/**\file nt_binomial_rnd_dist_obj.h - NT_binomial_rnd_dist_o class header
 * by Ahmed Aldo Faisal &copy; created 19.6.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mmath_binomial_rnd_dist_h_
#define _mmath_binomial_rnd_dist_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "nt_rnd_dist_obj.h"
/* NT includes */

/* other includes */
#include <cmath>
#include <vector>

/** @short NT_binomial_rnd_dist_o class
 \bug unknown
 \warning unknown
 */
namespace mmath {
class Binomial_rnd_dist: public NT_rnd_dist_o {

	class Initializer {
	public:
		Initializer();
		vector<NTreal> logGammaTable;
	};

	friend class Initializer;
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Binomial_rnd_dist(NTreal pp, NTsize n);Binomial_rnd_dist(const Binomial_rnd_dist & original);
	const Binomial_rnd_dist & operator=(
			const Binomial_rnd_dist & right);
	virtual ~Binomial_rnd_dist();
	NTreal RndVal() const;
	/** Identical to method 'bnldev' from Numerical Recipes in C (Press et al.) */
	NTreal Binomial(float pp, int n) const;
	NTreal LogGamma(NTreal val) const;
	/* ***  Methods              ***/
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	//static vector<NTreal> logGammaTable;
	static bool init;
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	NTreal p;
	NTsize n;
	static Initializer static_table;
};
}
#endif /* _nt_binomial_rnd_dist_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
