/**\file Config_file_parser.h - Config_file_parser class header
 * by Ahmed Aldo Faisal &copy; created 3.7.1999  
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.0
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mbase_config_file_parser_h_
#define _mbase_config_file_parser_h_

/* M core includes */
#include "main.h" 
#include "types.h" 
#include "Obj.h"  
/* M includes */
#include "Str2real.h"
/* other includes */
#include <cstring>
#include <map>
#include <fstream>

/** @short Config_file_parser class
 \bug unknown
 \warning unknown
 */
namespace mbase {
class Config_file_parser: public Obj {

	std::map<std::string, Str2real> content_;
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	Config_file_parser(std::string const& configFile);
	Config_file_parser();
	const Config_file_parser & operator=(const Config_file_parser & original);
	virtual ~Config_file_parser();

	/* ***  Methods              ***/
	Str2real const& Value(std::string const& section,
			std::string const& entry) const;

	Str2real const& Value(std::string const& section,
			std::string const& entry, double value);
	Str2real const& Value(std::string const& section,
			std::string const& entry, std::string const& value);
};
}

#endif /* _mbase_config_file_parser_h_ */

/* File skeleton generated by GenMObj version 0.7. */
