/**\file Gaussian_vec_rnd_dist.h - Gaussian_vec_rnd_dist class header
 * by Ahmed Aldo Faisal &copy; created 26.6.1999
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mbase_gaussian_vec_rnd_dist_h_
#define _mbase_gaussian_vec_rnd_dist_h_

#include "main.h"
#include "types.h"
#include "Obj.h"

#include "Vec_rnd_dist.h"
#include "Gaussian_rnd_dist.h"

/** @short Gaussian_vec_rnd_dist class

 \bug unknown
 \warning unknown
 */
namespace mbase {
class Gaussian_vec_rnd_dist: public Vec_rnd_dist {
public:
	/***   Constructors, CopyAssignment and Destructor  ***/
	Gaussian_vec_rnd_dist(Mreal mean, Mreal stdDev, Msize dim);
	Gaussian_vec_rnd_dist(Vector mean, Vector stdDev,
			Msize dim);

	Gaussian_vec_rnd_dist(const Gaussian_vec_rnd_dist & original);
	const Gaussian_vec_rnd_dist & operator=(
			const Gaussian_vec_rnd_dist & right);
	virtual ~Gaussian_vec_rnd_dist();
	/* ***  Methods              ***/
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	Vector meanVec;
	Vector stdDevVec;
};
}
#endif /* _mbase_gaussian_vec_rnd_dist_h_ */

/* File skeleton generated by GenMObj version 0.4. */
