/**\file nt_file_obj.h - NT_file_o class header
 * by Ahmed Aldo Faisal &copy; created 14.3.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt_file_obj.h,v 1.1 2001/06/11 13:18:56 face Exp $
* $Log: nt_file_obj.h,v $
* Revision 1.1  2001/06/11 13:18:56  face
* *** empty log message ***
*
* Revision 1.1  2000/05/18 10:38:32  face
* *** empty log message ***
*

*/
#ifndef _nt_file_obj_h_
#define _nt_file_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* NT includes */

/* other includes */

/** @short NT_file_o class
\bug unknown
\warning unknown
*/
class NT_file_o : public NT_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT_file_o();
    NT_file_o(const NT_file_o & original);
    const NT_file_o & operator= (const NT_file_o & right);
    virtual ~NT_file_o();
    /* ***  Methods              ***/
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
};
#endif /* _nt_file_obj_h_ */

/* File skeleton generated by GenNTObj version 0.7. */
