/**\file nt_gaussian_vec_rnd_dist_obj.cpp - NT_gaussian_vec_rnd_dist_o class implementation
 * by Ahmed Aldo Faisal &copy; created 26.6.1999
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: nt_gaussian_vec_rnd_dist_obj.cpp,v 1.1 2001/06/11 13:18:56 face Exp $
 * $Log: nt_gaussian_vec_rnd_dist_obj.cpp,v $
 * Revision 1.1  2001/06/11 13:18:56  face
 * *** empty log message ***
 *
 * Revision 1.4  2000/05/11 11:32:46  face
 * upgrade to NetTrader Version 0.5.
 * Common state of all files checkin (Versioon 0.5)
 * rearranged color and material classes...
 * texture class added
 *
 * Revision 1.3  1999/07/03 16:26:20  face
 * edited and added new nt_error_o class:
 * nt_dimension_error_o
 * to report dimension mismatches between (e.g.NT_VECTOR_O)
 * bjects
 *
 * Revision 1.2  1999/07/03 15:41:41  face
 * minor updates (made compatible to recent class name changes)
 *
 * Revision 1.1.1.1  1999/07/03 15:17:20  face
 * Switching from RCS to CVS to improve
 * the handling of the new src code subdirectory
 * structure. aaf
 *
 *
 * Revision 1.1  1999/06/26 16:49:02  face
 * Initial revision
 *
 * Revision 1.3  1999/06/06 23:52:06  face
 * *** empty log message ***
 *
 * Revision 1.2  1999/05/09 09:34:15  face
 * corrected output
 *
 * Revision 1.1  1999/04/22 11:37:49  face
 * Initial revision
 *
 *
 */

#include "nt_gaussian_vec_rnd_dist_obj.h"

/* ***      CONSTRUCTORS	***/
/** Create a NT_gaussian_vec_rnd_dist_o */
NT_gaussian_vec_rnd_dist_o::NT_gaussian_vec_rnd_dist_o(NTreal newMean,
		NTreal newStdDev, NTsize newDim) :
		NT_vec_rnd_dist_o(newDim), meanVec(newDim), stdDevVec(newDim) {
	NT_gaussian_rnd_dist_o * tmpPtr = new NT_gaussian_rnd_dist_o(newMean,
			newStdDev);

	NTsize ll;
	for (ll = 0; ll < dim; ll++) {
		meanVec[ll] = newMean;
		stdDevVec[ll] = newStdDev;
		rndDistPtrVec[ll] = tmpPtr;
	}
}

NT_gaussian_vec_rnd_dist_o::NT_gaussian_vec_rnd_dist_o(NT_vector_o newMean,
		NT_vector_o newStdDev, NTsize newDim) :
		NT_vec_rnd_dist_o(newDim), meanVec(newDim), stdDevVec(newDim) {
	NT_ASSERT_DIM(newMean._dimension(), dim);
	NT_ASSERT_DIM(newStdDev._dimension(), dim);
	meanVec = newMean;
	stdDevVec = newStdDev;

	NTsize ll;
	for (ll = 0; ll < dim; ll++) {
		rndDistPtrVec[ll] = new NT_gaussian_rnd_dist_o(newMean[ll],
				newStdDev[ll]);
	}
}

/* ***      COPY AND ASSIGNMENT	***/
NT_gaussian_vec_rnd_dist_o::NT_gaussian_vec_rnd_dist_o(
		const NT_gaussian_vec_rnd_dist_o __attribute__((unused)) & original) :
		NT_vec_rnd_dist_o(original.dim), meanVec(original.dim), stdDevVec(
				original.dim) {
	NT_ASSERT_DIM(original.meanVec._dimension(), dim);
	NT_ASSERT_DIM(original.stdDevVec._dimension(), dim);
	meanVec = original.meanVec;
	stdDevVec = original.stdDevVec;

	NTsize ll;
	for (ll = 0; ll < dim; ll++) {
		rndDistPtrVec[ll] = new NT_gaussian_rnd_dist_o(original.meanVec[ll],
				original.stdDevVec[ll]);
	}

}

const NT_gaussian_vec_rnd_dist_o&
NT_gaussian_vec_rnd_dist_o::operator=(
		const NT_gaussian_vec_rnd_dist_o & right) {
	if (this == &right)
		return *this; // Gracefully handle self assignment
	// add assignment code here
	return *this;
}

/* ***      DESTRUCTOR		***/
NT_gaussian_vec_rnd_dist_o::~NT_gaussian_vec_rnd_dist_o() {
}

/* ***  PUBLIC                                    ***   */
/** @short
 @param      none
 @return     none
 \warning    unknown
 \bug        unknown
 *//*
 void
 NT_gaussian_vec_rnd_dist_o::() const
 {
 }
 */
/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */

/* File skeleton generated by GenNTObj version 0.4. */
