/**\file nt_histogram_obj.h - NT_histogram_o class header
 * by Ahmed Aldo Faisal &copy; created 11.10.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt_histogram_obj.h,v 1.1 2001/06/11 13:18:56 face Exp $
* $Log: nt_histogram_obj.h,v $
* Revision 1.1  2001/06/11 13:18:56  face
* *** empty log message ***
*
* Revision 1.1  2000/10/15 19:22:58  face
* *** empty log message ***
*

*/
#ifndef _nt_histogram_obj_h_
#define _nt_histogram_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* NT includes */
#include "nt_error_obj.h"

/* other includes */
#include <vector>
#include <cmath>
#include <iostream>

typedef vector <NTsize> NT_HistogramBins;

/** @short NT_histogram_o class
\bug unknown
\warning unknown
*/
class NT_histogram_o : public NT_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT_histogram_o(NTreal minVal=0, NTreal maxVal=1, NTsize numberOfBins=10);
    NT_histogram_o(const NT_histogram_o & original);
    const NT_histogram_o & operator= (const NT_histogram_o & right);
    virtual ~NT_histogram_o();
    /* ***  Methods              ***/
    void Reset();
    void BinValue(NTreal value);
    void Show(bool showHeader = false) const;
    vector <NTreal> PDF() const;
    /* in bits */
    NTreal ShannonEntropy() const;

    friend ostream& operator<< (ostream& str, const NT_histogram_o & self);
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    NT_HistogramBins bins;
    NTreal min;
    NTreal max;
    NTreal numBins;
    NTreal binWidth;
    NTreal numDataPoints;
    NTsize numOutliers;
};
#endif /* _nt_histogram_obj_h_ */


/* File skeleton generated by GenNTObj version 0.7. */
