/**\file nt_multidim_histogram_obj.h - NT_multidim_histogram_o class header
 * by Ahmed Aldo Faisal &copy; created 29.6.2001
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt_multidim_histogram_obj.h,v 1.3 2001/10/12 09:18:39 face Exp $
* $Log: nt_multidim_histogram_obj.h,v $
* Revision 1.3  2001/10/12 09:18:39  face
* *** empty log message ***
*
* Revision 1.2  2001/10/03 14:37:13  face
* *** empty log message ***
*

*/
#ifndef _nt_multidim_histogram_obj_h_
#define _nt_multidim_histogram_obj_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* NT includes */
#include "nt_multidim_array_obj.h"
#include "nt_aux_math_func.h"
/* other includes */

/** @short NT_multidim_histogram_o class
\bug unknown
\warning unknown
*/
class NT_multidim_histogram_o : public NT_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT_multidim_histogram_o(NTreal low, NTreal high, NTsize binsPerDim, NTsize dims);
    NT_multidim_histogram_o(const NT_multidim_histogram_o & original);
    const NT_multidim_histogram_o & operator= (const NT_multidim_histogram_o & right);
    virtual ~NT_multidim_histogram_o();
    /* ***  Methods              ***/
    /** Enter data into histogram with data $\in [min,max] $*/
    NTsize BinValue( const vector <NTreal>  & valueVec);
    /** No descriptions */
    NTreal ShannonEntropy() const;
    /**  Set histogram to initial values */
    void Reset();
    NTsize _numBinned() const {
        return numBinned;
    }
    NTreal _min() const {
        return min;
    }
    NTreal _max() const {
        return max;
    }
    NTreal _range() const {
        return range;
    }
    NTreal _numBinPerDim() const {
        return numBins;
    }
    NTreal _dim() const {
        return dim;
    }
    vector <NTsize> _outsideBinVec() const {
        return outsideBinVec;
    }
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    NT_multidim_array_o<NTsize> oCube;
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    NTsize numBinned;
    vector <NTsize> outsideBinVec;
    NTreal min;
    NTreal max;
    NTreal range;
    NTsize numBins;
    NTsize dim;
    /* ***  Data                 ***/
};
#endif /* _nt_multidim_histogram_obj_h_ */


/* File skeleton generated by GenNTObj version 0.7. */
