/**\file nt_str2real_obj.h - NT_str2real_o class header 
 * by Ahmed Aldo Faisal &copy; created 3.7.1999  
 * code is originally based on Chameleon.h by René Nyffenegger
 * see http://www.adp-gmbh.ch/cpp/chameleon.html
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998-20005 Ahmed Aldo Faisal    
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */ 
  

/* $Id: nt_str2real_obj.h,v 1.1 2005/04/25 13:55:32 face Exp $ 
* $Log: nt_str2real_obj.h,v $
* Revision 1.1  2005/04/25 13:55:32  face
* *** empty log message ***
*

*/
#ifndef _nt_str2real_obj_h_ 
#define _nt_str2real_obj_h_ 

/* NT core includes */
#include "nt_main.h" 
#include "nt_types.h" 
#include "nt_obj.h"  
/* NT includes */

/* other includes */
#include <string>
#include <sstream>

/** @short NT_str2real_o class 
    A class that can can act as a number and a string
\bug unknown
\warning unknown 
*/
class NT_str2real_o : public NT_o {
public:
/***   Constructors, Copy/Assignment and Destructor  ***/  
  NT_str2real_o() {};
  NT_str2real_o(const std::string&);
  NT_str2real_o(double);
  NT_str2real_o(const char*);

  NT_str2real_o(const NT_str2real_o&);
  NT_str2real_o& operator=(NT_str2real_o const&);

  NT_str2real_o& operator=(double);
  NT_str2real_o& operator=(std::string const&);
  virtual ~NT_str2real_o();

/* ***  Methods              ***/  
  operator std::string() const;
  operator double     () const;
private:
/* ***  Data                 ***/  
  std::string value_;
};


#endif /* _nt_str2real_obj_h_ */ 

/* File skeleton generated by GenNTObj version 0.7. */
