/**\file nt3d_universe_vp_obj.h - NT3D_universe_vp_o class header
 * by Ahmed Aldo Faisal &copy; created 13.5.1999
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.3
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

/* $Id: nt3d_universe_vp_obj.h,v 1.1 2001/06/29 13:16:55 face Exp $
 * $Log: nt3d_universe_vp_obj.h,v $
 * Revision 1.1  2001/06/29 13:16:55  face
 * *** empty log message ***
 *
 * Revision 1.4  2000/10/03 08:29:59  face
 * *** empty log message ***
 *
 * Revision 1.3  2000/04/26 17:10:34  face
 * minor bug fixed
 * and upgrades:
 *
 * Revision 1.2  1999/07/17 18:22:10  face
 * imodified
 *
 * Revision 1.1.1.1  1999/07/03 15:17:20  face
 * Switching from RCS to CVS to improve
 * the handling of the new src code subdirectory
 * structure. aaf
 *
 *
 * Revision 1.2  1999/06/26 16:49:02  face
 * *** empty log message ***
 *
 * Revision 1.1  1999/06/06 23:51:28  face
 * Initial revision
 *
 * Revision 1.2  1999/05/09 09:34:15  face
 * corrected output
 *{
 * Revision 1.1  1999/04/22 11:37:49  face
 * Initial revision
 *
*/
#ifndef _nt3d_universe_vp_h_
#define _nt3d_universe_vp_h_


#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"

#include "nt3d_abstract_vp_obj.h"

#include "nt3d_universe_obj.h"

/** @short NT3D_universe_vp_o class

\bug unknown
\warning unknown
 */
class NT3D_universe_vp_o : public NT3D_abstract_vp_o {
public:
    /***   Constructors, CopyAssignment and Destructor  ***/
    NT3D_universe_vp_o();
    NT3D_universe_vp_o(NT3D_universe_o * pNewUniverse);
    NT3D_universe_vp_o(const NT3D_universe_vp_o & original);
    const NT3D_universe_vp_o & operator= (const NT3D_universe_vp_o & right);
    virtual ~NT3D_universe_vp_o();
    /* ***  Methods              ***/
    void Draw();
    void DrawUniverse() {
        pUniverse->Draw();
    }
    virtual void DrawChild() = 0;
    NTreturn SetUniverse(NT3D_universe_o * pNewUniverse);
    NTbool HasUniverse() {
        return haveUniverse;
    }
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
    NTbool haveUniverse;
    NT3D_universe_o * pUniverse;
};
#endif /* _nt3d_universe_vp_h_ */

/* File skeleton generated by GenNTObj version 0.4. */
