/**\file nt3d_universe_obj.h - NT3D_universe_o class header
 * by Ahmed Aldo Faisal &copy; created 19.7.1999
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.4
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */


/* $Id: nt3d_universe_obj.h,v 1.1 2001/06/29 13:16:55 face Exp $
* $Log: nt3d_universe_obj.h,v $
* Revision 1.1  2001/06/29 13:16:55  face
* *** empty log message ***
*
* Revision 1.5  2000/06/13 20:10:26  face
* *** empty log message ***
*
* Revision 1.4  2000/04/26 17:10:34  face
* minor bug fixed
* and upgrades:
*
* Revision 1.3  1999/07/20 01:15:09  face
* general debugging and clean up
*

*/
#ifndef _nt3d_universe_h_
#define _nt3d_universe_h_

/* NT core includes */
#include "nt_main.h"
#include "nt_types.h"
#include "nt_obj.h"
/* Parent includes */
#include "nt3d_obj.h"

/* NT includes */
#include "nt3d_stub_obj.h"
#include "nt3d_ambient_light_obj.h"
/* other includes */

/** @short NT3D_universe_o class
\bug unknown
\warning unknown
*/
class NT3D_universe_o : public NT3D_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NT3D_universe_o();
    NT3D_universe_o(const NT3D_universe_o & original);
    const NT3D_universe_o & operator= (const NT3D_universe_o & right);
    virtual ~NT3D_universe_o();
    /* ***  Methods              ***/
    void Draw();
    void AddChild( NT3D_hierarchic_object_o * pNewChild );
    /*   Data                   */
protected:
    /*   Methods                */
    /*   Data                   */
private:
    /*   Methods                */
    /*   Data                   */
    NT3D_ambient_light_o ambientLight;
    NT3D_stub_o universe;
};

#endif /* _nt3d_universe_h_ */

/* File skeleton generated by GenNTObj version 0.6. */
