/**\file Id_management.h - Id_management class header
 * by Ahmed Aldo Faisal &copy; created 3.7.1999
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.4
 * Copyright (C) 1998,199 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _mbase_id_management_h_
#define _mbase_id_management_h_

#include "Obj.h"
#include "Error.h"

#include <list>
#include <vector>
#include <algorithm>

namespace mbase {

/** @short Id_management class
 Manage a contiguous list of IDs which might be
 used or freed at any time.
 \bug unknown
 \warning unknown
 */
class Id_management: public Obj {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	/** Lowest and highest valid id */
	Id_management(Mid smallestId, Mid largestId);
	Id_management(const Id_management & original);
	const Id_management & operator=(const Id_management & right);
	virtual ~Id_management();
	/* ***  Methods              ***/
	Mbool IsTaken(Mid id) const;
	Mid LargestIssuedId();
	Mid IssueId();
	Mreturn FreeId(Mid returnedId);
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	Mid lowestId;
	Mid highestId;
	Mlong range;
	std::vector<Mid> usedIdList;
};
}
#endif /* _mbase_id_management_h_ */

/* File skeleton generated by GenMObj version 0.5. */
