.TH "fcscmat.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcscmat.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'tnt/tnt.h'\fP
.br
\fC#include 'tnt/vec.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTNT::Fortran_Sparse_Col_Matrix< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > ostream & \fBTNT::operator<<\fP (ostream &s, const Fortran_Sparse_Col_Matrix< T > &A)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
