.TH "fortran.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fortran.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTNT_SUBSCRIPT_TYPE\fP   \fBTNT::Fortran_integer\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBFortran_integer\fP"
.br
.ti -1c
.RI "typedef float \fBFortran_float\fP"
.br
.ti -1c
.RI "typedef double \fBFortran_double\fP"
.br
.ti -1c
.RI "typedef \fBFortran_double\fP * \fBfda_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_double\fP * \fBcfda_\fP"
.br
.ti -1c
.RI "typedef \fBFortran_double\fP * \fBfd_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_double\fP * \fBcfd_\fP"
.br
.ti -1c
.RI "typedef \fBFortran_float\fP * \fBffa_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_float\fP * \fBcffa_\fP"
.br
.ti -1c
.RI "typedef \fBFortran_float\fP * \fBff_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_float\fP * \fBcff_\fP"
.br
.ti -1c
.RI "typedef \fBFortran_integer\fP * \fBfia_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_integer\fP * \fBcfia_\fP"
.br
.ti -1c
.RI "typedef \fBFortran_integer\fP * \fBfi_\fP"
.br
.ti -1c
.RI "typedef const \fBFortran_integer\fP * \fBcfi_\fP"
.br
.ti -1c
.RI "typedef char * \fBfch_\fP"
.br
.ti -1c
.RI "typedef char * \fBcfch_\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TNT_SUBSCRIPT_TYPE   \fBTNT::Fortran_integer\fP"
.PP
Definition at line 62 of file fortran.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef char* \fBcfch_\fP"
.PP
Definition at line 57 of file fortran.h.
.SS "typedef const \fBFortran_double\fP* \fBcfd_\fP"
.PP
Definition at line 42 of file fortran.h.
.SS "typedef const \fBFortran_double\fP* \fBcfda_\fP"
.PP
Definition at line 39 of file fortran.h.
.SS "typedef const \fBFortran_float\fP* \fBcff_\fP"
.PP
Definition at line 48 of file fortran.h.
.SS "typedef const \fBFortran_float\fP* \fBcffa_\fP"
.PP
Definition at line 45 of file fortran.h.
.SS "typedef const \fBFortran_integer\fP* \fBcfi_\fP"
.PP
Definition at line 54 of file fortran.h.
.SS "typedef const \fBFortran_integer\fP* \fBcfia_\fP"
.PP
Definition at line 51 of file fortran.h.
.SS "typedef char* \fBfch_\fP"
.PP
Definition at line 56 of file fortran.h.
.SS "typedef \fBFortran_double\fP* \fBfd_\fP"
.PP
Definition at line 41 of file fortran.h.
.SS "typedef \fBFortran_double\fP* \fBfda_\fP"
.PP
Definition at line 38 of file fortran.h.
.SS "typedef \fBFortran_float\fP* \fBff_\fP"
.PP
Definition at line 47 of file fortran.h.
.SS "typedef \fBFortran_float\fP* \fBffa_\fP"
.PP
Definition at line 44 of file fortran.h.
.SS "typedef \fBFortran_integer\fP* \fBfi_\fP"
.PP
Definition at line 53 of file fortran.h.
.SS "typedef \fBFortran_integer\fP* \fBfia_\fP"
.PP
Definition at line 50 of file fortran.h.
.SS "typedef double \fBFortran_double\fP"
.PP
Definition at line 35 of file fortran.h.
.SS "typedef float \fBFortran_float\fP"
.PP
Definition at line 34 of file fortran.h.
.SS "typedef int \fBFortran_integer\fP"
.PP
Definition at line 33 of file fortran.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
