.TH "index.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
index.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tnt/subscript.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTNT::Index1D\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Index1D \fBTNT::operator+\fP (const Index1D &D, Subscript i)"
.br
.ti -1c
.RI "Index1D \fBTNT::operator+\fP (Subscript i, const Index1D &D)"
.br
.ti -1c
.RI "Index1D \fBTNT::operator-\fP (Index1D &D, Subscript i)"
.br
.ti -1c
.RI "Index1D \fBTNT::operator-\fP (Subscript i, Index1D &D)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
