.TH "ModiglianiFormatSkipGrammar_t" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModiglianiFormatSkipGrammar_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modigliani_model_format_grammar_t.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdefinition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 128 of file modigliani_model_format_grammar_t.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
