.TH "NT3D_demo_glut_drv_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_demo_glut_drv_o \- 
.PP
\fBNT3D_demo_glut_drv_o\fP class Simple demonstration of how to use the vp_glut_drv object.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_demo_glut_drv_obj.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_demo_glut_drv_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_demo_glut_drv_o\fP (const \fBNT3D_demo_glut_drv_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_demo_glut_drv_o\fP & \fBoperator=\fP (const \fBNT3D_demo_glut_drv_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_demo_glut_drv_o\fP ()"
.br
.ti -1c
.RI "void \fBCallBackDisplayFunc\fP (void)"
.br
.ti -1c
.RI "void \fBInit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 67 of file nt3d_demo_glut_drv_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_demo_glut_drv_o::NT3D_demo_glut_drv_o ()"
.SS "NT3D_demo_glut_drv_o::NT3D_demo_glut_drv_o (const \fBNT3D_demo_glut_drv_o\fP & original)"
.SS "virtual NT3D_demo_glut_drv_o::~NT3D_demo_glut_drv_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_demo_glut_drv_o::CallBackDisplayFunc (void)"
.SS "void NT3D_demo_glut_drv_o::Init ()"
.SS "const \fBNT3D_demo_glut_drv_o\fP& NT3D_demo_glut_drv_o::operator= (const \fBNT3D_demo_glut_drv_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
