.TH "NT3D_ambient_light_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_ambient_light_o \- 
.PP
\fBNT3D_ambient_light_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_ambient_light_obj.h>\fP
.PP
Inherits \fBNT3D_light_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_ambient_light_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_ambient_light_o\fP (const \fBNT3D_ambient_light_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_ambient_light_o\fP & \fBoperator=\fP (const \fBNT3D_ambient_light_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_ambient_light_o\fP ()"
.br
.ti -1c
.RI "void \fBIlluminateLight\fP ()"
.br
.RI "\fIDerive to implement lights. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 62 of file nt3d_ambient_light_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_ambient_light_o::NT3D_ambient_light_o ()"
.SS "NT3D_ambient_light_o::NT3D_ambient_light_o (const \fBNT3D_ambient_light_o\fP & original)"
.SS "virtual NT3D_ambient_light_o::~NT3D_ambient_light_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_ambient_light_o::IlluminateLight ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_light_o\fP.
.SS "const \fBNT3D_ambient_light_o\fP& NT3D_ambient_light_o::operator= (const \fBNT3D_ambient_light_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
