.TH "nt3d_line_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_line_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT3D_line_o\fP class declaration by Ahmed Aldo Faisal (C) created 15.10.1998 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt3d_hierarchic_object_obj.h'\fP
.br
\fC#include 'nt3d_material_obj.h'\fP
.br
\fC#include 'nt_vector3_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_line_o\fP"
.br
.RI "\fI\fBNT3D_line_o\fP class Line representation between to arbitraty positions in space. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt3d_line_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
