.TH "nt3d_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT3D_o\fP class declaration by Ahmed Aldo Faisal (C) created 15.10.1998 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include <GL/gl.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_o\fP"
.br
.RI "\fI\fBNT3D_o\fP class The superclass for the NT3D graphic visualisation classes. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBNT3D_MAX_LIGHTS\fP   GL_MAX_LIGHTS"
.br
.ti -1c
.RI "#define \fBNT3D_MAX_TEXTURES\fP   16"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt3d_obj.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define NT3D_MAX_LIGHTS   GL_MAX_LIGHTS"
.PP
Definition at line 77 of file nt3d_obj.h.
.SS "#define NT3D_MAX_TEXTURES   16"
.PP
Definition at line 78 of file nt3d_obj.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
