.TH "NT3D_rectangle_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_rectangle_o \- 
.PP
\fBNT3D_rectangle_o\fP class Draws an recangular area composed of steps^2 rectanlges which lies flat in the X-Y-plane (width-height) with the lower left corner in the origin.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_rectangle_obj.h>\fP
.PP
Inherits \fBNT3D_surfaced_object_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_rectangle_o\fP (\fBNTreal\fP width=1.0, \fBNTreal\fP height=1.0, \fBNTsize\fP steps=2)"
.br
.ti -1c
.RI "\fBNT3D_rectangle_o\fP (const \fBNT3D_rectangle_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_rectangle_o\fP & \fBoperator=\fP (const \fBNT3D_rectangle_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_rectangle_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 60 of file nt3d_rectangle_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_rectangle_o::NT3D_rectangle_o (\fBNTreal\fP width = \fC1.0\fP, \fBNTreal\fP height = \fC1.0\fP, \fBNTsize\fP steps = \fC2\fP)"
.SS "NT3D_rectangle_o::NT3D_rectangle_o (const \fBNT3D_rectangle_o\fP & original)"
.SS "virtual NT3D_rectangle_o::~NT3D_rectangle_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT3D_rectangle_o\fP& NT3D_rectangle_o::operator= (const \fBNT3D_rectangle_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
