.TH "NT3D_composite_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_composite_o \- 
.PP
\fBNT3D_composite_o\fP class template2.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_composite_obj.h>\fP
.PP
Inherits \fBNT3D_hierarchic_object_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_composite_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_composite_o\fP (const \fBNT3D_composite_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_composite_o\fP & \fBoperator=\fP (const \fBNT3D_composite_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_composite_o\fP ()"
.br
.ti -1c
.RI "void \fBDrawObj\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBControlObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)"
.br
.RI "\fIControlObj is to overwritten by derived classes to handle controller calls. \fP"
.ti -1c
.RI "void \fBControlObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNTreal\fP value)"
.br
.ti -1c
.RI "void \fBControlObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNT_vector_o\fP value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 64 of file nt3d_composite_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_composite_o::NT3D_composite_o ()"
.SS "NT3D_composite_o::NT3D_composite_o (const \fBNT3D_composite_o\fP & original)"
.SS "virtual NT3D_composite_o::~NT3D_composite_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_composite_o::ControlObj (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 75 of file nt3d_composite_obj.h.
.PP
.nf
{};
.fi
.SS "void NT3D_composite_o::ControlObj (\fBNT3Dcontroller\fP cntrl, \fBNT_vector_o\fP value)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 77 of file nt3d_composite_obj.h.
.PP
.nf
{};
.fi
.SS "void NT3D_composite_o::ControlObj (\fBNT3Dcontroller\fP cntrl, \fBNTreal\fP value)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 76 of file nt3d_composite_obj.h.
.PP
.nf
{}; 
.fi
.SS "void NT3D_composite_o::DrawObj ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 71 of file nt3d_composite_obj.h.
.PP
.nf
{}
.fi
.SS "const \fBNT3D_composite_o\fP& NT3D_composite_o::operator= (const \fBNT3D_composite_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
