.TH "nt3d_drv_vp_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_drv_vp_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT3D_drv_vp_o\fP class header by Ahmed Aldo Faisal (C) created 9.5.1999 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt3d_vp_spec_obj.h'\fP
.br
\fC#include 'nt3d_vp_obj.h'\fP
.br
\fC#include 'nt3d_bitmap_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_drv_vp_o\fP"
.br
.RI "\fI\fBNT3D_drv_vp_o\fP class This viewport driver parent class provides the infrastructure for the \fBNT3D_abstract_vp_o\fP child classes which register with this class. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt3d_drv_vp_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
