.TH "NT3D_universe_cylindric_camera_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_universe_cylindric_camera_o \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_universe_cylindric_camera_obj.h>\fP
.PP
Inherits \fBNT3D_universe_camera_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_universe_cylindric_camera_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_universe_cylindric_camera_o\fP (const \fBNT3D_universe_cylindric_camera_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_universe_cylindric_camera_o\fP & \fBoperator=\fP (const \fBNT3D_universe_cylindric_camera_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_universe_cylindric_camera_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 51 of file nt3d_universe_cylindric_camera_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_universe_cylindric_camera_o::NT3D_universe_cylindric_camera_o ()"
.SS "NT3D_universe_cylindric_camera_o::NT3D_universe_cylindric_camera_o (const \fBNT3D_universe_cylindric_camera_o\fP & original)"
.SS "virtual NT3D_universe_cylindric_camera_o::~NT3D_universe_cylindric_camera_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT3D_universe_cylindric_camera_o\fP& NT3D_universe_cylindric_camera_o::operator= (const \fBNT3D_universe_cylindric_camera_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
