.TH "NT3D_ellipsoid_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_ellipsoid_o \- 
.PP
Provides a scaled GLU sphere wrapped as an object.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_ellipsoid_obj.h>\fP
.PP
Inherits \fBNT3D_solid_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_ellipsoid_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_ellipsoid_o\fP (\fBNT_vector3_o\fP oNewPosition)"
.br
.ti -1c
.RI "\fBNT3D_ellipsoid_o\fP (\fBNT_vector3_o\fP oNewPosition, \fBNT_vector3_o\fP oNewHalfAxis)"
.br
.ti -1c
.RI "\fBNT3D_ellipsoid_o\fP (const \fBNT3D_ellipsoid_o\fP &original)"
.br
.ti -1c
.RI "\fB~NT3D_ellipsoid_o\fP ()"
.br
.ti -1c
.RI "void \fBDrawSolidObj\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 86 of file nt3d_ellipsoid_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_ellipsoid_o::NT3D_ellipsoid_o ()"
.SS "NT3D_ellipsoid_o::NT3D_ellipsoid_o (\fBNT_vector3_o\fP oNewPosition)\fC [inline]\fP"
.PP
Definition at line 89 of file nt3d_ellipsoid_obj.h.
.PP
.nf
                                             :
    NT3D_solid_o(oNewPosition), oHalfAxis(1.0, 1.0, 1.0){};
.fi
.SS "NT3D_ellipsoid_o::NT3D_ellipsoid_o (\fBNT_vector3_o\fP oNewPosition, \fBNT_vector3_o\fP oNewHalfAxis)"
.SS "NT3D_ellipsoid_o::NT3D_ellipsoid_o (const \fBNT3D_ellipsoid_o\fP & original)"
.SS "NT3D_ellipsoid_o::~NT3D_ellipsoid_o ()"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_ellipsoid_o::DrawSolidObj () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNT3D_solid_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
