.TH "NT3D_vp_spec_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_vp_spec_o \- 
.PP
\fBNT3D_vp_spec_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_vp_spec_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_vp_spec_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_vp_spec_o\fP (const \fBNT3D_vp_spec_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_vp_spec_o\fP & \fBoperator=\fP (const \fBNT3D_vp_spec_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_vp_spec_o\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNTsize\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBNTsize\fP \fBheight\fP"
.br
.ti -1c
.RI "string \fBwindowName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 62 of file nt3d_vp_spec_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_vp_spec_o::NT3D_vp_spec_o ()"
.SS "NT3D_vp_spec_o::NT3D_vp_spec_o (const \fBNT3D_vp_spec_o\fP & original)"
.SS "virtual NT3D_vp_spec_o::~NT3D_vp_spec_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT3D_vp_spec_o\fP& NT3D_vp_spec_o::operator= (const \fBNT3D_vp_spec_o\fP & right)"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTsize\fP \fBNT3D_vp_spec_o::height\fP"
.PP
Definition at line 72 of file nt3d_vp_spec_obj.h.
.SS "\fBNTsize\fP \fBNT3D_vp_spec_o::width\fP"
.PP
Definition at line 71 of file nt3d_vp_spec_obj.h.
.SS "string \fBNT3D_vp_spec_o::windowName\fP"
.PP
Definition at line 73 of file nt3d_vp_spec_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
