.TH "nt3d_hierarchic_object_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_hierarchic_object_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_vector_obj.h'\fP
.br
\fC#include 'nt_vector3_obj.h'\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'nt3d_obj.h'\fP
.br
\fC#include 'nt3d_object_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_hierarchic_object_o\fP"
.br
.RI "\fINetTrader 3D object visualisation superclass. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef deque< \fBNT3D_hierarchic_object_o\fP * > \fBNT3D_ChildrenQue\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef deque<\fBNT3D_hierarchic_object_o\fP *> \fBNT3D_ChildrenQue\fP"
.PP
Definition at line 110 of file nt3d_hierarchic_object_obj.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
