.TH "NT3D_color_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_color_o \- 
.PP
THe \fBNT3D_color_o\fP class handles the abstract color concept.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_color_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_color_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP (const valarray< GLfloat > &newColorRGBA)"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP (const \fBNT3D_color_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_color_o\fP & \fBoperator=\fP (const \fBNT3D_color_o\fP &right)"
.br
.ti -1c
.RI "\fB~NT3D_color_o\fP ()"
.br
.ti -1c
.RI "virtual void \fBPaint\fP () const "
.br
.ti -1c
.RI "void \fBSetColor\fP (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)"
.br
.ti -1c
.RI "void \fBSetColor\fP (const GLfloat newColor[])"
.br
.ti -1c
.RI "void \fBSetColor\fP (const \fBNT3D_color_o\fP &newColor)"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_R\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_G\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_B\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_Alpha\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP \fBoperator+\fP (const \fBNT3D_color_o\fP &right) const "
.br
.ti -1c
.RI "\fBNT3D_color_o\fP \fBoperator-\fP (const \fBNT3D_color_o\fP &right) const "
.br
.ti -1c
.RI "\fBNT3D_color_o\fP \fBoperator*\fP (\fBNTreal\fP alpha) const "
.br
.ti -1c
.RI "const GLfloat * \fB_colorPtr\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWarning:\fP
.RS 4
Once its derived classes are called in the drawing tree they affected ALL subsequent drawing (Modifies OpenGL state). 
.RE
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 81 of file nt3d_color_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_color_o::NT3D_color_o ()"
.SS "NT3D_color_o::NT3D_color_o (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)"
.SS "NT3D_color_o::NT3D_color_o (const valarray< GLfloat > & newColorRGBA)"
.SS "NT3D_color_o::NT3D_color_o (const \fBNT3D_color_o\fP & original)"
.SS "NT3D_color_o::~NT3D_color_o ()"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NT3D_color_o::_Alpha ()\fC [inline]\fP"
.PP
Definition at line 98 of file nt3d_color_obj.h.
.PP
.nf
{ return colorRGBA[3];}
.fi
.SS "\fBNTreal\fP NT3D_color_o::_B ()\fC [inline]\fP"
.PP
Definition at line 97 of file nt3d_color_obj.h.
.PP
.nf
{ return colorRGBA[2];}
.fi
.SS "const GLfloat* NT3D_color_o::_colorPtr ()\fC [inline]\fP"
.PP
Definition at line 103 of file nt3d_color_obj.h.
.PP
Referenced by NT3D_light_o::IlluminateAmbient(), NT3D_light_o::IlluminateDiffuse(), and NT3D_light_o::IlluminateSpecular().
.PP
.nf
{Update(); return (const GLfloat*) colorPtr;}
.fi
.SS "\fBNTreal\fP NT3D_color_o::_G ()\fC [inline]\fP"
.PP
Definition at line 96 of file nt3d_color_obj.h.
.PP
.nf
{ return colorRGBA[1];}
.fi
.SS "\fBNTreal\fP NT3D_color_o::_R ()\fC [inline]\fP"
.PP
Definition at line 95 of file nt3d_color_obj.h.
.PP
.nf
{ return colorRGBA[0];}
.fi
.SS "\fBNT3D_color_o\fP NT3D_color_o::operator* (\fBNTreal\fP alpha) const"
.SS "\fBNT3D_color_o\fP NT3D_color_o::operator+ (const \fBNT3D_color_o\fP & right) const"
.SS "\fBNT3D_color_o\fP NT3D_color_o::operator- (const \fBNT3D_color_o\fP & right) const"
.SS "const \fBNT3D_color_o\fP& NT3D_color_o::operator= (const \fBNT3D_color_o\fP & right)"
.SS "virtual void NT3D_color_o::Paint () const\fC [inline, virtual]\fP"
.PP
Definition at line 91 of file nt3d_color_obj.h.
.PP
.nf
{ glColor4fv(colorPtr);}
.fi
.SS "void NT3D_color_o::SetColor (const GLfloat newColor[])"
.SS "void NT3D_color_o::SetColor (GLfloat newR, GLfloat newG, GLfloat newB, GLfloat newAlpha)"
.SS "void NT3D_color_o::SetColor (const \fBNT3D_color_o\fP & newColor)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
