.TH "NT3D_universe_camera_vp_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_universe_camera_vp_o \- 
.PP
\fBNT3D_universe_camera_vp_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_universe_camera_vp_obj.h>\fP
.PP
Inherits \fBNT3D_camera_vp_o\fP.
.PP
Inherited by \fBNT3D_universe_cylindric_camera_o\fP, and \fBNT3D_universe_spheric_camera_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_universe_camera_vp_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_universe_camera_vp_o\fP (\fBNT3D_universe_o\fP *pNewUniverse)"
.br
.ti -1c
.RI "\fBNT3D_universe_camera_vp_o\fP (\fBNT3D_camera_o\fP *pNewCamera)"
.br
.ti -1c
.RI "\fBNT3D_universe_camera_vp_o\fP (const \fBNT3D_universe_camera_vp_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_universe_camera_vp_o\fP & \fBoperator=\fP (const \fBNT3D_universe_camera_vp_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_universe_camera_vp_o\fP ()"
.br
.ti -1c
.RI "void \fBDrawScene\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBAddUniverse\fP (\fBNT3D_universe_o\fP *pNewUniverse)"
.br
.ti -1c
.RI "\fBNTbool\fP \fBHasUniverse\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
The universe pointer is not deleted by the destructor ! 
.RE
.PP

.PP
Definition at line 60 of file nt3d_universe_camera_vp_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_universe_camera_vp_o::NT3D_universe_camera_vp_o ()"
.SS "NT3D_universe_camera_vp_o::NT3D_universe_camera_vp_o (\fBNT3D_universe_o\fP * pNewUniverse)"
.SS "NT3D_universe_camera_vp_o::NT3D_universe_camera_vp_o (\fBNT3D_camera_o\fP * pNewCamera)"
.SS "NT3D_universe_camera_vp_o::NT3D_universe_camera_vp_o (const \fBNT3D_universe_camera_vp_o\fP & original)"
.SS "virtual NT3D_universe_camera_vp_o::~NT3D_universe_camera_vp_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreturn\fP NT3D_universe_camera_vp_o::AddUniverse (\fBNT3D_universe_o\fP * pNewUniverse)"
.SS "void NT3D_universe_camera_vp_o::DrawScene ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_camera_vp_o\fP.
.SS "\fBNTbool\fP NT3D_universe_camera_vp_o::HasUniverse ()\fC [inline]\fP"
.PP
Definition at line 62 of file nt3d_universe_camera_vp_obj.h.
.PP
.nf
{return haveUniverse;}
.fi
.SS "const \fBNT3D_universe_camera_vp_o\fP& NT3D_universe_camera_vp_o::operator= (const \fBNT3D_universe_camera_vp_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
