.TH "NT3D_image_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_image_o \- 
.PP
\fBNT3D_image_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_image_obj.h>\fP
.PP
Inherits \fBNT_image_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_image_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_image_o\fP (const \fBNT3D_image_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_image_o\fP & \fBoperator=\fP (const \fBNT3D_image_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_image_o\fP ()"
.br
.ti -1c
.RI "GLfloat * \fBRGBImagePtr\fP () const "
.br
.ti -1c
.RI "GLfloat * \fBRGBAImagePtr\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 56 of file nt3d_image_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_image_o::NT3D_image_o ()"
.SS "NT3D_image_o::NT3D_image_o (const \fBNT3D_image_o\fP & original)"
.SS "virtual NT3D_image_o::~NT3D_image_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT3D_image_o\fP& NT3D_image_o::operator= (const \fBNT3D_image_o\fP & right)"
.SS "GLfloat* NT3D_image_o::RGBAImagePtr () const"
.SS "GLfloat* NT3D_image_o::RGBImagePtr () const"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
