.TH "nt3d_object_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_object_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_vector_obj.h'\fP
.br
\fC#include 'nt_vector3_obj.h'\fP
.br
\fC#include <deque>\fP
.br
\fC#include 'nt3d_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_object_o\fP"
.br
.RI "\fINT3D object class. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNT3Dcontroller\fP { \fBNT3D_DrawStyle\fP =  1000, \fBNT3D_Slices\fP, \fBNT3D_Stacks\fP, \fBNT3D_Texture\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNT3Dcontroller\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fINT3D_DrawStyle \fP\fP
.TP
\fB\fINT3D_Slices \fP\fP
.TP
\fB\fINT3D_Stacks \fP\fP
.TP
\fB\fINT3D_Texture \fP\fP

.PP
Definition at line 132 of file nt3d_object_obj.h.
.PP
.nf
                    { NT3D_DrawStyle = 1000, 
                NT3D_Slices, 
                NT3D_Stacks,
                NT3D_Texture
            } ;
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
