.TH "NT3D_material_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_material_o \- 
.PP
\fBNT3D_material_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_material_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_material_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_material_o\fP (const \fBNT3D_material_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_material_o\fP & \fBoperator=\fP (const \fBNT3D_material_o\fP &right)"
.br
.ti -1c
.RI "\fB~NT3D_material_o\fP ()"
.br
.ti -1c
.RI "void \fBPaint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 67 of file nt3d_material_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_material_o::NT3D_material_o ()"
.SS "NT3D_material_o::NT3D_material_o (const \fBNT3D_material_o\fP & original)"
.SS "NT3D_material_o::~NT3D_material_o ()"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT3D_material_o\fP& NT3D_material_o::operator= (const \fBNT3D_material_o\fP & right)"
.SS "void NT3D_material_o::Paint ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
