.TH "NT3D_lamp_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_lamp_o \- 
.PP
\fBNT3D_lamp_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_lamp_obj.h>\fP
.PP
Inherits \fBNT3D_light_o\fP, and \fBNT3D_hierarchic_object_o\fP.
.PP
Inherited by \fBNT3D_ambient_lamp_o\fP, \fBNT3D_position_lamp_o\fP, and \fBNT3D_spot_lamp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_lamp_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_lamp_o\fP (const \fBNT3D_lamp_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_lamp_o\fP & \fBoperator=\fP (const \fBNT3D_lamp_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_lamp_o\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBIlluminateLight\fP ()"
.br
.RI "\fIDo not override, use DrawLamp instead. \fP"
.ti -1c
.RI "virtual void \fBIlluminateLamp\fP ()=0"
.br
.RI "\fIDerive to implement lamps. \fP"
.ti -1c
.RI "void \fBDrawObj\fP ()"
.br
.ti -1c
.RI "void \fBControlObj\fP (enum \fBNT3Dcontroller\fP, \fBNTint\fP)"
.br
.ti -1c
.RI "void \fBControlObj\fP (enum \fBNT3Dcontroller\fP, \fBNTreal\fP)"
.br
.ti -1c
.RI "void \fBControlObj\fP (enum \fBNT3Dcontroller\fP, class \fBNT_vector_o\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTfloat\fP \fBwFactor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 69 of file nt3d_lamp_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_lamp_o::NT3D_lamp_o ()"
.SS "NT3D_lamp_o::NT3D_lamp_o (const \fBNT3D_lamp_o\fP & original)"
.SS "virtual NT3D_lamp_o::~NT3D_lamp_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_lamp_o::ControlObj (enum NT3Dcontroller, \fBNTint\fP)\fC [inline, protected]\fP"
.PP
Definition at line 87 of file nt3d_lamp_obj.h.
.PP
.nf
{}; 
.fi
.SS "void NT3D_lamp_o::ControlObj (enum NT3Dcontroller, class \fBNT_vector_o\fP)\fC [inline, protected]\fP"
.PP
Definition at line 89 of file nt3d_lamp_obj.h.
.PP
.nf
{};
.fi
.SS "void NT3D_lamp_o::ControlObj (enum NT3Dcontroller, \fBNTreal\fP)\fC [inline, protected]\fP"
.PP
Definition at line 88 of file nt3d_lamp_obj.h.
.PP
.nf
{};
.fi
.SS "void NT3D_lamp_o::DrawObj ()\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 86 of file nt3d_lamp_obj.h.
.PP
References NT3D_light_o::Illuminate().
.PP
.nf
{Illuminate();}
.fi
.SS "virtual void NT3D_lamp_o::IlluminateLamp ()\fC [protected, pure virtual]\fP"
.PP
Implemented in \fBNT3D_position_lamp_o\fP, and \fBNT3D_spot_lamp_o\fP.
.SS "void NT3D_lamp_o::IlluminateLight ()\fC [protected]\fP"
.SS "const \fBNT3D_lamp_o\fP& NT3D_lamp_o::operator= (const \fBNT3D_lamp_o\fP & right)"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTfloat\fP \fBNT3D_lamp_o::wFactor\fP\fC [protected]\fP"
.PP
Definition at line 89 of file nt3d_lamp_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
