.TH "NT3D_solid_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_solid_o \- 
.PP
\fBNT3D_solid_o\fP class ...  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_solid_obj.h>\fP
.PP
Inherits \fBNT3D_surfaced_object_o\fP.
.PP
Inherited by \fBNT3D_arrow_o\fP, \fBNT3D_axis_o\fP, \fBNT3D_cylinder_o\fP, \fBNT3D_ellipsoid_o\fP, and \fBNT3D_sphere_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_solid_o\fP (const \fBNT_vector3_o\fP &oNewPosition=NT_OriginVec3())"
.br
.ti -1c
.RI "\fBNT3D_solid_o\fP (const \fBNT3D_solid_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_solid_o\fP & \fBoperator=\fP (const \fBNT3D_solid_o\fP &right)"
.br
.ti -1c
.RI "\fB~NT3D_solid_o\fP ()"
.br
.ti -1c
.RI "void \fBScale\fP (\fBNT_vector3_o\fP oDeltaScaling)"
.br
.ti -1c
.RI "void \fBScaleX\fP (\fBNTreal\fP deltaSclX)"
.br
.ti -1c
.RI "void \fBScaleY\fP (\fBNTreal\fP deltaSclY)"
.br
.ti -1c
.RI "void \fBScaleZ\fP (\fBNTreal\fP deltaSclZ)"
.br
.ti -1c
.RI "void \fBScaleXYZ\fP (\fBNTreal\fP deltaSclXYZ)"
.br
.ti -1c
.RI "void \fBScaleUnit\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDrawSurfacedObj\fP ()"
.br
.ti -1c
.RI "virtual void \fBDrawSolidObj\fP () const "
.br
.ti -1c
.RI "void \fBControlSurfacedObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "GLUquadricObj * \fBpQuadObj\fP"
.br
.RI "\fIpointer to the incomplete type of an GLUquadicObj \fP"
.ti -1c
.RI "GLint \fBslices\fP"
.br
.ti -1c
.RI "GLint \fBstacks\fP"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP \fBoScaling\fP"
.br
.ti -1c
.RI "\fBNTint\fP \fBdrawStyle\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
oTexturePtr is deleted by destructor 
.RE
.PP

.PP
Definition at line 142 of file nt3d_solid_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_solid_o::NT3D_solid_o (const \fBNT_vector3_o\fP & oNewPosition = \fCNT_OriginVec3()\fP)"
.SS "NT3D_solid_o::NT3D_solid_o (const \fBNT3D_solid_o\fP & original)"
.SS "NT3D_solid_o::~NT3D_solid_o ()"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_solid_o::ControlSurfacedObj (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_surfaced_object_o\fP.
.SS "virtual void NT3D_solid_o::DrawSolidObj () const\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBNT3D_cylinder_o\fP, \fBNT3D_ellipsoid_o\fP, and \fBNT3D_sphere_o\fP.
.PP
Definition at line 160 of file nt3d_solid_obj.h.
.PP
References NT_CERR.
.PP
.nf
{NT_CERR(1,'NT3D_solid_o::DrawSolidObj() - Error : This method should be overridden by a derived class.');};
.fi
.SS "void NT3D_solid_o::DrawSurfacedObj ()\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_surfaced_object_o\fP.
.SS "const \fBNT3D_solid_o\fP& NT3D_solid_o::operator= (const \fBNT3D_solid_o\fP & right)"
.SS "void NT3D_solid_o::Scale (\fBNT_vector3_o\fP oDeltaScaling)"
.SS "void NT3D_solid_o::ScaleUnit ()\fC [inline]\fP"
.PP
Definition at line 154 of file nt3d_solid_obj.h.
.PP
References oScaling.
.PP
.nf
{ oScaling = NT_vector3_o(1.0,1.0,1.0);}
.fi
.SS "void NT3D_solid_o::ScaleX (\fBNTreal\fP deltaSclX)"
.SS "void NT3D_solid_o::ScaleXYZ (\fBNTreal\fP deltaSclXYZ)"
.SS "void NT3D_solid_o::ScaleY (\fBNTreal\fP deltaSclY)"
.SS "void NT3D_solid_o::ScaleZ (\fBNTreal\fP deltaSclZ)"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTint\fP \fBNT3D_solid_o::drawStyle\fP\fC [protected]\fP"
.PP
Definition at line 168 of file nt3d_solid_obj.h.
.SS "\fBNT_vector3_o\fP \fBNT3D_solid_o::oScaling\fP\fC [protected]\fP"
.PP
Definition at line 167 of file nt3d_solid_obj.h.
.PP
Referenced by ScaleUnit().
.SS "GLUquadricObj* \fBNT3D_solid_o::pQuadObj\fP\fC [protected]\fP"
.PP
Definition at line 164 of file nt3d_solid_obj.h.
.SS "GLint \fBNT3D_solid_o::slices\fP\fC [protected]\fP"
.PP
Definition at line 165 of file nt3d_solid_obj.h.
.SS "GLint \fBNT3D_solid_o::stacks\fP\fC [protected]\fP"
.PP
Definition at line 166 of file nt3d_solid_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
