.TH "nt3d_universe_spheric_camera_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_universe_spheric_camera_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT3D_universe_spheric_camera_o\fP class header by Ahmed Aldo Faisal (C) created 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt3d_universe_camera_vp_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_universe_spheric_camera_o\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDate:\fP
.RS 4
8.7.2000
.RE
.PP
\fBVersion:\fP
.RS 4
Version: 0.5 
.RE
.PP
\fBAuthor:\fP
.RS 4
Ahmed Aldo Faisal Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
.RE
.PP
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Library General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public License for more details.
.PP
You should have received a copy of the GNU Library General Public License along with this library; if not, write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. 
.PP
Definition in file \fBnt3d_universe_spheric_camera_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
