.TH "NT3D_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_o \- 
.PP
\fBNT3D_o\fP class The superclass for the NT3D graphic visualisation classes.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.PP
Inherited by \fBNT3D_bitmap_o\fP, \fBNT3D_object_o\fP, \fBNT3D_trajectory_o\fP, \fBNT3D_universe_o\fP, and \fBNT3D_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDraw\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 85 of file nt3d_obj.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual void NT3D_o::Draw ()\fC [pure virtual]\fP"
.PP
Implemented in \fBNT3D_abstract_vp_o\fP, \fBNT3D_bitmap_o\fP, \fBNT3D_bitmap_vp_o\fP, \fBNT3D_camera_o\fP, \fBNT3D_camera_vp_o\fP, \fBNT3D_hierarchic_object_o\fP, \fBNT3D_object_o\fP, \fBNT3D_plot2d_vp_o\fP, \fBNT3D_target_camera_o\fP, \fBNT3D_universal_vp_o\fP, \fBNT3D_universe_o\fP, and \fBNT3D_universe_vp_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
