.TH "NT3D_camera_vp_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_camera_vp_o \- 
.PP
\fBNT3D_camera_vp_o\fP class Provides a viewport with a universe rendered though the view of an camera abstraction.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_camera_vp_obj.h>\fP
.PP
Inherits \fBNT3D_abstract_vp_o\fP.
.PP
Inherited by \fBNT3D_universe_camera_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_camera_vp_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_camera_vp_o\fP (\fBNT3D_camera_o\fP *newCameraPtr)"
.br
.ti -1c
.RI "\fBNT3D_camera_vp_o\fP (const \fBNT3D_camera_vp_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_camera_vp_o\fP & \fBoperator=\fP (const \fBNT3D_camera_vp_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_camera_vp_o\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.ti -1c
.RI "\fBNTbool\fP \fBSetCamera\fP (\fBNT3D_camera_o\fP *newCameraPtr)"
.br
.ti -1c
.RI "\fBNTbool\fP \fB_hasCamera\fP ()"
.br
.ti -1c
.RI "void \fBRotateX\fP (const \fBNTreal\fP deltaRotX)"
.br
.ti -1c
.RI "void \fBRotateY\fP (const \fBNTreal\fP deltaRotY)"
.br
.ti -1c
.RI "void \fBRotateZ\fP (const \fBNTreal\fP deltaRotZ)"
.br
.ti -1c
.RI "void \fBSetRotationX\fP (const \fBNTreal\fP rotX)"
.br
.ti -1c
.RI "void \fBSetRotationY\fP (const \fBNTreal\fP rotY)"
.br
.ti -1c
.RI "void \fBSetRotationZ\fP (const \fBNTreal\fP rotZ)"
.br
.ti -1c
.RI "void \fBTranslateX\fP (const \fBNTreal\fP deltaTraX)"
.br
.ti -1c
.RI "void \fBTranslateY\fP (const \fBNTreal\fP deltaTraY)"
.br
.ti -1c
.RI "void \fBTranslateZ\fP (const \fBNTreal\fP deltaTraZ)"
.br
.ti -1c
.RI "void \fBSetTranslationX\fP (const \fBNTreal\fP traX)"
.br
.ti -1c
.RI "void \fBSetTranslationY\fP (const \fBNTreal\fP traY)"
.br
.ti -1c
.RI "void \fBSetTranslationZ\fP (const \fBNTreal\fP traZ)"
.br
.ti -1c
.RI "void \fBSetTranslationXYZ\fP (const \fBNT_vector3_o\fP &oTra)"
.br
.ti -1c
.RI "void \fBSetTarget\fP (const \fBNT_vector3_o\fP &oTarget)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBDrawScene\fP ()=0"
.br
.ti -1c
.RI "void \fBRedrawChild\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBResizeChild\fP (\fBNTsize\fP width, \fBNTsize\fP height)"
.br
.ti -1c
.RI "void \fBInitChild\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNT3D_camera_o\fP * \fBcameraPtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
do not override \fBDraw()\fP use \fBDrawScene()\fP instead! 
.RE
.PP

.PP
Definition at line 81 of file nt3d_camera_vp_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_camera_vp_o::NT3D_camera_vp_o ()"
.SS "NT3D_camera_vp_o::NT3D_camera_vp_o (\fBNT3D_camera_o\fP * newCameraPtr)"
.SS "NT3D_camera_vp_o::NT3D_camera_vp_o (const \fBNT3D_camera_vp_o\fP & original)"
.SS "virtual NT3D_camera_vp_o::~NT3D_camera_vp_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTbool\fP NT3D_camera_vp_o::_hasCamera ()\fC [inline]\fP"
.PP
Definition at line 87 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "void NT3D_camera_vp_o::Draw ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.SS "virtual void NT3D_camera_vp_o::DrawScene ()\fC [protected, pure virtual]\fP"
.PP
Implemented in \fBNT3D_universe_camera_vp_o\fP.
.SS "void NT3D_camera_vp_o::InitChild ()\fC [protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.SS "const \fBNT3D_camera_vp_o\fP& NT3D_camera_vp_o::operator= (const \fBNT3D_camera_vp_o\fP & right)"
.SS "void NT3D_camera_vp_o::RedrawChild ()\fC [inline, protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 109 of file nt3d_camera_vp_obj.h.
.PP
.nf
:
.fi
.SS "\fBNTreturn\fP NT3D_camera_vp_o::ResizeChild (\fBNTsize\fP width, \fBNTsize\fP height)\fC [protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.SS "void NT3D_camera_vp_o::RotateX (const \fBNTreal\fP deltaRotX)\fC [inline]\fP"
.PP
Definition at line 88 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "void NT3D_camera_vp_o::RotateY (const \fBNTreal\fP deltaRotY)\fC [inline]\fP"
.PP
Definition at line 89 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "void NT3D_camera_vp_o::RotateZ (const \fBNTreal\fP deltaRotZ)\fC [inline]\fP"
.PP
Definition at line 90 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "\fBNTbool\fP NT3D_camera_vp_o::SetCamera (\fBNT3D_camera_o\fP * newCameraPtr)"
.SS "void NT3D_camera_vp_o::SetRotationX (const \fBNTreal\fP rotX)\fC [inline]\fP"
.PP
Definition at line 91 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "void NT3D_camera_vp_o::SetRotationY (const \fBNTreal\fP rotY)\fC [inline]\fP"
.PP
Definition at line 92 of file nt3d_camera_vp_obj.h.
.PP
.nf
{ return haveCamera;}
.fi
.SS "void NT3D_camera_vp_o::SetRotationZ (const \fBNTreal\fP rotZ)\fC [inline]\fP"
.PP
Definition at line 93 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::RotateX().
.PP
.nf
{ cameraPtr->RotateX(deltaRotX);}
.fi
.SS "void NT3D_camera_vp_o::SetTarget (const \fBNT_vector3_o\fP & oTarget)\fC [inline]\fP"
.PP
Definition at line 101 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::TranslateZ().
.PP
.nf
{ cameraPtr->TranslateZ(deltaTraZ);}
.fi
.SS "void NT3D_camera_vp_o::SetTranslationX (const \fBNTreal\fP traX)\fC [inline]\fP"
.PP
Definition at line 97 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::SetRotationY().
.PP
.nf
{ cameraPtr->SetRotationY(rotY); }
.fi
.SS "void NT3D_camera_vp_o::SetTranslationXYZ (const \fBNT_vector3_o\fP & oTra)\fC [inline]\fP"
.PP
Definition at line 100 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::TranslateY().
.PP
.nf
{ cameraPtr->TranslateY(deltaTraY);}
.fi
.SS "void NT3D_camera_vp_o::SetTranslationY (const \fBNTreal\fP traY)\fC [inline]\fP"
.PP
Definition at line 98 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::SetRotationZ().
.PP
.nf
{ cameraPtr->SetRotationZ(rotZ); }
.fi
.SS "void NT3D_camera_vp_o::SetTranslationZ (const \fBNTreal\fP traZ)\fC [inline]\fP"
.PP
Definition at line 99 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::TranslateX().
.PP
.nf
{ cameraPtr->TranslateX(deltaTraX);}
.fi
.SS "void NT3D_camera_vp_o::TranslateX (const \fBNTreal\fP deltaTraX)\fC [inline]\fP"
.PP
Definition at line 94 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::RotateY().
.PP
.nf
{ cameraPtr->RotateY(deltaRotY);}
.fi
.SS "void NT3D_camera_vp_o::TranslateY (const \fBNTreal\fP deltaTraY)\fC [inline]\fP"
.PP
Definition at line 95 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::RotateZ().
.PP
.nf
{ cameraPtr->RotateZ(deltaRotZ);}
.fi
.SS "void NT3D_camera_vp_o::TranslateZ (const \fBNTreal\fP deltaTraZ)\fC [inline]\fP"
.PP
Definition at line 96 of file nt3d_camera_vp_obj.h.
.PP
References cameraPtr, and NT3D_object_o::SetRotationX().
.PP
.nf
{ cameraPtr->SetRotationX(rotX); }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNT3D_camera_o\fP* \fBNT3D_camera_vp_o::cameraPtr\fP\fC [protected]\fP"
.PP
Definition at line 113 of file nt3d_camera_vp_obj.h.
.PP
Referenced by SetRotationZ(), SetTarget(), SetTranslationX(), SetTranslationXYZ(), SetTranslationY(), SetTranslationZ(), TranslateX(), TranslateY(), and TranslateZ().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
