.TH "NT3D_bitmap_vp_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_bitmap_vp_o \- 
.PP
\fBNT3D_bitmap_vp_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_bitmap_vp_obj.h>\fP
.PP
Inherits \fBNT3D_abstract_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_bitmap_vp_o\fP (\fBNT3D_bitmap_o\fP *newBmpPtr=NULL)"
.br
.ti -1c
.RI "\fBNT3D_bitmap_vp_o\fP (const \fBNT3D_bitmap_vp_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_bitmap_vp_o\fP & \fBoperator=\fP (const \fBNT3D_bitmap_vp_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_bitmap_vp_o\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBRedrawChild\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBResizeChild\fP (\fBNTsize\fP newWidth, \fBNTsize\fP newHeight)"
.br
.ti -1c
.RI "void \fBInitChild\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 50 of file nt3d_bitmap_vp_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_bitmap_vp_o::NT3D_bitmap_vp_o (\fBNT3D_bitmap_o\fP * newBmpPtr = \fCNULL\fP)"
.SS "NT3D_bitmap_vp_o::NT3D_bitmap_vp_o (const \fBNT3D_bitmap_vp_o\fP & original)"
.SS "virtual NT3D_bitmap_vp_o::~NT3D_bitmap_vp_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_bitmap_vp_o::Draw ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.SS "void NT3D_bitmap_vp_o::InitChild ()\fC [inline, protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 57 of file nt3d_bitmap_vp_obj.h.
.PP
.nf
:
.fi
.SS "const \fBNT3D_bitmap_vp_o\fP& NT3D_bitmap_vp_o::operator= (const \fBNT3D_bitmap_vp_o\fP & right)"
.SS "void NT3D_bitmap_vp_o::RedrawChild ()\fC [inline, protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 55 of file nt3d_bitmap_vp_obj.h.
.PP
.nf
:
.fi
.SS "\fBNTreturn\fP NT3D_bitmap_vp_o::ResizeChild (\fBNTsize\fP newWidth, \fBNTsize\fP newHeight)\fC [inline, protected, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 56 of file nt3d_bitmap_vp_obj.h.
.PP
.nf
:
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
