.TH "NT3D_moonmap_texture_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_moonmap_texture_o \- 
.PP
\fBNT3D_moonmap_texture_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_moonmap_texture_obj.h>\fP
.PP
Inherits \fBNT3D_texture_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_moonmap_texture_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_moonmap_texture_o\fP (const \fBNT3D_moonmap_texture_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_moonmap_texture_o\fP & \fBoperator=\fP (const \fBNT3D_moonmap_texture_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_moonmap_texture_o\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNTreturn\fP \fBAssignTexture\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 59 of file nt3d_moonmap_texture_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_moonmap_texture_o::NT3D_moonmap_texture_o ()"
.SS "NT3D_moonmap_texture_o::NT3D_moonmap_texture_o (const \fBNT3D_moonmap_texture_o\fP & original)"
.SS "virtual NT3D_moonmap_texture_o::~NT3D_moonmap_texture_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreturn\fP NT3D_moonmap_texture_o::AssignTexture ()\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_texture_o\fP.
.SS "const \fBNT3D_moonmap_texture_o\fP& NT3D_moonmap_texture_o::operator= (const \fBNT3D_moonmap_texture_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
