.TH "NT3D_bitmap_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_bitmap_o \- 
.PP
\fBNT3D_bitmap_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_bitmap_obj.h>\fP
.PP
Inherits \fBNT3D_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_bitmap_o\fP (\fBNTsize\fP width=100, \fBNTsize\fP height=100, \fBNTimageDataFormat\fP format=NT_RGBA)"
.br
.ti -1c
.RI "\fBNT3D_bitmap_o\fP (const \fBNT3D_bitmap_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_bitmap_o\fP & \fBoperator=\fP (const \fBNT3D_bitmap_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_bitmap_o\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP ()"
.br
.ti -1c
.RI "void \fBGetBitmap\fP (\fBNTsize\fP x1, \fBNTsize\fP y1, \fBNTsize\fP x2, \fBNTsize\fP y2, \fBNTimageDataFormat\fP newFormat)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 53 of file nt3d_bitmap_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_bitmap_o::NT3D_bitmap_o (\fBNTsize\fP width = \fC100\fP, \fBNTsize\fP height = \fC100\fP, \fBNTimageDataFormat\fP format = \fCNT_RGBA\fP)"
.SS "NT3D_bitmap_o::NT3D_bitmap_o (const \fBNT3D_bitmap_o\fP & original)"
.SS "virtual NT3D_bitmap_o::~NT3D_bitmap_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_bitmap_o::Draw ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_o\fP.
.SS "void NT3D_bitmap_o::GetBitmap (\fBNTsize\fP x1, \fBNTsize\fP y1, \fBNTsize\fP x2, \fBNTsize\fP y2, \fBNTimageDataFormat\fP newFormat)"
.SS "const \fBNT3D_bitmap_o\fP& NT3D_bitmap_o::operator= (const \fBNT3D_bitmap_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
