.TH "NT3D_arrow_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_arrow_o \- 
.PP
\fBNT3D_arrow_o\fP class Draw an arrow which, is constructed of a cylinder as shaft and a conus as arrow head.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_arrow_obj.h>\fP
.PP
Inherits \fBNT3D_solid_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_arrow_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_arrow_o\fP (const \fBNT3D_arrow_o\fP &original)"
.br
.ti -1c
.RI "\fBNT3D_arrow_o\fP (const \fBNT_vector3_o\fP &newBase, const \fBNT_vector3_o\fP &newTip)"
.br
.ti -1c
.RI "const \fBNT3D_arrow_o\fP & \fBoperator=\fP (const \fBNT3D_arrow_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_arrow_o\fP ()"
.br
.ti -1c
.RI "void \fBCollinearize\fP (const \fBNT_vector3_o\fP &)"
.br
.RI "\fIrotate the object such that its (oRotation vector would rotate a vector on the) x-axis in the direction of oRelativeVector \fP"
.ti -1c
.RI "void \fBDrawSolidObject\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
It can either be rotated into a desired direction as all NT3D_objects_o OR it can be created and manipulated specifying a head and tail position for it in space. 
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
In case the arrow is ment to point into a certain direction designated by a base-tip constructor is used be sure to not rotate the object using any of the rotate calls! 
.RE
.PP

.PP
Definition at line 75 of file nt3d_arrow_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_arrow_o::NT3D_arrow_o ()"
.PP
Referenced by DrawSolidObject().
.SS "NT3D_arrow_o::NT3D_arrow_o (const \fBNT3D_arrow_o\fP & original)"
.SS "NT3D_arrow_o::NT3D_arrow_o (const \fBNT_vector3_o\fP & newBase, const \fBNT_vector3_o\fP & newTip)"
.SS "virtual NT3D_arrow_o::~NT3D_arrow_o ()\fC [virtual]\fP"
.PP
Referenced by DrawSolidObject().
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_arrow_o::Collinearize (const \fBNT_vector3_o\fP & oRelativeVector)"
.PP
Reimplemented from \fBNT3D_object_o\fP.
.PP
Referenced by DrawSolidObject().
.SS "void NT3D_arrow_o::DrawSolidObject () const\fC [inline]\fP"
.PP
Definition at line 75 of file nt3d_arrow_obj.h.
.PP
References Collinearize(), NT3D_arrow_o(), operator=(), and ~NT3D_arrow_o().
.PP
.nf
: public NT3D_solid_o {
.fi
.SS "const \fBNT3D_arrow_o\fP& NT3D_arrow_o::operator= (const \fBNT3D_arrow_o\fP & right)"
.PP
Referenced by DrawSolidObject().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
