.TH "nt3d_demo_glut_drv_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_demo_glut_drv_obj.h \- 
.PP
.IP "\(bu" 2
NT_demo_glut_drv_o class declaration by Ahmed Aldo Faisal (C) created 18.1.1998 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt3d_vp_glut_drv_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_demo_glut_drv_o\fP"
.br
.RI "\fI\fBNT3D_demo_glut_drv_o\fP class Simple demonstration of how to use the vp_glut_drv object. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt3d_demo_glut_drv_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
