.TH "nt3d_color_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt3d_color_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT3D_color_o\fP class declaration by Ahmed Aldo Faisal (C) created 15.10.1998 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt3d_obj.h'\fP
.br
\fC#include 'nt_vector_obj.h'\fP
.br
\fC#include <GL/gl.h>\fP
.br
\fC#include <valarray>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT3D_color_o\fP"
.br
.RI "\fITHe \fBNT3D_color_o\fP class handles the abstract color concept. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_alpha\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_white\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_red\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_green\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_blue\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_yellow\fP ()"
.br
.ti -1c
.RI "\fBNT3D_color_o\fP & \fBNT3D_black\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt3d_color_obj.h\fP.
.SH "Function Documentation"
.PP 
.SS "\fBNT3D_color_o\fP& NT3D_alpha ()"
.SS "\fBNT3D_color_o\fP& NT3D_black ()"
.SS "\fBNT3D_color_o\fP& NT3D_blue ()"
.SS "\fBNT3D_color_o\fP& NT3D_green ()"
.SS "\fBNT3D_color_o\fP& NT3D_red ()"
.SS "\fBNT3D_color_o\fP& NT3D_white ()"
.SS "\fBNT3D_color_o\fP& NT3D_yellow ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
