.TH "NT3D_spheric_camera_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_spheric_camera_o \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_spheric_camera_obj.h>\fP
.PP
Inherits \fBNT3D_universe_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_spheric_camera_o\fP (\fBNTsize\fP azimutalSteps=10, \fBNTsize\fP altitudalSteps=10)"
.br
.ti -1c
.RI "\fBNT3D_spheric_camera_o\fP (const \fBNT3D_spheric_camera_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_spheric_camera_o\fP & \fBoperator=\fP (const \fBNT3D_spheric_camera_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_spheric_camera_o\fP ()"
.br
.ti -1c
.RI "void \fBDrawChild\fP ()"
.br
.ti -1c
.RI "void \fBRedrawChild\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBResizeChild\fP (\fBNTsize\fP width, \fBNTsize\fP height)"
.br
.ti -1c
.RI "void \fBInitChild\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNT3D_stub_o\fP \fBeye\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 52 of file nt3d_spheric_camera_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_spheric_camera_o::NT3D_spheric_camera_o (\fBNTsize\fP azimutalSteps = \fC10\fP, \fBNTsize\fP altitudalSteps = \fC10\fP)"
.SS "NT3D_spheric_camera_o::NT3D_spheric_camera_o (const \fBNT3D_spheric_camera_o\fP & original)"
.SS "virtual NT3D_spheric_camera_o::~NT3D_spheric_camera_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_spheric_camera_o::DrawChild ()\fC [virtual]\fP"
.PP
Implements \fBNT3D_universe_vp_o\fP.
.SS "void NT3D_spheric_camera_o::InitChild ()\fC [inline, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 63 of file nt3d_spheric_camera_obj.h.
.PP
.nf
{}
.fi
.SS "const \fBNT3D_spheric_camera_o\fP& NT3D_spheric_camera_o::operator= (const \fBNT3D_spheric_camera_o\fP & right)"
.SS "void NT3D_spheric_camera_o::RedrawChild ()\fC [inline, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 61 of file nt3d_spheric_camera_obj.h.
.PP
.nf
{}
.fi
.SS "\fBNTreturn\fP NT3D_spheric_camera_o::ResizeChild (\fBNTsize\fP width, \fBNTsize\fP height)\fC [inline, virtual]\fP"
.PP
Implements \fBNT3D_abstract_vp_o\fP.
.PP
Definition at line 62 of file nt3d_spheric_camera_obj.h.
.PP
.nf
{return NT_SUCCESS;}
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNT3D_stub_o\fP \fBNT3D_spheric_camera_o::eye\fP"
.PP
Definition at line 65 of file nt3d_spheric_camera_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
