.TH "NT3D_surfaced_object_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_surfaced_object_o \- 
.PP
\fBNT3D_surfaced_object_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_surfaced_object_obj.h>\fP
.PP
Inherits \fBNT3D_hierarchic_object_o\fP.
.PP
Inherited by \fBNT3D_open_box_o\fP, \fBNT3D_rectangle_o\fP, and \fBNT3D_solid_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_surfaced_object_o\fP ()"
.br
.ti -1c
.RI "\fBNT3D_surfaced_object_o\fP (const \fBNT_vector3_o\fP &oPosition)"
.br
.ti -1c
.RI "\fBNT3D_surfaced_object_o\fP (const \fBNT3D_surfaced_object_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_surfaced_object_o\fP & \fBoperator=\fP (const \fBNT3D_surfaced_object_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_surfaced_object_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSetTexture\fP (\fBNT3D_texture_o\fP *newTexturePtr)"
.br
.ti -1c
.RI "bool \fB_textureSet\fP ()"
.br
.ti -1c
.RI "bool \fB_bUseTexture\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBDrawObj\fP ()"
.br
.ti -1c
.RI "virtual void \fBDrawSurfacedObj\fP ()"
.br
.ti -1c
.RI "void \fBControlObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)"
.br
.RI "\fIControlObj is to overwritten by derived classes to handle controller calls. \fP"
.ti -1c
.RI "virtual void \fBControlSurfacedObj\fP (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNT3D_material_o\fP \fBoMaterial\fP"
.br
.ti -1c
.RI "\fBNT3D_texture_o\fP * \fBoTexturePtr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 59 of file nt3d_surfaced_object_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_surfaced_object_o::NT3D_surfaced_object_o ()"
.SS "NT3D_surfaced_object_o::NT3D_surfaced_object_o (const \fBNT_vector3_o\fP & oPosition)"
.SS "NT3D_surfaced_object_o::NT3D_surfaced_object_o (const \fBNT3D_surfaced_object_o\fP & original)"
.SS "virtual NT3D_surfaced_object_o::~NT3D_surfaced_object_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "bool NT3D_surfaced_object_o::_bUseTexture ()\fC [inline]\fP"
.PP
Definition at line 70 of file nt3d_surfaced_object_obj.h.
.PP
.nf
{return bUseTexture;};
.fi
.SS "bool NT3D_surfaced_object_o::_textureSet ()\fC [inline]\fP"
.PP
Definition at line 69 of file nt3d_surfaced_object_obj.h.
.PP
.nf
{return textureSet;};
.fi
.SS "void NT3D_surfaced_object_o::ControlObj (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)\fC [protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.SS "virtual void NT3D_surfaced_object_o::ControlSurfacedObj (\fBNT3Dcontroller\fP cntrl, \fBNTint\fP value)\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBNT3D_solid_o\fP.
.PP
Definition at line 78 of file nt3d_surfaced_object_obj.h.
.PP
.nf
{NT_CERR(1,'NT3D_surfaced_object_o::ControlSurfacedObj() - Error : This method not overridden by derived class');};
.fi
.SS "void NT3D_surfaced_object_o::DrawObj ()\fC [inline, protected, virtual]\fP"
.PP
Reimplemented from \fBNT3D_hierarchic_object_o\fP.
.PP
Definition at line 75 of file nt3d_surfaced_object_obj.h.
.PP
References DrawSurfacedObj().
.PP
.nf
{ DrawSurfacedObj(); }; 
.fi
.SS "virtual void NT3D_surfaced_object_o::DrawSurfacedObj ()\fC [inline, protected, virtual]\fP"
.PP
Reimplemented in \fBNT3D_open_box_o\fP, and \fBNT3D_solid_o\fP.
.PP
Definition at line 76 of file nt3d_surfaced_object_obj.h.
.PP
References NT_CERR.
.PP
Referenced by DrawObj().
.PP
.nf
{NT_CERR(1,'NT3D_surfaced_object_o::DrawSurfacedObj() - Error : This method not overridden by derived class');};
.fi
.SS "const \fBNT3D_surfaced_object_o\fP& NT3D_surfaced_object_o::operator= (const \fBNT3D_surfaced_object_o\fP & right)"
.SS "\fBNTreturn\fP NT3D_surfaced_object_o::SetTexture (\fBNT3D_texture_o\fP * newTexturePtr)"
.SH "Member Data Documentation"
.PP 
.SS "\fBNT3D_material_o\fP \fBNT3D_surfaced_object_o::oMaterial\fP\fC [protected]\fP"
.PP
Definition at line 78 of file nt3d_surfaced_object_obj.h.
.SS "\fBNT3D_texture_o\fP* \fBNT3D_surfaced_object_o::oTexturePtr\fP\fC [protected]\fP"
.PP
Definition at line 81 of file nt3d_surfaced_object_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
