.TH "NT3D_plot2d_vec_vp_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT3D_plot2d_vec_vp_o \- 
.PP
\fBNT3D_plot2d_vec_vp_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt3d_plot2d_vec_vp_obj.h>\fP
.PP
Inherits \fBNT3D_plot2d_vp_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT3D_plot2d_vec_vp_o\fP (\fBNTsize\fP dim=0)"
.br
.ti -1c
.RI "\fBNT3D_plot2d_vec_vp_o\fP (const \fBNT3D_plot2d_vec_vp_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT3D_plot2d_vec_vp_o\fP & \fBoperator=\fP (const \fBNT3D_plot2d_vec_vp_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT3D_plot2d_vec_vp_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSetData\fP (const vector< \fBNTreal\fP > &\fBdataVec\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNTreturn\fP \fBset_dim\fP (\fBNTsize\fP newDim)"
.br
.ti -1c
.RI "void \fBDrawData\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "vector< \fBNTreal\fP > \fBpositionVec\fP"
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBdataVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 49 of file nt3d_plot2d_vec_vp_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT3D_plot2d_vec_vp_o::NT3D_plot2d_vec_vp_o (\fBNTsize\fP dim = \fC0\fP)"
.SS "NT3D_plot2d_vec_vp_o::NT3D_plot2d_vec_vp_o (const \fBNT3D_plot2d_vec_vp_o\fP & original)"
.SS "virtual NT3D_plot2d_vec_vp_o::~NT3D_plot2d_vec_vp_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT3D_plot2d_vec_vp_o::DrawData ()\fC [protected, virtual]\fP"
.PP
Implements \fBNT3D_plot2d_vp_o\fP.
.SS "const \fBNT3D_plot2d_vec_vp_o\fP& NT3D_plot2d_vec_vp_o::operator= (const \fBNT3D_plot2d_vec_vp_o\fP & right)"
.SS "\fBNTreturn\fP NT3D_plot2d_vec_vp_o::set_dim (\fBNTsize\fP newDim)\fC [inline, protected]\fP"
.PP
Definition at line 61 of file nt3d_plot2d_vec_vp_obj.h.
.PP
References positionVec.
.PP
.nf
{dim = newDim; positionVec.resize(dim); dataVec.resize(dim); return NT_SUCCESS;}
.fi
.SS "\fBNTreturn\fP NT3D_plot2d_vec_vp_o::SetData (const vector< \fBNTreal\fP > & dataVec)"
.SH "Member Data Documentation"
.PP 
.SS "vector<\fBNTreal\fP> \fBNT3D_plot2d_vec_vp_o::dataVec\fP\fC [protected]\fP"
.PP
Definition at line 65 of file nt3d_plot2d_vec_vp_obj.h.
.SS "vector<\fBNTreal\fP> \fBNT3D_plot2d_vec_vp_o::positionVec\fP\fC [protected]\fP"
.PP
Definition at line 64 of file nt3d_plot2d_vec_vp_obj.h.
.PP
Referenced by set_dim().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
