.TH "nt_aux_math_func.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_aux_math_func.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt_mersenne_twister_external_obj.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBNTComputePLogP\fP (\fBNTreal\fP prob)"
.br
.RI "\fINTlimit01 Limit a value between [0,1]. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBNTlimit01\fP (\fBNTreal\fP value)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBNTround\fP (\fBNTreal\fP value)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBNTLogGammaFunction\fP (\fBNTreal\fP arg)"
.br
.ti -1c
.RI "\fBMTRand\fP \fBNTMakeMTRandFunction\fP (\fBMTRand::uint32\fP oneSeed)"
.br
.ti -1c
.RI "int \fBNTisnan\fP (double value)"
.br
.ti -1c
.RI "int \fBNTisinf\fP (double value)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBNTreal\fP NTComputePLogP (\fBNTreal\fP prob)"\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.SS "int NTisinf (double value)"
.SS "int NTisnan (double value)"
.SS "\fBNTreal\fP NTlimit01 (\fBNTreal\fP value)"
.SS "\fBNTreal\fP NTLogGammaFunction (\fBNTreal\fP arg)"
.SS "\fBMTRand\fP NTMakeMTRandFunction (\fBMTRand::uint32\fP oneSeed)"
.SS "\fBNTreal\fP NTround (\fBNTreal\fP value)"
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
