.TH "NT_binomial_rnd_dist_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_binomial_rnd_dist_o \- 
.PP
\fBNT_binomial_rnd_dist_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_binomial_rnd_dist_obj.h>\fP
.PP
Inherits \fBNT_rnd_dist_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_binomial_rnd_dist_o\fP (\fBNTreal\fP pp, \fBNTsize\fP n)"
.br
.ti -1c
.RI "\fBNT_binomial_rnd_dist_o\fP (const \fBNT_binomial_rnd_dist_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_binomial_rnd_dist_o\fP & \fBoperator=\fP (const \fBNT_binomial_rnd_dist_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_binomial_rnd_dist_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBRndVal\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBBinomial\fP (float pp, int n) const "
.br
.RI "\fIIdentical to method 'bnldev' from Numerical Recipes in C (Press et al. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBLogGamma\fP (\fBNTreal\fP val) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 54 of file nt_binomial_rnd_dist_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_binomial_rnd_dist_o::NT_binomial_rnd_dist_o (\fBNTreal\fP pp, \fBNTsize\fP n)"
.SS "NT_binomial_rnd_dist_o::NT_binomial_rnd_dist_o (const \fBNT_binomial_rnd_dist_o\fP & original)"
.SS "virtual NT_binomial_rnd_dist_o::~NT_binomial_rnd_dist_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NT_binomial_rnd_dist_o::Binomial (float pp, int n) const") 
.SS "\fBNTreal\fP NT_binomial_rnd_dist_o::LogGamma (\fBNTreal\fP val) const"
.SS "const \fBNT_binomial_rnd_dist_o\fP& NT_binomial_rnd_dist_o::operator= (const \fBNT_binomial_rnd_dist_o\fP & right)"
.SS "\fBNTreal\fP NT_binomial_rnd_dist_o::RndVal () const\fC [virtual]\fP"
.PP
Implements \fBNT_rnd_dist_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
