.TH "NT_currency_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_currency_o \- 
.PP
A general class for NT supported coutnries == money class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_currency_obj.h>\fP
.PP
Inherits \fBNT_value_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_currency_o\fP ()"
.br
.ti -1c
.RI "\fBNT_currency_o\fP (\fBNTcountryCode\fP initCountry, \fBNTreal\fP initConversionFactor)"
.br
.ti -1c
.RI "\fBNT_currency_o\fP (const \fBNT_currency_o\fP &)"
.br
.ti -1c
.RI "\fB~NT_currency_o\fP ()"
.br
.ti -1c
.RI "string \fBcountryCode2currencyName\fP (\fBNTcountryCode\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBset_country\fP (\fBNTcountryCode\fP newCoutryCode)"
.br
.ti -1c
.RI "void \fBset_conversionFactor\fP (\fBNTreal\fP newConversionFactor)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBNT_currency_o\fP &self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 79 of file nt_currency_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_currency_o::NT_currency_o ()"
.SS "NT_currency_o::NT_currency_o (\fBNTcountryCode\fP initCountry, \fBNTreal\fP initConversionFactor)"
.SS "NT_currency_o::NT_currency_o (const \fBNT_currency_o\fP &)"
.SS "NT_currency_o::~NT_currency_o ()"
.SH "Member Function Documentation"
.PP 
.SS "string NT_currency_o::countryCode2currencyName (\fBNTcountryCode\fP)"
.SS "void NT_currency_o::set_conversionFactor (\fBNTreal\fP newConversionFactor)\fC [protected]\fP"
.SS "void NT_currency_o::set_country (\fBNTcountryCode\fP newCoutryCode)\fC [protected]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBNT_currency_o\fP & self)\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
