.TH "NT_dimension_error_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_dimension_error_o \- 
.PP
Class to report an dimension mismatch error.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_error_obj.h>\fP
.PP
Inherits \fBNT_error_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_dimension_error_o\fP (const char *f, int l, int left, int right)"
.br
.ti -1c
.RI "virtual void \fBmessage\fP (ostream &) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file nt_error_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_dimension_error_o::NT_dimension_error_o (const char * f, int l, int left, int right)"
.SH "Member Function Documentation"
.PP 
.SS "virtual void NT_dimension_error_o::message (ostream &) const\fC [virtual]\fP"
.PP
Reimplemented from \fBNT_error_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
