.TH "NT_error_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_error_o \- 
.PP
NT superclass to report an error.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_error_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.PP
Inherited by \fBNT_bounds_error_o\fP, \fBNT_dimension_error_o\fP, \fBNT_invariant_error_o\fP, \fBNT_mem_error_o\fP, \fBNT_postcond_error_o\fP, and \fBNT_precond_error_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_error_o\fP (const char *f, int l, const char *expr=0, const char *msg=0)"
.br
.ti -1c
.RI "void \fBabort\fP ()"
.br
.ti -1c
.RI "virtual void \fBmessage\fP (ostream &) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file nt_error_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_error_o::NT_error_o (const char * f, int l, const char * expr = \fC0\fP, const char * msg = \fC0\fP)"
.SH "Member Function Documentation"
.PP 
.SS "void NT_error_o::abort ()"
.SS "virtual void NT_error_o::message (ostream &) const\fC [virtual]\fP"
.PP
Reimplemented in \fBNT_bounds_error_o\fP, and \fBNT_dimension_error_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
