.TH "NT_file_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_file_o \- 
.PP
\fBNT_file_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_file_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_file_o\fP ()"
.br
.ti -1c
.RI "\fBNT_file_o\fP (const \fBNT_file_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_file_o\fP & \fBoperator=\fP (const \fBNT_file_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_file_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 49 of file nt_file_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_file_o::NT_file_o ()"
.SS "NT_file_o::NT_file_o (const \fBNT_file_o\fP & original)"
.SS "virtual NT_file_o::~NT_file_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT_file_o\fP& NT_file_o::operator= (const \fBNT_file_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
