.TH "nt_gaussian_rnd_dist_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_gaussian_rnd_dist_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_rnd_dist_obj.h'\fP
.br
\fC#include 'nt_vector_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_gaussian_rnd_dist_o\fP"
.br
.RI "\fI\fBNT_gaussian_rnd_dist_o\fP returns values out of a gaussian random distribution objects based upon inidividual paramters for each subspace Idea : The usage idea is to call the object which returns a NTreal or \fBNT_vector_o\fP containing random values out of its specific distribution [a,b]. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
