.TH "nt_gaussian_vec_rnd_dist_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_gaussian_vec_rnd_dist_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT_gaussian_vec_rnd_dist_o\fP class header by Ahmed Aldo Faisal (C) created 26.6.1999 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt_vec_rnd_dist_obj.h'\fP
.br
\fC#include 'nt_gaussian_rnd_dist_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_gaussian_vec_rnd_dist_o\fP"
.br
.RI "\fI\fBNT_gaussian_vec_rnd_dist_o\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt_gaussian_vec_rnd_dist_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
