.TH "NT_histogram_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_histogram_o \- 
.PP
\fBNT_histogram_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_histogram_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_histogram_o\fP (\fBNTreal\fP minVal=0, \fBNTreal\fP maxVal=1, \fBNTsize\fP numberOfBins=10)"
.br
.ti -1c
.RI "\fBNT_histogram_o\fP (const \fBNT_histogram_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_histogram_o\fP & \fBoperator=\fP (const \fBNT_histogram_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_histogram_o\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBBinValue\fP (\fBNTreal\fP value)"
.br
.ti -1c
.RI "void \fBShow\fP (bool showHeader=false) const "
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBPDF\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBShannonEntropy\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &str, const \fBNT_histogram_o\fP &self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 55 of file nt_histogram_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_histogram_o::NT_histogram_o (\fBNTreal\fP minVal = \fC0\fP, \fBNTreal\fP maxVal = \fC1\fP, \fBNTsize\fP numberOfBins = \fC10\fP)"
.SS "NT_histogram_o::NT_histogram_o (const \fBNT_histogram_o\fP & original)"
.SS "virtual NT_histogram_o::~NT_histogram_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void NT_histogram_o::BinValue (\fBNTreal\fP value)"
.SS "const \fBNT_histogram_o\fP& NT_histogram_o::operator= (const \fBNT_histogram_o\fP & right)"
.SS "vector<\fBNTreal\fP> NT_histogram_o::PDF () const"
.SS "void NT_histogram_o::Reset ()"
.SS "\fBNTreal\fP NT_histogram_o::ShannonEntropy () const"
.SS "void NT_histogram_o::Show (bool showHeader = \fCfalse\fP) const"
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & str, const \fBNT_histogram_o\fP & self)\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
