.TH "NT_header_string_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_header_string_o \- 
.PP
PURPOSE: The header block with reference count and available space REMARKS: An instance of this structure is BELOW each string that is allocated on the collectible heap.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_header_string_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBunique\fP ()"
.br
.ti -1c
.RI "void \fBincref\fP ()"
.br
.ti -1c
.RI "int \fBdecref\fP ()"
.br
.ti -1c
.RI "\fBNTsize\fP \fBlength\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static char * \fBalloc\fP (const char[])"
.br
.ti -1c
.RI "static char * \fBalloc\fP (int, const char[], int)"
.br
.ti -1c
.RI "static void \fBfree\fP (char *)"
.br
.ti -1c
.RI "static \fBNT_header_string_o\fP * \fBheader\fP (const char *p)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBNT_string_o\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 70 of file nt_header_string_obj.h.
.SH "Member Function Documentation"
.PP 
.SS "static char* NT_header_string_o::alloc (const  char[])\fC [static]\fP"
.SS "static char* NT_header_string_o::alloc (int, const  char[], int)\fC [static]\fP"
.SS "int NT_header_string_o::decref ()\fC [inline]\fP"
.PP
Definition at line 79 of file nt_header_string_obj.h.
.PP
.nf
{ return --_rc; }
.fi
.SS "static void NT_header_string_o::free (char *)\fC [static]\fP"
.SS "static \fBNT_header_string_o\fP* NT_header_string_o::header (const char * p)\fC [inline, static]\fP"
.PP
Definition at line 87 of file nt_header_string_obj.h.
.PP
.nf
{ return (NT_header_string_o*)p - 1; }
.fi
.SS "void NT_header_string_o::incref ()\fC [inline]\fP"
.PP
Definition at line 78 of file nt_header_string_obj.h.
.PP
.nf
{ ++_rc; }
.fi
.SS "\fBNTsize\fP NT_header_string_o::length () const\fC [inline]\fP"
.PP
Definition at line 81 of file nt_header_string_obj.h.
.PP
.nf
{ return _length; }
.fi
.SS "int NT_header_string_o::unique ()\fC [inline]\fP"
.PP
Definition at line 77 of file nt_header_string_obj.h.
.PP
.nf
{ return _rc == 1; }
.fi
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBNT_string_o\fP\fC [friend]\fP"
.PP
Definition at line 97 of file nt_header_string_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
