.TH "nt_histogram_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_histogram_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT_histogram_o\fP class header by Ahmed Aldo Faisal (C) created 11.10.2000 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt_error_obj.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_histogram_o\fP"
.br
.RI "\fI\fBNT_histogram_o\fP class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef vector< \fBNTsize\fP > \fBNT_HistogramBins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt_histogram_obj.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef vector<\fBNTsize\fP> \fBNT_HistogramBins\fP"
.PP
Definition at line 49 of file nt_histogram_obj.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
