.TH "NT_id_management_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_id_management_o \- 
.PP
\fBNT_id_management_o\fP class Manage a contiguous list of IDs which might be used or freed at any time.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_id_management_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_id_management_o\fP (\fBNTid\fP smallestId, \fBNTid\fP largestId)"
.br
.RI "\fILowest and highest valid id. \fP"
.ti -1c
.RI "\fBNT_id_management_o\fP (const \fBNT_id_management_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_id_management_o\fP & \fBoperator=\fP (const \fBNT_id_management_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_id_management_o\fP ()"
.br
.ti -1c
.RI "\fBNTbool\fP \fBIsTaken\fP (\fBNTid\fP id) const "
.br
.ti -1c
.RI "\fBNTid\fP \fBLargestIssuedId\fP ()"
.br
.ti -1c
.RI "\fBNTid\fP \fBIssueId\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBFreeId\fP (\fBNTid\fP returnedId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 57 of file nt_id_management_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_id_management_o::NT_id_management_o (\fBNTid\fP smallestId, \fBNTid\fP largestId)"
.SS "NT_id_management_o::NT_id_management_o (const \fBNT_id_management_o\fP & original)"
.SS "virtual NT_id_management_o::~NT_id_management_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreturn\fP NT_id_management_o::FreeId (\fBNTid\fP returnedId)"
.SS "\fBNTid\fP NT_id_management_o::IssueId ()"
.SS "\fBNTbool\fP NT_id_management_o::IsTaken (\fBNTid\fP id) const"
.SS "\fBNTid\fP NT_id_management_o::LargestIssuedId ()"
.SS "const \fBNT_id_management_o\fP& NT_id_management_o::operator= (const \fBNT_id_management_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
