.TH "NT_image_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_image_o \- 
.PP
\fBNT_image_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_image_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.PP
Inherited by \fBNT3D_image_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_image_o\fP (\fBNTsize\fP \fBwidth\fP=128, \fBNTsize\fP \fBheight\fP=64, \fBNTsize\fP \fBcolorDepth\fP=16, \fBNTimageDataFormat\fP \fBdataFormat\fP=NT_RGBA)"
.br
.ti -1c
.RI "\fBNT_image_o\fP (const \fBNT_image_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_image_o\fP & \fBoperator=\fP (const \fBNT_image_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_image_o\fP ()"
.br
.ti -1c
.RI "\fBNTsize\fP \fB_width\fP ()"
.br
.ti -1c
.RI "\fBNTsize\fP \fB_height\fP ()"
.br
.ti -1c
.RI "\fBNTsize\fP \fB_colorDepth\fP ()"
.br
.ti -1c
.RI "\fBNTimageDataFormat\fP \fB_dataFormat\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBLoad\fP (string filename, \fBNTimageFileType\fP fileType=NT_AUTO)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSave\fP (string filename, \fBNTimageFileType\fP fileType=NT_AUTO) const "
.br
.ti -1c
.RI "const valarray< \fBNTsize\fP > * \fBGetImageArray\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fB_imageVecR\fP (\fBNTsize\fP elementIndex) const "
.br
.ti -1c
.RI "\fBNTsize\fP \fB_imageVecI\fP (\fBNTsize\fP elementIndex) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTsize\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBNTsize\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBNTsize\fP \fBcolorDepth\fP"
.br
.ti -1c
.RI "\fBNTimageDataFormat\fP \fBdataFormat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 59 of file nt_image_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_image_o::NT_image_o (\fBNTsize\fP width = \fC128\fP, \fBNTsize\fP height = \fC64\fP, \fBNTsize\fP colorDepth = \fC16\fP, \fBNTimageDataFormat\fP dataFormat = \fCNT_RGBA\fP)"
.SS "NT_image_o::NT_image_o (const \fBNT_image_o\fP & original)"
.SS "virtual NT_image_o::~NT_image_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTsize\fP NT_image_o::_colorDepth ()\fC [inline]\fP"
.PP
Definition at line 69 of file nt_image_obj.h.
.PP
.nf
{ return 24;}
.fi
.SS "\fBNTimageDataFormat\fP NT_image_o::_dataFormat ()\fC [inline]\fP"
.PP
Definition at line 70 of file nt_image_obj.h.
.PP
References dataFormat.
.PP
.nf
{ return dataFormat;}
.fi
.SS "\fBNTsize\fP NT_image_o::_height ()\fC [inline]\fP"
.PP
Definition at line 68 of file nt_image_obj.h.
.PP
References height.
.PP
.nf
{ return height;}
.fi
.SS "\fBNTsize\fP NT_image_o::_imageVecI (\fBNTsize\fP elementIndex) const\fC [inline, protected]\fP"
.PP
Definition at line 80 of file nt_image_obj.h.
.PP
.nf
{ return imageVec[elementIndex]; }
.fi
.SS "\fBNTreal\fP NT_image_o::_imageVecR (\fBNTsize\fP elementIndex) const\fC [inline, protected]\fP"
.PP
Definition at line 79 of file nt_image_obj.h.
.PP
.nf
{ return imageVec[elementIndex]/255.0; }
.fi
.SS "\fBNTsize\fP NT_image_o::_width ()\fC [inline]\fP"
.PP
Definition at line 67 of file nt_image_obj.h.
.PP
References width.
.PP
.nf
{ return width;}
.fi
.SS "const valarray<\fBNTsize\fP>* NT_image_o::GetImageArray () const\fC [inline]\fP"
.PP
Definition at line 74 of file nt_image_obj.h.
.PP
.nf
{return &imageVec;}
.fi
.SS "\fBNTreturn\fP NT_image_o::Load (string filename, \fBNTimageFileType\fP fileType = \fCNT_AUTO\fP)"
.SS "const \fBNT_image_o\fP& NT_image_o::operator= (const \fBNT_image_o\fP & right)"
.SS "\fBNTreturn\fP NT_image_o::Save (string filename, \fBNTimageFileType\fP fileType = \fCNT_AUTO\fP) const\fC [inline]\fP"
.PP
Definition at line 73 of file nt_image_obj.h.
.PP
.nf
{};
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNTsize\fP \fBNT_image_o::colorDepth\fP\fC [protected]\fP"
.PP
Definition at line 84 of file nt_image_obj.h.
.SS "\fBNTimageDataFormat\fP \fBNT_image_o::dataFormat\fP\fC [protected]\fP"
.PP
Definition at line 85 of file nt_image_obj.h.
.PP
Referenced by _dataFormat().
.SS "\fBNTsize\fP \fBNT_image_o::height\fP\fC [protected]\fP"
.PP
Definition at line 83 of file nt_image_obj.h.
.PP
Referenced by _height().
.SS "\fBNTsize\fP \fBNT_image_o::width\fP\fC [protected]\fP"
.PP
Definition at line 82 of file nt_image_obj.h.
.PP
Referenced by _width().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
