.TH "NT_link_list_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_link_list_o \- 
.PP
The default constructor constructs an empty queue.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_list_obj.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_link_list_o\fP (const T &, \fBNT_link_list_o\fP< T > *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static const T & \fBdefval\fP ()"
.br
.RI "\fIPURPOSE: make a default object of type T REMARKS: We use a function because Borland 3.1 doesn't handle static data members in templates correctly. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fB_info\fP"
.br
.ti -1c
.RI "\fBNT_link_list_o\fP< T > * \fB_next\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T> class NT_link_list_o< T >"
The empty operation empties an existing queue. The length operation returns the number of elements currently stored in the queue. PURPOSE: A link in a linked list or queue REMARKS: The data fields are public, hence users of this class should not propagate \fBNT_link_list_o\fP pointers 
.PP
Definition at line 87 of file nt_list_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T > \fBNT_link_list_o\fP< T >::\fBNT_link_list_o\fP (const T & i, \fBNT_link_list_o\fP< T > * n)"
.PP
Definition at line 185 of file nt_list_obj.h.
.PP
.nf
                                                                                    :
   _info(i),
   _next(n)
{}
.fi
.SH "Member Function Documentation"
.PP 
.SS "template<class T > const T & \fBNT_link_list_o\fP< T >::defval ()\fC [static]\fP"
.PP
Definition at line 175 of file nt_list_obj.h.
.PP
.nf
{  static T t;
   return t;
}
.fi
.SH "Member Data Documentation"
.PP 
.SS "template<class T> T \fBNT_link_list_o\fP< T >::\fB_info\fP"
.PP
Definition at line 92 of file nt_list_obj.h.
.PP
Referenced by NT_iterator_list_o< T >::current(), NT_list_o< T >::current(), and NT_list_o< T >::remove().
.SS "template<class T> \fBNT_link_list_o\fP<T>* \fBNT_link_list_o\fP< T >::\fB_next\fP"
.PP
Definition at line 93 of file nt_list_obj.h.
.PP
Referenced by NT_list_o< T >::remove().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
