.TH "nt_list_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_list_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_error_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_link_list_o< T >\fP"
.br
.RI "\fIThe default constructor constructs an empty queue. \fP"
.ti -1c
.RI "class \fBNT_list_o< T >\fP"
.br
.RI "\fIPURPOSE: A linked list. \fP"
.ti -1c
.RI "class \fBNT_iterator_list_o< T >\fP"
.br
.RI "\fIREMARKS: 1. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
