.TH "NT_mem_error_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_mem_error_o \- 
.PP
Class to report memory exhaustion.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_error_obj.h>\fP
.PP
Inherits \fBNT_error_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_mem_error_o\fP (const char *f, int l, const char *expr)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 172 of file nt_error_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_mem_error_o::NT_mem_error_o (const char * f, int l, const char * expr)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
