.TH "nt_main.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_main.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB__STL_NO_DRAND48\fP"
.br
.ti -1c
.RI "#define \fB_NT_MAIN_H_\fP"
.br
.ti -1c
.RI "#define \fBNT_MAJOR_VERSION\fP   0"
.br
.ti -1c
.RI "#define \fBNT_MINOR_VERSION\fP   5"
.br
.ti -1c
.RI "#define \fBNT_STRING_LENGTH\fP   255"
.br
.ti -1c
.RI "#define \fBNT_SEPARATOR\fP   ' ;; '"
.br
.ti -1c
.RI "#define \fBNT_EXPORT\fP   extern"
.br
.ti -1c
.RI "#define \fBNT_TALKLEVEL\fP   9"
.br
.ti -1c
.RI "#define \fBNT_GL_SUPPORT\fP   \fBNT_TRUE\fP"
.br
.ti -1c
.RI "#define \fBNT_GLX_SUPPORT\fP   \fBNT_TRUE\fP"
.br
.ti -1c
.RI "#define \fBNT_DEBUG\fP   true"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define __STL_NO_DRAND48"
.PP
Definition at line 89 of file nt_main.h.
.SS "#define _NT_MAIN_H_"
.PP
Definition at line 93 of file nt_main.h.
.SS "#define NT_DEBUG   true"
.PP
Definition at line 108 of file nt_main.h.
.SS "#define NT_EXPORT   extern"
.PP
Definition at line 101 of file nt_main.h.
.SS "#define NT_GL_SUPPORT   \fBNT_TRUE\fP"
.PP
Definition at line 105 of file nt_main.h.
.SS "#define NT_GLX_SUPPORT   \fBNT_TRUE\fP"
.PP
Definition at line 106 of file nt_main.h.
.SS "#define NT_MAJOR_VERSION   0"
.PP
Definition at line 95 of file nt_main.h.
.SS "#define NT_MINOR_VERSION   5"
.PP
Definition at line 96 of file nt_main.h.
.SS "#define NT_SEPARATOR   ' ;; '"
.PP
Definition at line 99 of file nt_main.h.
.SS "#define NT_STRING_LENGTH   255"
.PP
Definition at line 98 of file nt_main.h.
.SS "#define NT_TALKLEVEL   9"
.PP
Definition at line 102 of file nt_main.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
