.TH "NT_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_o \- 
.PP
Master class for all NT objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_obj.h>\fP
.PP
Inherited by \fBNT3D_color_o\fP, \fBNT3D_light_o\fP, \fBNT3D_material_o\fP, \fBNT3D_o\fP, \fBNT3D_plot_o\fP, \fBNT3D_texture_o\fP, \fBNT3D_vp_spec_o\fP, \fBNT_2dim_histogram_o\fP, \fBNT_date_o\fP, \fBNT_error_o\fP, \fBNT_file_o\fP, \fBNT_gui_drv_o\fP, \fBNT_header_string_o\fP\fC [private]\fP, \fBNT_histogram_o\fP, \fBNT_id_management_o\fP, \fBNT_image_o\fP, \fBNT_multidim_array_o< T >\fP, \fBNT_multidim_array_o< NTsize >\fP, \fBNT_multidim_histogram_o\fP, \fBNT_rnd_dist_o\fP\fC [private]\fP, \fBNT_sequential_statistics_o\fP, \fBNT_simple_markov_o\fP, \fBNT_timing_o\fP, \fBNT_value_o\fP, \fBNT_vec_rnd_dist_o\fP, \fBNT_vector3_o\fP, \fBNT_vector_o\fP, \fBNTBP_object_o\fP, \fBNTBP_tridiag_solver_o\fP, and \fBNTG_graph_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_o\fP ()"
.br
.ti -1c
.RI "\fBNT_o\fP (const \fBNT_o\fP &)"
.br
.ti -1c
.RI "virtual \fB~NT_o\fP ()"
.br
.ti -1c
.RI "\fBNTlong\fP \fB_runnId\fP () const "
.br
.ti -1c
.RI "\fBNTlong\fP \fB_uniqId\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
It provides object accounting, and a unique identifier (uniqId) for each object. The unique id might become ambigous when uniqId gets greater LONG_MAX. However, the initialisation of each NT object with this class might help in synchronisation of a threaded version. 
.PP
Definition at line 79 of file nt_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_o::NT_o ()"
.SS "NT_o::NT_o (const \fBNT_o\fP &)"
.SS "virtual NT_o::~NT_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTlong\fP NT_o::_runnId () const\fC [inline]\fP"
.PP
Definition at line 106 of file nt_obj.h.
.PP
.nf
{
  return runnId;
}
.fi
.SS "\fBNTlong\fP NT_o::_uniqId () const\fC [inline]\fP"
.PP
Definition at line 119 of file nt_obj.h.
.PP
.nf
{
  return uniqId;
}
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
