.TH "nt_physical_constants.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_physical_constants.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fB_NT_PHYSCIAL_CONSTANTS_H_\fP"
.br
.ti -1c
.RI "#define \fBNT_0_CELSIUS\fP   \fBNTreal\fP(273.15)"
.br
.ti -1c
.RI "#define \fBNT_0_KELVIN\fP   \fBNTreal\fP(-273.15)"
.br
.ti -1c
.RI "#define \fBNT_BOLTZMANN\fP   \fBNTreal\fP(1.380658*10e-23)"
.br
.ti -1c
.RI "#define \fBNT_PLANCK\fP   \fBNTreal\fP(6.6260755*10e-34)"
.br
.ti -1c
.RI "#define \fBNT_PROTON_CHARGE\fP   \fBNTreal\fP(1.60217733*10e-19)"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define _NT_PHYSCIAL_CONSTANTS_H_"
.PP
Definition at line 34 of file nt_physical_constants.h.
.SS "#define NT_0_CELSIUS   \fBNTreal\fP(273.15)"
.PP
Definition at line 39 of file nt_physical_constants.h.
.SS "#define NT_0_KELVIN   \fBNTreal\fP(-273.15)"
.PP
Definition at line 40 of file nt_physical_constants.h.
.PP
Referenced by NTBP_membrane_current_o::Set_temperature().
.SS "#define NT_BOLTZMANN   \fBNTreal\fP(1.380658*10e-23)"
.PP
Definition at line 41 of file nt_physical_constants.h.
.SS "#define NT_PLANCK   \fBNTreal\fP(6.6260755*10e-34)"
.PP
Definition at line 42 of file nt_physical_constants.h.
.SS "#define NT_PROTON_CHARGE   \fBNTreal\fP(1.60217733*10e-19)"
.PP
Definition at line 43 of file nt_physical_constants.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
