.TH "NT_rnd_dist_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_rnd_dist_o \- 
.PP
\fBNT_rnd_dist_o\fP is a parent object to individual random distribution objects.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_rnd_dist_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.PP
Inherited by \fBNT_binomial_rnd_dist_o\fP, \fBNT_gaussian_rnd_dist_o\fP, and \fBNT_uniform_rnd_dist_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_rnd_dist_o\fP ()"
.br
.ti -1c
.RI "\fBNT_rnd_dist_o\fP (\fBNTint\fP dim)"
.br
.ti -1c
.RI "\fBNT_rnd_dist_o\fP (const \fBNT_rnd_dist_o\fP &)"
.br
.ti -1c
.RI "\fB~NT_rnd_dist_o\fP ()"
.br
.ti -1c
.RI "virtual \fBNTreal\fP \fBRndVal\fP () const =0"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_mean\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_variance\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "float \fBuniformQuickDirty\fP () const "
.br
.ti -1c
.RI "float \fBuniform1\fP () const "
.br
.ti -1c
.RI "float \fBuniformMT\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBmean\fP"
.br
.ti -1c
.RI "\fBNTreal\fP \fBvariance\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBNT_rnd_dist_o\fP &self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Idea : The usage idea is to call the object which returns a NTreal or \fBNT_vector_o\fP containing random values out of its specific distribution 
.PP
Definition at line 95 of file nt_rnd_dist_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_rnd_dist_o::NT_rnd_dist_o ()"
.SS "NT_rnd_dist_o::NT_rnd_dist_o (\fBNTint\fP dim)"
.SS "NT_rnd_dist_o::NT_rnd_dist_o (const \fBNT_rnd_dist_o\fP &)"
.SS "NT_rnd_dist_o::~NT_rnd_dist_o ()"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NT_rnd_dist_o::_mean () const\fC [inline]\fP"
.PP
Reimplemented in \fBNT_uniform_rnd_dist_o\fP.
.PP
Definition at line 106 of file nt_rnd_dist_obj.h.
.PP
References mean.
.PP
.nf
{ return mean; };           
.fi
.SS "\fBNTreal\fP NT_rnd_dist_o::_variance () const\fC [inline]\fP"
.PP
Reimplemented in \fBNT_uniform_rnd_dist_o\fP.
.PP
Definition at line 107 of file nt_rnd_dist_obj.h.
.PP
References variance.
.PP
.nf
{ return variance; };           
.fi
.SS "virtual \fBNTreal\fP NT_rnd_dist_o::RndVal () const\fC [pure virtual]\fP"
.PP
Implemented in \fBNT_binomial_rnd_dist_o\fP, \fBNT_gaussian_rnd_dist_o\fP, and \fBNT_uniform_rnd_dist_o\fP.
.SS "float NT_rnd_dist_o::uniform1 () const\fC [protected]\fP"
.SS "float NT_rnd_dist_o::uniformMT () const\fC [inline, protected]\fP"
.PP
Definition at line 114 of file nt_rnd_dist_obj.h.
.PP
References MTRand::rand().
.PP
.nf
{ return randgen.rand(); }
.fi
.SS "float NT_rnd_dist_o::uniformQuickDirty () const\fC [protected]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBNT_rnd_dist_o\fP & self)\fC [friend]\fP"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTreal\fP \fBNT_rnd_dist_o::mean\fP\fC [protected]\fP"
.PP
Definition at line 116 of file nt_rnd_dist_obj.h.
.PP
Referenced by NT_uniform_rnd_dist_o::_mean(), and _mean().
.SS "\fBNTreal\fP \fBNT_rnd_dist_o::variance\fP\fC [protected]\fP"
.PP
Definition at line 117 of file nt_rnd_dist_obj.h.
.PP
Referenced by NT_uniform_rnd_dist_o::_variance(), and _variance().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
