.TH "NT_stock_value_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_stock_value_o \- 
.PP
Bbase class for values traded at a stock exchange.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_stock_value_obj.h>\fP
.PP
Inherits \fBNT_value_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_stock_value_o\fP ()"
.br
.ti -1c
.RI "\fBNT_stock_value_o\fP (const \fBNT_stock_value_o\fP &)"
.br
.ti -1c
.RI "\fB~NT_stock_value_o\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &os, const \fBNT_stock_value_o\fP &self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file nt_stock_value_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_stock_value_o::NT_stock_value_o ()"
.SS "NT_stock_value_o::NT_stock_value_o (const \fBNT_stock_value_o\fP &)"
.SS "NT_stock_value_o::~NT_stock_value_o ()"
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & os, const \fBNT_stock_value_o\fP & self)\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
