.TH "nt_sequential_statistics_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_sequential_statistics_obj.h \- 
.PP
.IP "\(bu" 2
\fBNT_sequential_statistics_o\fP class header by Ahmed Aldo Faisal (C) created 5.11.2000 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <values.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_sequential_statistics_o\fP"
.br
.RI "\fI\fBNT_sequential_statistics_o\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt_sequential_statistics_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
