.TH "NT_sequential_statistics_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_sequential_statistics_o \- 
.PP
\fBNT_sequential_statistics_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_sequential_statistics_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_sequential_statistics_o\fP ()"
.br
.ti -1c
.RI "\fBNT_sequential_statistics_o\fP (const \fBNT_sequential_statistics_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_sequential_statistics_o\fP & \fBoperator=\fP (const \fBNT_sequential_statistics_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_sequential_statistics_o\fP ()"
.br
.ti -1c
.RI "void \fBReset\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBNTreal\fP val)"
.br
.ti -1c
.RI "unsigned long int \fB_counter\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_average\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_valSquareAverage\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_variance\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_min\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_max\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "ostream & \fBoperator<<\fP (ostream &str, const \fBNT_sequential_statistics_o\fP &self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 48 of file nt_sequential_statistics_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_sequential_statistics_o::NT_sequential_statistics_o ()"
.SS "NT_sequential_statistics_o::NT_sequential_statistics_o (const \fBNT_sequential_statistics_o\fP & original)"
.SS "virtual NT_sequential_statistics_o::~NT_sequential_statistics_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NT_sequential_statistics_o::_average () const\fC [inline]\fP"
.PP
Definition at line 59 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return average;}
.fi
.SS "unsigned long int NT_sequential_statistics_o::_counter () const\fC [inline]\fP"
.PP
Definition at line 58 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return counter;}
.fi
.SS "\fBNTreal\fP NT_sequential_statistics_o::_max () const\fC [inline]\fP"
.PP
Definition at line 63 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return max;}
.fi
.SS "\fBNTreal\fP NT_sequential_statistics_o::_min () const\fC [inline]\fP"
.PP
Definition at line 62 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return min;}
.fi
.SS "\fBNTreal\fP NT_sequential_statistics_o::_valSquareAverage () const\fC [inline]\fP"
.PP
Definition at line 60 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return valSquareAverage;}
.fi
.SS "\fBNTreal\fP NT_sequential_statistics_o::_variance () const\fC [inline]\fP"
.PP
Definition at line 61 of file nt_sequential_statistics_obj.h.
.PP
.nf
{return variance;}
.fi
.SS "void NT_sequential_statistics_o::Add (\fBNTreal\fP val)"
.SS "const \fBNT_sequential_statistics_o\fP& NT_sequential_statistics_o::operator= (const \fBNT_sequential_statistics_o\fP & right)"
.SS "void NT_sequential_statistics_o::Reset ()"
.SH "Friends And Related Function Documentation"
.PP 
.SS "ostream& operator<< (ostream & str, const \fBNT_sequential_statistics_o\fP & self)\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
