.TH "nt_timing_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_timing_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_timing_o\fP"
.br
.RI "\fI\fBNT_timing_o\fP a stopwatch like measurement object: void \fBstart()\fP : start timing double \fBstop()\fP : stop timing void \fBreset()\fP : set elapsed time to 0.0 double \fBread()\fP : read elapsed time (in seconds). \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
