.TH "NT_uniform_vec_rnd_dist_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_uniform_vec_rnd_dist_o \- 
.PP
\fBNT_uniform_vec_rnd_dist_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_uniform_vec_rnd_dist_obj.h>\fP
.PP
Inherits \fBNT_vec_rnd_dist_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_uniform_vec_rnd_dist_o\fP (\fBNTreal\fP lowerBound, \fBNTreal\fP upperBound, \fBNTsize\fP \fBdim\fP)"
.br
.ti -1c
.RI "\fBNT_uniform_vec_rnd_dist_o\fP (\fBNT_vector_o\fP lowerBound, \fBNT_vector_o\fP upperBound, \fBNTsize\fP \fBdim\fP)"
.br
.ti -1c
.RI "\fBNT_uniform_vec_rnd_dist_o\fP (const \fBNT_uniform_vec_rnd_dist_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_uniform_vec_rnd_dist_o\fP & \fBoperator=\fP (const \fBNT_uniform_vec_rnd_dist_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_uniform_vec_rnd_dist_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 66 of file nt_uniform_vec_rnd_dist_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_uniform_vec_rnd_dist_o::NT_uniform_vec_rnd_dist_o (\fBNTreal\fP lowerBound, \fBNTreal\fP upperBound, \fBNTsize\fP dim)"
.SS "NT_uniform_vec_rnd_dist_o::NT_uniform_vec_rnd_dist_o (\fBNT_vector_o\fP lowerBound, \fBNT_vector_o\fP upperBound, \fBNTsize\fP dim)"
.SS "NT_uniform_vec_rnd_dist_o::NT_uniform_vec_rnd_dist_o (const \fBNT_uniform_vec_rnd_dist_o\fP & original)"
.SS "virtual NT_uniform_vec_rnd_dist_o::~NT_uniform_vec_rnd_dist_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT_uniform_vec_rnd_dist_o\fP& NT_uniform_vec_rnd_dist_o::operator= (const \fBNT_uniform_vec_rnd_dist_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
