.TH "nt_vector3_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nt_vector3_obj.h \- 
.PP
.IP "\(bu" 2
NT_solid_o class declaration by Ahmed Aldo Faisal (C) created 15.10.1998 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'nt_error_obj.h'\fP
.br
\fC#include 'nt_aux_math_func.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNT_vector3_o\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_UnitXVec3\fP ()"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_UnitYVec3\fP ()"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_UnitZVec3\fP ()"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_UnitMinusZVec3\fP ()"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_UnitXYZVec3\fP ()"
.br
.ti -1c
.RI "\fBNT_vector3_o\fP & \fBNT_OriginVec3\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBnt_vector3_obj.h\fP.
.SH "Function Documentation"
.PP 
.SS "\fBNT_vector3_o\fP& NT_OriginVec3 ()"
.PP
Referenced by NT_vector3_o::Norm(), NT3D_object_o::RotateNull(), and NT3D_object_o::TranslateNull().
.SS "\fBNT_vector3_o\fP& NT_UnitMinusZVec3 ()"
.SS "\fBNT_vector3_o\fP& NT_UnitXVec3 ()"
.SS "\fBNT_vector3_o\fP& NT_UnitXYZVec3 ()"
.SS "\fBNT_vector3_o\fP& NT_UnitYVec3 ()"
.SS "\fBNT_vector3_o\fP& NT_UnitZVec3 ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
