.TH "NT_vec_rnd_dist_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NT_vec_rnd_dist_o \- 
.PP
\fBNT_vec_rnd_dist_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nt_vec_rnd_dist_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.PP
Inherited by \fBNT_gaussian_vec_rnd_dist_o\fP, and \fBNT_uniform_vec_rnd_dist_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNT_vec_rnd_dist_o\fP (\fBNTsize\fP newDim=3)"
.br
.ti -1c
.RI "\fBNT_vec_rnd_dist_o\fP (const \fBNT_vec_rnd_dist_o\fP &original)"
.br
.ti -1c
.RI "const \fBNT_vec_rnd_dist_o\fP & \fBoperator=\fP (const \fBNT_vec_rnd_dist_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NT_vec_rnd_dist_o\fP ()"
.br
.ti -1c
.RI "\fBNT_vector_o\fP \fBRndVec\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTsize\fP \fBdim\fP"
.br
.ti -1c
.RI "vector< \fBNT_rnd_dist_o\fP * > \fBrndDistPtrVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 73 of file nt_vec_rnd_dist_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NT_vec_rnd_dist_o::NT_vec_rnd_dist_o (\fBNTsize\fP newDim = \fC3\fP)"
.SS "NT_vec_rnd_dist_o::NT_vec_rnd_dist_o (const \fBNT_vec_rnd_dist_o\fP & original)"
.SS "virtual NT_vec_rnd_dist_o::~NT_vec_rnd_dist_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNT_vec_rnd_dist_o\fP& NT_vec_rnd_dist_o::operator= (const \fBNT_vec_rnd_dist_o\fP & right)"
.SS "\fBNT_vector_o\fP NT_vec_rnd_dist_o::RndVec () const"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTsize\fP \fBNT_vec_rnd_dist_o::dim\fP\fC [protected]\fP"
.PP
Definition at line 86 of file nt_vec_rnd_dist_obj.h.
.SS "vector<\fBNT_rnd_dist_o\fP *> \fBNT_vec_rnd_dist_o::rndDistPtrVec\fP\fC [protected]\fP"
.PP
Definition at line 87 of file nt_vec_rnd_dist_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
