.TH "ntbp_ion_channels_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntbp_ion_channels_obj.h \- 
.PP
.IP "\(bu" 2
\fBNTBP_ion_channels_o\fP class header by Ahmed Aldo Faisal (C) created 15.3.2001 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'ntbp_object_obj.h'\fP
.br
\fC#include 'nt_error_obj.h'\fP
.br
\fC#include 'nt_uniform_rnd_dist_obj.h'\fP
.br
\fC#include 'nt_binomial_rnd_dist_obj.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNTBP_ion_channels_o\fP"
.br
.RI "\fI\fBNTBP_ion_channels_o\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBntbp_ion_channels_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
