.TH "NTBP_membrane_compartment_sequence_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_membrane_compartment_sequence_o \- 
.PP
\fBNTBP_membrane_compartment_sequence_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_membrane_compartment_sequence_obj.h>\fP
.PP
Inherits \fBNTBP_membrane_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_membrane_compartment_sequence_o\fP ()"
.br
.ti -1c
.RI "\fBNTBP_membrane_compartment_sequence_o\fP (const \fBNTBP_membrane_compartment_sequence_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_membrane_compartment_sequence_o\fP & \fBoperator=\fP (const \fBNTBP_membrane_compartment_sequence_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_membrane_compartment_sequence_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBPushBack\fP (\fBNTBP_cylindrical_compartment_o\fP *compartPtr)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBInit\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBInitialStep\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStep\fP ()"
.br
.ti -1c
.RI "void \fBShowVoltage\fP ()"
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fB_vVec\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBMembraneVoltage\fP (\fBNTsize\fP compartmentId)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBInjectCurrent\fP (\fBNTreal\fP current, \fBNTsize\fP compartmentId)"
.br
.ti -1c
.RI "\fBNTsize\fP \fB_numCompartments\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBCompartmentSequenceChannelStateTimeConstant\fP () const "
.br
.ti -1c
.RI "void \fBShowHinesMatrix\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAttachedCurrent\fP (\fBNTsize\fP compIndex, \fBNTsize\fP currIndex)"
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBOpenChannels\fP (\fBNTsize\fP currIndex) const "
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBOpenChannelsRatio\fP (\fBNTsize\fP currIndex) const "
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBNumChannels\fP (\fBNTsize\fP currIndex) const "
.br
.ti -1c
.RI "\fBNTreturn\fP \fBWriteMembranePotential\fP (ofstream &file)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBWriteCurrent\fP (ofstream &file, \fBNTsize\fP currentIndex)"
.br
.ti -1c
.RI "bool \fBGillespieStep\fP ()"
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBGiveCurrent\fP (\fBNTsize\fP index)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "vector< \fBNTreal\fP > \fBZadorPearlmutterSolveTriDiag\fP (vector< \fBNTreal\fP > lNewVec, vector< \fBNTreal\fP > dNewVec, vector< \fBNTreal\fP >uNewVec, vector< \fBNTreal\fP >rNewVec) const "
.br
.RI "\fICRAP not working. \fP"
.ti -1c
.RI "vector< \fBNTreal\fP > \fBMascagniSolveTriDiag\fP (vector< \fBNTreal\fP > lNewVec, vector< \fBNTreal\fP >dNewVec, vector< \fBNTreal\fP >uNewVec, vector< \fBNTreal\fP >rNewVec) const "
.br
.RI "\fICRAP not working. \fP"
.ti -1c
.RI "vector< \fBNTreal\fP > \fBNumericalRecipesSolveTriDiag\fP (const vector< \fBNTreal\fP > &l, const vector< \fBNTreal\fP > &d, const vector< \fBNTreal\fP > &u, const vector< \fBNTreal\fP > &r) const "
.br
.RI "\fIWORKING ! \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "vector< \fBNTBP_cylindrical_compartment_o\fP * > \fBcompartmentVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 63 of file ntbp_membrane_compartment_sequence_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_membrane_compartment_sequence_o::NTBP_membrane_compartment_sequence_o ()"
.SS "NTBP_membrane_compartment_sequence_o::NTBP_membrane_compartment_sequence_o (const \fBNTBP_membrane_compartment_sequence_o\fP & original)"
.SS "virtual NTBP_membrane_compartment_sequence_o::~NTBP_membrane_compartment_sequence_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTsize\fP NTBP_membrane_compartment_sequence_o::_numCompartments () const\fC [inline]\fP"
.PP
Definition at line 78 of file ntbp_membrane_compartment_sequence_obj.h.
.PP
.nf
{ cerr << 'Voltage [';
.fi
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::_vVec ()\fC [inline]\fP"
.PP
Definition at line 75 of file ntbp_membrane_compartment_sequence_obj.h.
.PP
.nf
{ cerr << 'Voltage [';
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_sequence_o::AttachedCurrent (\fBNTsize\fP compIndex, \fBNTsize\fP currIndex)\fC [inline]\fP"
.PP
Definition at line 83 of file ntbp_membrane_compartment_sequence_obj.h.
.PP
.nf
{ return vVec;}
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_sequence_o::CompartmentSequenceChannelStateTimeConstant () const"
.SS "bool NTBP_membrane_compartment_sequence_o::GillespieStep ()"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::GiveCurrent (\fBNTsize\fP index)"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::Init ()"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::InitialStep ()"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::InjectCurrent (\fBNTreal\fP current, \fBNTsize\fP compartmentId)"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::MascagniSolveTriDiag (vector< \fBNTreal\fP > lNewVec, vector< \fBNTreal\fP > dNewVec, vector< \fBNTreal\fP > uNewVec, vector< \fBNTreal\fP > rNewVec) const\fC [protected]\fP"
.SS "\fBNTreal\fP NTBP_membrane_compartment_sequence_o::MembraneVoltage (\fBNTsize\fP compartmentId)\fC [inline]\fP"
.PP
Definition at line 76 of file ntbp_membrane_compartment_sequence_obj.h.
.PP
.nf
{ cerr << 'Voltage [';
.fi
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::NumChannels (\fBNTsize\fP currIndex) const"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::NumericalRecipesSolveTriDiag (const vector< \fBNTreal\fP > & l, const vector< \fBNTreal\fP > & d, const vector< \fBNTreal\fP > & u, const vector< \fBNTreal\fP > & r) const\fC [protected]\fP"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::OpenChannels (\fBNTsize\fP currIndex) const"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::OpenChannelsRatio (\fBNTsize\fP currIndex) const"
.SS "const \fBNTBP_membrane_compartment_sequence_o\fP& NTBP_membrane_compartment_sequence_o::operator= (const \fBNTBP_membrane_compartment_sequence_o\fP & right)"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::PushBack (\fBNTBP_cylindrical_compartment_o\fP * compartPtr)"
.SS "void NTBP_membrane_compartment_sequence_o::ShowHinesMatrix ()"
.SS "void NTBP_membrane_compartment_sequence_o::ShowVoltage ()\fC [inline]\fP"
.PP
Definition at line 68 of file ntbp_membrane_compartment_sequence_obj.h.
.PP
.nf
                   { cerr << 'Voltage [';
.fi
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::Step ()\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_object_o\fP.
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::WriteCurrent (ofstream & file, \fBNTsize\fP currentIndex)"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_sequence_o::WriteMembranePotential (ofstream & file)"
.SS "vector<\fBNTreal\fP> NTBP_membrane_compartment_sequence_o::ZadorPearlmutterSolveTriDiag (vector< \fBNTreal\fP > lNewVec, vector< \fBNTreal\fP > dNewVec, vector< \fBNTreal\fP > uNewVec, vector< \fBNTreal\fP > rNewVec) const\fC [protected]\fP"
.SH "Member Data Documentation"
.PP 
.SS "vector< \fBNTBP_cylindrical_compartment_o\fP* > \fBNTBP_membrane_compartment_sequence_o::compartmentVec\fP\fC [protected]\fP"
.PP
Definition at line 103 of file ntbp_membrane_compartment_sequence_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
