.TH "NTBP_hh_sga_potassium_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_hh_sga_potassium_current_o \- 
.PP
\fBNTBP_hh_sga_potassium_current_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_hh_sga_potassium_current_obj.h>\fP
.PP
Inherits \fBNTBP_hh_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_hh_sga_potassium_current_o\fP (\fBNTreal\fP area)"
.br
.ti -1c
.RI "\fBNTBP_hh_sga_potassium_current_o\fP (const \fBNTBP_hh_sga_potassium_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_hh_sga_potassium_current_o\fP & \fBoperator=\fP (const \fBNTBP_hh_sga_potassium_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_hh_sga_potassium_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBOpenChannelsRatio\fP () const "
.br
.RI "\fINumber of open over total number of channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBComputeConductance\fP ()"
.br
.RI "\fIcompute and return conductance in mSiemens \fP"
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP vM)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "void \fBShow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 57 of file ntbp_hh_sga_potassium_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_hh_sga_potassium_current_o::NTBP_hh_sga_potassium_current_o (\fBNTreal\fP area)"
.SS "NTBP_hh_sga_potassium_current_o::NTBP_hh_sga_potassium_current_o (const \fBNTBP_hh_sga_potassium_current_o\fP & original)"
.SS "virtual NTBP_hh_sga_potassium_current_o::~NTBP_hh_sga_potassium_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_hh_sga_potassium_current_o::ComputeConductance ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "void NTBP_hh_sga_potassium_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_hh_sga_potassium_current_o::OpenChannelsRatio () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.PP
Definition at line 66 of file ntbp_hh_sga_potassium_current_obj.h.
.PP
.nf
{ NTreal temp = n*n; return temp*temp;}
.fi
.SS "const \fBNTBP_hh_sga_potassium_current_o\fP& NTBP_hh_sga_potassium_current_o::operator= (const \fBNTBP_hh_sga_potassium_current_o\fP & right)"
.SS "void NTBP_hh_sga_potassium_current_o::Show ()\fC [inline, virtual]\fP"
.PP
Implements \fBNTBP_hh_current_o\fP.
.PP
Definition at line 70 of file ntbp_hh_sga_potassium_current_obj.h.
.PP
.nf
{ cout<<'alphaN= ' << alphaN << '\t betaN= ' << betaN << '\t n= ' << n ;}
.fi
.SS "\fBNTreturn\fP NTBP_hh_sga_potassium_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
