.TH "NTBP_patlak_sodium_ion_channels_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_patlak_sodium_ion_channels_o \- 
.PP
\fBNTBP_patlak_sodium_ion_channels_o\fP class The ion channels kinetical scheme is based on J.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_patlak_sodium_ion_channels_obj.h>\fP
.PP
Inherits \fBNTBP_ion_channels_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_patlak_sodium_ion_channels_o\fP (\fBNTsize\fP numNewChannels=1)"
.br
.ti -1c
.RI "\fBNTBP_patlak_sodium_ion_channels_o\fP (const \fBNTBP_patlak_sodium_ion_channels_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_patlak_sodium_ion_channels_o\fP & \fBoperator=\fP (const \fBNTBP_patlak_sodium_ion_channels_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_patlak_sodium_ion_channels_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStep\fP ()"
.br
.ti -1c
.RI "void \fBShowStates\fP () const "
.br
.ti -1c
.RI "\fBNTsize\fP \fBNumOpen\fP () const "
.br
.ti -1c
.RI "\fBNTsize\fP \fBNumClosed\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.RI "\fISum of escape rates from current state [1/s]. \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBUpdateStateProb\fP (vector< \fBNTreal\fP > rateConstVec)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSteadyStateDistribution\fP ()"
.br
.RI "\fIset the steady state distribution of channel states for current rate constants, DIRTY HACK \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBBinomialStep\fP ()"
.br
.RI "\fINo descriptions. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Patlak (1991) 'Molecular kinetics of voltage-dependent Na^+ channels', Physiological Review, Vol. 71, No. 6, p. 1047-1080 and implements model number 8. It consists of 7 discrete states, of which 1-4 are closed, 5 is open and 6-7 are inactivated. 
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 54 of file ntbp_patlak_sodium_ion_channels_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_patlak_sodium_ion_channels_o::NTBP_patlak_sodium_ion_channels_o (\fBNTsize\fP numNewChannels = \fC1\fP)"
.SS "NTBP_patlak_sodium_ion_channels_o::NTBP_patlak_sodium_ion_channels_o (const \fBNTBP_patlak_sodium_ion_channels_o\fP & original)"
.SS "virtual NTBP_patlak_sodium_ion_channels_o::~NTBP_patlak_sodium_ion_channels_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreturn\fP NTBP_patlak_sodium_ion_channels_o::BinomialStep ()\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_ion_channels_o\fP.
.SS "\fBNTreal\fP NTBP_patlak_sodium_ion_channels_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.
.SS "\fBNTsize\fP NTBP_patlak_sodium_ion_channels_o::NumClosed () const\fC [inline, virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.
.PP
Definition at line 65 of file ntbp_patlak_sodium_ion_channels_obj.h.
.PP
References NTBP_ion_channels_o::_numChannels(), and NumOpen().
.PP
.nf
{ return _numChannels() - NumOpen();}
.fi
.SS "\fBNTsize\fP NTBP_patlak_sodium_ion_channels_o::NumOpen () const\fC [inline, virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.
.PP
Definition at line 64 of file ntbp_patlak_sodium_ion_channels_obj.h.
.PP
References NTBP_ion_channels_o::stateCounterVec.
.PP
Referenced by NumClosed().
.PP
.nf
{ return stateCounterVec[5];} // because 0 is num total channels
.fi
.SS "const \fBNTBP_patlak_sodium_ion_channels_o\fP& NTBP_patlak_sodium_ion_channels_o::operator= (const \fBNTBP_patlak_sodium_ion_channels_o\fP & right)"
.SS "void NTBP_patlak_sodium_ion_channels_o::ShowStates () const\fC [virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.
.SS "\fBNTreturn\fP NTBP_patlak_sodium_ion_channels_o::SteadyStateDistribution ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.
.SS "\fBNTreturn\fP NTBP_patlak_sodium_ion_channels_o::Step ()\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_object_o\fP.
.SS "\fBNTreturn\fP NTBP_patlak_sodium_ion_channels_o::UpdateStateProb (vector< \fBNTreal\fP > rateConstVec)\fC [virtual]\fP"
.PP
Implements \fBNTBP_ion_channels_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
