.TH "NTBP_cylindrical_compartment_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_cylindrical_compartment_o \- 
.PP
\fBNTBP_cylindrical_compartment_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_cylindrical_compartment_obj.h>\fP
.PP
Inherits \fBNTBP_membrane_compartment_o\fP.
.PP
Inherited by \fBNTBP_custom_cylindrical_compartment_o\fP, \fBNTBP_k_only_sga_cylindrical_compartment_o\fP, \fBNTBP_na_only_sga_cylindrical_compartment_o\fP, \fBNTBP_sga_cylindrical_compartment_o\fP, \fBNTBP_simple_myelinated_cylindrical_compartment_o\fP, and \fBNTBP_simple_ranvier_cylindrical_compartment_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_cylindrical_compartment_o\fP (\fBNTreal\fP length, \fBNTreal\fP diameter)"
.br
.ti -1c
.RI "\fBNTBP_cylindrical_compartment_o\fP (const \fBNTBP_cylindrical_compartment_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_cylindrical_compartment_o\fP & \fBoperator=\fP (const \fBNTBP_cylindrical_compartment_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_cylindrical_compartment_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBActiveLengthConstant\fP ()"
.br
.RI "\fIlength constant in muMeter for instantenous membrane conductance \fP"
.ti -1c
.RI "\fBNTreal\fP \fB_CrosssectionalArea\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_diameter\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_radius\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_length\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 48 of file ntbp_cylindrical_compartment_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o (\fBNTreal\fP length, \fBNTreal\fP diameter)"
.SS "NTBP_cylindrical_compartment_o::NTBP_cylindrical_compartment_o (const \fBNTBP_cylindrical_compartment_o\fP & original)"
.SS "virtual NTBP_cylindrical_compartment_o::~NTBP_cylindrical_compartment_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_cylindrical_compartment_o::_CrosssectionalArea () const\fC [inline]\fP"
.PP
Definition at line 59 of file ntbp_cylindrical_compartment_obj.h.
.PP
References _radius().
.PP
.nf
{return _radius() * _radius() * M_PI;}
.fi
.SS "\fBNTreal\fP NTBP_cylindrical_compartment_o::_diameter () const\fC [inline]\fP"
.PP
Definition at line 61 of file ntbp_cylindrical_compartment_obj.h.
.PP
Referenced by _radius(), and ActiveLengthConstant().
.PP
.nf
{ return diameter;}
.fi
.SS "\fBNTreal\fP NTBP_cylindrical_compartment_o::_length () const\fC [inline]\fP"
.PP
Definition at line 65 of file ntbp_cylindrical_compartment_obj.h.
.PP
.nf
{ return length; }
.fi
.SS "\fBNTreal\fP NTBP_cylindrical_compartment_o::_radius () const\fC [inline]\fP"
.PP
Definition at line 63 of file ntbp_cylindrical_compartment_obj.h.
.PP
References _diameter().
.PP
Referenced by _CrosssectionalArea().
.PP
.nf
{ return _diameter()/2.0;}
.fi
.SS "\fBNTreal\fP NTBP_cylindrical_compartment_o::ActiveLengthConstant ()\fC [inline]\fP"
.PP
Definition at line 57 of file ntbp_cylindrical_compartment_obj.h.
.PP
References _diameter(), NTBP_membrane_compartment_o::_rA(), and NTBP_membrane_compartment_o::TotalConductance().
.PP
.nf
{ return _diameter()/(4.0 * _rA() * 1.0e4 * TotalConductance());}
.fi
.SS "const \fBNTBP_cylindrical_compartment_o\fP& NTBP_cylindrical_compartment_o::operator= (const \fBNTBP_cylindrical_compartment_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
