.TH "NTBP_membrane_compartment_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_membrane_compartment_o \- 
.PP
\fBNTBP_membrane_compartment_o\fP class acts as a 'container + glue' for the various membrane_current classes that can be attached to it.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_membrane_compartment_obj.h>\fP
.PP
Inherits \fBNTBP_object_o\fP.
.PP
Inherited by \fBNTBP_cylindrical_compartment_o\fP, \fBNTBP_membrane_patch_o\fP, and \fBNTBP_spherical_compartment_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_membrane_compartment_o\fP (\fBNTreal\fP area)"
.br
.ti -1c
.RI "\fBNTBP_membrane_compartment_o\fP (const \fBNTBP_membrane_compartment_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_membrane_compartment_o\fP & \fBoperator=\fP (const \fBNTBP_membrane_compartment_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_membrane_compartment_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBAttachCurrent\fP (\fBNTBP_membrane_current_o\fP *currentPtr, \fBNTBPcurrentType\fP type)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStep\fP (\fBNTreal\fP newVM)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBInjectCurrent\fP (\fBNTreal\fP current)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAttachedCurrent\fP (\fBNTsize\fP currentIndex)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAttachedConductance\fP (\fBNTsize\fP currentIndex)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAttachedReversalPotential\fP (\fBNTsize\fP currentIndex)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBTimeConstant\fP ()"
.br
.RI "\fImembrane time constant at instaneous membrane conductivity in ms \fP"
.ti -1c
.RI "const \fBNTBP_membrane_current_o\fP * \fBCurrent\fP (\fBNTsize\fP currentIndex)"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_area\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_vM\fP () const "
.br
.ti -1c
.RI "void \fBSet_cM\fP (\fBNTreal\fP newCm)"
.br
.RI "\fISet specific membrane capacitance in muF / cm^2. \fP"
.ti -1c
.RI "\fBNTreal\fP \fB_cM\fP () const "
.br
.ti -1c
.RI "void \fBSet_rA\fP (\fBNTreal\fP newRa)"
.br
.RI "\fISet specific axoplasmic resistivity in Ohm cm. \fP"
.ti -1c
.RI "\fBNTreal\fP \fB_rA\fP () const "
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSet_temperature\fP (\fBNTreal\fP newTemp)"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_temperature\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_compartmentMembraneCapacitance\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBCompartmentMembraneCapacitance\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBCompartmentMembraneNetCurrent\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBCompartmentChannelStateTimeConstant\fP () const "
.br
.RI "\fIin 1/mSec or 1 kHz \fP"
.ti -1c
.RI "bool \fBGillespieStep\fP ()"
.br
.ti -1c
.RI "void \fBShowParam\fP () const "
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBTotalConductance\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBWeightedConductance\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBvM\fP"
.br
.ti -1c
.RI "\fBNTreal\fP \fBiInj\fP"
.br
.ti -1c
.RI "vector< \fBNTBP_membrane_current_o\fP * > \fBcurrentVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
1. rA, rM and cM are set to (arbitrary) standard values, overwrite in derived class 2. leak current IS incorported into the COMPARTMENT VECTOR 
.RE
.PP

.PP
Definition at line 71 of file ntbp_membrane_compartment_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_membrane_compartment_o::NTBP_membrane_compartment_o (\fBNTreal\fP area)"
.SS "NTBP_membrane_compartment_o::NTBP_membrane_compartment_o (const \fBNTBP_membrane_compartment_o\fP & original)"
.SS "virtual NTBP_membrane_compartment_o::~NTBP_membrane_compartment_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_area () const\fC [inline]\fP"
.PP
Definition at line 89 of file ntbp_membrane_compartment_obj.h.
.PP
Referenced by TimeConstant().
.PP
.nf
{ return area; }
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_cM () const\fC [inline]\fP"
.PP
Definition at line 95 of file ntbp_membrane_compartment_obj.h.
.PP
Referenced by TimeConstant().
.PP
.nf
{ return cM; }
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_compartmentMembraneCapacitance () const\fC [inline]\fP"
.PP
Definition at line 105 of file ntbp_membrane_compartment_obj.h.
.PP
.nf
{ return compartmentMembraneCapacitance; }
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_rA () const\fC [inline]\fP"
.PP
Definition at line 99 of file ntbp_membrane_compartment_obj.h.
.PP
Referenced by NTBP_cylindrical_compartment_o::ActiveLengthConstant().
.PP
.nf
{ return rA; }
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_temperature () const\fC [inline]\fP"
.PP
Definition at line 103 of file ntbp_membrane_compartment_obj.h.
.PP
.nf
{ return temperature;}
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::_vM () const\fC [inline]\fP"
.PP
Definition at line 91 of file ntbp_membrane_compartment_obj.h.
.PP
References vM.
.PP
Referenced by NTBP_membrane_patch_o::MembranePotential().
.PP
.nf
{ return vM; }
.fi
.SS "\fBNTreturn\fP NTBP_membrane_compartment_o::AttachCurrent (\fBNTBP_membrane_current_o\fP * currentPtr, \fBNTBPcurrentType\fP type)"
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::AttachedConductance (\fBNTsize\fP currentIndex)\fC [inline]\fP"
.PP
Definition at line 83 of file ntbp_membrane_compartment_obj.h.
.PP
References currentVec, and NT_ASSERT.
.PP
.nf
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_conductance();}
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::AttachedCurrent (\fBNTsize\fP currentIndex)\fC [inline]\fP"
.PP
Definition at line 82 of file ntbp_membrane_compartment_obj.h.
.PP
References currentVec, and NT_ASSERT.
.PP
.nf
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_current();}
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::AttachedReversalPotential (\fBNTsize\fP currentIndex)\fC [inline]\fP"
.PP
Definition at line 84 of file ntbp_membrane_compartment_obj.h.
.PP
References currentVec, and NT_ASSERT.
.PP
.nf
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1]->_reversalPotential();}
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::CompartmentChannelStateTimeConstant () const"
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::CompartmentMembraneCapacitance () const"
.PP
Referenced by Set_cM().
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::CompartmentMembraneNetCurrent () const"
.SS "const \fBNTBP_membrane_current_o\fP* NTBP_membrane_compartment_o::Current (\fBNTsize\fP currentIndex)\fC [inline]\fP"
.PP
Definition at line 87 of file ntbp_membrane_compartment_obj.h.
.PP
References currentVec, and NT_ASSERT.
.PP
.nf
{NT_ASSERT((currentIndex > 0) && (currentIndex-1 < currentVec.size())); return currentVec[currentIndex-1];}
.fi
.SS "bool NTBP_membrane_compartment_o::GillespieStep ()"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_o::InjectCurrent (\fBNTreal\fP current)"
.SS "const \fBNTBP_membrane_compartment_o\fP& NTBP_membrane_compartment_o::operator= (const \fBNTBP_membrane_compartment_o\fP & right)"
.SS "void NTBP_membrane_compartment_o::Set_cM (\fBNTreal\fP newCm)\fC [inline]\fP"
.PP
Definition at line 93 of file ntbp_membrane_compartment_obj.h.
.PP
References CompartmentMembraneCapacitance().
.PP
.nf
{ cM = newCm;  compartmentMembraneCapacitance = CompartmentMembraneCapacitance(); }
.fi
.SS "void NTBP_membrane_compartment_o::Set_rA (\fBNTreal\fP newRa)\fC [inline]\fP"
.PP
Definition at line 97 of file ntbp_membrane_compartment_obj.h.
.PP
.nf
{ rA = newRa;}
.fi
.SS "\fBNTreturn\fP NTBP_membrane_compartment_o::Set_temperature (\fBNTreal\fP newTemp)\fC [inline]\fP"
.PP
Definition at line 101 of file ntbp_membrane_compartment_obj.h.
.PP
References currentVec, and Set_temperature().
.PP
Referenced by Set_temperature().
.PP
.nf
{ temperature = newTemp; for (NTsize i = 0; i < currentVec.size(); i++) currentVec[i]->Set_temperature(newTemp); return NT_SUCCESS;}
.fi
.SS "void NTBP_membrane_compartment_o::ShowParam () const"
.SS "\fBNTreturn\fP NTBP_membrane_compartment_o::Step (\fBNTreal\fP newVM)"
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::TimeConstant ()\fC [inline]\fP"
.PP
Definition at line 86 of file ntbp_membrane_compartment_obj.h.
.PP
References _area(), _cM(), and TotalConductance().
.PP
.nf
{ return (_cM()/TotalConductance())*_area()*1.0e8; }
.fi
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::TotalConductance () const\fC [protected]\fP"
.PP
Referenced by NTBP_cylindrical_compartment_o::ActiveLengthConstant(), and TimeConstant().
.SS "\fBNTreal\fP NTBP_membrane_compartment_o::WeightedConductance () const\fC [protected]\fP"
.SH "Member Data Documentation"
.PP 
.SS "vector< \fBNTBP_membrane_current_o\fP * > \fBNTBP_membrane_compartment_o::currentVec\fP\fC [protected]\fP"
.PP
Definition at line 124 of file ntbp_membrane_compartment_obj.h.
.PP
Referenced by AttachedConductance(), AttachedCurrent(), AttachedReversalPotential(), Current(), NTBP_membrane_patch_o::MembraneCurrent(), and Set_temperature().
.SS "\fBNTreal\fP \fBNTBP_membrane_compartment_o::iInj\fP\fC [protected]\fP"
.PP
Definition at line 123 of file ntbp_membrane_compartment_obj.h.
.SS "\fBNTreal\fP \fBNTBP_membrane_compartment_o::vM\fP\fC [protected]\fP"
.PP
Definition at line 122 of file ntbp_membrane_compartment_obj.h.
.PP
Referenced by _vM().

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
