.TH "ntbp_sga_sodium_current_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntbp_sga_sodium_current_obj.h \- 
.PP
.IP "\(bu" 2
\fBNTBP_sga_sodium_current_o\fP class header by Ahmed Aldo Faisal (C) created 16.3.2001 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'ntbp_channels_current_obj.h'\fP
.br
\fC#include 'ntbp_sodium_ion_channels_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNTBP_sga_sodium_current_o\fP"
.br
.RI "\fI\fBNTBP_sga_sodium_current_o\fP class Channel density 330/muM^2 Single channel conductivity 4 pS Temperature 9 Celsius (see Hille (1992) p. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBntbp_sga_sodium_current_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
