.TH "NTBP_hranvier_sodium_multi_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_hranvier_sodium_multi_current_o \- 
.PP
\fBNTBP_hranvier_sodium_multi_current_o\fP class based on Schwartz, J.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_hranvier_sodium_multi_current_obj.h>\fP
.PP
Inherits \fBNTBP_multi_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_hranvier_sodium_multi_current_o\fP (\fBNTreal\fP area, \fBNTreal\fP \fBdensity\fP=110, \fBNTreal\fP channelConductance=1.3e-8, NTreal vBase=-84)"
.br
.ti -1c
.RI "\fBNTBP_hranvier_sodium_multi_current_o\fP (const \fBNTBP_hranvier_sodium_multi_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_hranvier_sodium_multi_current_o\fP & \fBoperator=\fP (const \fBNTBP_hranvier_sodium_multi_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_hranvier_sodium_multi_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.RI "\fIin 1/ms or kHz \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBOpenChannels\fP () const "
.br
.RI "\fINumber of open ionic channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBComputeConductance\fP ()"
.br
.RI "\fIcompute and return conductance in mSiemens \fP"
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP vM)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "void \fBShowChannelStatePopulation\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAlphaM\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBBetaM\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAlphaH\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBBetaH\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "void \fBShowParam\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
and Reid, G. and Bostock, H. (1995) 'Action potentials and membrane currents in the human node of Ranvier' J.Physiol. 430:283-292
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 64 of file ntbp_hranvier_sodium_multi_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_hranvier_sodium_multi_current_o::NTBP_hranvier_sodium_multi_current_o (\fBNTreal\fP area, \fBNTreal\fP density = \fC110\fP, \fBNTreal\fP channelConductance = \fC1.3e-8\fP, \fBNTreal\fP vBase = \fC-84\fP)"
.SS "NTBP_hranvier_sodium_multi_current_o::NTBP_hranvier_sodium_multi_current_o (const \fBNTBP_hranvier_sodium_multi_current_o\fP & original)"
.SS "virtual NTBP_hranvier_sodium_multi_current_o::~NTBP_hranvier_sodium_multi_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::AlphaH (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 87 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_multi_current_o::_vBase().
.PP
.nf
{    vM += _vBase(); return 0.0336*(-111.0-vM)/(1-exp((vM+111.0)/11.0)); }
.fi
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::AlphaM (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 85 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_multi_current_o::_vBase().
.PP
.nf
{      vM += _vBase(); return 1.86*(vM+18.4)/(1-exp((-18.4-vM)/10.3));}
.fi
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::BetaH (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 88 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_multi_current_o::_vBase().
.PP
.nf
{  vM += _vBase(); return 2.30/(1+exp((-28.8-vM)/13.4)); }
.fi
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::BetaM (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 86 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_multi_current_o::_vBase().
.PP
.nf
{  vM += _vBase(); return 0.0860*(-22.7-vM)/(1-exp((vM+22.7)/9.16)); }
.fi
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::ComputeConductance ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "void NTBP_hranvier_sodium_multi_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_hranvier_sodium_multi_current_o::OpenChannels () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "const \fBNTBP_hranvier_sodium_multi_current_o\fP& NTBP_hranvier_sodium_multi_current_o::operator= (const \fBNTBP_hranvier_sodium_multi_current_o\fP & right)"
.SS "void NTBP_hranvier_sodium_multi_current_o::Show ()\fC [inline]\fP"
.PP
Definition at line 83 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_ion_channels_o::_numChannels(), NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
.PP
.nf
            {  cout << ' alphaM= ' << alphaM << '\t betaM= ' << betaM << '\t openRatio= ' << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << '\t alphaH= ' << alphaH << '\t betaH= ' << betaH << '\t openNum= ' << channelsPtr->NumOpen();}
.fi
.SS "void NTBP_hranvier_sodium_multi_current_o::ShowChannelStatePopulation ()\fC [inline]\fP"
.PP
Definition at line 82 of file ntbp_hranvier_sodium_multi_current_obj.h.
.PP
References NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
.PP
.nf
{ channelsPtr->ShowStates(); }
.fi
.SS "void NTBP_hranvier_sodium_multi_current_o::ShowParam () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreturn\fP NTBP_hranvier_sodium_multi_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
