.TH "NTBP_delayed_potassium_rectifier_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_delayed_potassium_rectifier_current_o \- 
.PP
\fBNTBP_delayed_potassium_rectifier_current_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_delayed_potassium_rectifier_current_obj.h>\fP
.PP
Inherits \fBNTBP_channels_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_delayed_potassium_rectifier_current_o\fP (\fBNTreal\fP \fBarea\fP, enum \fBNTBPdelayedPotassiumRectifierType\fP newType, \fBNTreal\fP \fBdensity\fP=30)"
.br
.ti -1c
.RI "\fBNTBP_delayed_potassium_rectifier_current_o\fP (const \fBNTBP_delayed_potassium_rectifier_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_delayed_potassium_rectifier_current_o\fP & \fBoperator=\fP (const \fBNTBP_delayed_potassium_rectifier_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_delayed_potassium_rectifier_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeRateSum\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeConductance\fP ()"
.br
.RI "\fIcompute and return conductance in mSiemens \fP"
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP voltage)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBSetDensity\fP (\fBNTreal\fP channelDensity)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 55 of file ntbp_delayed_potassium_rectifier_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_delayed_potassium_rectifier_current_o::NTBP_delayed_potassium_rectifier_current_o (\fBNTreal\fP area, enum \fBNTBPdelayedPotassiumRectifierType\fP newType, \fBNTreal\fP density = \fC30\fP)"
.SS "NTBP_delayed_potassium_rectifier_current_o::NTBP_delayed_potassium_rectifier_current_o (const \fBNTBP_delayed_potassium_rectifier_current_o\fP & original)"
.SS "virtual NTBP_delayed_potassium_rectifier_current_o::~NTBP_delayed_potassium_rectifier_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_delayed_potassium_rectifier_current_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_delayed_potassium_rectifier_current_o::ComputeConductance ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNTBP_channels_current_o\fP.
.PP
Definition at line 66 of file ntbp_delayed_potassium_rectifier_current_obj.h.
.PP
References NTBP_channels_current_o::channelsPtr, NTBP_channels_current_o::conductivity, NTBP_ion_channels_o::NumOpen(), and NTBP_membrane_current_o::Set_conductance().
.PP
.nf
{ return Set_conductance( channelsPtr->NumOpen() * conductivity);}
.fi
.SS "void NTBP_delayed_potassium_rectifier_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_delayed_potassium_rectifier_current_o::ComputeRateSum () const"
.SS "const \fBNTBP_delayed_potassium_rectifier_current_o\fP& NTBP_delayed_potassium_rectifier_current_o::operator= (const \fBNTBP_delayed_potassium_rectifier_current_o\fP & right)"
.SS "\fBNTreturn\fP NTBP_delayed_potassium_rectifier_current_o::SetDensity (\fBNTreal\fP channelDensity)"
.SS "\fBNTreturn\fP NTBP_delayed_potassium_rectifier_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
