.TH "NTBP_multi_sodium_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_multi_sodium_current_o \- 
.PP
-e \fBntbp_multi_sodium_current_obj.h\fP - \fBNTBP_multi_sodium_current_o\fP class header by Ahmed Aldo Faisal (C) created 16.3.2001  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_multi_sodium_current_obj.h>\fP
.PP
Inherits \fBNTBP_multi_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_multi_sodium_current_o\fP (\fBNTreal\fP area, \fBNTreal\fP \fBdensity\fP=330, \fBNTreal\fP channelConductave=4.0e-9)"
.br
.ti -1c
.RI "\fBNTBP_multi_sodium_current_o\fP (const \fBNTBP_multi_sodium_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_multi_sodium_current_o\fP & \fBoperator=\fP (const \fBNTBP_multi_sodium_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_multi_sodium_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.RI "\fIin 1/ms or kHz \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBOpenChannels\fP () const "
.br
.RI "\fINumber of open ionic channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBComputeConductance\fP ()"
.br
.RI "\fIcompute and return conductance in mSiemens \fP"
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP vM)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "void \fBShowChannelStatePopulation\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAlphaM\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBBetaM\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAlphaH\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "\fBNTreal\fP \fBBetaH\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "void \fBShowParam\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBNTBP_multi_sodium_current_o\fP class Channel density 330/muM^2 Single channel conductivity 4 pS Temperature 9 Celsius (see Hille (1992) p. 329 or Conti et. al (1975) ) 
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 60 of file ntbp_multi_sodium_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_multi_sodium_current_o::NTBP_multi_sodium_current_o (\fBNTreal\fP area, \fBNTreal\fP density = \fC330\fP, \fBNTreal\fP channelConductave = \fC4.0e-9\fP)"
.SS "NTBP_multi_sodium_current_o::NTBP_multi_sodium_current_o (const \fBNTBP_multi_sodium_current_o\fP & original)"
.SS "virtual NTBP_multi_sodium_current_o::~NTBP_multi_sodium_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::AlphaH (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 79 of file ntbp_multi_sodium_current_obj.h.
.PP
.nf
{     return 0.07 * exp( -vM / 20.0 ); }
.fi
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::AlphaM (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 77 of file ntbp_multi_sodium_current_obj.h.
.PP
.nf
{   return (25.0 - vM) / (10.0 * (exp((25.0 - vM)/10.0) - 1.0));}
.fi
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::BetaH (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 80 of file ntbp_multi_sodium_current_obj.h.
.PP
.nf
{    return 1.0/(exp(3.0 - vM/10.0) + 1.0); }
.fi
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::BetaM (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 78 of file ntbp_multi_sodium_current_obj.h.
.PP
.nf
{    return 4.0 * exp( -vM / 18.0 ); }
.fi
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::ComputeConductance ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "void NTBP_multi_sodium_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_multi_sodium_current_o::OpenChannels () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "const \fBNTBP_multi_sodium_current_o\fP& NTBP_multi_sodium_current_o::operator= (const \fBNTBP_multi_sodium_current_o\fP & right)"
.SS "void NTBP_multi_sodium_current_o::Show ()\fC [inline]\fP"
.PP
Definition at line 75 of file ntbp_multi_sodium_current_obj.h.
.PP
References NTBP_ion_channels_o::_numChannels(), NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
.PP
.nf
            {  cout << ' alphaM= ' << alphaM << '\t betaM= ' << betaM << '\t openRatio= ' << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << '\t alphaH= ' << alphaH << '\t betaH= ' << betaH << '\t openNum= ' << channelsPtr->NumOpen();}
.fi
.SS "void NTBP_multi_sodium_current_o::ShowChannelStatePopulation ()\fC [inline]\fP"
.PP
Definition at line 74 of file ntbp_multi_sodium_current_obj.h.
.PP
References NTBP_multi_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
.PP
.nf
{ channelsPtr->ShowStates(); }
.fi
.SS "void NTBP_multi_sodium_current_o::ShowParam () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreturn\fP NTBP_multi_sodium_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
