.TH "NTBP_spherical_compartment_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_spherical_compartment_o \- 
.PP
\fBNTBP_spherical_compartment_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_spherical_compartment_obj.h>\fP
.PP
Inherits \fBNTBP_membrane_compartment_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_spherical_compartment_o\fP (\fBNTreal\fP radius, \fBNTreal\fP cM)"
.br
.ti -1c
.RI "\fBNTBP_spherical_compartment_o\fP (const \fBNTBP_spherical_compartment_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_spherical_compartment_o\fP & \fBoperator=\fP (const \fBNTBP_spherical_compartment_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_spherical_compartment_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_radius\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 56 of file ntbp_spherical_compartment_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_spherical_compartment_o::NTBP_spherical_compartment_o (\fBNTreal\fP radius, \fBNTreal\fP cM)"
.SS "NTBP_spherical_compartment_o::NTBP_spherical_compartment_o (const \fBNTBP_spherical_compartment_o\fP & original)"
.SS "virtual NTBP_spherical_compartment_o::~NTBP_spherical_compartment_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_spherical_compartment_o::_radius () const\fC [inline]\fP"
.PP
Definition at line 64 of file ntbp_spherical_compartment_obj.h.
.PP
.nf
{ return radius;}
.fi
.SS "const \fBNTBP_spherical_compartment_o\fP& NTBP_spherical_compartment_o::operator= (const \fBNTBP_spherical_compartment_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
