.TH "NTBP_sga_sodium_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_sga_sodium_current_o \- 
.PP
\fBNTBP_sga_sodium_current_o\fP class Channel density 330/muM^2 Single channel conductivity 4 pS Temperature 9 Celsius (see Hille (1992) p.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_sga_sodium_current_obj.h>\fP
.PP
Inherits \fBNTBP_channels_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_sga_sodium_current_o\fP (\fBNTreal\fP \fBarea\fP, \fBNTreal\fP \fBdensity\fP=330)"
.br
.ti -1c
.RI "\fBNTBP_sga_sodium_current_o\fP (const \fBNTBP_sga_sodium_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_sga_sodium_current_o\fP & \fBoperator=\fP (const \fBNTBP_sga_sodium_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_sga_sodium_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP vM)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "void \fBShowChannelStatePopulation\fP ()"
.br
.ti -1c
.RI "void \fBShow\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
329 or Conti et. al (1975) ) 
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 52 of file ntbp_sga_sodium_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_sga_sodium_current_o::NTBP_sga_sodium_current_o (\fBNTreal\fP area, \fBNTreal\fP density = \fC330\fP)"
.SS "NTBP_sga_sodium_current_o::NTBP_sga_sodium_current_o (const \fBNTBP_sga_sodium_current_o\fP & original)"
.SS "virtual NTBP_sga_sodium_current_o::~NTBP_sga_sodium_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_sga_sodium_current_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "void NTBP_sga_sodium_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "const \fBNTBP_sga_sodium_current_o\fP& NTBP_sga_sodium_current_o::operator= (const \fBNTBP_sga_sodium_current_o\fP & right)"
.SS "void NTBP_sga_sodium_current_o::Show ()\fC [inline]\fP"
.PP
Definition at line 64 of file ntbp_sga_sodium_current_obj.h.
.PP
References NTBP_ion_channels_o::_numChannels(), NTBP_channels_current_o::channelsPtr, and NTBP_ion_channels_o::NumOpen().
.PP
.nf
            {  cout << ' alphaM= ' << alphaM << '\t betaM= ' << betaM << '\t openRatio= ' << ((double)channelsPtr->NumOpen())/channelsPtr->_numChannels()
                   << '\t alphaH= ' << alphaH << '\t betaH= ' << betaH << '\t openNum= ' << channelsPtr->NumOpen();}
.fi
.SS "void NTBP_sga_sodium_current_o::ShowChannelStatePopulation ()\fC [inline]\fP"
.PP
Definition at line 63 of file ntbp_sga_sodium_current_obj.h.
.PP
References NTBP_channels_current_o::channelsPtr, and NTBP_ion_channels_o::ShowStates().
.PP
.nf
{ channelsPtr->ShowStates(); }
.fi
.SS "\fBNTreturn\fP NTBP_sga_sodium_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
