.TH "NTBP_tridiag_solver_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_tridiag_solver_o \- 
.PP
\fBNTBP_tridiag_solver_o\fP class Solve tridiangonal sequence of multi-compartment cable equations using the Thomas algorithm cerr << 'OBSOLETE code called';.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_tridiag_solver_obj.h>\fP
.PP
Inherits \fBNT_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_tridiag_solver_o\fP (\fBNTsize\fP numCompartments)"
.br
.ti -1c
.RI "\fBNTBP_tridiag_solver_o\fP (const \fBNTBP_tridiag_solver_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_tridiag_solver_o\fP & \fBoperator=\fP (const \fBNTBP_tridiag_solver_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_tridiag_solver_o\fP ()"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBSetup\fP (vector< \fBNTreal\fP > newLVec, vector< \fBNTreal\fP > newUVec)"
.br
.ti -1c
.RI "vector< \fBNTreal\fP > \fBSolve\fP (vector< \fBNTreal\fP > dVec, vector< \fBNTreal\fP > vVec, vector< \fBNTreal\fP > rVec)"
.br
.ti -1c
.RI "\fBNTreturn\fP \fBResize\fP (\fBNTsize\fP numCompartment)"
.br
.in -1c
.SH "Detailed Description"
.PP 
OBSOLETE CODE
.PP
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 54 of file ntbp_tridiag_solver_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_tridiag_solver_o::NTBP_tridiag_solver_o (\fBNTsize\fP numCompartments)"
.SS "NTBP_tridiag_solver_o::NTBP_tridiag_solver_o (const \fBNTBP_tridiag_solver_o\fP & original)"
.SS "virtual NTBP_tridiag_solver_o::~NTBP_tridiag_solver_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTBP_tridiag_solver_o\fP& NTBP_tridiag_solver_o::operator= (const \fBNTBP_tridiag_solver_o\fP & right)"
.SS "\fBNTreturn\fP NTBP_tridiag_solver_o::Resize (\fBNTsize\fP numCompartment)"
.SS "\fBNTreturn\fP NTBP_tridiag_solver_o::Setup (vector< \fBNTreal\fP > newLVec, vector< \fBNTreal\fP > newUVec)"
.SS "vector<\fBNTreal\fP> NTBP_tridiag_solver_o::Solve (vector< \fBNTreal\fP > dVec, vector< \fBNTreal\fP > vVec, vector< \fBNTreal\fP > rVec)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
