.TH "NTBP_multi_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_multi_current_o \- 
.PP
\fBNTBP_multi_current_o\fP class Base class for stochastic channel simulations of individual channels.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_multi_current_obj.h>\fP
.PP
Inherits \fBNTBP_membrane_current_o\fP.
.PP
Inherited by \fBNTBP_colbert_axonal_potassium_multi_current_o\fP, \fBNTBP_colbert_axonal_sodium_multi_current_o\fP, \fBNTBP_hranvier_potassium_multi_current_o\fP, \fBNTBP_hranvier_sodium_multi_current_o\fP, \fBNTBP_multi_potassium_current_o\fP, \fBNTBP_multi_sodium_current_o\fP, and \fBNTBP_patlak_sodium_multi_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_multi_current_o\fP (\fBNTreal\fP reversalPotential, \fBNTreal\fP \fBdensity\fP, \fBNTreal\fP area, \fBNTreal\fP \fBconductivity\fP, \fBNTreal\fP vBase=0)"
.br
.ti -1c
.RI "\fBNTBP_multi_current_o\fP (const \fBNTBP_multi_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_multi_current_o\fP & \fBoperator=\fP (const \fBNTBP_multi_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_multi_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fB_density\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_area\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_conductivity\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fB_maxConductivity\fP () const "
.br
.ti -1c
.RI "bool \fBComputeGillespieStep\fP ()"
.br
.ti -1c
.RI "void \fBUpdateNumChannels\fP ()"
.br
.ti -1c
.RI "\fBNTsize\fP \fB_numChannels\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBNumChannels\fP () const "
.br
.RI "\fINumber of total ionic channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBOpenChannelsRatio\fP () const "
.br
.RI "\fINumber of open over total number of channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fB_vBase\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBconductivity\fP"
.br
.ti -1c
.RI "\fBNTreal\fP \fBdensity\fP"
.br
.ti -1c
.RI "\fBNTBP_ion_channels_o\fP * \fBchannelsPtr\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fBNT_uniform_rnd_dist_o\fP \fBuniformRnd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 61 of file ntbp_multi_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_multi_current_o::NTBP_multi_current_o (\fBNTreal\fP reversalPotential, \fBNTreal\fP density, \fBNTreal\fP area, \fBNTreal\fP conductivity, \fBNTreal\fP vBase = \fC0\fP)"
.SS "NTBP_multi_current_o::NTBP_multi_current_o (const \fBNTBP_multi_current_o\fP & original)"
.SS "virtual NTBP_multi_current_o::~NTBP_multi_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_multi_current_o::_area () const\fC [inline]\fP"
.PP
Definition at line 79 of file ntbp_multi_current_obj.h.
.PP
.nf
{ return area; }
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::_conductivity () const\fC [inline]\fP"
.PP
Definition at line 81 of file ntbp_multi_current_obj.h.
.PP
.nf
{ return conductivity; }
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::_density () const\fC [inline]\fP"
.PP
Definition at line 78 of file ntbp_multi_current_obj.h.
.PP
.nf
{ return density;}
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::_maxConductivity () const\fC [inline, virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.PP
Definition at line 83 of file ntbp_multi_current_obj.h.
.PP
.nf
{return density /* num/muMeter^2 */ * conductivity /* mSiemens */* 1.0e8 /* muMeter^2/cm^2 */;}
.fi
.SS "\fBNTsize\fP NTBP_multi_current_o::_numChannels () const\fC [inline]\fP"
.PP
Definition at line 87 of file ntbp_multi_current_obj.h.
.PP
Referenced by NumChannels().
.PP
.nf
{ return numChannels; }
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::_vBase () const\fC [inline]\fP"
.PP
Definition at line 91 of file ntbp_multi_current_obj.h.
.PP
Referenced by NTBP_hranvier_sodium_multi_current_o::AlphaH(), NTBP_hranvier_sodium_multi_current_o::AlphaM(), NTBP_hranvier_potassium_multi_current_o::AlphaN(), NTBP_hranvier_sodium_multi_current_o::BetaH(), NTBP_hranvier_sodium_multi_current_o::BetaM(), and NTBP_hranvier_potassium_multi_current_o::BetaN().
.PP
.nf
{ return vBase;}
.fi
.SS "bool NTBP_multi_current_o::ComputeGillespieStep ()\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.PP
Definition at line 85 of file ntbp_multi_current_obj.h.
.PP
References channelsPtr, and NTBP_ion_channels_o::GillespieStep().
.PP
.nf
{cerr <<'NTBP_multi_current_o::ComputeGillespieStep()' << endl; return channelsPtr->GillespieStep();}
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::NumChannels () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.PP
Definition at line 89 of file ntbp_multi_current_obj.h.
.PP
References _numChannels().
.PP
Referenced by OpenChannelsRatio().
.PP
.nf
{ return _numChannels(); }
.fi
.SS "\fBNTreal\fP NTBP_multi_current_o::OpenChannelsRatio () const\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.PP
Definition at line 90 of file ntbp_multi_current_obj.h.
.PP
References NumChannels(), and NTBP_membrane_current_o::OpenChannels().
.PP
.nf
{ return OpenChannels()/NumChannels(); }
.fi
.SS "const \fBNTBP_multi_current_o\fP& NTBP_multi_current_o::operator= (const \fBNTBP_multi_current_o\fP & right)"
.SS "void NTBP_multi_current_o::UpdateNumChannels ()\fC [inline]\fP"
.PP
Definition at line 86 of file ntbp_multi_current_obj.h.
.PP
.nf
{ numChannels = (NTsize) ceil(density*area); }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNTBP_ion_channels_o\fP* \fBNTBP_multi_current_o::channelsPtr\fP\fC [protected]\fP"
.PP
Definition at line 101 of file ntbp_multi_current_obj.h.
.PP
Referenced by ComputeGillespieStep(), NTBP_multi_sodium_current_o::Show(), NTBP_hranvier_sodium_multi_current_o::Show(), NTBP_multi_sodium_current_o::ShowChannelStatePopulation(), and NTBP_hranvier_sodium_multi_current_o::ShowChannelStatePopulation().
.SS "\fBNTreal\fP \fBNTBP_multi_current_o::conductivity\fP\fC [protected]\fP"
.PP
Definition at line 99 of file ntbp_multi_current_obj.h.
.SS "\fBNTreal\fP \fBNTBP_multi_current_o::density\fP\fC [protected]\fP"
.PP
Definition at line 100 of file ntbp_multi_current_obj.h.
.SS "\fBNT_uniform_rnd_dist_o\fP \fBNTBP_multi_current_o::uniformRnd\fP\fC [static, protected]\fP"
.PP
Definition at line 98 of file ntbp_multi_current_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
