.TH "NTBP_custom_cylindrical_compartment_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_custom_cylindrical_compartment_o \- 
.PP
\fBNTBP_custom_cylindrical_compartment_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_custom_cylindrical_compartment_obj.h>\fP
.PP
Inherits \fBNTBP_cylindrical_compartment_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_custom_cylindrical_compartment_o\fP (\fBNTreal\fP length, \fBNTreal\fP diameter, \fBNTreal\fP cM, \fBNTreal\fP rA)"
.br
.ti -1c
.RI "\fBNTBP_custom_cylindrical_compartment_o\fP (const \fBNTBP_custom_cylindrical_compartment_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_custom_cylindrical_compartment_o\fP & \fBoperator=\fP (const \fBNTBP_custom_cylindrical_compartment_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_custom_cylindrical_compartment_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 51 of file ntbp_custom_cylindrical_compartment_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_custom_cylindrical_compartment_o::NTBP_custom_cylindrical_compartment_o (\fBNTreal\fP length, \fBNTreal\fP diameter, \fBNTreal\fP cM, \fBNTreal\fP rA)"
.SS "NTBP_custom_cylindrical_compartment_o::NTBP_custom_cylindrical_compartment_o (const \fBNTBP_custom_cylindrical_compartment_o\fP & original)"
.SS "virtual NTBP_custom_cylindrical_compartment_o::~NTBP_custom_cylindrical_compartment_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTBP_custom_cylindrical_compartment_o\fP& NTBP_custom_cylindrical_compartment_o::operator= (const \fBNTBP_custom_cylindrical_compartment_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
