.TH "NTBP_colbert_axonal_potassium_multi_current_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_colbert_axonal_potassium_multi_current_o \- 
.PP
\fBNTBP_colbert_axonal_potassium_multi_current_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_colbert_axonal_potassium_multi_current_obj.h>\fP
.PP
Inherits \fBNTBP_multi_current_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_colbert_axonal_potassium_multi_current_o\fP (\fBNTreal\fP area, \fBNTreal\fP \fBdensity\fP=8, \fBNTreal\fP channelConductance=2.0e-8, NTreal newVBase=-64.5)"
.br
.ti -1c
.RI "\fBNTBP_colbert_axonal_potassium_multi_current_o\fP (const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP & \fBoperator=\fP (const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_colbert_axonal_potassium_multi_current_o\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBComputeRateSum\fP () const "
.br
.ti -1c
.RI "\fBNTreal\fP \fBOpenChannels\fP () const "
.br
.RI "\fINumber of open ionic channels. \fP"
.ti -1c
.RI "\fBNTreal\fP \fBComputeConductance\fP ()"
.br
.RI "\fIcompute and return conductance in mSiemens \fP"
.ti -1c
.RI "void \fBComputeRateConstants\fP (\fBNTreal\fP voltage)"
.br
.RI "\fIcompute the rate constants ( in ms^-1 ) \fP"
.ti -1c
.RI "\fBNTreal\fP \fBComputeChannelStateTimeConstant\fP () const "
.br
.RI "\fIin kHz \fP"
.ti -1c
.RI "\fBNTreturn\fP \fBStepCurrent\fP ()"
.br
.ti -1c
.RI "\fBNTreal\fP \fBAlphaN\fP (\fBNTreal\fP vM)"
.br
.RI "\fIrate constant in ms^-1 \fP"
.ti -1c
.RI "\fBNTreal\fP \fBBetaN\fP (\fBNTreal\fP vM)"
.br
.ti -1c
.RI "void \fBShowParam\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 88 of file ntbp_colbert_axonal_potassium_multi_current_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_colbert_axonal_potassium_multi_current_o::NTBP_colbert_axonal_potassium_multi_current_o (\fBNTreal\fP area, \fBNTreal\fP density = \fC8\fP, \fBNTreal\fP channelConductance = \fC2.0e-8\fP, \fBNTreal\fP newVBase = \fC-64.5\fP)"
.SS "NTBP_colbert_axonal_potassium_multi_current_o::NTBP_colbert_axonal_potassium_multi_current_o (const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP & original)"
.SS "virtual NTBP_colbert_axonal_potassium_multi_current_o::~NTBP_colbert_axonal_potassium_multi_current_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::AlphaN (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 77 of file ntbp_colbert_axonal_potassium_multi_current_obj.h.
.PP
.nf
: public NTBP_multi_current_o {
.fi
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::BetaN (\fBNTreal\fP vM)\fC [inline]\fP"
.PP
Definition at line 78 of file ntbp_colbert_axonal_potassium_multi_current_obj.h.
.PP
.nf
: public NTBP_multi_current_o {
.fi
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::ComputeChannelStateTimeConstant () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::ComputeConductance ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "void NTBP_colbert_axonal_potassium_multi_current_o::ComputeRateConstants (\fBNTreal\fP vM)\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::ComputeRateSum () const"
.SS "\fBNTreal\fP NTBP_colbert_axonal_potassium_multi_current_o::OpenChannels () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP& NTBP_colbert_axonal_potassium_multi_current_o::operator= (const \fBNTBP_colbert_axonal_potassium_multi_current_o\fP & right)"
.SS "void NTBP_colbert_axonal_potassium_multi_current_o::ShowParam () const\fC [virtual]\fP"
.PP
Reimplemented from \fBNTBP_membrane_current_o\fP.
.SS "\fBNTreturn\fP NTBP_colbert_axonal_potassium_multi_current_o::StepCurrent ()\fC [virtual]\fP"
.PP
Implements \fBNTBP_membrane_current_o\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
