.TH "NTBP_membrane_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTBP_membrane_o \- 
.PP
\fBNTBP_membrane_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntbp_membrane_obj.h>\fP
.PP
Inherits \fBNTBP_object_o\fP.
.PP
Inherited by \fBNTBP_membrane_compartment_sequence_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTBP_membrane_o\fP ()"
.br
.ti -1c
.RI "\fBNTBP_membrane_o\fP (const \fBNTBP_membrane_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTBP_membrane_o\fP & \fBoperator=\fP (const \fBNTBP_membrane_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTBP_membrane_o\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "vector< \fBNTBP_membrane_compartment_o\fP > \fBmembCompVec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 48 of file ntbp_membrane_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTBP_membrane_o::NTBP_membrane_o ()"
.SS "NTBP_membrane_o::NTBP_membrane_o (const \fBNTBP_membrane_o\fP & original)"
.SS "virtual NTBP_membrane_o::~NTBP_membrane_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTBP_membrane_o\fP& NTBP_membrane_o::operator= (const \fBNTBP_membrane_o\fP & right)"
.SH "Member Data Documentation"
.PP 
.SS "vector< \fBNTBP_membrane_compartment_o\fP > \fBNTBP_membrane_o::membCompVec\fP\fC [protected]\fP"
.PP
Definition at line 60 of file ntbp_membrane_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
