.TH "ntbp_multi_sodium_current_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntbp_multi_sodium_current_obj.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'nt_main.h'\fP
.br
\fC#include 'nt_types.h'\fP
.br
\fC#include 'nt_obj.h'\fP
.br
\fC#include 'ntbp_multi_current_obj.h'\fP
.br
\fC#include 'ntbp_sodium_ion_channels_obj.h'\fP
.br
\fC#include 'nt_gaussian_rnd_dist_obj.h'\fP
.br
\fC#include <cmath>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNTBP_multi_sodium_current_o\fP"
.br
.RI "\fI-e \fBntbp_multi_sodium_current_obj.h\fP - \fBNTBP_multi_sodium_current_o\fP class header by Ahmed Aldo Faisal (C) created 16.3.2001 \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
