.TH "NTG_random_ring_graph_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTG_random_ring_graph_o \- 
.PP
\fBNTG_random_ring_graph_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntg_random_ring_graph_obj.h>\fP
.PP
Inherits \fBNTG_neighbour_ring_graph_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTG_random_ring_graph_o\fP (\fBNTsize\fP nodes, \fBNTsize\fP neighbourhoodRange, \fBNTreal\fP reconnectProbability, bool deterministic, const \fBNTG_node_o\fP &nodeProto, const \fBNTG_edge_o\fP &edgeProto)"
.br
.ti -1c
.RI "\fBNTG_random_ring_graph_o\fP (const \fBNTG_random_ring_graph_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTG_random_ring_graph_o\fP & \fBoperator=\fP (const \fBNTG_random_ring_graph_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTG_random_ring_graph_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 53 of file ntg_random_ring_graph_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTG_random_ring_graph_o::NTG_random_ring_graph_o (\fBNTsize\fP nodes, \fBNTsize\fP neighbourhoodRange, \fBNTreal\fP reconnectProbability, bool deterministic, const \fBNTG_node_o\fP & nodeProto, const \fBNTG_edge_o\fP & edgeProto)"
.SS "NTG_random_ring_graph_o::NTG_random_ring_graph_o (const \fBNTG_random_ring_graph_o\fP & original)"
.SS "virtual NTG_random_ring_graph_o::~NTG_random_ring_graph_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTG_random_ring_graph_o\fP& NTG_random_ring_graph_o::operator= (const \fBNTG_random_ring_graph_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
