.TH "NTG_undirected_graph_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTG_undirected_graph_o \- 
.PP
\fBNTG_undirected_graph_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntg_undirected_graph_obj.h>\fP
.PP
Inherits \fBNTG_graph_o\fP.
.PP
Inherited by \fBNTG_neighbour_ring_graph_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTG_undirected_graph_o\fP ()"
.br
.ti -1c
.RI "\fBNTG_undirected_graph_o\fP (const \fBNTG_undirected_graph_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTG_undirected_graph_o\fP & \fBoperator=\fP (const \fBNTG_undirected_graph_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTG_undirected_graph_o\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 54 of file ntg_undirected_graph_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTG_undirected_graph_o::NTG_undirected_graph_o ()"
.SS "NTG_undirected_graph_o::NTG_undirected_graph_o (const \fBNTG_undirected_graph_o\fP & original)"
.SS "virtual NTG_undirected_graph_o::~NTG_undirected_graph_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTG_undirected_graph_o\fP& NTG_undirected_graph_o::operator= (const \fBNTG_undirected_graph_o\fP & right)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
