.TH "ntg_matrix_graph_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntg_matrix_graph_obj.h \- 
.PP
.IP "\(bu" 2
\fBNTG_matrix_graph_o\fP class header by Ahmed Aldo Faisal (C) created 30.9.2000 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'ntg_node_obj.h'\fP
.br
\fC#include 'ntg_edge_obj.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'tnt/tnt.h'\fP
.br
\fC#include 'tnt/vec.h'\fP
.br
\fC#include 'tnt/cmat.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNTG_matrix_graph_o\fP"
.br
.RI "\fI\fBNTG_matrix_graph_o\fP class. \fP"
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBMatrix\fP< int > \fBIntMatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBntg_matrix_graph_obj.h\fP.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBMatrix\fP<int> \fBIntMatrix\fP"
.PP
Definition at line 57 of file ntg_matrix_graph_obj.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
