.TH "NTG_node_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTG_node_o \- 
.PP
\fBNTG_node_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntg_node_obj.h>\fP
.PP
Inherited by \fBNTG_value_node_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTG_node_o\fP (\fBNTid\fP newUniqId=0)"
.br
.ti -1c
.RI "\fBNTG_node_o\fP (const \fBNTG_node_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTG_node_o\fP & \fBoperator=\fP (const \fBNTG_node_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTG_node_o\fP ()"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBNTG_node_o\fP &rhs)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 52 of file ntg_node_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTG_node_o::NTG_node_o (\fBNTid\fP newUniqId = \fC0\fP)"
.SS "NTG_node_o::NTG_node_o (const \fBNTG_node_o\fP & original)"
.SS "virtual NTG_node_o::~NTG_node_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTG_node_o\fP& NTG_node_o::operator= (const \fBNTG_node_o\fP & right)"
.SS "bool NTG_node_o::operator== (\fBNTG_node_o\fP & rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
