.TH "NTG_value_node_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTG_value_node_o \- 
.PP
\fBNTG_value_node_o\fP class.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntg_value_node_obj.h>\fP
.PP
Inherits \fBNTG_node_o\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTG_value_node_o\fP (\fBNTid\fP newNodeId=0)"
.br
.ti -1c
.RI "\fBNTG_value_node_o\fP (const \fBNTG_value_node_o\fP &original)"
.br
.ti -1c
.RI "const \fBNTG_value_node_o\fP & \fBoperator=\fP (const \fBNTG_value_node_o\fP &right)"
.br
.ti -1c
.RI "virtual \fB~NTG_value_node_o\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNTreal\fP \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBBug\fP
.RS 4
unknown 
.RE
.PP
\fBWarning:\fP
.RS 4
unknown 
.RE
.PP

.PP
Definition at line 51 of file ntg_value_node_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTG_value_node_o::NTG_value_node_o (\fBNTid\fP newNodeId = \fC0\fP)"
.SS "NTG_value_node_o::NTG_value_node_o (const \fBNTG_value_node_o\fP & original)"
.SS "virtual NTG_value_node_o::~NTG_value_node_o ()\fC [virtual]\fP"
.SH "Member Function Documentation"
.PP 
.SS "const \fBNTG_value_node_o\fP& NTG_value_node_o::operator= (const \fBNTG_value_node_o\fP & right)"
.SH "Member Data Documentation"
.PP 
.SS "\fBNTreal\fP \fBNTG_value_node_o::value\fP"
.PP
Definition at line 60 of file ntg_value_node_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
