.TH "NTG_vertex_o" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NTG_vertex_o \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ntg_graph_obj.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNTG_vertex_o\fP (\fBNTid\fP id=0, \fBNTG_node_o\fP node=\fBNTG_node_o\fP(), string name='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBNTid\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBNTG_node_o\fP \fBsecond\fP"
.br
.ti -1c
.RI "string \fBthird\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file ntg_graph_obj.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "NTG_vertex_o::NTG_vertex_o (\fBNTid\fP id = \fC0\fP, \fBNTG_node_o\fP node = \fC\fBNTG_node_o\fP()\fP, string name = \fC''\fP)\fC [inline]\fP"
.PP
Definition at line 93 of file ntg_graph_obj.h.
.PP
.nf
                                                                                {
        first = id;
        second = node;
        if (name == '') third = first;
        else third = name;
    }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBNTid\fP \fBNTG_vertex_o::first\fP"
.PP
Definition at line 99 of file ntg_graph_obj.h.
.SS "\fBNTG_node_o\fP \fBNTG_vertex_o::second\fP"
.PP
Definition at line 100 of file ntg_graph_obj.h.
.SS "string \fBNTG_vertex_o::third\fP"
.PP
Definition at line 101 of file ntg_graph_obj.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
