.TH "ntg_value_node_obj.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ntg_value_node_obj.h \- 
.PP
.IP "\(bu" 2
\fBNTG_value_node_o\fP class header by Ahmed Aldo Faisal (C) created 30.9.2000 
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'ntg_node_obj.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNTG_value_node_o\fP"
.br
.RI "\fI\fBNTG_value_node_o\fP class. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBntg_value_node_obj.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
