.TH "region2d.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
region2d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tnt/index.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cassert>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTNT::Region2D< Array2D >\fP"
.br
.ti -1c
.RI "class \fBTNT::const_Region2D< Array2D >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Array2D > std::ostream & \fBTNT::operator<<\fP (std::ostream &s, const const_Region2D< Array2D > &A)"
.br
.ti -1c
.RI "template<class Array2D > std::ostream & \fBTNT::operator<<\fP (std::ostream &s, const Region2D< Array2D > &A)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
