.TH "stopwatch.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stopwatch.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ctime>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTNT::stopwatch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBTNT::seconds\fP (void)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
