.TH "tnt.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tnt.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tnt/version.h'\fP
.br
\fC#include 'tnt/subscript.h'\fP
.br
\fC#include 'tnt/tntmath.h'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTNT_BOUNDS_CHECK\fP"
.br
.ti -1c
.RI "#define \fBTNT_USE_REGIONS\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TNT_BOUNDS_CHECK"
.PP
Definition at line 61 of file tnt.h.
.SS "#define TNT_USE_REGIONS"
.PP
Definition at line 75 of file tnt.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
