.TH "TNT::stopwatch" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TNT::stopwatch \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stopwatch.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstopwatch\fP ()"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "double \fBstop\fP ()"
.br
.ti -1c
.RI "double \fBread\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file stopwatch.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TNT::stopwatch::stopwatch ()\fC [inline]\fP"
.PP
Definition at line 58 of file stopwatch.h.
.PP
.nf
: running(0), last_time(0.0), total(0.0) {}
.fi
.SH "Member Function Documentation"
.PP 
.SS "double TNT::stopwatch::read ()\fC [inline]\fP"
.PP
Definition at line 68 of file stopwatch.h.
.PP
References TNT::seconds().
.PP
.nf
                        {  if (running) 
                            {
                                total+= seconds() - last_time;
                                last_time = seconds();
                            }
                           return total;
                        }       
.fi
.SS "void TNT::stopwatch::reset ()\fC [inline]\fP"
.PP
Definition at line 59 of file stopwatch.h.
.PP
.nf
{ running = 0; last_time = 0.0; total=0.0; }
.fi
.SS "void TNT::stopwatch::start ()\fC [inline]\fP"
.PP
Definition at line 60 of file stopwatch.h.
.PP
References TNT::seconds().
.PP
.nf
{ if (!running) { last_time = seconds(); running = 1;}}
.fi
.SS "double TNT::stopwatch::stop ()\fC [inline]\fP"
.PP
Definition at line 61 of file stopwatch.h.
.PP
References TNT::seconds().
.PP
.nf
                       { if (running) 
                            {
                                total += seconds() - last_time; 
                                running = 0;
                             }
                          return total; 
                        }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
