.TH "tntmath.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tntmath.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBTNT::abs\fP (double t)"
.br
.ti -1c
.RI "double \fBTNT::min\fP (double a, double b)"
.br
.ti -1c
.RI "double \fBTNT::max\fP (double a, double b)"
.br
.ti -1c
.RI "float \fBTNT::abs\fP (float t)"
.br
.ti -1c
.RI "float \fBTNT::min\fP (float a, float b)"
.br
.ti -1c
.RI "float \fBTNT::max\fP (float a, float b)"
.br
.ti -1c
.RI "double \fBTNT::sign\fP (double a)"
.br
.ti -1c
.RI "float \fBTNT::sign\fP (float a)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
