.TH "transv.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transv.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cassert>\fP
.br
\fC#include 'tnt/vec.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTNT::Transpose_View< Array2D >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Matrix > Transpose_View< Matrix > \fBTNT::Transpose_view\fP (const Matrix &A)"
.br
.ti -1c
.RI "template<class Matrix , class T > Vector< T > \fBTNT::matmult\fP (const Transpose_View< Matrix > &A, const Vector< T > &B)"
.br
.ti -1c
.RI "template<class Matrix , class T > Vector< T > \fBTNT::operator*\fP (const Transpose_View< Matrix > &A, const Vector< T > &B)"
.br
.ti -1c
.RI "template<class Matrix > std::ostream & \fBTNT::operator<<\fP (std::ostream &s, const Transpose_View< Matrix > &A)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
