.TH "trisolve.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
trisolve.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'triang.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTNT\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::Lower_triangular_solve\fP (MaTriX &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::Unit_lower_triangular_solve\fP (MaTriX &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::linear_solve\fP (LowerTriangularView< MaTriX > &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::linear_solve\fP (UnitLowerTriangularView< MaTriX > &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::Upper_triangular_solve\fP (MaTriX &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::Unit_upper_triangular_solve\fP (MaTriX &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::linear_solve\fP (UpperTriangularView< MaTriX > &A, VecToR &b)"
.br
.ti -1c
.RI "template<class MaTriX , class VecToR > VecToR \fBTNT::linear_solve\fP (UnitUpperTriangularView< MaTriX > &A, VecToR &b)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
