.TH "version.h" 3 "Wed Nov 17 2010" "Version 0.5" "NetTrader" \" -*- nroff -*-
.ad l
.nh
.SH NAME
version.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTNT_MAJOR_VERSION\fP   '0'"
.br
.ti -1c
.RI "#define \fBTNT_MINOR_VERSION\fP   '9'"
.br
.ti -1c
.RI "#define \fBTNT_SUBMINOR_VERSION\fP   '4'"
.br
.ti -1c
.RI "#define \fBTNT_VERSION_STRING\fP   '0.9.4'"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define TNT_MAJOR_VERSION   '0'"
.PP
Definition at line 15 of file version.h.
.SS "#define TNT_MINOR_VERSION   '9'"
.PP
Definition at line 16 of file version.h.
.SS "#define TNT_SUBMINOR_VERSION   '4'"
.PP
Definition at line 17 of file version.h.
.SS "#define TNT_VERSION_STRING   '0.9.4'"
.PP
Definition at line 18 of file version.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for NetTrader from the source code.
