/**\file ntg_edge_obj.h - NTG_edge_o class header
 * by Ahmed Aldo Faisal &copy; created 30.9.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _ntg_edge_obj_h_
#define _ntg_edge_obj_h_

/* M core includes */
#include "mbase/Obj.h"
/* M includes */

/* other includes */

/** @short NTG_edge_o class
 ** This base class mimics <pair<mbase::Mid, mbase::Mid>>
 \bug unknown
 \warning unknown
 */
class NTG_edge_o {
public:
	/***   Constructors, Copy/Assignment and Destructor  ***/
	NTG_edge_o(mbase::Mid newSource = 0, mbase::Mid newTarget = 0);
	NTG_edge_o(const NTG_edge_o & original);
	const NTG_edge_o & operator=(const NTG_edge_o & right);
	virtual ~NTG_edge_o();
	/* ***  Methods              ***/
	mbase::Mid first() const {
		return (Source());
	}
	mbase::Mid Source() const {
		return (source);
	}
	mbase::Mid second() const {
		return (Target());
	}
	mbase::Mid Target() const {
		return (target);
	}

	mbase::Mreturn SetSource(mbase::Mid __attribute__((unused)) newSource) {
		return (mbase::M_NOT_IMPLEMENTED);
	}
	mbase::Mreturn SetTarget(mbase::Mid __attribute__((unused)) newTarget) {
		return (mbase::M_NOT_IMPLEMENTED);
	}
	mbase::Mreturn SetConnection(mbase::Mid newSource, mbase::Mid newTarget);
	/* ***  Data                 ***/
protected:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
private:
	/* ***  Methods              ***/
	/* ***  Data                 ***/
	mbase::Mid source;
	mbase::Mid target;
};
#endif /* _ntg_edge_obj_h_ */

/* File skeleton generated by GenMObj version 0.7. */
