/**\file ntg_undirected_graph_obj.cpp - NTG_undirected_graph_o class implementation
 * by Ahmed Aldo Faisal &copy; created 13.10.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#include "ntg_undirected_graph_obj.h"

/* ***      CONSTRUCTORS	***/
/** Create a NTG_undirected_graph_o */
NTG_undirected_graph_o::NTG_undirected_graph_o() :
		NTG_graph_o() {
}
/* ***      COPY AND ASSIGNMENT	***/
NTG_undirected_graph_o::NTG_undirected_graph_o(
		const NTG_undirected_graph_o __attribute__((unused)) & original) :
		NTG_graph_o() {
// add assignment code here
}

const NTG_undirected_graph_o&
NTG_undirected_graph_o::operator=(const NTG_undirected_graph_o & right) {
	if (this == &right)
		return (*this); // Gracefully handle self assignment
// add assignment code here
	return (*this);
}

/* ***      DESTRUCTOR		***/
NTG_undirected_graph_o::~NTG_undirected_graph_o() {
}

/* ***  PUBLIC                                    ***   */
/** @short
 @param      none
 @return     none
 \warning    unknown
 \bug        unknown
 void
 NTG_undirected_graph_o::() const
 {
 }
 */

/* ***  PROTECTED                         ***   */
/* ***  PRIVATE                           ***   */

/* File skeleton generated by GenNTObj version 0.7. */
