/**\file ntg_random_graph_obj.h - NTG_random_graph_o class header
 * by Ahmed Aldo Faisal &copy; created 10.10.2000
 */
/* NetTrader - visualisation, scientific and financial analysis and simulation system
 * Version:  0.5
 * Copyright (C) 1998,1999,2000 Ahmed Aldo Faisal
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRAMY; without even the implied warranty of
 * MERCHAMABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the Free
 * Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 */

#ifndef _ntg_random_graph_obj_h_
#define _ntg_random_graph_obj_h_

/* M core includes */
#include "mbase/main.h"
#include "mbase/types.h"
#include "mbase/Obj.h"
/* Parent includes */
#include "ntg_graph_obj.h"
/* M includes */
#include "mbase/Uniform_rnd_dist.h"

/* other includes */


#include <cstdlib>
#include <vector>
#include <algorithm>
#include <cmath>

/* apparently g++ and STL dont know this one */
/* Apparently they do in 2011 */
//extern long int lrand48 __P ((void));


/** @short NTG_random_graph_o class
\bug unknown
\warning unknown
*/
class NTG_random_graph_o : public NTG_graph_o {
public:
    /***   Constructors, Copy/Assignment and Destructor  ***/
    NTG_random_graph_o(mbase::Size_t numInitialNodes, const NTG_node_o & nodeProto, const NTG_edge_o & edgeProto);
    NTG_random_graph_o(mbase::Size_t numInitialNodes, mbase::Real connectivityProbability, const NTG_node_o & nodeProto, const NTG_edge_o & edgeProto);
    NTG_random_graph_o(const NTG_random_graph_o & original);
    const NTG_random_graph_o & operator= (const NTG_random_graph_o & right);
    virtual ~NTG_random_graph_o();
    /* ***  Methods              ***/
    mbase::Mreturn AddRandomNode(const NTG_node_o & nodeProto);
    mbase::Mreturn AddRandomEdge(const NTG_edge_o & edgeProto);
    /* ***  Data                 ***/
protected:
    /* ***  Methods              ***/
    /* ***  Data                 ***/
private:
    /* ***  Methods              ***/
    void InitFullyConnectedGraph(mbase::Size_t numInitialNodes, const NTG_node_o & nodeProto, const NTG_edge_o & edgeProto);
    /* ***  Data                 ***/
    mbase::Real p;

};
#endif /* _ntg_random_graph_obj_h_ */

/* File skeleton generated by GenMObj version 0.7. */
